### ISSUE TITLE
Indices organization

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#10]
At the moment there are indices in hydro, icclim and xclim which is going to be confusing. 

I suggest we put all indices in xclim.py in alphabetical order, and create "fake" modules like icclim to aggregate them into thematic packages. 

To be clear, icclim,py would only import indices from xclim.

**Comment by huard** [comment]
Done.

**Comment by tlogan2000** [comment]
Ok. this is close to what I was thinking about yesterday.... i.e. 'ICCLIM' is a grouping/name only really relevant to those who have used the original package.  
New users or Ouranos employees won't really understand when they need to use a submodule vs another.   

I was thinking even the submodule name 'ICCLIM' was potentially a little too specific .... as we will most likely add indicators that are not in the original package? 

True 'ICCLIM' indicators could simply be indicated as such in the help? ... e,g,  ' TXx - max of daily max temp as in ICCLIM package (link)'.   Index 'Y' with defintion as in 'Climdex/ETTCI' (link)
