### ISSUE TITLE
Nans are added when interpolation of adjustment factors for quantile mapping when grouper is 'time.month'

### ISSUE THREAD

**Issue by folmerkrikken** [Ouranosinc/xclim#1008]
* xclim version: 0.33.0
* Python version: 3.8.10
* Operating System: Ubuntu 20.04

### Description
Hi, thanks for this great package that I'm using a lot! I ran into a small issue with the quantile mapping routines which is most likely a bug. I'm applying the empirical quantile mapping (sdba.EmpiricalQuantileMapping) and found numerous 'NaN' values in the quantile mapped data which were not in the input data. This only happens when the group is `time.month` and I use either the 
`linear` or `cubic` interpolation method in the `.adjust` function. The nans are mostly present with values at the edge of distribution. Also when there is no trend (comment out `+ 0.1 * (t - t[0]).days / 365`) there are still 3 nans present.

### What I Did (minimum reproducable example)
Taking the example data from https://xclim.readthedocs.io/en/stable/notebooks/sdba.html

```
import numpy as np
import xarray as xr
import cftime
import matplotlib.pyplot as plt
from xclim import sdba

# Create toy data to explore bias adjustment, here fake temperature timeseries
t = xr.cftime_range("2000-01-01", "2030-12-31", freq="D", calendar="noleap")
ref = xr.DataArray(
    (
        -20 * np.cos(2 * np.pi * t.dayofyear / 365)
        + 2 * np.random.random_sample((t.size,))
        + 273.15
        + 0.1 * (t - t[0]).days / 365
    ),  # "warming" of 1K per decade,
    dims=("time",),
    coords={"time": t},
    attrs={"units": "K"},
)
sim = xr.DataArray(
    (
        -18 * np.cos(2 * np.pi * t.dayofyear / 365)
        + 2 * np.random.random_sample((t.size,))
        + 273.15
        + 0.11 * (t - t[0]).days / 365
    ),  # "warming" of 1.1K per decade
    dims=("time",),
    coords={"time": t},
    attrs={"units": "K"},
)

ref = ref.sel(time=slice(None, "2015-01-01"))
hist = sim.sel(time=slice(None, "2015-01-01"))



QM = sdba.EmpiricalQuantileMapping.train(
    ref, hist, nquantiles=15, group='time.month', kind="+"
)
scen = QM.adjust(sim, extrapolation="constant", interp="nearest")
print(f"{scen.isnull().sum('time').values} nans for nearest interpolation")

scen = QM.adjust(sim, extrapolation="constant", interp="linear")
print(f"{scen.isnull().sum('time').values} nans for linear interpolation")

scen = QM.adjust(sim, extrapolation="constant", interp="cubic")
print(f"{scen.isnull().sum('time').values} nans for cubic interpolation")

f,(ax1,ax2) = plt.subplots(2,1)
scen.isnull().plot(ax=ax1)

sim.plot(ax=ax2,color='k')
sim[scen.isnull()].to_dataset(name='scen').plot.scatter(x='time',y='scen',color='r')
```

### What I Received

```
0 nans for nearest interpolation
78 nans for linear interpolation
78 nans for cubic interpolation
```
![Screenshot from 2022-02-04 16-00-05](https://user-images.githubusercontent.com/35295222/152551352-6f456676-e500-4da9-b321-ceeda7e116c7.png)

Thanks, Folmer Krikken

**Comment by aulemahal** [comment]
Hi, 

Thanks a lot for the issue, I confirm I can replicate this on my end. I also confirm it disappears when using xclim 0.31.0, which points to #941 as the culprit for this regression...
I'll dig in today, this is high priority.

**Comment by aulemahal** [comment]
@folmerkrikken 

I found the bug, it was due to the new extrapolation method indeed. The monthly grouping case passed under my radar when implementing the new method, #1009 fixes the issue. If you are able to test your code against this branch, that would be nice.

**Comment by folmerkrikken** [comment]
@aulemahal 
Thanks for the quick fix. I've checked against this branch and I can confirm I no longer get the NaN's.
