### ISSUE TITLE
interpolate output of percentile_doy for indices using it.

### ISSUE THREAD

**Issue by sbiner** [Ouranosinc/xclim#101]

**Comment by huard** [comment]
@sbiner This seems to be done, correct ?

**Comment by sbiner** [comment]
Ça dépend. Il y a `xclim.utils.adjuts_doy_calendar` qui permet de d'interpoler les _percentiles_ d'un calendrier à l'autre et qui est utilisé dans `xclim.utils.percentile_doy`. Par contre pour les indices qui utilisent les _percentiles_ il n'y a pas d'ajustement fait, il faut le faire en amont. Il n'y a pas de check de cohérence de fait non plus ... On pourrait utiliser des _percentiles_ calculés pour un calendrier 360j avec  des données ayant un calendrier 365j et je pense qu'il n'y aurait pas d'erreur.

**Comment by Zeitsperre** [comment]
@sosnku Hi there, sorry to see that you're having trouble.

If you could open a "new issue" (green button on the top-right) and fill in a few of the details (operating system, xclim version, etc.) we'll be much more capable of helping you with this problem. From the looks of it, it could be a version issue (your xclim might be old) but I'm not sure.

**Comment by sosnku** [comment]
Thank you very much. I'm going to do it 





Get Outlook for Android







On Wed, Sep 16, 2020 at 4:07 PM +0100, "Trevor James Smith" <notifications@github.com> wrote:















@sosnku Hi there, sorry to see that you're having trouble.


If you could open a "new issue" (green button on the top-right) and fill in a few of the details (operating system, xclim version, etc.) we'll be much more capable of helping you with this problem. From the looks of it, it could be a version issue (your xclim might be old) but I'm not sure.
