### ISSUE TITLE
Helper Function to show results by global warming levels

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xclim#1014]
With CMIP6 models warming too quickly, the new trendy way to show data is by global warming levels, as done in the IPCC AR6 (see figure below). I  am planning on doing this for the Info-Crue CMIP6 project and I assume many other projects will do this.

It would be good to have a helper function to standardized how this is done at Ouranos (with flexible parameters but well thought-out defaults). I am thinking of a function that takes an array of global temperatures (lat, lon, time), does a global average and outputs the year when a given level of warming is passed. The user can calculate this year for different models for 1 threshold.  The function could go in xclim's "Other utilities"?

`year_when_we_pass_threshold = xc.core.utils.thresh_year_of_warming(tas, thresh, method, reference_period)`

Questions about the default method:
1. Which temperature dataset to use (tas, tos, etc)/ what to do over the ocean ?
2. Do we want the first time or the last time the threshold is passed?
3. Do we want to do a rolling mean over a time window before finding the threshold? Or the user just add a window around that year afterwards to get the data?
4. Should we include poles in the global averaging?
5. What reference period do we use?

![image](https://user-images.githubusercontent.com/29236239/153612456-ffda2dd7-35e5-444a-9746-e7debd2ebd78.png)

**Comment by juliettelavoie** [comment]
In the Ouranos webinar on February 9th, Chris McCray (@mccrayc) showed results by level of global warming. I reached out to him to ask about his methods. His answer is below. He also provided me with a code snippet of a function similar to what I am proposing here.

Je me suis surtout basé sur la méthode utilisé pour l’Atlas du GIEC https://github.com/IPCC-WG1/Atlas/tree/main/warming-levels qui est basée sur [Nikulin et al. (2018)](https://doi.org/10.1088/1748-9326/aab1b1). Ils ont utilisé des périodes de 20 ans, moi j’ai utilisé 30 ans pour le verglas étant donné que c’est un événement plus rare. J’ai mis en pièce jointe un document dans lequel j’ai copié collé du code du mon notebook (pas un script). En particulier il y a une fonction get_thresh_years qui sort le début/la fin d’une période de n années qui atteint le seuil x, ça pourrait servir d’inspiration pour une fonction xclim.
 
**As-tu utilisé juste tas  ou tas/tos?**
J’ai utilisé les fichiers sur le Github ([tas_landsea](https://github.com/IPCC-WG1/Atlas/tree/main/datasets-aggregated-regionally/data/CMIP5/CMIP5_tas_landsea), colonne « world »). J’ai pu reproduire exactement les mêmes valeurs en utilisant tas (les fichiers tas_Amon_*.nc dans nos répertoires CMIP5). J’ai inclus un exemple du code que j’ai utilisé pour calculer ces valeurs pour différents membres de l’ensemble CanESM - il y a seulement le premier membre de chaque GCM sur le Github.

**Est-ce que tu choisis la première fois ou la dernière fois où on passe le seuil de réchauffement?**
C’est calculé à partir de moyenne mobiles de 20 ou 30 ans et c’est la première fois qu’on passe le seuil, mais étant donné qu’on utilise la moyenne mobile la première fois est généralement la seule fois. Dans mon code tu verras que je calcule la moyenne mobile manuellement, je n’ai pas utilisé pandas rolling parce que je n’arrivais pas à  faire n-15, n+14 comme décrit dans Nikulin/le GIEC (seulement n-14, n+15) à cause d’un problème avec le paramètre closed=. C’est probablement possible de le faire.

**Est-ce que les pôles sont inclus dans la moyenne globale?**
Oui. La façon décrite dans le github du GIEC prend la moyenne globale après avoir interpolé tous les modèles sur la même grille de 2˚.

**Quelle période référence as-tu utilisée?**
1850-1900, la même utilisée par le GIEC

**Autres détails pertinents de ta méthode ?**
Non mais je te suggère de lire l’article de Nikulin et al. et la documentation du code GitHub, ces deux ressources m’ont beaucoup aidé.

**Comment by juliettelavoie** [comment]
1. I thought it couldn't be an indice because it doesn't have `freq` as an argument... but if you say it ok, it's fine by me.

2. It is part of the question. Do we want an option for taking 2 datasets and merging or the user has to provide one already merged? Do we want to force a cerain type of data/mask certain regions? I am not sure how to handle all that yet. I need to read more on how other people do it.

3. I am not sure I understand what you mean by "including too much spatial handling in xclim." ?

**Comment by aulemahal** [comment]
3. Simply that xclim is not the place to play with coordinate reference systems or with fancy GIS-like spatial averaging and all that jazz. Like, up to recently I would have said `da.mean('lat')`  is assuming too much, but we now have `cf-xarray`, so one can get the spatial dimensiosns from there instead of assuming.

**Comment by Zeitsperre** [comment]
Closed with https://github.com/Ouranosinc/xscen/pull/100
