### ISSUE TITLE
Importing custom indicator python module sometimes fail

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1020]
* xclim version: 0.33.2
* Python version: 3.9
* Operating System: linux

Issue found by @RondeauG , while using pycharm on doris.

### Description

When loading a virtual module with `xc.build_indicator_module_from_yaml`  and that some indices are declared in a custom python file, the module loading sometimes fail.

### What I Did

```python3
xc.build_indicator_module_from_yaml("module")
# where module.yml and module.py are files
```

### What I Received

```
ImportError: Indice function <name> not found in xclim.indices or xclim.indices.generic.
```

Two issues here:

1. This is not the correct error. If the python file exists but xclim fails to load it, the user should be explicitly warned.
2. It seems that `sys.path` does not _always_ include the local directory. Thus, the trick used by `xclim.core.utils.load_module` fails.

**Comment by RondeauG** [comment]
This seems to work (adapted from: https://stackoverflow.com/questions/63416336/import-module-from-different-directory-with-import-module)

```
  import os
  from pathlib import Path
  import importlib.util

  def load_module(path: os.PathLike):
      path = Path(path).absolute()
      try:
          spec = importlib.util.spec_from_file_location(path.stem, path)
          mod = importlib.util.module_from_spec(spec)
      except ModuleNotFoundError as err:
          raise err
      return mod
```

**Comment by aulemahal** [comment]
PR 1021 should fix this.

To document, the issue was that PyCharm handles the python PATH differently than the default interpreter, Ipython or jupyter. Instead of adding `""` to the path (the local directly, even when we change it with `os.chdir`), it adds the directory when the interpreter was started as an absolute path. I am guessing this behaviour is customizable, but still, it made `xclim.core.utils.load_module` fail.  As coco cat suggested here : https://stackoverflow.com/a/70757718/9291575, the builtin `importlib` library offers a more robust way of loading custom files like this.
