### ISSUE TITLE
Implement a "keep_attrs" argument when calculating variables

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xclim#1026]
**Is your feature request related to a problem? Please describe.**
When using xclim to calculate a new variable (e.g. `tasmin/tasmax --> tas`), some essential attributes such as `grid_mapping` are lost.

**Describe the solution you'd like**
A "keep_attrs" functionnality could be added, which would compare the attributes of the old and new variables and re-add any missing one. My main issue is with `grid_mapping`, but other similar attributes might be lost too.

**Comment by huard** [comment]
@RondeauG Could you clarify what exactly is needed here? Some of the data you mention are non-coordinate DataArrays, so cannot be embedded within the output of xclim indicators.

**Comment by RondeauG** [comment]
I'm not talking about the grid mapping variable itself, but rather, the `grid_mapping` attribute that is often added under a variable. https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#grid-mappings-and-projections. `{"grid_mapping": "rotated_pole"}` in the example below.

```
variables:
  float T(lev,rlat,rlon) ;
    T:long_name = "temperature" ;
    T:units = "K" ;
    T:coordinates = "lon lat" ;
    T:grid_mapping = "rotated_pole" ;
```

The problem is that currently in `xclim`, an indicator calculated from `T` would lose the `grid_mapping` attribute.

**Comment by aulemahal** [comment]
Oh nice, so a first simple step would simply to add some lines in the indicator's `__call__`:

if the global "keep_attrs" option is set to true (our own or xarray's ?):
    - Combine attrs from all inputs (with the ["drop_conflicts" strategy](https://docs.xarray.dev/en/stable/generated/xarray.merge.html#xarray-merge))
    - Update all outputs with those attrs.
    - Update with xclim-computed attrs.
