### ISSUE TITLE
PCC indicators

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#103]
### Description

Indicators used by PCC. Should we plan their inclusion ? 

Variable | Description | Importance
-- | -- | --
Coldest Minimum Temperature | The very coldest temperature of the year. | Affects safety, recreation,  buildings, transportation, energy use, etc. 
Cooling Degree Days | Annual sum of the number of degrees Celsius that each day’s mean temperature is above 18 °C. | Often used to estimate how much air-conditioning is required in a year. An increase implies hotter or longer summers
Corn Heat Units | Temperature index used by farmers for when it’s ideal to grow corn. | Used by farmers and agricultural researchers to make planting decisions and maximize production.
Date of First Fall Frost | The earliest date in the autumn when temperatures drop below freezing. | Marks the approximate end of the growing season and indicates the return of cold weather.
Date of Last Spring Frost | The latest date in the spring when temperatures drop below freezing. | Marks the approximate beginning of growing season and indicates the return of warm weather.
Freeze-Thaw Cycles | Total number of days per year when temperatures fluctuate between freezing and non-freezing. | Can have major structural impact on infrastructure such as roadways, sidewalks, etc.
Freezing Degree Days | Annual sum of the number of degrees Celsius that each day’s mean temperature is below 0 °C. | High values are associated with relatively cold conditions, and indicate many days with temperatures significantly below freezing.
Frost Days | Total number of days per year when the coldest temperature of the day is less than 0°C. | These conditions indicate frost might form at ground level or on cold services.
Frost-Free Season | Interval between the first frost of the fall and the final frost of the spring. | Indicates when no freezing temperatures occur that might kill or damage plants or animals.
Growing Degree Days (5, 10, 15 °C) | Index of heat available for organisms (such as plants and insects) for growth. | Helpful for crop selection, insect control, and other management.
Heating Degree Days | Annual sum of the number of degrees Celsius a given day's mean temperature is below 18 °C. | Often used as a measure of how much heating is required in a year.
Heavy Precipitation Days (10mm / 20mm) | Total number of days per year when at least 10 mm or 20 mm of rain or frozen precipitation falls. | Heavy rainfall can impact storm drains, flooding, erosion, roads, etc
Icing Days | Total number of days per year when the warmest temperature of the day does not go above freezing (0 °C). | Indicator of the length and/or severity of the winter season, which affects human health and safety, recreation, heating costs, and more.
Maximum Temperature | The highest temperature of the day. | The temperature range we expect within a season or year is a very important aspect of climate. Changes in average and extreme temperatures can dramatically affect our everyday lives as well as a wide range of planning and policy decisions.
Mean Temperature | The average temperature of the day. | idem
Minimum Temperatures | The lowest temperature of the day. | idem
P-Days | Temperature index used by farmers for when it’s ideal to grow potatoes. | Often used by farmers and agricultural researchers to maximize production.
Precipitation | Total annual amount of rain, drizzle, snow, sleet, etc. | Affects water availability, crop viability, hydroelectric power generation, fire risk, snow accumulation, flooding, and drought.
Summer Days | Total number of days per year when the temperature rises to at least 25°C. | Increased health risks to vulnerable people, limits outdoor recreation, increased energy use, increased drought and fire risk, changes to ecosystems and biodiversity, etc. 
Tropical Nights | Total number of days per year when the lowest temperature of the day does not go below 20°C. | idem
Very Cold Days (-30 °C) | Total number of days per year when the temperature drops to -30°C or below. | Indicator of winter severity that affects health, safety, recreation, ecosystems, etc.
Very Hot Days (+30 °C) | Total number of days per year when the temperature rises to at least 30°C. | Increased health risks to vulnerable people, limits outdoor recreation, increased energy use, increased drought and fire risk, changes to ecosystems and biodiversity, etc.
Warmest Maximum Temperature | The highest temperature of the year | idem

**Comment by Zeitsperre** [comment]
I was thinking the same thing when I saw the email. There's more than a few here that are already in xclim. I'm familiar with the methods for the agroclimate indicators (GDD, CHU, CDD) and wanted to integrate them anyway.

**Comment by cothel** [comment]
Plusieurs de ces indicateurs font partie de l’Atlas agroclimatique du Québec.
Suite à l’évaluation de l’atlas, les usagers nous on demander la possibilité d’utiliser des seuils différents.
Par exemple :
pour Frost days ( 0deg C) – garder le seuil de 0 mais  inclure la provision pour utiliser une autre température gélive,
pour Growing Degree Days – garder 5,10, 15 deg C mais  inclure la provision pour utiliser une autre température gélive
C’est peut-être déjà, sinon je vous garantis que l’effort additionnel sera rentable.

Hélène

----------------------------------------------------------
cote.helene@ouranos.ca<mailto:cote.helene@ouranos.ca>   Tel: (514) 282-6464 poste 260
                                           Fax: (514) 282-7131
----------------------------------------------------------
Hélène Côté, MSc
Spécialiste
Groupe Simulations et analyses climatiques
Ouranos
550, Sherbrooke ouest, 19e étage, tour ouest
Montréal, Qc, CANADA H3A 1B9
http://www.ouranos.ca/

Consultez le document de synthèse « Vers l’adaptation »
https://www.ouranos.ca/synthese-2015/


De : Trevor James Smith <notifications@github.com>
Répondre à : Ouranosinc/xclim <reply@reply.github.com>
Date : jeudi 8 novembre 2018 à 13:08
À : Ouranosinc/xclim <xclim@noreply.github.com>
Cc : Subscribed <subscribed@noreply.github.com>
Objet : Re: [Ouranosinc/xclim] PCC indicators (#103)


I was thinking the same thing when I saw the email. There's more than a few here that are already in xclim. I'm familiar with the methods for the agroclimate indicators (GDD, CHU, CDD) and wanted to integrate them anyway.

**Comment by huard** [comment]
Bien reçu, les seuils sont paramétrables.

**Comment by huard** [comment]
@cothel Pourrais-tu créer un issue avec la liste des indicateurs de l'atlas pour qu'on garde ça dans notre liste d'épicerie ?

**Comment by tlogan2000** [comment]
Most of these seem pretty doable, and would increase usability of XCLIM (both independantly and via PAVICS).  We already have matlab code for Corn Heat Units and other agroclimat atlas variables to start from

**Comment by Zeitsperre** [comment]
I realize it's shameless self-promotion, but these are a few others that could be interesting to add in https://github.com/Zeitsperre/wine-climatology. The scripts are written for PyQGIS, but the methods are clear in the literature. 

Not having to handle the calendar-based resampling with xarray makes these much easier to write out.

**Comment by tlogan2000** [comment]
Document avec les calculs / defintions de l'atlas agropclimatique
http://www.agrometeo.org/atlas/display_guide/Formules_atlas_agroclim_2012_v10.docx

**Comment by huard** [comment]
Excellent ! Travis, veux-tu mettre un milestone là-dessus ? Genre 1.2 ?

**Comment by tlogan2000** [comment]
1.2 engage! 
![image](https://user-images.githubusercontent.com/22454970/48224546-13050480-e368-11e8-8c9e-63feca451322.png)

**Comment by Zeitsperre** [comment]
@huard Would you be interested in me working on this in the next few weeks?

**Comment by huard** [comment]
@Zeitsperre My sense of priorities is a bit off at the moment, but I would rather spend efforts on cleaning the THREDDS server's content. Additional indicators can be added on an *as the need arise* basis.

**Comment by huard** [comment]
@Zeitsperre 
I suggest here we create a mock module (similar to ICCLIM), with this list of indices. Seems like a low-hanging fruit.

**Comment by tlogan2000** [comment]
I'm not convinced that this is really that useful unless we start coding the missing indicators (mostly for agricultural applications from what I see).   To me the low hanging indicators overlap heavily with ICCLIM ... for which we already have the mock module which has a lot more name recognition.
 
Are their users that are that familiar with PCC's definitions and thrshold choices that we need to create a module specifically for this?  Also a new 'PCC' module would bring yet another flavor to xclim (along with atmos and ICCLIM) and  i think it might start becoming confusing

**Comment by tlogan2000** [comment]
I think a dedicated agricultural module including the missing things like corn heat units etc etc would be more interesting

**Comment by Zeitsperre** [comment]
I have plans for this already. It needs a few more very specific indices.

**Comment by huard** [comment]
I guess my thinking was to make it easy for the PCC to use xclim by clarifying the mapping between xclim's indicators and theirs. Agree this has a very limited use outside the PCC and we could provide them with the mock module offline.

**Comment by tlogan2000** [comment]
Could we possibly have 'targeted' notebooks appearing in pavics jupyter instances?  I don,t think they should necessarily be in the 'read the docs' for pavics-sdi but could be available in the tutorial notebooks for individual users on the jupyter hub..  not sure
 
Example : I am working on an notebook for climatedata.ca to show the various steps in the calculations (in reallity for D. Caron so he can reproduce the outputs via the analysis page) but this could be useful as a workflow example for our jupyter users

Something similar could be done here for PCC... i.e. the mapping of xclim calcs for the PCC calculations
