### ISSUE TITLE
Disable logging in xclim.ensembles module?

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#1039]
### Generic Issue

When importing `clisops.subset.core` and `xclim.ensembles` the logging output in the xclim.ensembles is somehow always sent to the console, or worse, to the jupyter notebook output window.    

@Zeitsperre has been digging into this (see https://github.com/roocs/clisops/pull/216) but I am wondering just how critical it is to have a logger at all?  

Notes - this seems to be the only submodule where a logger is used and as far as I can tell and only keeps track of 1) whether matplotlib is installed or not (for ensemble reduction graphs) or 2) which simulation is being accessed in the loop for the ensemble creation.   

### Code of Conduct

- [X] #1040

**Comment by huard** [comment]
Ok to scrap logging.

**Comment by Zeitsperre** [comment]
I'm OK as well for commenting the existing calls out, but this would be a good opportunity to drop-in [`loguru`](https://github.com/Delgan/loguru) in its stead.

**Comment by aulemahal** [comment]
Ok to scrap clisops.
