### ISSUE TITLE
Inclure des seuils paramétrables pour les différents indicateurs

### ISSUE THREAD

**Issue by cothel** [Ouranosinc/xclim#104]
Plusieurs indicateurs utilisent des seuils prédéfinis (ex Frost Days, Growing Degree Days, etc). En plus de ces seuils existants, il serait pertinent, et hyper utile dans les années à venir, d'inclure la provision d'utiliser des seuils différents (user-defined).
C'est une demande très forte du _Bilan de l'utilisation de l'Atlas agroclimatique_ du Québec.
Merci

**Comment by tlogan2000** [comment]
Oui. Tout les indicateurs dans XCLIM utilisant des seuils ont la possibilité de definir un seuil 'custom'.  Le defaut on utilise un seuil definie par ICCLIM (ou via une description 'classique') mais il y a possibilité d'envyer un threshold en input

**Comment by huard** [comment]
L'enjeu est que la description des indicateurs dépend parfois du seuil. Par exemple, si on paramétrise le seuil dans frost days et que quelqu'un met 25C, on ne parle plus de frost days du tout. 

Bref, je pense qu'on pourrait argumenter pour avoir des indicateurs génériques avec seuils paramétrables, et des indicateurs "thématiques" avec seuils prédéfinis.

**Comment by Balinus** [comment]
D'accord avec la solution proposée. On pourrait simplement définir :

`custom_threshold(DataArray, operator = ">20")` ou qqchose de similaire.

**Comment by cothel** [comment]
Je suis aussi relativement d'accord avec la proposition de David mais je sais que pour les indices agroclimatiques, les besoins seront très variés avoir diverses températures gélives pour les Frost days, différents seuils pour les saisons de croissance / DJ de croissance, et finalement les seuils de tasmax pour les températures chaudes. Je pense que même les indices thématiques auront besoin d'un peu de flexibilité (avec un test / flat pour les valeurs custom incongrues ?).

**Comment by huard** [comment]
Options:
- Offrir un seuil variable pour frost_days sans contrainte: risque de confusion si le nom de le variable et le seuil choisi n'ont pas rapport
- Offrir un seuil variable pour frost_days avec contrainte (genre -10 à 0). 
-  Offrir dans la fonction générique la possibilité de personnaliser les métadonnées pour que l'utilisateur puisse assigner un sens à l'indicateur, genre
`custom_threshold(da, operator="<2", long_name="seuil gélif pour le bleuet des bois") `

**Comment by cothel** [comment]
J'aime bien les deux dernières suggestions de David: 
-seuil variable avec contrainte
- fonction générique avec personnalisation des métadonnées
Ce sont de bons compromis entre "flexibilité" et "réduire le potentiel d'incohérence"

**Comment by huard** [comment]
See https://github.com/Ouranosinc/xclim/pull/144 for a start.

**Comment by Zeitsperre** [comment]
@huard I feel like most of our indicators follow this approach. Good to close?
