### ISSUE TITLE
In `{cold, warm}_spell_duration_index` indicators description, the percentile threshold is not dynamically set.

### ISSUE THREAD

**Issue by bzah** [Ouranosinc/xclim#1047]
### Setup Information

- Xclim version: 0.35
- Python version: all
- Operating System: all

### Description

I tried to compute `cold_spell_duration_index` with, instead of the 10th percentile, the 5th percentile.
The result looks good however, in the description attribute, hard-coded values are used for "10th percentile" and for "a 5-day window". 
Both the percentile threshold and the window are parameters of `percentile_doy` and should not be hard-coded.

`percentile_doy` returns a DataArray, we could store these parameters in its attributes (actually the window is already in them).
Then, the Indicator formatter could trace back these and properly format the indices.

This issue exists for at least `cold_spell_duration_index` and `warm_spell_duration_index`. I haven't check if other indices could be impacted by this.

### Steps To Reproduce

```
da = xr.open_dataset("tas.nc").tasmax
per = percentile_doy(da, window=5, per=5)
csdi = cold_spell_duration_index(da, tn10=per, freq="YS", bootstrap=False)

# assert fails
assert "5th percentile" in csdi.attrs["description"]
```

### Additional context

I already tried to implement something but it needs more effort than initially expected. Thus, I prefer to make sure this feature/bug-fix is worth before continuing to work on it.

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Indeed, we don't have a generic mechanism for now... I don't see a better solution than writing a special case in `Indicator.format` for this.  This would require that we recognize inputs that are percentile thresholds, which might mean a new entry to `xclim.core.utils.InputKind`. Then `format` could parse the coords of this input and create a "{var_name)_percentiles" variable to send to the formatter?

There might be caveats:
`percentile_doy` accepts lists of percentiles, what would you do in that case?

**Comment by bzah** [comment]
> This would require that we recognize inputs that are percentile thresholds

I think that's quite easy, we already do this kind of stuff in bootstrapping.py,we use the following reasoning: input must be a DataArray and have "percentile_doy" string in its history. We could also use the DataArray `attrs` and make sure it contains `climatology_bounds` for example. However, these assume that percentile were computed with xclim percentile_doy function.

> Then format could parse the coords of this input and create a "{var_name)_percentiles" variable to send to the formatter?

That's almost what I tried, in `_parse_variables_from_call` I tried to add entries in `params` such as `{"per_thresh": 5}` and use it in the Indicator description but it fails because `per_thresh` is not part of the "indice" function signature.

> There might be caveats:
percentile_doy accepts lists of percentiles, what would you do in that case?

I think a description like `[...] the daily minimum temperature is below the [5, 10]th percentile(s) [...]` would be understandable.


For the record, from icclim p.o.v it came up with a workaround by replacing the `xth` string with a regex.
