### ISSUE TITLE
Doc update

### ISSUE THREAD

**Issue by cyndyfem** [Ouranosinc/xclim#1054]
### Setup Information

- Xclim version: 0.35.0
- Python version:3.9.9
- Operating System:Ubuntu 20.04

### Context

HI,
Thanks for this wonderful tool.
I was trying to Bias Correction (https://xclim.readthedocs.io/en/stable/notebooks/sdba-advanced.html) but it seems the examples here are not updated. I have also noticed that in some other examples in the document.
For example,
sdba.processing.to_additive_space seems to be unavailable anymore,
same as sdba.processing.jitter, sdba.processing.from_additive_space e.t.c.

Perhaps, there is a list somewhere detailing these changes and what replaced them.

thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
I'm not sure what your environment setup is, but if Jupyter is not installed in the same environment as xclim (e.g. Jupyter installed in /usr/ and xclim via Anaconda), the libraries won't be available. 

If you continue having issues related to the dataset dimension output, feel free to open a new issue detailing the problem with the stack trace.

Best of luck!
