### ISSUE TITLE
ANUCLIM indice names/descriptions are inconsistent

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1055]
### Setup Information

- Xclim version: 0.35
- Python version: 3.9
- Operating System: Fedora 35

### Description

The ANUCLIM indices don't have a consistent naming mechanism (see: https://xclim.readthedocs.io/en/stable/indicators.html#id1). It would be good to make them more uniform.

### Steps To Reproduce

--

### Additional context

--

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
I'm not sure I see what you mean here?
The `PX_` prefix is consistent, no? The rest of the names is indeed our own creation, but ANUCLIM doesn't provide real short names, AFAIK.

**Comment by Zeitsperre** [comment]
Prefix is fine, I mean the docstrings themselves. Most of them begin with `ANUCLIM` while others are either very short or too long. Very simple fixes.

**Comment by huard** [comment]
I suggest removing ANUCLIM from the name.
