### ISSUE TITLE
sdba.ExtremeValues sets larger extremes to nans.

### ISSUE THREAD

**Issue by juliettelavoie** [Ouranosinc/xclim#1056]
### Setup Information

- Xclim version: 0.34.1-beta
- Python version: 3.9.10
- Operating System: macOS Monterey version 12.3.1

### Description

I was trying to use the `xclim.sdba.ExtremeValues` to do some bias correction of extreme precipitation. The 16 larger values in the raw simulation turned to NaN after the bias correction...

The NaNs seem to appear on l.397 of `sdba/_adjustement.py`. I think the problem is in ` _interp_on_quantiles_1D` of `sdba/utils.py`. The 16 larger values require an extrapolation. Unfortunately, `fill_value` takes the value at the first and last quantile (` fill_value = (oldy[0], oldy[-1])` on l.317). This is fine with `quantile mapping` when all space is used, but in `ExtremeValues` the `quantiles` dimension is filled with NaNs in the spaces that we don't end up needing. If `fill_value` were to take the last non-nan value instead, I think the problem would be fixed.

### Steps To Reproduce

I can send you the workdir in private.
```
ds_scen_qm = xr.open_zarr(f'{workdir}/A10_RCP45_R41_qc_pr_half_biasadjusted.zarr',decode_timedelta=False).pr.isel(loc=0).load()
ds_sim = xr.open_zarr(f'{workdir}/A10_RCP45_R41_qc_regridded.zarr', decode_timedelta=False).pr.isel(loc=0).load()
ds_tr = xr.open_zarr(f'{workdir}/A10_RCP45_R41_qc_pr_training_ex.zarr', decode_timedelta=False).isel(loc=0).load()

ds_sim=convert_calendar(ds_sim, 'noleap')

ADJ = sdba.adjustment.TrainAdjust.from_dataset(ds_tr)

sim_period = slice(*map(str, ['1980','1985']))

out = ADJ.adjust(ds_sim.sel(time=sim_period), ds_scen_qm.sel(time=sim_period) )
print('out')
print(out.sel(time='1982-09-06').values) --> NAN
print(ds_sim.sel(time='1982-09-06').values) --> Really big
```

### Additional context

I think it could be fixed by `fill_value = (oldy[~np.isnan(oldy)][0],oldy[~np.isnan(oldy)][-1])` .

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Dang it. I did have a similar problem and fixed it in a similar case, but I only applied the fix for the 2D case (meaning with a time grouping)... 
There is  `sdba.nbutils._first_and_last_nonnull` that does that. But the use of numba may not be necessary here.

**Comment by juliettelavoie** [comment]
I think `_first_and_last_nonnull` might be overkill.. `oldy[~np.isnan(oldy)]` seems to do the trick. Is there a special case I am not thinking of ?

**Comment by aulemahal** [comment]
I'm not 100% sure, but I think the reason this function exists is because when `oldy` is 2D, the intuitive numpy way is either not numba-compatible, slower, or both. But we're not using numba in the 1D version, so it is irrelevant.
