### ISSUE TITLE
Proposal: migrate xclim typing to python 3.10 style

### ISSUE THREAD

**Issue by bzah** [Ouranosinc/xclim#1065]
### Generic Issue

* xclim version: 0.35.x
* Python version: 3.8
* Operating System: all

### Description

Follow up to this discussion: https://github.com/Ouranosinc/xclim/pull/1050#discussion_r859897719

The [__future__ module](https://docs.python.org/3/library/__future__.html#module-__future__) allows to access some of the latest features of python without needing to increment the minimal python requirement of xclim.

In [PEP604](https://peps.python.org/pep-0604/) for python 3.10, a new type hint syntax has been added. It is made available on older python version by starting modules with the statement `from __future__ import annotations` .
Basically, it replaces `Union` and `Optional` keywords by the pipe operator such: `data: str | int | None`
I believe this makes the typing much more readable and pleasant to use.

It also allows some forward referencing such as:
```
from __future__ import annotations

class Cacahuete()

   @classmethod
   def from_generic_food(food) -> Cacahuete: # Without annotations this would need to be a `-> Any` or a string `-> "Cacahuete"`
      return Cacahuete(food)
```

And it removes the need of most imports from `typing` module by allowing to use python types directly:
`def my_func(a: List[str], b: Optional[Tuple[int]]) -> Dict[str]:    pass `
becomes
`def my_func(a: list[str], b: tuple[int] | None) -> dict[str]:    pass `

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
I personally see no problem with this approach. `__future__` with the `annotation` module is available in the standard libraries for all currently-maintained Python implementations. 

An orchestrated push towards adopting this new PEP would be a great opportunity to fully type our code base, including classes. I'd love to see xclim become fully `mypy`-compliant in the future.

I'd like to propose we add this to the xclim 0.37 milestone.

**Comment by huard** [comment]
What are the minimum patch versions with support for this? 

3.8.x ?
3.9.y ?

**Comment by Zeitsperre** [comment]
https://stackoverflow.com/questions/72092848/how-does-one-determine-the-minimum-patch-version-of-python-supporting-a-future

**Comment by bzah** [comment]
I got lazy and wrote a script to update every .py file which don't already have `from __future__ import annotations` and are not empty (case of __init__.py).
It relies on `fsspec` but this library comes with dask.

```
def truc():
    from fsspec.implementations.local import LocalFileSystem
    from functools import reduce
    fs = LocalFileSystem()
    IMPORT_STATEMENT = "from __future__ import annotations"
    for file_path in filter(lambda f: f.endswith(".py"), fs.find("./xclim", 20)):
        with fs.open(file_path, "r") as file:
            content = reduce(lambda a,b : a+b, file.readlines(), "")
            if IMPORT_STATEMENT in content or content == "":
                continue
        with fs.open(file_path, "w") as file:
            file.write(f"{IMPORT_STATEMENT}\n\n"+content)

```
If right after the script you run `pre-commit run -a`, pyupgrade will transform typing everywhere to the new syntax.
Then there are a few minor issues reported by black that must be handled manually. On icclim it was only unused imports of the `typing` module.

I can submit a PR with this but, I'm pretty sure it will create quite a big diff, so you probably want to do it whenever you feel it will not generate too many conflicts with the ongoing work.

**Comment by Zeitsperre** [comment]
@bzah 

That's a really neat algorithm! I could see something with that type of functionality being integrated into `pyupgrade` on its own! I'd encourage you to open an issue at the very least about it.

From the StackOverflow discussion, I gather that syntax rules allowing for this have been in Python since 3.7.0 (i.e.: [PEP 563](https://peps.python.org/pep-0563/)). If we want to adopt this syntax with the help of `__future__` I see no major issues. The `pre-commit` setting for `pyupgrade` is set for `"py38-plus"` so we also don't have to worry about `__future__` imports being removed automatically if the base python used to run the hooks is Python3.10.

Feel free to open a PR and mark me as a reviewer. We'll aim to migrate these changes in when the number of open PRs descends a bit, ideally for the next minor version.

Thanks again!

**Comment by bzah** [comment]
@Zeitsperre Ha! it seems this feature was discussed recently on pyupgrade: https://github.com/asottile/pyupgrade/issues/618

Obviously a solution already exist and I re-invented the wheel with my script, at least I had fun doing it !
