### ISSUE TITLE
Add "Celsius" to pint registry

### ISSUE THREAD

**Issue by bzah** [Ouranosinc/xclim#1067]
### Generic Issue

* xclim version: 0.36

### Description

The [E-OBS datasets](https://climexp.knmi.nl/showmetadata.cgi?field=ensembles_025_tg_mo&id=someone@somewhere) sometimes uses "Celsius" unit. It is not the standard way of writing this unit and therefore is not accepted by xclim due to the capitalized 'C'.

As it is seems to be a commonly used datasets, I would like to add "Celsius" in the pint unit registry.

# Proposed changed
In units.py, update the corresponding alias to `units.define("@alias degC = C = deg_C = Celsius")`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
I agree with this. You might want to also open an issue/PR in `cf-xarray`. Our goal is to upstream the unit handling there when some issues about formatting are solved. But if they don't want to include, we can always add the alias here.

**Comment by Zeitsperre** [comment]
Related: #890

**Comment by huard** [comment]
I suggest to make a PR here for this, so we have a fix for this fairly quickly, and then follow-up with cf-xarray to future proof this.
