### ISSUE TITLE
date bounds with xclim.indicators.atmos.precip_accumulation

### ISSUE THREAD

**Issue by rb4844** [Ouranosinc/xclim#1069]
### Setup Information

- Xclim version: '0.35.0'
- Python version: 3.9.12
- Operating System:  Linux

### Context

Trying to use this command:

pr_mam = xclim.indicators.atmos.precip_accumulation(pr=pr, freq="YS", date_bounds=("03-01", "05-31"))

but get this error:

TypeError: got an unexpected keyword argument 'date_bounds'

I have used date_bounds successfully elsewhere and dit should work with this diagnostic?

Thanks.

Roger Bodman

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Hi Roger,

I completely agree with your intuition that this _should_ work. However, these "indexer" arguments were added to indicators fairly recently and they have not yet been implemented everywhere. Some indicators have issues where the default way of indexing the data would lead to wrong results, and this is why we only pushed the feature on a small subset of indicators.
But there are no reason for `precip_accumulation` not to have this. 

We'll try to push something for the next release.

**Comment by bzah** [comment]
>Some indicators have issues where the default way of indexing the data would lead to wrong results,

@aulemahal could you give an example of such case ?

**Comment by rb4844** [comment]
Hi Pascal,

Thanks for your reply and the information on how to check the indexer argument.  Look forward to next release!

Regards,

Roger

Dr Roger Bodman
Climate Scientist and Data Analyst, Regional Projections
Oceans and Atmosphere  |  CSIRO
E ***@***.*** M 0433 963 322 W 9239 4437


From: Pascal Bourgault ***@***.***>
Date: Thursday, 5 May 2022 at 1:33 am
To: Ouranosinc/xclim ***@***.***>
Cc: Bodman, Roger (O&A, Aspendale) ***@***.***>, Author ***@***.***>
Subject: Re: [Ouranosinc/xclim] date bounds with xclim.indicators.atmos.precip_accumulation (Issue #1069)

Oh, for the time being you can see which indicator accept the date_bounds, month, doy_bounds or season arguments by looking at their docstring. Look for the **indexer argument in the signature or in the "parameters" section of the docstring.

In a IPython interpreter or jupyter cell : xc.atmos.<indicator>?
In a basic python interpreter: help(xc.atmos.<indicator>)
Or programmatically:

'indexer' in xc.atmos.<indicator>

**Comment by bzah** [comment]
> All the "spells": when we ask to count the spells within a given period, should we allow them to start before or after said period

What would happen in edge cases such as consecutive_frost_day in Antarctica or dry_spell_total_length in the Sahara ? How far in the past should this approach try to find a start for the spell ?

IMHO, user interested in a specific period, say JJA, may not want to have side effects coming from data outside this period. If he/she needs a "safety net" around the period of interest, one could simply widen the studied period with `date_bounds=("05-15", "09-15")` (for JJA case) no ?

**Comment by bzah** [comment]
@aulemahal It seems Christian, as well others researchers (from SMHI) agree with you that spells beginning before the season start should be taken into account.
