### ISSUE TITLE
Indicator class masking when no-nans present

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#109]
Using my dev branch it seems the missing_any() call masks my test result even when there are no nans in my synthetic data.  Output is fine before missing_any is called in the univariate indicator class 
I don't quite follow how missing_any() is working.

branch:

https://github.com/Ouranosinc/xclim/tree/Add_IndicatorClasses

in test_temperature.py : TestConsecutiveFrostDays fails as it gives me an output of [nan] when I expect [1] 
```python
class TestConsecutiveFrostDays:

    def test_one_freeze_day(self, tasmin_series):
        a = np.zeros(365) + K2C + 5.0
        a[2] -= 20

        ts = tasmin_series(a)
        out = temp.consecutive_frost_days(ts)
        np.testing.assert_array_equal(out, [1])
```

**Comment by tlogan2000** [comment]
In the missing_any() code these lines seem to be the culprit

```python
p = c.indexes['time'].to_period()
n = (p.end_time - p.start_time).days + 1
```
Note that the frost days default frequency is 'AS-JUL' but the 'p' value from above gives 'A-DEC':

"PeriodIndex(['2000'], dtype='period[A-DEC]', name='time', freq='A-DEC')"

and p.start_time / p.end_time of '2000-01-01' and '2000-12-31'

Year 2000 being a leap year it then results in n == 366 ... one day longer than my test data

**Comment by tlogan2000** [comment]
need to provide the freq to the .to_period() I think
Doesn't play nicely with 'S' though e.g. would need to send A-JUN instead of AS-JUL

**Comment by huard** [comment]
Reached the same conclusion. Writing a "to_period_freq" conversion function.

**Comment by huard** [comment]
Should be fixed in your branch.

**Comment by tlogan2000** [comment]
cool thx

**Comment by huard** [comment]
Can be closed ?

**Comment by tlogan2000** [comment]
yes
