### ISSUE TITLE
Move function reference targets into module docstrings

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1094]
### Addressing a Problem?

ReadTheDocs gives us [A LOT of warnings](https://readthedocs.org/projects/xclim/builds/16969326/) due to the way we've handled references to date. 

We make good use of the `References` fields of function to place target references but often we repeat ourselves when the same reference is used across multiple indices/functions, thus causing duplicate label warnings.

### Potential Solution

I would like to see the reference targets (ie: `.. [Ipsum&Mit2022] Ipsum, L., D. Mit. (2022)...`) at the module level so that we can track all references used in a particular module.

### Additional context

Resolving this particulr issue would allow us to enable `fail_on_warning` for our RtD builds, allowing us to know right away if there are documentation-affecting build issues (bad references or hyperlinks, specific pages failing to be built, notebooks failing to load, etc.)

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
What do you think of : https://sphinxcontrib-bibtex.readthedocs.io/en/latest/quickstart.html
I.e.: Moving ALL references to a single bib file and a single bibliography page. Citing them in docstrings and rsts with `:cite:blabla`.
