### ISSUE TITLE
what's the correct format to compute TX90p

### ISSUE THREAD

**Issue by Patty-Lyn** [Ouranosinc/xclim#1097]
### Setup Information

- Xclim version:
- Python version:
- Operating System:

### Context

Hi, I have tried several method to try to compute the TX90 in JJA and DJF from 1950-2021, with the base_period from 1961-1990, but I failed to do so and got different errors, may I ask how to compute the TX90 correctly?

My codes are below:
tas_ref = tas.sel(time=slice('1961-01-01','1990-12-31'))
t90 = percentile_doy(tas_ref,window=5,per=90).
tx = tg90p(tas, t90=t90.sel(percentile=90),freq='YS',bootstrap=True,season='JJA',drop=True)

Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tlogan2000** [comment]
@Patty-Lyn could you possibly provide the error output ?

**Comment by aulemahal** [comment]
Hi @Patty-Lyn !

Your code looks good, but I think you are hitting issue #1091. I'm only guessing; if you give us the version of xclim you are using and an example of an error message, we could help narrow down the problem. And eventually fix it if it's a bug.

If my guess is right, this means you can't use the `season`  argument when using `bootstrap=True`. This is a limitation of xclim that we need to fix. However, depending on your needs you could very easily work around it:

```
tas_ref = tas.sel(time=slice('1961-01-01', '1990-12-31'))
t90 = percentile_doy(tas_ref, window=5, per=90)
txSEAS = tg90p(tas, t90=t90.sel(percentile=90), freq='QS-DEC', bootstrap=True)

txJJA = txSEAS.sel(time=txQ.time.dt.month==6)
txDJF = txSEAS.sel(time=txQ.time.dt.month==12)
```
Where I computed the `tg90p` indicator seasonally and then extracted the summer and the winter into their own variables, dropping spring and fall that i computed unnecessarily. 

`txJJA` is the same data as what your code would have given without the issue, except that the time coordinate is an annual series on the 1st of june. (instead of the 1st of january).

--
You might know, but note that for the DJF series, your code would have to use `freq='AS-DEC` to make sense and it would output the exact same thing as my example here. If you use YS, it means you are starting the year with january first, and thus for year X, the data from january, february and december are used. With my technique or with `freq='AS-DEC', season='DJF'`, then you're using december of year X, january and february of year X+1, which makes most sense.

**Comment by bzah** [comment]
Hi! 

@aulemahal It looks like #1091 indeed but, it breaks in cases I did not expect. 
I think here it's the combination of `bootstrap=True` and `drop=True`.
When running bootstrap=True, the bootstrap algorithm calls multiple time tg90p on an altered versions of the input dataset.
However, with `drop=True` this input dataset is already truncated to JJA subset, so there is only 93 values per year.
In that case, it breaks in`resample_doy` called within tg90p and not in `percentile_doy` like in #1091.


To fix both, I guess we could avoid calling  `_interpolate_doy_calendar` when the calendars match ?
```
# Instead of doing:
if doy_max_source == doy_max:
   return source
# We could do:
if target.dayofyear == source.dayofyear:
   return source
```

By the way, there is another broken case, when both drop and bootstrap are False:
```
xclim.atmos.tg90p(da,
         tas_per=t90.sel(percentiles=90),
         freq='YS',
         bootstrap=False,
         season='JJA',
         drop=False
 )
```
It's different, it's an issue in missing.py::is_null function which adds `drop=True` to the select_time call.
Instead, I think we should do `indexer.update({"drop": True})` to avoid this issue. 

I can try to make a PR to fix both issues.


@Patty-Lyn As a workaround until those are fixed, if you don't mind having NaNs in your output, you can remove `drop=True` from your call:
```
xclim.atmos.tg90p(da,
         tas_per=t90.sel(percentiles=90),
         freq='YS',
         bootstrap=True,
         season='JJA',
         # drop=False
 )
```



I'm willing to work on a fix, it also breaks in icclim anyway (https://github.com/cerfacs-globc/icclim/issues/178)

**Comment by Patty-Lyn** [comment]
> Hi @Patty-Lyn !
> 
> Your code looks good, but I think you are hitting issue #1091. I'm only guessing; if you give us the version of xclim you are using and an example of an error message, we could help narrow down the problem. And eventually fix it if it's a bug.
> 
> If my guess is right, this means you can't use the `season` argument when using `bootstrap=True`. This is a limitation of xclim that we need to fix. However, depending on your needs you could very easily work around it:
> 
> ```
> tas_ref = tas.sel(time=slice('1961-01-01', '1990-12-31'))
> t90 = percentile_doy(tas_ref, window=5, per=90)
> txSEAS = tg90p(tas, t90=t90.sel(percentile=90), freq='QS-DEC', bootstrap=True)
> 
> txJJA = txSEAS.sel(time=txQ.time.dt.month==6)
> txDJF = txSEAS.sel(time=txQ.time.dt.month==12)
> ```
> 
> Where I computed the `tg90p` indicator seasonally and then extracted the summer and the winter into their own variables, dropping spring and fall that i computed unnecessarily.
> 
> `txJJA` is the same data as what your code would have given without the issue, except that the time coordinate is an annual series on the 1st of june. (instead of the 1st of january).
> 
> -- You might know, but note that for the DJF series, your code would have to use `freq='AS-DEC` to make sense and it would output the exact same thing as my example here. If you use YS, it means you are starting the year with january first, and thus for year X, the data from january, february and december are used. With my technique or with `freq='AS-DEC', season='DJF'`, then you're using december of year X, january and february of year X+1, which makes most sense.

Hi! Thank you for the help, the version of xclim is 0.36.0, and I have tried to use your codes to run but strange error occured as "'percentile is not a valid dimension or coordinate'" in the code 'txSEAS = tg90p(tas, t90=t90.sel(percentile=90),freq='QS-DEC',bootstrap=True)', do you know what is the problem?

**Comment by Patty-Lyn** [comment]
> Hi!
> 
> @aulemahal It looks like #1091 indeed but, it breaks in cases I did not expect. I think here it's the combination of `bootstrap=True` and `drop=True`. When running bootstrap=True, the bootstrap algorithm calls multiple time tg90p on an altered versions of the input dataset. However, with `drop=True` this input dataset is already truncated to JJA subset, so there is only 93 values per year. In that case, it breaks in`resample_doy` called within tg90p and not in `percentile_doy` like in #1091.
> 
> To fix both, I guess we could avoid calling `_interpolate_doy_calendar` when the calendars exactly match ?
> 
> ```
> def adjust_doy_calendar(
>     source: xr.DataArray, target: xr.DataArray | xr.Dataset
> ) -> xr.DataArray:
> doy_max_source = source.dayofyear.max()
> 
> # -- Instead of doing:
> if doy_max_source == doy_max:
>    return source
> # -- We could do:
> if target.dayofyear == source.dayofyear:
>    return source
> 
> return _interpolate_doy_calendar(source, doy_max)
> ```
> 
> By the way, there is another broken case, when both drop and bootstrap are False:
> 
> ```
> xclim.atmos.tg90p(da,
>          tas_per=t90.sel(percentiles=90),
>          freq='YS',
>          bootstrap=False,
>          season='JJA',
>          drop=False
>  )
> ```
> 
> Here it's a different issue, it's in missing.py::is_null function which adds `drop=True` to the select_time call. Instead, I think we should probably do `indexer.update({"drop": True})` to avoid this issue.
> 
> @Patty-Lyn As a workaround until those are fixed, if you don't mind having NaNs in your output, you can remove `drop=True` from your call:
> 
> ```
> xclim.atmos.tg90p(da,
>          tas_per=t90.sel(percentiles=90),
>          freq='YS',
>          bootstrap=True,
>          season='JJA',
>          # drop=False
>  )
> ```
> 
> I'm willing to work on a fix, it also breaks in icclim anyway ([cerfacs-globc/icclim#178](https://github.com/cerfacs-globc/icclim/issues/178))

Hi, thank you for the reply. I also encountered the error with " 'percentile is not a valid dimension or coordinate'", may i ask is it the bug? Also, for the bootstrap reference period, is it set to 1961-1990 as default?

**Comment by bzah** [comment]
As for the reference period used in bootstrap, the time range used is the one stored in `t90.attrs["climatology_bounds"]`.
This attributes is filled in t90 when calling `t90 = percentile_doy(tas_ref,window=5,per=90)`.

**Comment by Patty-Lyn** [comment]
> I guess "percentile is not a valid dimension or coordinate" comes from `t90.sel(percentile=90)` Try doing `t90.sel(percentiles=90)` instead (notice the 's' of percentiles).

Hi, I fixed this but when I used the sentence 'txJJA = xclim.atmos.tg90p(tas,t90,freq='YS',bootstrap=True,season='JJA')',
an error orrcued as " got an unexpected keyword argument 'season'"...

**Comment by aulemahal** [comment]
Hum, I don't think I have ever seen this with a simple xclim script. For us to help you better, please include code snippets to show what you're trying to do and more detailed error tracebacks.

**Comment by Patty-Lyn** [comment]
dask.config.set({"array.slicing.split_large_chunks": False})

dask.config.set({"distributed.worker.memory.target": "0.8"})
dask.config.set({"distributed.worker.memory.spill": "0.9"})
dask.config.set({"distributed.worker.memory.pause": "0.95"})
dask.config.set({"distributed.worker.memory.terminate": "0.98"})

dask.config.set({"array.chunk-size": "100 MB"})
tas = xr.open_dataset('atmax-1.nc').tmax
tas_ref = tas.sel(time=slice('1961-01-01','1990-12-31'))
t90 = percentile_doy(tas_ref,window=5,per=90).sel(percentiles=90)
txJJA = xclim.atmos.tg90p(tas,t90,freq='YS',bootstrap=True,season='JJA')

output:
UserWarning: Variable does not have a `cell_methods` attribute.
UserWarning: Variable does not have a `standard_name` attribute.  check_valid(vardata, "standard_name", data["standard_name"])

Process finished with exit code 137 (interrupted by signal 9: SIGKILL)

It generally means it runs out of memory but I don't think it will run out of memory.

**Comment by aulemahal** [comment]
Well bootstrapping does use a lot of memory, more than one might expect from the size of the data. Also, I don't think dask is being used here. First, `chunks` are not specified in the `open_dataset` call. Secondly, when using dask this should all be _lazy_, there shouldn't be any computation done in the code snippet you showed as neither `load` or `values` or a plot or a `to_netcdf` was specified.

I'd retry with a chunking specified along the latitude/longitude but not time, unless the on-disk chunking of your data requires something else. You could also try the code on a single point, in order to see if the problems from dask/memory or from xclim.

Both UserWarning are unimportant if you know what your data is. On this point, if you are using `tmax`, maybe you want to use `tx90p` (instead of `tg90p`), it's the same calculation, but the metadata will reflect that `tasmax` was used.
