### ISSUE TITLE
Developing (with Python 2/3 Compatibility in mind)

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#11]
@tlogan2000 and I were talking about this and we're wondering how best to proceed.

As mentioned previously, Python2 will be end-of-life [soon](https://pythonclock.org/). Having the library compatible with both for the time being is feasible but that shouldn't mean that we shy away from using Python3 advancements (e.g. **F-strings** and **AsyncIO**). 

At the moment, we're aiming to use a fair amount of abstraction libraries (xarray, numpy) that will handle most of the errors that can be introduced by Python2/3 math issues (integer division) but we should consider using [Python2/3 compatible syntax](http://python-future.org/compatible_idioms.html) where possible. So long as we follow good practices and make use of libraries that can convert code base from Py2->2/3 and Py3->2/3, we should be okay.

Suggestion for Contribution guidelines:
- **When adding a new module or set of algorithms, creating a branch of the library, open a Pull Release and ask someone to review changes when adding to Master** 
- if the additions are written in Python2, install and run [`python-futurize`](http://python-future.org/futurize.html) (Not `python-modernize` as we want to make use of more Python3 features) or;
- if the additions are written in Python3, install and run [`python-pasteurize`](http://python-future.org/pasteurize.html)
- Try installing/running the library in conda environments for both Py2 and Py3. (**The Travis CI is set to automatically try building the Pull Release when created, so you can opt to simply push changes to your branch after running the Python2/3 compatibility library**)
- Comment/document any known errors in the code or on GitHub so others can jump where needed.

**Comment by Zeitsperre** [comment]
For Unicode conversions between Py2 and Py3, [this video](https://www.youtube.com/watch?v=sgHbC6udIqc) can help demystify the major differences.

**Comment by huard** [comment]
I've given a bad example so far, but now I'm done experimenting. I'll follow the contribution guidelines from now on.

**Comment by Zeitsperre** [comment]
Just a warning, but `python-futurize` will make things look kind of ugly (`future` and `alias` imports) and gets tripped up on strings (e.g. bytes vs. unicode handling). It's not a silver bullet but it handles the hard parts. Thankfully, moving from `futurized` Python2 code to stand-alone Python3 code largely involves simply drop the convoluted imports. We're making things easier down the line.

**Comment by huard** [comment]
Tox and the Travis build make a good job of catching py2 and 3 gotchas. I've switched to developing in a py3 environment and will check it works with py2.

**Comment by huard** [comment]
@tlogan2000  Can be closed ?

**Comment by tlogan2000** [comment]
I think so... All the build tests etc that @Zeitsperre has setup take care of this

**Comment by Balinus** [comment]
I know decision's been made but I stumbled on this : https://python3statement.org/#sections40-timeline

More specifically, xarray pledged to drop support for Python 2 before 2020.
https://python3statement.org/#sections30-projects

I don't know how much time you're spending on accommodating for Python 2 though. Just some food for thoughts!

**Comment by huard** [comment]
Thanks for the info. 
I think we can drop 2 as soon as birdhouse does.

**Comment by huard** [comment]
I suggest we close this issue as long as we don't hit a major problem with PY2 compatibility (dependency drops support).
