### ISSUE TITLE
Add experimental wrapping of SBCK to sdba

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1109]
### Generic Issue

Yoan Robin's [SBCK](https://github.com/yrobink/SBCK) implements many bias adjustment methods, including most interesting multivariate ones. It follows a fit-predict syntax quite similar to xclim's sdba. It uses numpy, but only acts (AFAIU) on timeseries (by that I mean that is doesn't try to vectorize or loop the adjustment, there's no parallelism).

Which means, it could be quite easy (I usually underestimate things) to wrap it up into xclim. I'm talking of automatically generating sdba Adjustment classes from SBCK ones, and using `apply_ufunc` to loop on elements of the xarray inputs (like gridpoints. This would allow usage of dask with the same constraints as the other methods.

However, the license (GPL3) doesn't allow sub-licensing, which means we can't copy the code as-is into xclim. Let's just hope there's no bug...

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tlogan2000** [comment]
Looks promising.  @Zeitsperre Any feeling how much of an issue will the **`Eigen`** requirement might be for conda builds / testing or windows releases?  ... seems to be  C++ only?  http://eigen.tuxfamily.org/index.php?title=Main_Page

**Comment by tlogan2000** [comment]
nb * might be possible via conda already https://github.com/conda-forge/eigen-feedstock

**Comment by aulemahal** [comment]
Oh, true, that could be an issue. I was thinking of keeping SBCK an optional dependency with lower standards as for bugs and stability. Thus the "experimental" keyword in this issue's title. I don't expect the development of the package to be eternal or even constant... At one point, we'll need to translate some of the algos into xclim directly.

**Comment by Zeitsperre** [comment]
@tlogan2000 

Conda doesn't look like an issue, except it seems to be specifically built for some architectures (Like ARM/PPC/x86_64), so running it on something wild (like HPC) might cause issues. I can see this being a much bigger issue for straight Python builds, and I don't think we can extend support in that.

Having it as an optional dep makes sense to me, until we can get the OK to port some code from the library itself.
