### ISSUE TITLE
Check compatibility of time coordinates of inputs

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1111]
When calling an indicator with multiple inputs, the user has to make sure all those inputs have compatible time coordinates. For example, if one variable has daily values on midnight and the other at noon, xarray will try to align the two and the result will either have no time steps (the intersection) or interspersed ones (the union). In the second case, everything will usually be NaN.

Q1 : Does it fall in xclim's scope to detect this problem?

Q2 : If so, to what extent would xclim intervene? 
If we implement something, I would suggest a `datacheck`, so the behaviour is controllable from the options.

What do @huard and @tlogan2000  think?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huard** [comment]
I see this as an extension of the check for daily frequency. Here we're making sure that both daily frequencies are "compatible". 

My first impulse would be to catch it and raise an informative error.

**Comment by tlogan2000** [comment]
I think an error coming from `check_daily` makes sense.  The fix would be pretty simple on the users' end so I'm not sure that we really need a mechanism to handle it automatically.  We could simply have the error message suggest how to fix? something like "error both `da` and `da1` are daily but do not align properly ... try using da.resample('1D').mean() and all input before calculation"
