### ISSUE TITLE
`frequency_analysis` indicator weirdly declared

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1130]
### Setup Information

- Xclim version: master
- Python version: all
- Operating System: all

### Description

https://github.com/Ouranosinc/xclim/blob/1505aacbd9c5fd86885ee202aed99012e45c5abd/xclim/indicators/land/_streamflow.py#L69-L78

Here you see that the output of `frequency_analysis` is a discharge (var name `q`, units m³/s). However, the input variable has a generic name `da` and no prescribed dimensionality.  This would mean that if you pass anything else then a discharge, the unit check will not fail, but the indicator will fail when attempting to convert the output units.

Indeed, the next example fails. But even weirder,  is that we have a special CF check that looks for the "water_volume_transport_in_river_channel" standard name. Thus, we already are expecting a discharge.

### Steps To Reproduce

```python3
import xclim as xc
from xclim.testing import open_dataset

ds = open_dataset('ERA5/daily_surface_cancities_1990-1993.nc')
xc.land.freq_analysis(da=ds.dtas, t=100, dist='norm', mode='max')
```
warns:
```
UserWarning: Variable has a non-conforming standard_name: Got `dew_point_temperature`, expected `['water_volume_transport_in_river_channel']`
```
and fails:
```
DimensionalityError: Cannot convert from 'kelvin' ([temperature]) to 'meter ** 3 / second' ([length] ** 3 / [time])
```
The expect error would be:
```
ValidationError: Data units K are not compatible with requested [discharge].
```

### Additional context

@RondeauG 

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by RondeauG** [comment]
Adding to this issue, I think a discharge variable should be added to `VARIABLES` if we want to add and support more and more discharge-related indicators (which I think is the case?).

As for the name, I'd argue that `q` is **not** good, since this is already used for "specific discharge" in hydrology, with units in `m3 s-1 km-2`. `Q` is used for discharge in `m3 s-1`, but I don't think that we want a capital letter?
