### ISSUE TITLE
Accelerate xclim import

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1135]
### Generic Issue

* xclim version: all
* Python version: any
* Operating System: any

### Description
Importing `xclim.sdba` is currently quite slow. I think this is due to the numba utilities being pre-compiled because we give explicit input types. 

### What I Did
In `perfimport.py`:
```python3
import xclim as xc
from xclim import sdba


if __name__ == '__main__':
    print('yeah')
```
and then:
```bash
python -X importtime perfimport.py 2> import.log
tuna import.log
```
Using [tuna](https://github.com/nschloe/tuna).

### What I Received
![image](https://user-images.githubusercontent.com/20629530/180317242-dc37cef6-51a2-4f89-a62f-71c141fa1e8b.png)

I believe the other long import,  "xclim/indices/_conversion.py", may be due to the UTCI function, which also uses numba.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
Do you mean to say that this can be solved by relaxing static typing in SDBA? Is this a "feature" of numba?

**Comment by aulemahal** [comment]
Yep, this is what I read from the doc! https://numba.readthedocs.io/en/stable/user/jit.html#eager-compilation

IIRC, my goal with the static typing was avoid dtype promotions (float32 to 64). With this "eager" compilation, the tests would fail if the functions received mixed inputs, which I would then try to explicitly avoid. It may be thus be unnecessary to have them "in production". Also, a dtype promotion is not a tragic bug...
