### ISSUE TITLE
Unable to run `biologically_effective_degree_days` with DataArrays with multiple values of latitude

### ISSUE THREAD

**Issue by covix** [Ouranosinc/xclim#1136]
### Setup Information

- Xclim version: 0.33.0  
- Python version: 3.7.13
- Operating System: Linux Ubuntu 18.04 LTS

The problem is present also with python==3.9.12 and xclim==0.37.0

### Description

I tried to calculate `xclim.atmos.biologically_effective_degree_days` using a DataArray with dimension: time: 366, latitude: 131, longitude: 131, but it raised a valuerror:

`ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

The issue is found at line https://github.com/Ouranosinc/xclim/blob/master/xclim/indices/_agro.py#L387 in `max(((abs(lat) - 40) / 10) * 0.06, 0)`, since `max` tries to perform the maximum between the (transformed) lat values and 0.
Following the formula reported in the function's docstring, I believe that instead the maximum operation should be performed element-wise, e.g. by applying a `.clip(min=0)` operation.

I can create a pull request to fix the issue, but I do not know if it happens somewhere else (I am a new user of xclim). For this reason I am also looking for confirmation from more developers with more experience on the project.

Full error stack: 
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_5501/3565425813.py in <module>
      2     tmin_slice,
      3     tmax_slice,
----> 4     lat=tmin_slice.latitude,
      5 )
      6 era5_land_winkler

/usr/bin/miniconda3/envs/climate/lib/python3.7/site-packages/xclim/core/indicator.py in __call__(self, *args, **kwds)
    789             elif nm not in compute_das and nm in params:
    790                 kwargs[nm] = params[nm]
--> 791         outs = self.compute(**compute_das, **kwargs, **var_kwargs)
    792 
    793         if isinstance(outs, DataArray):

<boltons.funcutils.FunctionBuilder-55> in biologically_effective_degree_days(tasmin, tasmax, lat, thresh_tasmin, method, low_dtr, high_dtr, max_daily_degree_days, start_date, end_date, freq)

/usr/bin/miniconda3/envs/climate/lib/python3.7/site-packages/xclim/core/units.py in wrapper(*args, **kwargs)
    689                 check_units(val, bound_units.arguments.get(name, None))
    690 
--> 691             out = func(*args, **kwargs)
    692 
    693             # Perform very basic sanity check on the output.

/usr/bin/miniconda3/envs/climate/lib/python3.7/site-packages/xclim/indices/_agro.py in biologically_effective_degree_days(tasmin, tasmax, lat, thresh_tasmin, method, low_dtr, high_dtr, max_daily_degree_days, start_date, end_date, freq)
    390         if method.lower() == "gladstones":
    391             lat_mask = abs(lat) <= 50
--> 392             k = 1 + xarray.where(lat_mask, max(((abs(lat) - 40) / 10) * 0.06, 0), 0)
    393             k_aggregated = 1
    394         else:

/usr/bin/miniconda3/envs/climate/lib/python3.7/site-packages/xarray/core/common.py in __bool__(self)
    134 
    135     def __bool__(self: Any) -> bool:
--> 136         return bool(self.values)
    137 
    138     def __float__(self: Any) -> float:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

### Steps To Reproduce

[sample_data.zip](https://github.com/Ouranosinc/xclim/files/9168122/sample_data.zip)

Download the sample data and run:

```python
import xarray as xr
import xclim

tmin_slice = xr.open_dataarray("../data/tmin_slice.nc")
tmax_slice = xr.open_dataarray("../data/tmax_slice.nc")

era5_land_winkler = xclim.atmos.biologically_effective_degree_days(
    tmin_slice,
    tmax_slice,
    lat=tmin_slice.latitude,
)
```

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Oh woops, indeed this is a bug!

The issue is a misuse of `max(..., 0)` I think. Using the `clip` method solves that problem, I'll push a fix PR soon.

Thanks for raising the issue!
