### ISSUE TITLE
Climate indice class identifiers / dynamix naming 

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#114]
For climate indicator classes:

- [x]  harmonize instance, identifier and the compute function syntax : e.g. for the temperature.tm_mean class, id=tmmean, compute=tg_mean().  Lack of undescore in id is trying to follow the proposed CF-metadata 

- [x] Dynamic variable names : Decide on naming convention when using  cases of {thresh} and {window} in order to separate from the root variable name. My preference would be to use underscores, however this is not the pattern using the CF  metadata sheet (Lars and Claus). E.g. gdd5 (cf spreadsheet) would be gdd_5 (preferred).  Also, for certain cases  (e.g. csdi ) proposed metadata doesn't incorporate the window size (e.g. ICCLIM is always 6).  However xclim allows users to specify the window (if desired)

- [x] For variable naming ensure that {thresh} or {window} values are converted to integers before being string formatted (e.g. some functions have 'thresh=5.0' as defaults ...  gives 'gdd5.0'..

**Comment by tlogan2000** [comment]
I think this is done. @huard can close?   I've started using underscores as a default when including threshholds in the vari names.  Maybe we can influence Lars and Claus for the metadata conventions to follow our lead....

**Comment by huard** [comment]
The error is just the time stamp being different by one second. I'll think of something to give a little bit of leg room in the test.

**Comment by Zeitsperre** [comment]
I think it's been dealt with. I've given it a range of `now`, `now+1s`, and `now+2s`. Feel free to add more if you feel it's necessary.

**Comment by huard** [comment]
Nice !
