### ISSUE TITLE
Log-logistic Distribution for SPEI

### ISSUE THREAD

**Issue by lukruh** [Ouranosinc/xclim#1141]
### Addressing a Problem?

According to the [docs](https://xclim.readthedocs.io/en/latest/xclim.indices.html?highlight=spei#xclim.indices._agro.standardized_precipitation_evapotranspiration_index) `Gamma` is the only supported distribution for the SP(E)I calculation. AFAIK the Log-logistic distribution can be used for the SPEI as well, which is not supported by xclim yet.

### Potential Solution

According to the [scipy docs](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisk.html) there is a log-logistic (aka fisk) dist available in `scipy.stats.fisk`. From a quick view at the code, it seems that only the name of the distribution needs to be added in some lines. If it is that easy to implement I'd try to do it in a PR.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coxipi** [comment]
Hi @lukruh, indeed, the support for log-logistic will be quite straightforward to add. 

You're welcome to submit a PR for this. Please check the documentation on how to create new indices and indicators here: https://xclim.readthedocs.io/en/stable/contributing.html#implement-features-indices-or-indicators

You could do as you say, simply unlock the log-logistic by allowing `fisk` as an input distribution. However, I don't think you will get good results if you don't add the approximated parameters computation in `_fit_start` (at least, that's what I see from a quick try). At first glance, I think that adding the approximated computation for `dist === "fisk"` in `_fit_start` using Maximum Likelihood Estimator is a bit more complicated than for `dist == "gamma".

I was already planning to add support for log-logistic at some point this month, so I'll have a look at this eventually if you don't do it first!

**Comment by coxipi** [comment]
You're welcome!
