### ISSUE TITLE
Add McArthur Forest Fire Danger Index?

### ISSUE THREAD

**Issue by dougiesquire** [Ouranosinc/xclim#1152]
### Addressing a Problem?

Thanks for this terrific package!

Is there interest in adding the McArthur Forest Fire Danger Index (FFDI) to `xclim`?

The FFDI is a fire weather index that is heavily used in operation and research, particularly in Australia, e.g.

- http://www.bom.gov.au/vic/forecasts/fire-map.shtml
- https://www.nature.com/articles/s41467-021-27225-4

The calculation of the FFDI requires the calculation of a Drought Factor, commonly the Griffiths Drought Factor (DF) using the Keech-Byram Drought Index (KBDI), so functions for calculating these (at least) would also need to be included.

### Potential Solution

If there’s interest in including the FFDI, DF and KBDI in `xclim`, I’d be happy to have a stab at implementation. I have some code already, though it’s currently just some functions in a notebook [here](https://notebooksharing.space/view/a38d8bc9093ab0b612f8aaab8767a48bad686944ff0774cc6af6af49da6f2e8c#displayOptions=). My code could probably benefit from some refactoring when slotting into xclim (efficient implementation of DF, in particular, is a little sticky), but the gist of it is there.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
There's always an interest in adding more useful indices! We spent a lot of time into the Fire Weather Indices from the Canadian Forest Service, it seems only logical to add this other fire index. 

If you can open a PR with a first implementation draft, that would be best. The code could live in its own new file under  `indices/` or we could widen the scope of `indices/_fwi.py` to include all fire-related things. I think the algorithm logic between the two is similar, so you could try taking inspiration from the FWI for your implementation? (Though I know it became quite complex)

I quickly looked at your notebook and, indeed, the drought code seems heavier... We'll figure something out!
