### ISSUE TITLE
Investigate Poetry package and pyproject.toml for automated deployment

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#118]
With [PEP 518](https://www.python.org/dev/peps/pep-0518/), dependency management has been gradually building towards a new standard to replace `setup.py` using `pyproject.toml` and `.ini` syntax. The gains are that this is a lot easier than rigging code to examine requirements files as well as makes it easy to start, test, implement CI services, and package projects from start to finish. One project that keeps coming up that does this is [Poetry](https://poetry.eustace.io/).

While we already make use of `cookiecutter` to build our Python packages, it can't hurt to see whether we can leverage this for automated deployment of packages to PyPI and conda/conda-forge.

**Comment by huard** [comment]
Sounds interesting. Caveat is I've seen half a dozen of those nifty installation tools popping up (and dying) over the last 10 years. Before we invest time, I'd like to see a couple of large scientific projects taking it up and become less bleeding edge (so that most people actually know how to use it).

**Comment by Zeitsperre** [comment]
That's fair. I'm with you on this. The values I see in this is how easy it is to create and deploy package standards and prevent us from spending effort in optimizing setup code. I'm keeping an eye on it for a day when I'm not busy, whenever that happens. ;)

**Comment by huard** [comment]
Sounds good. Don't hold your breadth... Have you spoken to Carsten about this ? You could put it on his radar.

**Comment by huard** [comment]
Or just ping him on gitter.

**Comment by huard** [comment]
@Zeitsperre I would close this due to the lack of support for conda environment.

**Comment by Zeitsperre** [comment]
Poetry is supported in conda and can be used to build out recipes on for packages on conda-forge, similar to pip. https://anaconda.org/anaconda/poetry. I'm porting `cruft` to conda-forge using poetry right now. I'm not sure what you mean.

From what I understand, poetry is a `toml`-based replacement for setup.py with some neat enhancements for dependency-handling and publishing to PyPI. I don't think there's anything to lose in keeping an eye on it.

**Comment by huard** [comment]
https://github.com/python-poetry/poetry/issues/1856#issuecomment-574082852

**Comment by Zeitsperre** [comment]
Dang. That's really too bad. I suppose this would be useful if we want to publish something with pure python dependencies but the lack of access to a conda channel for binaries really diminishes the value of using `poetry` here.

 Closing.
