### ISSUE TITLE
Hot days vs summer days

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#120]
Summer days and hot days  indices are identical except for the threshold (now variable in summer days) I propose deleting hot days  function from indices.py

Objections?

**Comment by Balinus** [comment]
So, if I want to calculate the nb of days higher than -15 Celsius between jan and march I use `summerdays` ? ;)

**Comment by tlogan2000** [comment]
I guess  so...  Does keeping 'hot days' make more sense

**Comment by Balinus** [comment]
I think it makes more sense!

**Comment by huard** [comment]
No, I think we need a generic function like `count_above`, and then specialized versions that fix the threshold. 
If you use a lambda expression for the compute attribute of the Indicator classes, does it work ? It might screw with the argument binding logic.

**Comment by Balinus** [comment]
Been out of the loop for a couple of weeks so discard the suggestion if it does not make sense. 

How about a simple wrapper?
```python
def summerdays(data, args...):
    dataout = count_above(data, args... , op=">=20")
   # add metada to dataout
   # etc
```

**Comment by huard** [comment]
That totally works. I was wondering if we could skip that, but I think it would create more trouble than it's worth. Let's do that.

**Comment by cothel** [comment]
Je suis d'accord pour conserver hot days car ceux-ci se produirons de plus en plus en dehors de l'été.
Je n'ai jamais été une fan de "Summer days".

**Comment by tlogan2000** [comment]
Ok, I imagine we would want a count_below as well or do we want as even more generic 'count' where we send in the operator as in phil's example

**Comment by huard** [comment]
Generic sounds good.

**Comment by tlogan2000** [comment]
Proposing class and indicator name of 'tx_days_above' instead of hot days?
variable name = 'txge_30'
