### ISSUE TITLE
Cold spell duration index vs Cold spell index

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#121]
Two different but similar indices. ..  cold spell duration index is ICCLIM while cold_spell_index does not have a reference.

I suggest we need a new name for 'Cold spell index' to avoid confusion between the two but can't think of anything .. .any suggestions?

**Comment by tlogan2000** [comment]
**Cold spell index**

The number of days that are part of a cold spell, defined as five or more consecutive days with mean daily temperature below a threshold in °C.

**Cold spell duration index**

Number of days with at least six consecutive days where the daily minimum temperature is below the 10th percentile. The 10th percentile should be computed for a 5-day window centred on each calendar day in the 1961-1990 period.

**Comment by cothel** [comment]
Ça prend clairement les deux car les définitions diffèrent beaucoup. Pourquoi ne pas inclure explicitement  ICCLIM dans le nom pour les distinguer d'avantage? Ça se fait  pour d'autres types d'indices comme ceux liés aux sécheresses en raison de la multitude de définitions.

**Comment by tlogan2000** [comment]
Je pense que cold spell index pourrait  devenir 'cold spell days'.  On veut garder les deux certianement mais je pense que les gens peuvent facilement se tromper entre les deux.  Je vise seulement une nomenclature différent/plus clair dans ce cas si

**Comment by Zeitsperre** [comment]
I'll second the "Cold Spell Days". Dropping index from the name removes the impression that it's a standardized metric.

**Comment by Zeitsperre** [comment]
@cothel Within the docs, we already have a special module section for ICCLIM indices. Ensuring that the Cold Spell Duration Index is listed there should be adequate to differentiate the two.

**Comment by Zeitsperre** [comment]
Closed with #123
