### ISSUE TITLE
Failures in doctests

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#1226]
### Setup Information

- Xclim version: master

### Description

Doctests have new failures, possibly due to dependency updates. 

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
I think I found the bug : https://github.com/pydata/xarray/issues/7275
