### ISSUE TITLE
Save Xclim training result to file

### ISSUE THREAD

**Issue by dustming** [Ouranosinc/xclim#1229]
### Setup Information

- Xclim version:
- Python version:
- Operating System:

### Context

Hi everyone ~~

    I am using sdba.EmpiricalQuantileMapping to do bias correction. 
    
     Is it possible to save the Xclim training parameters result to a file? 
     
     So next time, when I need to correct new data, I do not need to do the training process again. 

Thanks
Ming 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Hi @dustming!

Yes it is possible, you after the  `EQM = EmpiricalQuantileMapping.train` call, the adjustment factors are other parameters are stored in a xarray dataset `EQM.ds`, which you can write to disk and use with `EmpiricalQuantileMapping.from_dataset(ds)`.

The process is explained here : https://xclim.readthedocs.io/en/stable/notebooks/sdba-advanced.html#Initializing-an-Adjustment-object-from-a-training-dataset

Does that answer your question?

**Comment by dustming** [comment]
Yes, It is, thank you very much~!!

**Comment by aulemahal** [comment]
Happy to hear that!
