### ISSUE TITLE
units2pint crashes when replacing "%" to "pct"

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1245]
### Setup Information

- Xclim version: 0.39
- Python version: 3.10
- Operating System: Linux

### Description

When trying to convert units from Celsius to Kelvin, xclim is raising an AttributeError.

### Steps To Reproduce

When converting a data array from Celsius to Kelvin:
```
...
File ".../xclim/core/units.py", line 300, in convert_units_to
    fu = units2pint(source)
File ".../xclim/core/units.py", line 142, in units2pint
    unit = unit.replace("%", "pct")
AttributeError: 'bool' object has no attribute 'replace'
```

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Hum.
What does your data look like?
The code does:
```python3
    if isinstance(value, str):
        unit = value
    elif isinstance(value, xr.DataArray):
        unit = value.attrs["units"]
    elif isinstance(value, units.Quantity):
        return value.units
    else:
        raise NotImplementedError(f"Value of type `{type(value)}` not supported.")

    unit = unit.replace("%", "pct")
```
This would mean that your data array has a boolean in its `units` attribute?

This would be case of unclear error message, but a data bug nonetheless!

**Comment by Zeitsperre** [comment]
This was an error on my part. My workflow was accidentally sending a boolean to this function. Sorry!
