### ISSUE TITLE
Can't build docs locally

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1248]
### Setup Information

- Xclim version: master
- Python version: 3.10
- Operating System: Fedora 36

### Description

When I try to build the documentation the official way, it fails.

### Steps To Reproduce

In the root directory of  `xclim`: `make docs`
The "apidoc" step passes, as does the "linkcheck" one (with 2 warnings), but the "html" fails with:
```
make -C docs html
make[1] : on entre dans le répertoire « /home/pbourg/Projets/xclim/docs »
Sphinx v5.3.0 en cours d'exécution
Création du répertoire de sortie... fait
Chargement de l'environnement pickled... checking bibtex cache... up to date
fait
Construction en cours [mo] : cibles périmées pour les fichiers po 0
Construction [html] : cibles périmées pour les fichiers sources 40
Mise à jour de l'environnement : 0 ajouté(s), 0 modifié(s), 0 supprimé(s)
Recherche des fichiers périmés... aucun résultat
Document en préparation... fait
/home/pbourg/Projets/xclim/HISTORY.rst:299: WARNING: type de node inconnu : <SkipMarker: >                                                                                         

Une exception a été levée :
  File "/home/pbourg/mambaforge/envs/xclim/lib/python3.10/site-packages/docutils/nodes.py", line 2056, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: SkipMarker
La trace d’appels complète a été sauvegardée dans /tmp/sphinx-err-36pdrc5f.log, au cas où vous souhaiteriez signaler le problème aux développeurs.
Merci de rapporter ceci s'il s'agit d'une erreur utilisateur, afin d'améliorer le message d'erreur à l'avenir.
Un rapport d'erreur peut être déposé dans le système de tickets à <https://github.com/sphinx-doc/sphinx/issues>. Merci !
make[1]: *** [Makefile:20 : html] Erreur 2
make[1] : on quitte le répertoire « /home/pbourg/Projets/xclim/docs »
make: *** [Makefile:88 : docs] Erreur 2
```

### Additional context

I seem to have every package up to date.

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Note: After the failure shown above, if I:
```
cd docs
make html
```
It works.

**Comment by Zeitsperre** [comment]
wha?? Weird. I raised an issue about this here, but hadn't advanced on it yet. I thought it might have just been me: https://github.com/felix-hilden/sphinx-codeautolink/issues/118

**Comment by aulemahal** [comment]
Haha weirder, but we are approaching the bug: it only happens on the first `make html` after a `clean` + `apidoc` + `linkcheck`. If I simply re-run `make html` after the failure it works.

To correct my previous comment : it doesn't seem related to the specific folder from which the command is run, but rather to the order of operations.
