### ISSUE TITLE
MBCn reordering (xclim.sdba.processing.reordering)

### ISSUE THREAD

**Issue by KkcChow** [Ouranosinc/xclim#1249]
### Setup Information

- Xclim version:
- Python version:
- Operating System:

### Context

Hello!

I've previously used MBCn via the MBC R package, and I was pouring through the xclim Statistical Downscaling and Bias-Adjustment notebook out of curiosity. As I was going through it I noticed something peculiar in the reordering/Restoring the Trend section.

Under the [Restoring the Trend](https://xclim.readthedocs.io/en/stable/notebooks/sdba.html#Restoring-the-trend) section, it states that "We reorder the result of the initial adjustment according to the rank structure of the NpdfT outputs to get our final bias-adjusted series", as also described in Alex Cannon's paper. In the subsequent function call however, it appears that the NpdfT output is being reordered using the rank structure of the initial adjustment as reference:

scenh = sdba.processing.reordering(hist, scenh, group="time")

As I understand, hist is the standardized initial QDM-adjusted variables, while scenh is the NpdfT adjusted historical output. In the function, ref=hist, and sim=scenh. Am I interpreting the syntax, or how the reordering is performed incorrectly?

Thanks!

Kenneth
 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Oh! You are totally right, the arguments are indeed inverted...
The notebook should read:
```
scenh = sdba.processing.reordering(scenh, hist, group="time")
scens = sdba.processing.reordering(scens, sim, group="time")
```

Thanks a lot for notifying us! I'll fix the documentation asap.
