### ISSUE TITLE
DOCS: Example not rendered correctly

### ISSUE THREAD

**Issue by gutzbenj** [Ouranosinc/xclim#1264]
### Generic Issue

Dear @Zeitsperre ,

I was just scrolling through the list of climate indicators in the rendered documentation and noticed that one example is not rendered correctly. 

At [1] you find the following part:

```rst
# For the Northern Hemisphere: >>> gsl_nh = growing_season_length(tas, mid_date=”07-01”, freq=”AS”)

# If working in the Southern Hemisphere, one can use: >>> gsl_sh = growing_season_length(tas, mid_date=”01-01”, freq=”AS-JUL”)
```

It seems like the newline characters are not recognized and thus the render fails and the actual commands behind >>>> fail to be rendered as such.

Cheers,
Benjamin

[1] https://xclim.readthedocs.io/en/stable/indices.html#indices-library

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
Happy New Year, and thanks for the keen eye, Benjamin! Will look into this!
