### ISSUE TITLE
Drop Python3.8

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1268]
Python3.8 has entered the security fixes stage and is gradually losing support from major scientific libraries: https://peps.python.org/pep-0569/

Dropping this version will open us up to some new features that were introduced in Puthon3.9 (https://peps.python.org/pep-0596/#features-for-3-9), notably `__future__.annotations` (https://peps.python.org/pep-0585/)

**Comment by Zeitsperre** [comment]
Looks like xarray just dropped support for Python3.8 in main dev branch! https://github.com/pydata/xarray/pull/7461

**Comment by huard** [comment]
Security fixes are going to be "provided irregularly on an “as-needed” basis until October 2024." Unless supporting 3.8 proves problematic, I would defer dropping support to as late as reasonable. Updating environments is not pleasant when you have a working setup.

**Comment by Zeitsperre** [comment]
Sphinx just dropped Python3.8 support: https://www.sphinx-doc.org/en/master/changes.html#release-7-2-0-released-aug-17-2023
