### ISSUE TITLE
[PyOpenSci] Basic Usage notebook needs cleanup / better flow

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1282]
### Generic Issue

* xclim version: 0.40.0
* Python version: Any 
* Operating System: All

### Description

One of the suggestions coming from the PyOpenSci review process was to clean up the `Basic Usage` notebook to make it a bit more consistent with the rest of the documentation (https://github.com/pyOpenSci/software-submission/issues/73). The flow of the text needs a bit of work.

For context, this issue is not blocking the PyOpenSci review process, but would be nice to have.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
@NickleDave

Changes that were just merged to the main branch (#1308) included modifications to the `usage` page (one of your initial comments). If you're interested in taking another look at that, please let me know. Otherwise, I'll consider this issue closed in the next few days.

Thanks again!

**Comment by NickleDave** [comment]
Hi @Zeitsperre, I took a quick look and see in the PR where revisions were made in places where there were minor typos / unclear language. LGTM!!! Thank you for noting this and integrating it into the review.

**Comment by Zeitsperre** [comment]
Awesome! All the best!
