### ISSUE TITLE
keetch byram drought index input parameters

### ISSUE THREAD

**Issue by GvdDool** [Ouranosinc/xclim#1298]
### Setup Information

- Xclim version: 0.40.0
- Python version: 3.9.13
- Operating System: Windows - Jupyter notebook

### Context

I am trying to compute the KBDI with the NEX-GDDP data for an area (y: 26, x: 38) over the historical data (1985-2005, time: 7670), but the call is returning errors related to the format of the input data, and I don't know how to format the data arrays in an acceptable form for the tool to run.

The code I am using looks roughly like this, and I can add screenshots or share the notebook, but I hope that this gives a general idea of what I am trying to do, and where it goes wrong:
```
#### Signature:      
# xc.indicators.atmos.keetch_byram_drought_index(
#     pr: Union[xarray.core.dataarray.DataArray, str] = 'pr',
#     tasmax: Union[xarray.core.dataarray.DataArray, str] = 'tasmax',
#     pr_annual: Union[xarray.core.dataarray.DataArray, str] = 'pr_annual',
#     kbdi0: Union[xarray.core.dataarray.DataArray, str, NoneType] = None,
#     *,
#     ds: xarray.core.dataset.Dataset = None,
# ) -> xarray.core.dataarray.DataArray
```

```
data_hist_pr = "./prec_pr_sum_his00CP.nc" #daily data 
data_hist_tasmax =  "./Data_v1/temp_tasmax_his00CP.nc"

ds2_hist_pr = xr.open_dataset(data_hist_pr)
ds2_hist_pr.attrs["units"] = "mmday"
ds2_hist_pr  = ds2_hist_pr.rename({'band_data': 'pr'})

ds2_hist_tasmax = xr.open_dataset(data_hist_tasmax)
ds2_hist_tasmax.attrs["units"] = "C"
ds2_hist_tasmax  = ds2_hist_tasmax.rename({'band_data': 'tasmax'})
```

and then I can either give pr_annual as 400 or
```
out2 = xc.atmos.precip_accumulation(pr_mmd_pr, freq='YS')
pr_total = pr_mmd * 0 + out2.mean()
pr_total.attrs["units"] = "mm/y"
pr_total.attrs['standard_name'] = 'precipitation_flux'
```
I don't know what would work, or what I am doing wrong, because 400 gives an "int" error and as data_array I get a KeyError: 'units'

Any help and insights is very much appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Hi @GvdDool !

This function was written by @dougiesquire, maybe they will have more insight on this.

I'm not sure I see the exact problem you are hitting, but here are a few hypotheses and guesses:

- Are you passing `ds2_hist_pr` directly? From your snippet, it looks like a Dataset, rather than a  `DataArray`. Do you mean:
```python3
ds2_hist_pr = xr.open_dataset(data_hist_pr)
pr = ds2_hist_pr.band_data  # The variable name is not that important, but we need a DataArray
pr.attrs["units"] = "mm/day" 

ds2_hist_tasmax = xr.open_dataset(data_hist_tasmax)
tasmax = ds2_hist_tasmax.band_data
tasmax.attrs["units"] = "degC"
```

- The way you are constructing `pr_total` seems good. Passing an `int` would indeed raise an error as the code can't be sure which units are being used. If I could give one unrequested advice here, I would do:
```python3
out2 = xc.atmos.precip_accumulation(pr_mmd_pr, freq='YS').mean('time')
pr_total =  xc.units.convert_units_to(out2, 'mm')  # Convert explicitly rather than assume.
pr_total.attrs["units"] = "mm/y"
```
Notice that I average the annual precipitation over _time_ only, rather than over all dimensions. Maybe, that's not what you want, but my understanding of the KBDI is that the annual precip is site-specific, unique to a lat/lon point. It is also the reason the input is requested as a `DataArray` and not a constant.

If these do not fix your problem, please send us your xclim call with the traceback, so we might have a better understanding of the bug!

**Comment by GvdDool** [comment]
Thanks @aulemahal (Pascal)
I indeed was passing datasets instead of data arrays, and I changed the code using your suggestions, keeping pr_total as the average area mean:
```
#### Signature:      
# xc.indicators.atmos.keetch_byram_drought_index(
#     pr: Union[xarray.core.dataarray.DataArray, str] = 'pr',
#     tasmax: Union[xarray.core.dataarray.DataArray, str] = 'tasmax',
#     pr_annual: Union[xarray.core.dataarray.DataArray, str] = 'pr_annual',
#     kbdi0: Union[xarray.core.dataarray.DataArray, str, NoneType] = None,
#     *,
#     ds: xarray.core.dataset.Dataset = None,
# ) -> xarray.core.dataarray.DataArray

kbdi = xc.indicators.atmos.keetch_byram_drought_index(pr=pr, 
                                                      tasmax=tasmax, 
                                                      pr_annual=pr_total,) 
                                                      #kbdi0=0)
```
and now the code fails on:
C:\Users\RueDuMidi_G\anaconda3\envs\geo_py\lib\site-packages\xclim\core\cfchecks.py:46: UserWarning: Variable does not have a `standard_name` attribute.
  check_valid(vardata, "standard_name", data["standard_name"])
  
and: **UndefinedUnitError**: 'y' is not defined in the unit registry

perhaps I should rename x,y to lon/lat?

**Comment by aulemahal** [comment]
I believe the second error is simply the `pr_total` units, "years" are noted "yr" in netCDF conventions (and thus xclim's pint registry). I didn't catch that on my first read!
```python3
pr_total.attrs["units"] = "mm/yr"
```

You can ignore the UserWarning, it is simply notifying you that it cannot check for perfect compliance between your inputs and the expected ones as some CF metadata is missing. As long as you know what your data is, it's no problem.

**Comment by GvdDool** [comment]
```
Thanks, still not perfect:
File ~\anaconda3\envs\geo_py\lib\site-packages\xarray\core\computation.py:621, in broadcast_compat_data(variable, broadcast_dims, core_dims)
    619 unexpected_dims = [d for d in old_dims if d not in set_new_dims]
    620 if unexpected_dims:
--> 621     raise ValueError(
    622         "operand to apply_ufunc encountered unexpected "
    623         f"dimensions {unexpected_dims!r} on an input variable: these are core "
    624         "dimensions on other input or output variables"
    625     )
    627 # for consistency with numpy, keep broadcast dimensions to the left
    628 old_broadcast_dims = tuple(d for d in broadcast_dims if d in set_old_dims)

ValueError: operand to apply_ufunc encountered unexpected dimensions ['time'] on an input variable: these are core dimensions on other input or output variables

```
Sorry for all these questions; I appreciate the help!

**Comment by aulemahal** [comment]
Looking at the code, it seems that  `pr_annual` should NOT have a `time` dimension. 

In your first post, the line `pr_total = pr_mmd * 0 + out2.mean()` is putting all the dimensions of `pr_mmd` in `pr_total`. If you are using a single value of `pr_total/annual` for your call, there's no need for this broadcasting, you can simply do `pr_total = out2.mean()`. (Broadcasting over the spatial dimensions will be automatic inside the function, as it is implicit in xarray's `apply_ufunc`).  

If you still want a `pr_total` as a map, maybe it's better to do: 
```python3
pr_total =  out2.mean().broadcast_like(pr_mmd.isel(time=0))
```

**Comment by GvdDool** [comment]
Success - this time the code runs without an error - thank you so much for your help.
