### ISSUE TITLE
Simplified Potential EvapoTranspiration (PET)

### ISSUE THREAD

**Issue by GvdDool** [Ouranosinc/xclim#1306]
### Addressing a Problem?

I am working on a problem with limited data available, and the task is to create a drought indicator. Looking at the tools available in xclim I noticed the SPEI [standardized_precipitation_evapotranspiration_index()](https://xclim.readthedocs.io/en/stable/xclim.indices.html#xclim.indices._agro.standardized_precipitation_evapotranspiration_index).) but this function needs the daily precipitation in combination with Potential EvapoTranspiration (PET), and currently this parameter is calculated using: xclim.indicators.atmos._conversion.potential_evapotranspiration with several data dependencies.

I could calculate PET if I had access to all the data, but unfortunately, I am missing many variables for this function, luckily there is a simplified method (less precise) which is used as an alternative: Blaney-Criddle equation (BC) is a simpler method for ETo estimation, and it requires only air temperature as an input data.

### Potential Solution

Using Wikipedia for a quick reference to the Equation:
ETo = p ·(0.457·T[mean] + 8.128)

Where:

ETo is the reference evapotranspiration [mm day−1] (monthly)

T[mean] is the mean daily temperature [°C] given as Tmean = (Tmax + Tmin )/ 2

p is the mean daily percentage of annual daytime hours.[[3]]

### Additional context

[[3]](https://en.wikipedia.org/wiki/Blaney%E2%80%93Criddle_equation#cite_note-3)
https://mepas.pnnl.gov/mepas/formulations/source_term/5_0/5_13/5_13.html

Quick literature review:
https://search.r-project.org/CRAN/refmans/Evapotranspiration/html/ET.BlaneyCriddle.html

> The general form of Blaney–Criddle is:
> PET = a1 * f + a2 (16)
> f = p * (0.457·T[mean] + 8.128)(17)
> where a1 and a2 are constants depend on the average values during the month of lowest relative humidity during the day, p is the percentage of the average number of daylight hours in the day for the specified month to the total of daylight hours in the year, and T is the average temperature for a full day during the month in Celsius.

https://www.sciencedirect.com/science/article/pii/S1110016812001123

> Alternatively, the Blaney and Criddle equation (BC) which requires only air temperature as input data will be applied.  However,  BC  often  need  to  be  calibrated to  individual  stations.  In  this  study, a  new technique  of  the  BC  called  the  modified  Blaney  and  Criddle  equation  (MBC)  was introduced. The MBC  used  effective temperature instead of average temperature. The effective temperature can be calculated based on the minimum and maximum temperature and a calibrated coefficient (k). The variable k values (kv) and the three constant k values (0.72, 0.69 and 0.64) were used to evaluate the MBC. 

https://www.researchgate.net/publication/281281160_Estimating_reference_evapotranspiration_using_modified_Blaney-Criddle_equation_in_arid_region

I would not have ticked the PR box because my coding skills are not professional enough to contribute, but I am more than happy to review and test.

### Contribution

- [x] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GvdDool** [comment]
In the helper function for xclim there is `[day_lengths](https://xclim.readthedocs.io/en/stable/_modules/xclim/indices/helpers.html#) ` which should help to solve for _p_ 

How would this array be constructed?
```
def day_lengths(
    dates: xr.DataArray,
    lat: xr.DataArray,
    method: str = "spencer",
) -> xr.DataArray:
```

**Comment by Zeitsperre** [comment]
I just stumbled across this project which could also serve the need (or potentially be built into xclim??): https://github.com/pyet-org/pyet

**Comment by Zeitsperre** [comment]
@GvdDool 

Quickly going through the code for `pyet`, I came across an implementation of your example: https://github.com/pyet-org/pyet/blob/b3ff8f70d221b1c6e79d56cdd3c60d119375079a/pyet/temperature.py#L13

The approach is very similar to what we would perform if the indice were to be ported to xclim (the call syntax is what we would likely follow as well). Unless there are some gains to be had (e.g. better optimizations using `apply_ufunc` or `dask` parallelization), I don't think it would be worth the time and effort to re-implement their indices; I think it would be a better approach to contribute those features to `pyet` instead.

I'll be adding `pyet` as a project worth consulting in our documentation at the very least.

**Comment by GvdDool** [comment]
Dear Trevor,
Apologies for my late reaction to your previous post; tomorrow I am
revisiting SPEI, and it's on my list to look at the code you are proposing,
but from what I gathered so far, I think you are right, and it should be
enough to wrap a function around pyet.

Kind regards,
Gijs
