### ISSUE TITLE
maximum_consecutive_* indicators split runs over a frequency boundary

### ISSUE THREAD

**Issue by cuell** [Ouranosinc/xclim#1329]
### Setup Information

- Xclim version: 0.40.
- Python version: 3.10
- Operating System: Ubuntu 22.04.02

### Context

I was trying to expand on some of the run-type indicators, and when I tested mine against `xclim.indicators.atmos.maximum_consecutive_dry_days` with `freq='YS`, I found a few years where the values were different. This is because `xclim` is resampling before computing the run lengths. That means runs are being broken up at year-end.

e.g.

```
def max_consecutive_dry_days_test():
    import numpy as np
    import pandas as pd
    import xarray as xr
    import xclim

    times = pd.date_range('2001-01-01', '2002-12-31')
    lat = np.array([54.5])
    lon = np.array([-128.4])
    data = np.full((len(times), 1, 1), 10)
    pr = xr.DataArray(data=data, dims=['time', 'lon', 'lat'], coords=dict(time=times, lon=lon, lat=lat))

    dry_times = pd.date_range('2001-12-25', '2002-01-04')  # 11 days
    pr.loc[dict(time=dry_times)] = 0.
    pr.attrs['units'] = '1. kg m-2 d-1'

    # returns 11, 0
    mask = pr < 1
    longest_run = xclim.indices.run_length.longest_run(mask, freq='YS', ufunc_1dim=False)

    # returns 7, 4
    max_cdd = xclim.indicators.atmos.maximum_consecutive_dry_days(pr)

    return longest_run, max_cdd
```
I just want to know if this is the expected behaviour.

Thanks for your help!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coxipi** [comment]
Hi @cuell, 

Exactly. Some indicators like `dry_spell_frequency` have a built-in capacity to choose between those two behaviours you note, with an argument `resample_before_rl` ^[1] set to either `True` or `False`. The default is `True`, i.e. the second example you give.  This option apparently has not been implemented in `maximum_consecutive_dry_days` (and a few other indicators), but there is no particular challenge why it has not been done.  I can look into it.

^[1] : `rl`  referring to a generic `run_length` operation, e.g. the `longest_run` you use

**Comment by cuell** [comment]
Thank you!
