### ISSUE TITLE
0th Quantile not adjusted in QuantileDeltaMapping

### ISSUE THREAD

**Issue by saschahofmann** [Ouranosinc/xclim#1334]
### Setup Information

- Xclim version: 0.41.0
- Python version: 3.9.15
- Operating System: Ubuntu 18.04

### Description

We are using QuantileDeltaMapping to adjust some climate variables and are seeing that the 0th quantile doesnt seem to be properly adjusted in xclime 0.41 compared to 0.24. Here is a code snippet to reproduce this behaviour (*Note:* you have to do a small adjustment to run with 0.24). It is based on the example from the docs. In reality, we are seeing a little stronger behaviour on our own data.

```python
import numpy as np
import xarray as xr
from matplotlib import pyplot as plt
from xclim.sdba.adjustment import QuantileDeltaMapping

# Create toy data for the example, here fake temperature timeseries
t = xr.cftime_range("2000-01-01", "2030-12-31", freq="D", calendar="noleap")
ref = xr.DataArray(
    (
        -20 * np.cos(2 * np.pi * t.dayofyear / 365)
        + 2 * np.random.random_sample((t.size,))
        + 273.15
        + 0.1 * (t - t[0]).days / 365
    ),  # "warming" of 1K per decade,
    dims=("time",),
    coords={"time": t},
    attrs={"units": "K"},
)
sim = xr.DataArray(
    (
        -18 * np.cos(2 * np.pi * t.dayofyear / 365)
        + 2 * np.random.random_sample((t.size,))
        + 273.15
        + 0.11 * (t - t[0]).days / 365
    ),  # "warming" of 1.1K per decade
    dims=("time",),
    coords={"time": t},
    attrs={"units": "K"},
)

ref = ref.sel(time=slice(None, "2015-01-01"))
hist = sim.sel(time=slice(None, "2015-01-01"))


# Change to this in xclim 0.24
# QDM = QuantileDeltaMapping(
#     nquantiles=100, kind="+", group="time"
# )
# QDM.train( ref, hist)
QDM = QuantileDeltaMapping.train(
    ref, hist, nquantiles=100, kind="+", group="time"
)


hist_adj = QDM.adjust(hist)

# Create some plots to see the extreme values
qref=np.linspace(0,0.05,100)
tr0_qref= ref.quantile(q=qref,dim='time')
t0_qref = hist_adj.quantile(q=qref,dim='time')


plt.plot(tr0_qref, t0_qref,'.-', label='raw_models', alpha=0.4)
plt.plot(tr0_qref, tr0_qref,'.-', color='k',label='reference')
plt.legend(bbox_to_anchor=(1.05, 1.05))
plt.show()
```
## With xclim 0.41
The adjustment aligns well expect for the 0th quantile.
### Example data
![image](https://user-images.githubusercontent.com/24508496/227987953-477cfb20-963c-4216-81a5-98ad00c3a389.png)

### Our data
![image](https://user-images.githubusercontent.com/24508496/227988117-91ae51cb-71ff-4c6a-b59a-8308cbefa562.png)

## With xclim 0.24
As expected the adjusted quantile 0 is coinciding with the reference.

### Example data
![image](https://user-images.githubusercontent.com/24508496/227986316-a3ae0eb4-7c74-470c-b90c-34922c44dba1.png)

### Our data

![image](https://user-images.githubusercontent.com/24508496/227988213-fe604c24-fb2b-4a3a-9f5c-286229d567bd.png)

I hope it becomes clear that 0.41 seems to perform very well except for the very last extreme value. Any idea why that would be?

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Hi @saschahofmann,
I believe this is due to the change in #1016 (added in v0.34). After finding some weird behaviours in a few bias-adjustment projects done with xclim's quantile mapping, we realized that adjusting the 0th and 100th percentiles was not always appropriate. I invite you to read #1015 for my explanation. Unfortunately the rest of the discussion between me and collaborators happened in another, private channel.

Currently, the best way around this change is to simply pass an explicit list of quantiles to adjust. For example, to fit with the same quantiles you use in your plots:
```
QDM = QuantileDeltaMapping.train(
    ref, hist, nquantiles=np.linspace(0,0.05,100),
    kind="+", group="time"
)
```
Or to go back with the same behaviour as 0.24 :

```
from xclim.sdba.utils import equally_spaced_nodes
QDM = QuantileDeltaMapping.train(
    ref, hist, nquantiles=equally_spaced_nodes(100, eps=1e-6),
    kind="+", group="time"
)
```
The latter generates 100 nodes from 0.005 to 0.995 and then adds 0.000001 and 0.999999.

**Comment by saschahofmann** [comment]
Thanks @aulemahal for the quick response. The data plot for our data in 0.41 was actually generated with a list of quantiles. Interestingly the plot doesnt change whether I include the 0 or dont.

Reading your changes now.

**Comment by saschahofmann** [comment]
Ok. As I mentioned it seems like whether or not I include the 0th percentile has no impact on the result, I will try to see what happens if I use a very small quantile like you suggested. We are using quantiles that arent equally distanced not sure what would the impact be.

**Comment by saschahofmann** [comment]
Hi @aulemahal , Even with the borders included or small quantiles around 0 and 1 the spread is still very different from what we got in 0.24 ? Any idea how we could enforce the extreme quantiles to be adjusted as well?

**Comment by aulemahal** [comment]
Hi @saschahofmann , sorry for the long delay, I was overloaded with other projects...

I ran your example again, but added a few lines after  the creation of `hist_adj`:
```python3
qq=np.linspace(0,1,101)
QDM2 = QuantileDeltaMapping.train(
    ref, hist, nquantiles=qq, kind="+", group="time"
)
hist_adj2 = QDM2.adjust(hist)

# Create some plots to see the extreme values
qref=np.linspace(0,0.05,100)
tr0_qref= ref.quantile(q=qref,dim='time')
t0_qref = hist_adj.quantile(q=qref,dim='time')
t0_qref2 = hist_adj2.quantile(q=qref,dim='time')
```
And plotting:
```python3
plt.plot(tr0_qref, t0_qref,'.-', label='Adj - normal', alpha=0.4)
plt.plot(tr0_qref, t0_qref2,'.-', label='Adj - explicit array', alpha=0.4)
plt.plot(tr0_qref, tr0_qref,'.-', color='k',label='reference')
plt.legend(bbox_to_anchor=(1.05, 1.05))
```
Which gives:
![image](https://user-images.githubusercontent.com/20629530/231262792-f19c9fe2-8a66-4423-a70c-5d33687cc894.png)
The 0th quantile is here "perfectly" adjusted. 

Thus, I'm not sure I understand your questions... Do you expect _all_ quantiles to be "perfectly" on the 1:1 line ? Only the ones explicitly specified in the training part should be exact, which is what my example shows for `q= 0, 0.01, 0.02, 0.03, 0.04 and 0.05`.

**Comment by saschahofmann** [comment]
Hi @aulemahal,
Thanks for your example and sorry for taking so long to try it again! You're right it seems like that with equidistant quantiles it seems to adjust the 0th percentile perfectly.

We are playing around with higher resolution around the extreme (basically to have better performance we are saving points around the median).

If you replace `qq` with something like this 
```python
qq=np.hstack([
    np.linspace(0,0.01, 60,endpoint=False),
    np.linspace(0.01,0.1, 55,endpoint=False),
    np.linspace(0.1,0.9, 40,endpoint=False),
    np.linspace(0.9,0.99, 55,endpoint=False),
    np.linspace(0.99,1, 59,endpoint=True),
])
```
You should end up with something like this (I zoomed in a bit and selected the worst ) 
![image](https://user-images.githubusercontent.com/24508496/234120634-08f2fb07-6ab2-4ebd-8526-8d198151dbc9.png)

**Comment by aulemahal** [comment]
I think I found the « bug » !

During the adjustment, instead of finding the quantile of each value, QDM takes a shortcut and computes the _rank_ of each value. A priori, this should yield the exact same result, but it turns out it's not. The minimum value of an array of N values will have a quantile of 0 and a rank of 1. The maximum will have a quantile of 1 and a rank of N. The `pct=True` option of xarray's  `rank` method translates the integer ranks back to the 0-1 range. However, while the maximum goes from rank N to pct-rank 1, the minimum goes from 1 to 1/N. Not 0.  Thus, when adjusting there's a small difference between the computed quantiles/ranks and the adjustment' factor's "quantile" dimension.

I can fix that in a PR, soon. Thanks for the issue and the discussion, this is really a subtle nuance I wouldn't have caught while testing!

**Comment by saschahofmann** [comment]
Wow thanks for looking into seems like a very subtle thing!
