### ISSUE TITLE
[PyOpenSci] Non-"time" dimensions in frequency_analysis

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1342]
Original reviewer comment : 

> Since, at the moment, "all frequency analysis functions are hard-coded to operate along the `time` dimension", perhaps a brief reference to `xr.DataArray.rename` on how to rename a dimension in xarray would be useful?

It is referring to a comment appearing in the "Frequency Analysis" notebook. The culprit function is [xclim.indices.stats.frequency_analysis](https://github.com/Ouranosinc/xclim/blob/78ff493ded25907c4e17f0695950d1e04ff88d28/xclim/indices/stats.py#L346) .

Indeed, like most of xclim, the reduced dimension is hardcoded to "time", but the rest of the function is also specifically coded for temporal data, with a resampling operation. The reviewer suggest explaining how one would rename a dimension so that users can use this with any variable.

--

Personally, I think  `frequency_analysis` needs a major review before running on non-temporal dimensions, it's not just a matter of renaming the dimension because of the `resampling` operation.

**Comment by Zeitsperre** [comment]
Original comment post: https://github.com/pyOpenSci/software-submission/issues/73#issuecomment-1484520663
