### ISSUE TITLE
"How to cite this library" link broken in README

### ISSUE THREAD

**Issue by VeckoTheGecko** [Ouranosinc/xclim#1353]
### Generic Issue

- [x] I looked for a similar issue in the issue tracker

In the README, the link for "How to cite this library" is broken

https://github.com/Ouranosinc/xclim/blob/1966c0f8bb6bdeceb97bc7a70fc5f4eb8121be1b/README.rst?plain=1#L78-L82

![image](https://user-images.githubusercontent.com/36369090/232953658-dc04ca0b-b198-4bcc-b4e8-e938ce72729d.png)

Not sure what the appropriate link would be (hence no PR).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
@VeckoTheGecko 

We regularly run link checks in our documentation, but not for those within the README. Thanks for letting us know!

**Comment by VeckoTheGecko** [comment]
Happy to help 🙂. For interest, do you use an automated tool for link checking? I've been looking for something similar

**Comment by Zeitsperre** [comment]
Our documentation is built using `sphinx`, so we try to check for valid URLs in the rendered documentation using their `linkcheck` Makefile command:
https://github.com/Ouranosinc/xclim/blob/1966c0f8bb6bdeceb97bc7a70fc5f4eb8121be1b/.readthedocs.yml#L19 

* [Linkcheck configuration documentation](https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-linkcheck-builder)
* [Linkcheck builder documentation](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder)

**Comment by VeckoTheGecko** [comment]
Just wanted to say thanks @Zeitsperre for your thorough `linkcheck` comment! Really helped me with setup 😄

**Comment by Zeitsperre** [comment]
@VeckoTheGecko No problem! Happy to see that the information was useful!
