### ISSUE TITLE
`tasmin` in cold spell indices

### ISSUE THREAD

**Issue by coxipi** [Ouranosinc/xclim#1387]
### Generic Issue

This issue stems from the points discussed in #1370 . I'll be closing the PR, but I just want to document the discussion / reflexions I had on this topic here.

 `xclim.indices.cold_spell_frequency` currently uses  `tas`. There doesn't to be a clear cut answer in the literature for "cold_spell" if it should use `tas` or `tasmin`. There is however a well formulated `cold_spell_duration_index` is formulated using `tasmin`, e.g.  https://gmao.gsfc.nasa.gov/research/subseasonal/atlas/Tindices-html/CSDI-ts.html

It might be a matter of `cold_night` vs. `cold_days`.  Night will use the `min` variable, day will use the `avg` or `max` variable, so it might make sense in this context.

In comparison, the case of `hot_spell_XYZ`  seems to be a reduction of analog `heat_wave` indices where the constraints on `tasmin` were dropped, leaving only `tasmax` in the indicator. We could similarly base our `cold_spell_XYZ` on a variation of `cold_spell_duration_index`. 

If we are not basing `cold_spell_XYZ` and `hot_spell_XYZ` on specific indices in the literature, then in my opinion, it would make more sense to use `tasmin` & `tasmax` OR only `tas`. We currently have a mix of `tas` & `tasmax` 

It was also suggested in xclim discussions that we could create new indices that accept `tasmin` instead of `tas`, that could be another approach.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ludwiglierhammer** [comment]
If I may make a suggestion, I would recommend the use of `tasmin` to make a clear differentiation between `cold_spell_XYZ` and `hot_spell_XYZ`. In my opinion, there are more relevant points in favor of using `tasmin` than in favor of using `tas` (differentiation to `hot_spell_XYZ`, literature using `tasmin` for `cold_spell_duration_index`).

**Comment by coxipi** [comment]
I agree with you, I think if we were writing the index now, we would choose this way. Since it's already written and as far as I know, there is no specific index in the literature named `cold_spell_XYZ` that would require a change of our function, the general sentiment was that we should leave this as-is. I'll be closing the issue for now.
