### ISSUE TITLE
DOCS: Better documentation for climate indicators and indices

### ISSUE THREAD

**Issue by SarahG-579462** [Ouranosinc/xclim#1395]
### Addressing a Problem?

The current documentation for climate indicators (https://xclim.readthedocs.io/en/latest/indicators.html) is very hard to read: lines extend indefinitely, all indicators are on the same page, and details about the calculations and inputs require jumping between multiple places in the documentation. Some indicators have extra parameters (e.g. `id`) that others don't. The realm for "atmos" is very large, making searching for the correct indicator quite laborious.

The documentation on the difference between indices and indicators isn't located in an easily accessible location, currently it's in "examples > extending xclim > indices vs indicators". There is some description on the pages themselves for indicators/indices, but it does not link to this page.

The indices module does not distinguish realms, making searching laborious (e.g., 599 results for "temperature"...)

### Potential Solution

- [x] #1436
- [x] #1437
  - The API page has been significantly sped up using a different backend and since migrating to the `furo` theme. 
- [x] Explain why some indicators don't have an `id`, or other parameters. 
- [x] #1438
- [x] potentially have a link from these to `atmos` in the `atmos/__init__.py`, as `from xc.core.indicators.atmos.temperature import *`, for example
- [x] #1433

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
Related issue: #1312

**Comment by Zeitsperre** [comment]
@SarahG-579462 

> potentially have a link from these to atmos in the atmos/__init__.py, as from xc.core.indicators.atmos.temperature import *, for example

I feel like we already do this, no?
