### ISSUE TITLE
Comments on xclim.ensembles._filters.py

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xclim#1412]
### Generic Issue

* xclim version: 0.44.5-beta

### Description
Since I wasn't able to submit a review of those functions in time, here are a few comments.

1. Overall, I think the functions are well defined and separated. We do have something similar in `xscen`, but applied on catalog entries instead of DataArrays. Thus, I don't think it overlaps. FYI, here are the two similar `xscen` functions:
     - `_concat_hist`: [_dispatch_historical_to_future](https://github.com/Ouranosinc/xscen/blob/03e071f999b0d18a883b7e7c151dbc9a6ad7c1f3/xscen/extract.py#L1088)
     - `_single_member`: [_restrict_multimembers](https://github.com/Ouranosinc/xscen/blob/03e071f999b0d18a883b7e7c151dbc9a6ad7c1f3/xscen/extract.py#L1302)

2. To be closer to the CMIP6 vocabulary, and since we don't have something similar elsewhere in `xclim`, I'd rename `model --> source` and `scenario --> experiment` both in the Docstrings and the function names (including in `xclim.ensembles._partitioning`).

3. Since the required `da` differs substantially from what is created with `xclim.ensembles.create_ensemble()`, I think that it could be worth it to have an example somewhere in the documentation of how this DataArray is created.

Other than that, it looks good to me!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huard** [comment]
For 2, I suggest to keep the same names as those used in the paper. 

For 3, see PR #1463

**Comment by RondeauG** [comment]
Sounds goods! Thanks.
