### ISSUE TITLE
Create subrealms/categories, atmos.temperature, atmos.precipitation, atmos.wind, atmos.mixed, etc, for temperature, precip, wind and mixed indicators

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1433]
### Problem

We currently divide our indicators according to the CMIP CV-style "realm" in which its composite variables can be found (ie: `tas`: `atmos`; `q`: `land`). This was reasonable to take as an approach at the start, when the number of indicators was more manageable, but we've passed 150 indicators now.

This is causing some UX problems on the docs:
 - The nesting of indicators within the docs means that `atmos` indicators must all be loaded within the API page before scrolling, causing major slowdown.
 - The sidebar is so long that it is unnavigable/redundant. 
 - More generalized indicators are mixed in with very specialized ones, listed alphabetically

### Potential Solution

We develop sub-realms for indicators so that they can be more effectively managed and divided. We already do this to some degree with the structure (e.g `fire` indices), but perhaps splitting out the `agro` indicators (like `winkler_index`) and `anthro` indicators (like `humidex`), and others would make this more approachable?

This would constitute a major breaking change, but would be a good step towards v1.0.

### Additional Context

An example of the nesting issue (even problematic for portrait oriented screens):

![image](https://github.com/Ouranosinc/xclim/assets/10819524/4a58e855-ca18-42f5-a0a4-be3d8442761d)

**Comment by aulemahal** [comment]
We have a "keyword" metadata field that is currently unused. Maybe we could make use of that to pass this categorical information ? 

This reorganization could be non-breaking if it concerned only the documentation ? Instead of a static list of indicator, could we expose a search section with option for keyword filtering / variable filtering / free text search ?
