### ISSUE TITLE
Call signatures for functions are exhaustively shown in search

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1441]
### Setup Information

- Xclim version: 0.44.0
- Python version: Any
- Operating System: All

### Description

When searching for a particular index/indicator, the first entries (that likely are what you need) are easy to miss, as the entire call signature with default values is visible in the entry. This makes it very busy and looks incomprehensible at first glance.

### Steps To Reproduce

Go to https://xclim.readthedocs.io/en/stable/ → Search for anything

### Additional context

Search keyword: "Huglin"

![image](https://github.com/Ouranosinc/xclim/assets/10819524/69454123-5d65-48be-873f-0857f243e559)

### Contribution

- [ ] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huard** [comment]
I think we could tweak the ranking of results with some configuration: https://docs.readthedocs.io/en/stable/config-file/v2.html#search-ranking

**Comment by huard** [comment]
My superficial understanding is that the search results only display "existing content". So to remove the call signatures in search results, you'd have to remove the call signatures in the docs themselves, which we probably don't want to do. 

I thought we could maybe tweak the CSS to hide the parameters, but the search converts the HTML content to text before displaying the results (as far as I understand). That, or what we see is actually the "index" in the content database, so we probably don't want to play there. 

Unless someone has other ideas to move this forward, I suggest we close this.

**Comment by Zeitsperre** [comment]
Thanks for looking into this. I couldn't find much to handle the call signatures issue either. I did stumble upon https://github.com/sphinx-contrib/sphinx-pretty-searchresults for removing the broken formatting found under entries, but not cleaning up the entries themselves. 

We'll probably be fine with adjusting the scoring system.
