### ISSUE TITLE
Should we be importing `indices` at the top-level?

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1448]
### Setup Information

- Xclim version: 0.44.0
- Python version: Any
- Operating System: All

### Context

I've always noticed that when writing scripts dependent on `xclim.indices`, unless we explicitly import `indices` we'll get IDE warnings:

![image](https://github.com/Ouranosinc/xclim/assets/10819524/cc2748b3-d666-464e-916e-3977c202d1c9)

This is of course only a warning (I imagine that `xclim.indices` is implicitly imported via the indicators or Python allows for importing modules that are otherwise not listed within ```__init__.py```).

What I'm wondering is if there is any reason _not_ to import indices on import of `xclim`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huard** [comment]
It's there anyway, so if we can remove warnings by importing it explicitly, I say go for it.

**Comment by Zeitsperre** [comment]
This issue was addressed in commit 37bfd503c3cdec743f85fcb48cb8d216a8841b24
