### ISSUE TITLE
xclim.core.utils.ValidationError: Value's dimension `[length]` does not match expected units `[mass] / [length] ** 2 / [time]`.

### ISSUE THREAD

**Issue by millet5818** [Ouranosinc/xclim#1453]
### Setup Information

- Xclim version: 0.25.0
- Python version: 3.6
- Operating System: windows 10

### Context

Dear developers:
  I tried to use the function (xclim.indicators.atmos.wetdays) to calculate the total number of days during the period with precipitation over the threshold, but an issue happened. the code and error are listed below:
"Code":
```
file="F:\\file\\total_precipitation_1984.nc"
ds=xr.open_dataset(file)
ds=xclim.core.units.convert_units_to(ds.tp,'mm')
a=xclim.indices.wetdays(ds,thresh='1 mm/day', freq='YS')

```
"Error":
xclim.core.utils.ValidationError: Value's dimension `[length]` does not match expected units `[mass] / [length] ** 2 / [time]`.
I don't know what's wrong with this code and NC file. The above file was downloaded from the ERA5 website. The units of origin file is m.  

Thank you very much for your help, and I look forward to your reply！

Zheng Zhao

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Hi @millet5818 !

In the first versions of xclim, after much discussion and trials, the dev team decided that "precipitation" data would be supported only with units (dimensions) of flux (mass per area per time, `kg m-2 s-1`, CMIP6 standard) or rate (length per time, `mm/d`). This already results in somewhat complex code, so we decided NOT to support units of length only (`m`, like your case). It is too ambiguous.

But, if you know what your data is, there are a few ways to adapt it for xclim:

- Assuming you know the sampling timestep, simply swap the attribute: `ds.tp.attrs['units'] = 'mm/day'`
- Assuming the lengths are the accumulation during the timesteps of  `ds.time`  : `xc.core.units.amount2rate(ds.tp)`

See the doc of the second function [here](https://xclim.readthedocs.io/en/stable/xclim.core.html#xclim.core.units.amount2rate).

Both are similar, but the second is a but more flexible and less arbitrary.

Hope that helps!

**Comment by millet5818** [comment]
Hi @aulemahal !
Thank you for your valuable suggestions. I have adopted the function `xc.core.units.amount2rate(ds.tp)` to convert units of precipitation.
Best wishes！

**Comment by millet5818** [comment]
Hello, @aulemahal 
I tried to calculate R95P by using function `xclim.indicators.icclim.R95p`. For definition of R95P, a wet day with precipitation is above 1mm. So i first filtered the data, and then calculate the 95th percentile of a wet day over a given period, and finally calculated the R95P by using  the` xclim.indicators.icclim.R95p` function. Can you help me if the following code is correct?

Due to the first use of xclim packgae, many functions are not well understood for me. I'm sorry to disturb you again. Looking forward to your reply.
```
file="F:\\file\\total_precipitation_1984.nc"
ds=xr.open_dataset(file)
ds=xclim.core.units.amount2rate(ds.tp, out_units="mm/d")
wetdays_Array=ds.where(ds> 1)
R95T = wetdays_Array.quantile(0.95, dim='time', keep_attrs=True)
R95P=xclim.indicators.icclim.R95p(ds, pr_per=R95T,freq='YS')
```

**Comment by aulemahal** [comment]
Yes this looks good!

**Comment by millet5818** [comment]
Hi @Zeitsperre
Yeah, thanks so much for your reminder, I have updated the newer version of xclim (v0.44) and python (3.9).  The tool (xclim) is very helpful for me to develop the procedures for the identification of compound events.
