### ISSUE TITLE
Drop Python2.7 support

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#147]
The maintainers of xarray, numpy, and birdhouse (mostly) have all dropped Python2.7 support. Extending support would require us to use deprecated libraries and ignore the amazing work @jwenfai has done in our xarray fork (soon to be merged upstream!). I think we should remove Python2.7 from this and other libraries dependent on/related to those projects.

**Comment by huard** [comment]
I suggest we stop investing time in 2.7 support, but defer clean-up to a later time.
