### ISSUE TITLE
Add a rolling_statistics

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xclim#1480]
### Addressing a Problem?

We already have `statistics` and `thresholded_statistics`, but a `rolling_statistics` would be very useful for anything related to hydrology and probably other domains too.

Use cases include for example computing the `maximum 14-day mean flow (q14max)`, or the `minimum 7-day mean flow (q7min)`.

### Potential Solution

Possible code to be used:
```
def roll_stats(da: xr.DataArray, window: int, window_reducer: str, reducer: str, freq: str, **indexer) -> xr.DataArray:
    """Calculate a stat on a rolling stat."""
    rolled = getattr(da.rolling(time=window, center=True), window_reducer)()
    rolled_indexed = select_time(rolled, **indexer)
    out = getattr(rolled_indexed.resample(time=freq), reducer)()
    out.attrs["units"] = da.attrs["units"]  # on peut faire mieux
    return out
```

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
@RondeauG Still willing to contribute this?

**Comment by RondeauG** [comment]
Sorry I kinda abandoned this! Yes, I can contribute.
