### ISSUE TITLE
module 'xclim' has no attribute 'icclim'

### ISSUE THREAD

**Issue by matteodefelice** [Ouranosinc/xclim#149]
* xclim version: 0.1.0
* Python version: 3.6.7
* Operating System: macOS

### Description

I have just installed `xclim` with `pip` and I have tried to run the four lines in the Github README:
```
import xclim     
import xarray as xr 
ds = xr.open_dataset('myfilename.nc') 
tg = xclim.icclim.TG(ds.tas, freq='YS')
```

and...

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-82f75f519f18> in <module>
----> 1 tg = xclim.icclim.TG(ds.tas, freq='YS')

AttributeError: module 'xclim' has no attribute 'icclim'
```

**Comment by huard** [comment]
Hi Matteo, 

I'm suspecting the release on PyPi to be out of date, sorry about that. Please try to install from master and give it another spin. 

@tlogan2000 @Zeitsperre I think this calls for a release and upload on PyPi.

**Comment by matteodefelice** [comment]
You are right, unfortunately I couldn't install it from source because there is a kind of conflict with my anaconda environment during the installation of bottleneck:
```
AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
```
then I think I will wait for the PyPI release!

**Comment by tlogan2000** [comment]
For your info : For an updated pypi release we are simply waiting for an xarray pull release, with some key functionality, that we have submitted to be integrated into their master. see https://github.com/pydata/xarray/pull/2593.  

We can then directly include xarray (and not our branch) in the xclim requirement for the PyPI release .
It should not be too long as it is in the final stages...

**Comment by Zeitsperre** [comment]
@matteodefelice 

@tlogan2000 is correct, we are almost ready to deploy a working version on PyPI. Once we have stable dependencies and a few more basic indices coded, we'll tag a version that automatically deploys there. The current version on PyPI is simply a parked template to keep the name.

If you are interested in trying it out now. I would make a new environment in conda (`conda create -n xclim && conda activate xclim`) and follow the [source installation directions](https://xclim.readthedocs.io/en/latest/installation.html#from-sources) from there.

**Comment by Zeitsperre** [comment]
@matteodefelice The library now has a beta version available on PyPI. Can you try reinstalling via "pip install xclim" and let us know if the problems persist?

**Comment by matteodefelice** [comment]
now it works! Great!
