### ISSUE TITLE
Number of  days can be both nan and 0

### ISSUE THREAD

**Issue by KatharinaBuelow** [Ouranosinc/xclim#1491]
### Generic Issue

* xclim version: 0.44.0
* Python version: 3.10
* Operating System: linux

### Description
We calculated [snow cover duration](https://xclim.readthedocs.io/en/stable/api.html#xclim.indicators.land.snd_season_length) for CORDEX data.

We noticed number of days can be both nan and 0 .
The calculation leads to nan if all values are equal 0. 
The calculation leads to 0 if at least one value is greater than 0 but all values are below threshold.
In both cases we expected a 0.
Is there a special purpose for this differentiation?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Hi @KatharinaBuelow and thanks for the issue!

Indeed, I'm not sure why we would need this differentiation. We have code that ensures that NaN is returned if there are not enough valid values, but it seems that "> 0" test was added to it. Here : https://github.com/Ouranosinc/xclim/blob/0ce4d30000a820578483400a5bfe1e68beb7254c/xclim/indices/_threshold.py#L2072

Maybe @coxipi knows ?

But we could remove that extra test indeed.
