### ISSUE TITLE
"parallel" -> "parallelized"

### ISSUE THREAD

**Issue by KatharinaBuelow** [Ouranosinc/xclim#1493]
### Generic Issue

* xclim version: 0.44.0
* Python version: 3.10
* Operating System: linux

### Description

We found a spelling mistake:
https://github.com/Ouranosinc/xclim/blob/master/xclim/indices/helpers.py#L299
"parallel" -> "parallelized"

here it is fine:
https://github.com/Ouranosinc/xclim/blob/master/xclim/indices/generic.py#L993

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Vielen dank, I'll slip a fix in my other PR!
