### ISSUE TITLE
Adopting `flox` as a "true" optional dependency?

### ISSUE THREAD

**Issue by coxipi** [Ouranosinc/xclim#1509]
### Addressing a Problem?

`xclim` could benefit from faster/more optimized implementations wherever it is possible.

### Potential Solution

The `flox` module has been proposed as a way to optimize grouping/reducing operations. We should investigate where its implementation could be useful and add flox as an optional dependency if it's worth it.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
Closing until the situation changes, and we require `flox`.
