### ISSUE TITLE
Validate YAML using schema

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#1523]
### Addressing a Problem?

Help identify errors in YAML indicator definition by validating config against schema. 

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
This is also a recommendation made in [LFD121](https://training.linuxfoundation.org/training/developing-secure-software-lfd121/).
