### ISSUE TITLE
Grouper.__init__() got an unexpected keyword argument 'base'

### ISSUE THREAD

**Issue by CGL5230** [Ouranosinc/xclim#1533]
### Generic Issue

* xclim version: 0.46.0
* Python version:3.11.4
* Operating System:Linux

### Description
When I want to run this, this error occured."TypeError: Grouper.__init__() got an unexpected keyword argument 'base'". The dataset I used is daily data.

### What I Did

```
AWI_CM_ssp585rx1day = xclim.indicators.atmos.max_1day_precipitation_amount(pr='pr',freq='YS',ds=pr_AWI_CM_ssp585)
```

### What I Received

```
TypeError                                 Traceback (most recent call last)
Cell In[3], line 1
----> 1 AWI_CM_ssp585rx1day = xclim.indicators.atmos.max_1day_precipitation_amount(pr='pr',freq='YS',ds=pr_AWI_CM_ssp585)
....

File /opt/conda/lib/python3.11/site-packages/pandas/core/resample.py:1663, in TimeGrouper.__init__(self, freq, closed, label, how, axis, fill_method, limit, kind, convention, origin, offset, group_keys, **kwargs)
   1660 # always sort time groupers
   1661 kwargs["sort"] = True
-> 1663 super().__init__(freq=freq, axis=axis, **kwargs)

TypeError: Grouper.__init__() got an unexpected keyword argument 'base'

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Hi @CGL5230 !

For the moment, I forget which versions are problematic, but I'm pretty sure this issue comes from a mismatch between your versions of `xarray` and `pandas`. I though we had this issue fixed in our dependencies, but it seems not, may be our CI setup simply does not build with the problematic versions anymore.

I suggest you upgrade xarray and pandas if you can. If you can't, or it doesn't fix the problem, please provide us the output of :
```python3
from xclim.testing import show_versions
print(show_versions())
```
We'll try to find the exact culprit and suggest a specific environment change.

**Comment by CGL5230** [comment]
Here is the output based your suggestion. I can't find the dependencies in the xclim doc. Maybe you can add those imformation to the Home page.

> 

INSTALLED VERSIONS
------------------
python: 3.11.4
boltons: installed
bottleneck: 1.3.7
cf_xarray: 0.8.6
cftime: 1.6.2
click: 8.1.6
clisops: None
dask: 2022.02.0
flox: None
jsonpickle: 3.0.2
lmoments3: 1.0.6
numba: 0.57.1
pandas: 2.0.3
pint: 0.22
scipy: 1.9.3
sklearn: 1.3.0
statsmodels: 0.14.0
xarray: 2023.1.0
xclim: 0.46.0
Anaconda-based environment: yes

>

**Comment by CGL5230** [comment]
I create a new enviroment and reinstall xarray and xclim. The above command can work. I guess the problem is the version of dependencies unmatch the xclim

INSTALLED VERSIONS
------------------
python: 3.11.0
boltons: installed
bottleneck: 1.3.7
cf_xarray: 0.8.6
cftime: 1.6.3
click: 8.1.7
clisops: None
dask: 2023.11.0
flox: None
jsonpickle: 3.0.2
lmoments3: 1.0.6
numba: 0.58.1
pandas: 2.1.3
pint: 0.22
scipy: 1.11.4
sklearn: 1.3.2
statsmodels: 0.14.0
xarray: 2023.11.0
xclim: 0.46.0
Anaconda-based environment: yes
