### ISSUE TITLE
AttributeError: module 'xclim.ensembles' has no attribute 'robustness_fractions'

### ISSUE THREAD

**Issue by AlvaroSalazar2021** [Ouranosinc/xclim#1553]
### Setup Information

- Xclim version: 0.45.14-beta
- Python version: 3.11.6
- Operating System: Linux

### Context

I wanted to apply robustness analysis from the xclim.ensembles package but I'm getting the error 'module xclim.ensemble' has no attribute 'robustness_fractions'. I have 3 members of an ensamble and want to test the same method as in the online tutorial with the example command 'fractions = 'xclim.ensembles._robustness.robustness_fractions)(fut, ref, test="ipcc-ar6-c")
fractions' but I run into the mentioned error. I have followed the ensemble analysis tutorial using my data (statistics, percentile analysis and plotting) and all worked fine until the most important section of robustness analysis. Any guidance is much appreciated.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tlogan2000** [comment]
Updating to v0.47 should solve this .  `robustness_fractions` is a recent addition https://github.com/Ouranosinc/xclim/releases/tag/v0.47.0

**Comment by AlvaroSalazar2021** [comment]
Thank you very much to both of you, happy that the solution was that simple. Cheers
