### ISSUE TITLE
Better search results 

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1559]
### Addressing a Problem?

Current search results of the indicators page are purely alphabetical and include the "virtual" modules.

### Potential Solution

- Add a larger "weight" to the atmos indicators
- Add a checkbox to include/exclude the virtual modules

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huard** [comment]
Possiblement que `boostDocument` pourrais servir à ça.
