### ISSUE TITLE
Which units should a "sum" aggregation return ?

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1645]
### Generic Issue

Generic indices such as `select_resample_op` manage the units automatically using `to_agg_units`. This function decides how to transform the units according to the type of aggregation.

When it was first written, the only case for "sum" was degree-days, i.e. _integrating_ temperature over time. As such, the units are multiplied by the timestep. In most cases, this is a day and so it simply adds "d" to the existing units. Ex:
```
tas : daily temperature in K
out = to_agg_units(tas.sum(), tas, op='sum')
out.units == "K d"
```

However, an example where this is wrong has been raised in xhydro. https://xhydro.readthedocs.io/en/latest/notebooks/local_frequency_analysis.html#d)-Computing-volumes, see cell output 12.

The input data is the daily _volume_ of water flowing in a river. Thus, here we want the actual sum, not an integral.

Question:
Should we go back to considering `op='sum'` as an actual sum (and leave the units untouched) ? We already have `'integral'` as an available choice for `op`, it just isn't a common method name.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
I think that approach makes the most sense. `sum` should be understood to be a true summation. A change like this should be considered equivalent to a bug fix, IMO.

**Comment by coxipi** [comment]
I agree, sum should leave units intact, integral changes units
