### ISSUE TITLE
Rename the `master` branch to `main`

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#1667]
### Why?

We have been progressively moving over the trunk names for all of our projects to the new default that was adopted in 2020 (https://www.techrepublic.com/article/github-to-replace-master-with-main-starting-in-october-what-developers-need-to-know/). This repo hasn't moved until now as we didn't want to negatively impact those who've forked our code, but given that the majority of Ouranos projects _around_ xclim have now fully migrated to `main`, it just makes sense to change it now.

I'd like to see us effect this change in advance of v0.49.0. Thoughts?

**Comment by coxipi** [comment]
> negatively impact those who've forked our code

Any big projects that we should warn as a courtesy? e.g. `icclim`? I don't know if this change would even affect them.

**Comment by aulemahal** [comment]
We have 48 forks according to github, but only 7 have seen any push activity in the last 2 years, it goes down to 3 for the last year (including one bot). I think we're safe!

**Comment by Zeitsperre** [comment]
> > negatively impact those who've forked our code
> 
> Any big projects that we should warn as a courtesy? e.g. `icclim`? I don't know if this change would even affect them.

I don't think so. `icclim` based on our stable releases, so no problem there. Right, @bzah?

**Comment by bzah** [comment]
Yep, no issues for icclim :)
