### ISSUE TITLE
Ensemble agreement assigns members with exactly no change to the negative fraction

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1690]
### Addressing a Problem?

 `robustness_fractions` has the `agree` output which is the fraction of valid models agreeing on the sign of change. It is currently a simple calculation based on `positive`, fraction of valid members showing positive change.

In summary:
```python3
positive = delta > 0
agree = max(positive, 1 - positive)
```

If the `delta` has real zeros, they are not counted towards `positive`. A dataset where a few members showing real positive change could come out has having low agreement.

### Potential Solution

I think it would be more intuitive if the agreement fraction included the members showing no change.

```python3
positive = delta > 0
negative = delta < 0
no_change = delta == 0
agree = max(positive + no_change, negative + no_change)
```

This is also the opinion of the Portraits Climatiques team.

### Additional context

The previous value of `agree` could always be recomputed by a user as `positive` is an output of the function.

What does @RondeauG and @huard think of this ?

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huard** [comment]
I would tend to disagree. I consider a model with a change of 2C in disagreement  with a model with a change of 0C. 

I understand this is beyond the scope of this function, but in my mind you'd have a threshold `t` such that models can be divided into 

```
negative change < -t <= no significant change <= t < positive change
```
Here t is 0, and values with 0 change would simply be part of another category of "no change". 

My suggestion is thus to say:
```
positive = delta > 0
negative = delta < 0
agree = max(positive, negative)
```

**Comment by aulemahal** [comment]
I understand. The threshold idea is not really beyond the scope of the function, ...  it is pretty much what the `threshold` method does!

In fact, I can avoid my problem by using that method, I didn't think of that!

**Comment by RondeauG** [comment]
Let's say that we have 15 simulations. 5 negative, 4 not significantly negative, 3 with a change of exactly +0, 2 not significantly positive, 1 positive.

- `changed`: Unless `test=None` --> 6/15.
- `positive`: I'd argue that _exactly_ +0 is not positive, thus `positive = delta > 0` is correct. --> 3/15.
- `changed_positive`: A change of +0 will not be counted here, since it will fail both tests. --> 1/15.
- `agree`: `max(3/15, 1 - 3/15) = 12/15` --> _**This is wrong!**_ --> This should be `max(positive, negative)`, aka 9/15.

**Comment by aulemahal** [comment]
The scientific consensus has spoken against my idea.
Thanks!
