### ISSUE TITLE
Dark mode docs

### ISSUE THREAD

**Issue by SarahG-579462** [Ouranosinc/xclim#1693]
### Addressing a Problem?

Could we have the docs for xclim be available in darkmode? with a toggle switch of course.

### Potential Solution

Change the readthedocs theme to something with a toggle for darkmode :) 

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
Should I investigate using `Furo`? Dark mode for free.
