### ISSUE TITLE
Implement additional methods for ensemble_percentile

### ISSUE THREAD

**Issue by SarahG-579462** [Ouranosinc/xclim#1694]
### Addressing a Problem?

At the moment only linear interpolation method 7 of [Hyndman and Fan](https://www.researchgate.net/publication/222105754_Sample_Quantiles_in_Statistical_Packages) is implemented for ensemble_percentiles.

Supposedly, method 8 is better for distribution-free variables, and method 9 is better for normally distributed variables. I would be interested to seeing the effects of choosing other interpolation methods on low-n variables (such as freezing rain indices for portraits climatiques, which only includes four models at the moment.) 

To do so, I would need other methods (at least methods 8 and 9) implemented for ensemble_percentiles.

### Potential Solution

Implement methods 8 and 9 for ensemble_percentiles in xclim, and expose the api for this function to allow a method selection.

### Additional context

Willing to contribute, but might take a while to get around to :) 

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
AFAIU, those three methods differ on what they use as the $\alpha$ and $\beta$ coefficients. xclim's `nan_quantile` exposes those two, so the simplest PR would be to expose that through the layers up until `ensemble_percentiles`.

(We discussed this in slack, but putting it here for all)  I believe however that xclim deserves a small performance check to see if our homemade `nan_quantile` really is still more performant than xarray's wrapping of numpy. 

Considering recent additions to flox and xarray (https://github.com/pydata/xarray/pull/8720), maybe `ensemble_percentiles` also deserves a look at its rechunking behaviour (i.e. maybe the usage of flox makes it unnecessary?).

**Comment by SarahG-579462** [comment]
There are plans to eventually have a benchmarking set up for xclim, #1510, your second point could be included in that, or it could be a small testbed for the benchmarks.

**Comment by bzah** [comment]
In case you don't want to start from scratch, I had a script to compare xclim's nan_quantile and numpy's nan_quantile on random samples, also testing how the performance change with the number of NaNs in the sample: https://gist.github.com/bzah/2a84d050b8a1aed1b40a2ed1526e1f12
Also numbagg added a performant nan_quantile not too long ago (https://github.com/numbagg/numbagg/pull/166), it might be interesting to add it to the comparison.
