### ISSUE TITLE
Duff moisture code

### ISSUE THREAD

**Issue by raybellwaves** [Ouranosinc/xclim#1698]
### Addressing a Problem?

I would like to use the Duff moisture code for wildfire analysis

### Potential Solution

Similar to https://xclim.readthedocs.io/en/stable/indices.html#xclim.indices.drought_code

### Additional context

See https://wikifire.wsl.ch/tiki-index9436.html?page=Duff+moisture+code

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
That should be fairly easy. If you want to give it a try, it could be as simple as copying the drought code indicator  and updating the inputs and body for the DMC. Mostly adding `hurs` as an input and removing the `overwintering` stuff.

https://github.com/Ouranosinc/xclim/blob/9bdc4e8a0d3fedf97892ce65547327d4acee3566/xclim/indices/fire/_cffwis.py#L1392-L1404

We will be happy to help you making a PR!
