### ISSUE TITLE
Python 3.4 Build Speed

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#17]
The CI build for Py3.4 is really slow. Is this simply normal behaviour?

**Comment by huard** [comment]
Don't know. I suggest we kill it and test for 2.7 and 3.6 only during development. Can we instruct travis to build for 3.4 and 3.5 for major releases only ?

**Comment by Zeitsperre** [comment]
Yep. I'll get to that to that in a new issue.

**Comment by huard** [comment]
Let's not spend too much time on "building the tool to build the tool" though.

**Comment by Zeitsperre** [comment]
This was worked around in 040d0e6cc5c4ee570f261c69c20a3a5eb89827c6 as build wait time limit is now 20 minutes.
