### ISSUE TITLE
Coveralls not updating

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1701]
### Generic Issue

Since March 27th 11am, coveralls has not performed any check on the xclim codebase.

See https://coveralls.io/github/Ouranosinc/xclim/

Also, the "branches" dropdown on that page only shows `main` and `pmp`... The latter being a stale branch from 2019!

For the time being, @tlogan2000 has made this check optional for PRs merging into `main`. (removed it from the "required" checks)  So we can carry on with small fixes while Zeit _github-master_ Sperre is on vacation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
Labas is lietuvos! Noted for when I get back.

Sėkmės!

**Comment by Zeitsperre** [comment]
I needed to recache the repo on Coveralls (we have a lot of stale branches, btw), but it seems as though everything is working as intended. I've re-enabled the coveralls check.

Closing for now. Re-open if this comes up again.
