### ISSUE TITLE
Support multiple dimensions in `stats.fit`

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#1715]
### Addressing a Problem?

stats.fit takes a dimension string, but I think it would be useful to be able to specify a list of dimensions, to fit parameters over data from multiple dimensions (e.g. `time` and `realization`).

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Is the solution as easy as :
```
daStckd = da.stack(stat_dim=['time', 'realization'])
stats.fit(daStckd)
```
?

If yes, could this be an example somewhere instead ?

**Comment by huard** [comment]
Yes, that's indeed the easiest way to solve this. I wonder if it's worth supporting out of the box. Maybe not.
