### ISSUE TITLE
Use/package `fastnanquantile`?

### ISSUE THREAD

**Issue by coxipi** [Ouranosinc/xclim#1751]
### Description

I was proposing the use of `fastnanquantile` in #1743, but in the discussion, it was noted that there is only one maintainer in this library and it is not packaged with conda. There was a suggestion we could help the maintainer:
* release the package on conda
* do an upstream contribution? `fastnanquantile` uses `numba`, it could be considered in `numbagg`, but it also has `xarray` bindings. It looks it could be somewhere between `numbagg` and `flox`?

We should also look at `xclim.core.utils._nan_quantile`. If it performs similarly well, then perhaps this is not necessary.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lbferreira** [comment]
Hi guys. I'm the creator of fastnanquantile. I'm very happy to know that my library has been useful for you.
As you mentioned that having it available in conda would be useful for xclim, today I submitted a PR to add fastnanquantile to conda-forge. I expected it to be approved soon.

**Comment by coxipi** [comment]
Thanks for the heads-up and also for this nice module, it helped us improve our computation speeds substantially!

**Comment by lbferreira** [comment]
Just to let you know, fastnanquantile can now be installed from conda forge:
`conda install -c conda-forge fastnanquantile`
