### ISSUE TITLE
Hardcoded window=1 in hot_spell_total_length and cold_spell_total_length

### ISSUE THREAD

**Issue by garciampred** [Ouranosinc/xclim#1765]
### Setup Information

- Xclim version: 0.48.1
- Python version: 3.10
- Operating System: Ubuntu 22.04.4 LTS

### Description

In https://github.com/Ouranosinc/xclim/blob/main/xclim/indices/_threshold.py I think that the window should be set to the window argument when resample_and_rl is called, and not to 1. 

```
    max_l = rl.resample_and_rl(
        cond,
        resample_before_rl,
        rl.windowed_run_count,
        window=1,
        freq=freq,
    )
```

### Steps To Reproduce

```python
import pandas as pd
import numpy as np
import xarray as xr
from xclim.indices import hot_spell_total_length

python
da = xr.DataArray(
    np.array([15, 34, 35, 37, 20, 25, 22, 24, 31, 22, 28, 32, 33], dtype=np.float32), 
    coords=dict(time=pd.date_range(start="2000-01-01", periods=13, freq="D")), 
    dims=["time"],
    attrs=dict(units="Celsius")
)
print(da)
```

    <xarray.DataArray (time: 13)> Size: 52B
    array([15., 34., 35., 37., 20., 25., 22., 24., 31., 22., 28., 32., 33.],
          dtype=float32)
    Coordinates:
      * time     (time) datetime64[ns] 104B 2000-01-01 2000-01-02 ... 2000-01-13
    Attributes:
        units:    Celsius

```python
result = hot_spell_total_length(da, window=3)
print(result)
```

    <xarray.DataArray (time: 1)> Size: 8B
    array([6])
    Coordinates:
      * time     (time) datetime64[ns] 8B 2000-01-01
    Attributes:
        units:    d

Expected result would be 3, not 6, as there is only one spell with three or more consecutive days exceeding the defult threshold of 30 degrees.

### Contribution

- [X] I would be willing/able to open a Pull Request to address this bug.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Zeitsperre** [comment]
@garciampred 

Thanks for raising this issue! This is clearly an oversight, IMHO. If you're willing to open a Pull Request to address this, let us know and we can merge that in very quickly.

**Comment by garciampred** [comment]
I can do the PR if it is simple. I think that cold_spell_total_length is affected too, while dry_spell_total_length and wet_spell_total_length have more code before calling resample_and_rl  and I think they may be OK.

So now I am not sure if the window=1 is the problem or if the problem is that these lines are missing:

```
pram_pad = pram.pad(time=(0, window))
mask = getattr(pram_pad.rolling(time=window), op)() < thresh
dry = (mask.rolling(time=window).sum() >= 1).shift(time=-(window - 1))
dry = dry.isel(time=slice(0, pram.time.size)).astype(float)
```

**Comment by Zeitsperre** [comment]
@aulemahal Thoughts?

**Comment by coxipi** [comment]
Just saw this during our meeting. 

I agree with this, there would be no point in having a `window` parameter as it is. The comparison just after the code shown `max_l.where(max_l >= window, 0)` doesn't make sense, `max_l` represents a sum of many spells, it should not be compared to `window` (which is minimum value for a single spell).  We actually had a test for this, and it excepts the current wrong behaviour:
```python
class TestHotSpellTotalLength:
    @pytest.mark.parametrize(
        "thresh,window,op,expected",
        [
            ("30 C", 3, ">", 8),  # Some HS
            ("10 C", 3, ">", 10),  # One long HS
            ("29 C", 3, ">", 8),  # Two HS
            ("29 C", 3, ">=", 9),  # One long HS, minus a day
            ("40 C", 3, ">", 0),  # No HS
            ("30 C", 5, ">", 8),  # LOOK HERE... WE SHOULD EXPECT 5 AS A TOTAL LENGTH
        ],
    )
    def test_1d(self, tasmax_series, thresh, window, op, expected):
        tx = tasmax_series(np.asarray([28, 31, 31, 31, 29, 31, 31, 31, 31, 31]) + K2C)

        hsml = xci.hot_spell_total_length(tx, thresh=thresh, window=window, op=op)
        np.testing.assert_allclose(hsml.values, expected)
```
