### ISSUE TITLE
First day with temperature threshold reached does not benefits from RL improvements

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1767]
The generic `first_day_temperature_reached`  does not use `rl.resample_and_rl`, which make the potential improvments of inverting the operation order inaccessible.

https://github.com/Ouranosinc/xclim/blob/edf1e13b7d47e4ead94506cdbb3bce1f977376f9/xclim/indices/generic.py#L947-L953

**Comment by Zeitsperre** [comment]
Proposition doesn't make sense, sadly. Closing.
