### ISSUE TITLE
Ability to choose operator for Indicators growing_season_start/end

### ISSUE THREAD

**Issue by nCarolina** [Ouranosinc/xclim#1794]
### Addressing a Problem?

It would be nice to be able to choose which operator to use for the indicators` growing_season_start/growing_season_end`. This is possible for the `growing_season_length` indicator. However, I find it a bit confusing if the default operator ">=" corresponds to the definition under **Notes** with `Tmean > 5 degC and Tmean < 5 degC` or if the default behaviour is ` Tmean >= 5 degC and Tmean <= 5 degC`.

### Contribution

- [ ] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aulemahal** [comment]
Hi @nCarolina!

Indeed, the same addition of the `op` argument of `growing_season_length` could be done to the other growing season indicators.  FYI, `>=` is what is currently coded in the start and end functions,

And sorry for the confusing documentation, the default behaviour for  `growing_season_lenght` is "T >= thresh" for a start and "T < thresh" (the boolean opposite) for an end.

**Comment by nCarolina** [comment]
Thanks to both of you for this quick response to my request!

@aulemahal Okey, then I understand how it works!
