### ISSUE TITLE
Github / Unit test / PyCharm review

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#18]
Sit down in the next few days to go over development procedures

**Comment by Zeitsperre** [comment]
Currently working on a PyCharm Quickstart for PAVICS training. Feel free to add comments there. https://docs.google.com/presentation/d/1ASsWtblcKljKl76WnFDVnRJw_xn5rUmpn50WXZUJEBI/edit#slide=id.g3f1d5ae7b8_0_703

**Comment by Zeitsperre** [comment]
Are people still interested in this? The development features/process is mostly solidified in my mind. If people have questions, my door is always open.

**Comment by tlogan2000** [comment]
Went through this with team members thx @Zeitsperre
