### ISSUE TITLE
Architecture clean-up 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#180]
### Description
I think we should take a moment and clean the files and namespace before the next release. 

For example, there is a lot of stuff in utils that I think should go into their own file. I don't like the fact that we have `temperature.py` and `precip.py` files for indicators, it seems arbitrary. 

Another question is then what should be exposed in the `xclim` namespace. 

Suggestion to clean up utils: 
- `base.py`for the Indicator class
- `generic.py` for generic functions used by indices.
- `ens.py` for ensemble related functions
- ... ?

Options for indicator classes: 
- follow the CMIP realm notation: `xclim.atmos` for all related atmospheric indicators, and `land` for hydrological processes, 'ocn' for ocean related stuff, etc. 
- all indicators directly in `xclim`

**Comment by Zeitsperre** [comment]
I like this idea. One thing I like to add if we decide to move forward with refactoring/restructuring is to ensure that file lengths don't become so long that they become difficult to navigate/maintain (ie: `indices.py` is nearly 1400 lines now). splitting the indices into realms is good, but if we expand the new structure to this level, we should consider another method of maintaining it (such as building another module shortcut like `xclim.icclim`, maybe even calling it `xclim.indices`).

Would we be okay with making this the final goal before a v1.0 release?

**Comment by tlogan2000** [comment]
@Zeitsperre is going to try to merge precip and temperature.py into an atmos directory.   As well, we are thinking of spltting indices.py into 3 separate files to reduce length : simple_indices.py, threshold_indices.py and multivariate_indices.py (or similar)
