### ISSUE TITLE
Update xrray requirement

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#181]
Xarray has recently released v0.12.0 on pypi containing the cf-calendar resampling work that was done by Low
https://pypi.org/project/xarray/#history

we should be able to modify xclim requirements to xarray >= 0.12.0

**Comment by Zeitsperre** [comment]
Done with https://github.com/Ouranosinc/xclim/commit/13ed5b35fa49e8dbd409e3c647048402831035c6
