### ISSUE TITLE
Use `units_metadata` where appropriate.

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#1822]
### Addressing a Problem?

It can sometimes be ambiguous whether a temperature represents a difference or an absolute measure.

### Potential Solution

The CF conventions have a special way to distinguish between the two : http://cfconventions.org/Data/cf-conventions/cf-conventions-1.11/cf-conventions.html#temperature-units

### Additional context

This would be complementary to #1804. That PR removed the ambiguous case that resulted in errors with pint. However, the new attribute could help in making the distinction more explicit. See discussion on the PR.

### Contribution

- [X] I would be willing/able to open a Pull Request to contribute this feature.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by huard** [comment]
One issue is that pint2cfunits returns a string, while here we'd need to return a dict with units and unis_metadata. 

One option would be to create `pint2cfattrs`, which would return a dict. This would not break anything.
