### ISSUE TITLE
Solve problem with {} tags in identifier

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#183]
### Description
In the indicator class, we use the identifier attribute as the unique identifier of a given class. Since this was also used as the output variable name for the created netCDF, we introduced formatting tags in the identifier attribute. The problem is that the same identifier is also used in other contacts (finch) to identify uniquely the process, but before the class is called, we can't format the identifier string. 

We should have two distinct attributes: the unique class identifier, and the output variable name. The identifier should not contain {}, but the output variable name could. 

More generally, we should clarify which attributes need to be clearly defined without arguments tags, and which can include tags.

**Comment by tlogan2000** [comment]
I agree 100%.. should be a relatively quick fix

**Comment by tlogan2000** [comment]
Also noticed that with the changes in https://github.com/Ouranosinc/xclim/pull/173  {thresh} in id (or proposed  variname) will now contain the string as thesholds : e.g. '30 degC' instead of the previous '30'.  Thus an index of 'txgt_30' becomes 'txgt_30 degC' or similar ...
