### ISSUE TITLE
growing season length memory use

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#184]
### Description
Calling growing season length calculation on large multiyear datasets (e.g. mf_datset of nrcan over canada) causes memory errors / accumulation.
Dask writing of chunks to netcdf (xr.to_netcdf) does not seem to work as expected and RAM use quickly accumulates and crashes... 

Running calculation on single years can alleviate the problem but still requires large amounts of memory

Unsure as to why this occurs ... Is it a dask/xarray problem or something in our xclim code

**Comment by Balinus** [comment]
Is it the only indice that behave like that on large datasets?

**Comment by tlogan2000** [comment]
so far yes.
