### ISSUE TITLE
Add Zenodo integration for library citation

### ISSUE THREAD

**Issue by Balinus** [Ouranosinc/xclim#185]
* xclim version: NA
* Python version: NA
* Operating System: NA

### Description

Integrate [Zenodo](https://zenodo.org/) API for citable library.

We are currently developing a proposal and having a simple way to cite the package would be useful before we submit it (...in the next days...)!

I'd do it myself but I do not have the permission for "third-party access" at the **Ouranos inc** org level. See [Zenodo doc](https://help.github.com/en/articles/approving-oauth-apps-for-your-organization) for details for how to allow such access to Zenodo.

**Comment by Zeitsperre** [comment]
I'm adding this to the v1.0-rc goals, but since this demands a stable/citable version, I would consider us waiting on performing this until v1.0 is finalized tagged.
