### ISSUE TITLE
Use datetime in subsetting utilities

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#189]
At the  moment the subsetting methods use start_year and end_year. Why not use a datetime instead to select a given start and end day ?

**Comment by Balinus** [comment]
Much better imo. Also, consider that someone might want to subset sub-daily datasets, hence the need for a proper datetime handling.

**Comment by sbiner** [comment]
Est-ce que le fait d'utiliser des données avec des calendrier non-standards (et donc pas des vrais datetime) ne va pas causer des problèmes?

**Comment by huard** [comment]
Bon point. Je pense que netcdftime offre un datetime pour des calendriers non-standards. Clairement, avant de faire un changement il faut tester ce genre de cas.

**Comment by Balinus** [comment]
En effet. De loin j'avais cependant l'impression que les datetime incluaient maintenant les autres calendriers?

**Comment by huard** [comment]
Exact, mais reste que si tu dis end=2000-12-31 (calendrier standard) et que tu passes ça à un array qui a calendrier de 360 jours, il faut s'assurer que ça donne la bonne affaire.

**Comment by huard** [comment]
@tlogan2000 If we want to do this we need to enforce rules on calendar changes. We want a solution where we can subset over multiples files with multiple calendars with the same arguments; I don't want to have to check the type of calendar for each run before doing a subset. One option is to have a semi-open domain `[start, end)`, where the start_date is included, but the end_date is not. So you can always specify the first day of the next year as the end_date, which will always be valid. Please advise.
