### ISSUE TITLE
threshold doesnt work

### ISSUE THREAD

**Issue by mada0007** [Ouranosinc/xclim#198]
* xclim version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

a = xclim.indices._threshold.daily_pr_intensity(AS, thresh=1,
                     freq='YS')  # set rolling window here calculate rolling decades win:59

tg = tm_mean(AS, freq="QS-DEC")
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Traceback (most recent call last):
  File "/Users/mada0007/anaconda3/envs/RAWORK/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-56-ceb5a9e08152>", line 1, in <module>
    a = xclim.indices._threshold.daily_pr_intensity(AS, thresh=1,
AttributeError: module 'xclim.indices' has no attribute '_threshold'

**Comment by Zeitsperre** [comment]
We just refactored a good chunk of the code so there might be some strangeness. Can you try dropping the `_threshold` and tell us if it works then.

**Comment by mada0007** [comment]
Works now maybe consider updating docs,

Thanks for the help

**Comment by Zeitsperre** [comment]
We're in heavy development still and are releasing a new beta in the next week so the docs and the PyPI package aren't synonymous at the moment. Glad it's working!
