### ISSUE TITLE
Heat wave frequency is taking too long?

### ISSUE THREAD

**Issue by davidcaron** [Ouranosinc/xclim#213]
* xclim version: 8438b0e5001c4014d0a318b974863e2b4dc4cc41
* Python version: 3.6 and 3.7
* Operating System: ubuntu

### Description

Trying to compute heat_wave_frequency on a small dataset (350Kb) takes 2-3 minutes. Is that normal? You can see the list of files I used attached to this message. So each paris of files takes 2-3 minutes. Processing all of them, a couple hours...

### What I Did

Here is a rough script I'm using to process this folder:

```
from pathlib import Path

import xarray as xr
from xclim.atmos import heat_wave_frequency
from time import perf_counter

path = "/d/xclim_data/heat_wave_test"
files = list(sorted(Path(path).glob("*.nc")))

mid = len(files) // 2
pairs = list(zip(files[:mid], files[mid:]))

t = perf_counter()

for n, pair in enumerate(pairs):
    tasmax = xr.open_dataset(str(pair[0])).data_vars["tasmax"]
    tasmin = xr.open_dataset(str(pair[1])).data_vars["tasmin"]
    out = heat_wave_frequency(tasmax=tasmax, tasmin=tasmin)
    out.to_netcdf(Path(path) / "test.nc")
    print(n)

print(f"{perf_counter() - t:.2f} seconds")
```

[heat_wave_test - sample.zip](https://github.com/Ouranosinc/xclim/files/3233372/heat_wave_test.-.sample.zip)

**Comment by davidcaron** [comment]
@tlogan2000 any idea?

**Comment by tlogan2000** [comment]
Not sure.  This would be called after a bccaqv2_download?  i.e. on a set of netcdf files with a single gridcell?

**Comment by tlogan2000** [comment]
can you provide the test files?

**Comment by davidcaron** [comment]
exactly

**Comment by davidcaron** [comment]
> 
> 
> can you provide the test files?

see the link at the end of the first message

**Comment by davidcaron** [comment]
Also, could you check the file `tasmax_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231_sub.nc`? 

When running `assert_daily` on it, it raises an error saying the time is not monotinocally increasing. The assert passes for all the other files...

**Comment by tlogan2000** [comment]
This is a pretty involved calculation (rolling windows, resampling etc etc ) so even with a small amount of data there are simply a lot of operations to do on the 150 year time series.
The best thing I have found to speed things up is again set a few worker processes to worker in parralel
getting processing time split between them. Also chunking the data as close to the annual resampling frequency seems like a good idea.  I seem to get processing times around 30-60 sec

``` 
client=Client(n_workers=4,threads_per_worker=4, diagnostics_port=44621)
# # client=Client(n_workers=1, diagnostics_port=8788)
client
for n, pair in enumerate(pairs):
    t = perf_counter()
    tasmax = xr.open_dataset(str(pair[0]), chunks=dict(time=366)).data_vars["tasmax"]
    tasmin = xr.open_dataset(str(pair[1]), chunks=dict(time=366)).data_vars["tasmin"]
    out = heat_wave_frequency(tasmax=tasmax, tasmin=tasmin)
    #out.values
    
    out.to_netcdf(Path(path) / "test.nc")
    print(n)

    print(f"{perf_counter() - t:.2f} seconds")

**Comment by davidcaron** [comment]
You probably considered it, but would this help? http://xarray.pydata.org/en/stable/generated/xarray.DataArray.rolling.html

**Comment by tlogan2000** [comment]
Yes this is what is used in the heat wave calculation already.   Under the hood it is used in the 'windowed_run_length' function

**Comment by tlogan2000** [comment]
> Also, could you check the file `tasmax_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231_sub.nc`?
> 
> When running `assert_daily` on it, it raises an error saying the time is not monotinocally increasing. The assert passes for all the other files...

This file has an error in the timestamp data. 2036-10-28 time step coded as 1850-01-01

I think we should probably really rewrite the original bccaqv2 file copying the time from the tasmin file which is ok.

This might work. We would need to rechunk as before etc
```
ds_tasmin = xr.open_dataset('tasmin_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231_sub.nc', decode_times=False)
ds_tasmax = xr.open_dataset('tasmax_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231_sub.nc',mask_and_scale=False, drop_variables='time')
ds_tasmax['time'] = ds_tasmin.time
ds_tasmax.to_netcdf('corrected_file.nc')

**Comment by davidcaron** [comment]
> This file has an error in the timestamp data. 2036-10-28 time step coded as 1850-01-01
> 
> I think we should probably really rewrite the original bccaqv2 file copying the time from the tasmin file which is ok.
> 
> This might work. We would need to rechunk as before etc

@tomLandry this would mean changing the source data... for a very small portion though. Are you cofortable with us doing this?

**Comment by tomLandry** [comment]
Yes, I am ok with this in the sense that it needs to be done. Problem I have really is the validity of the climate indices that are already there. Is there an impact? For the rest, correcting the source file is fine with me, and we can do it on our side. But once done, communicate new file to PCIC.

File needs to be avail both at CRIM and Ouranos, then PCIC.

**Comment by tlogan2000** [comment]
> @tomLandry this would mean changing the source data... for a very small portion though. Are you comfortable with us doing this?
> 
> This is what is breaking the heat wave calculation for the whole datasets.

without changing source data this could be a workaround by changin the tasmax time 'on the fly' in the script:
```
tasmin = xr.open_dataset(str(pair[1]), chunks=dict(time=366)).data_vars["tasmin"]
tasmax = xr.open_dataset(str(pair[0]), drop_variables='time',chunks=dict(time=366)).data_vars["tasmax"]
tasmax['time'] = tasmin.time

**Comment by tomLandry** [comment]
Code is acceptable as a short term solution, but would need to be removed after data is corrected. Less risky with code than data I think, but this would need to go away soon.

**Comment by tlogan2000** [comment]
I agree this is only a short term fix.  We could maybe contact James from PCIC and ask them for an 'official' corrected file even

**Comment by tomLandry** [comment]
Yep, always better if data is corrected at provider. But time is of the essence, so if same behavior can be made from code, it's our call.

**Comment by davidcaron** [comment]
I get segmentation faults when trying to correct the source data... So I will try later. I will do it on the fly in finch for now

``` python
import xarray as xr

chunks = {"chunksizes": [256, 16, 16]}


def main():
    time = xr.open_dataset(
        "/ccdp/BCCAQv2/tasmin_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231.nc",
        decode_times=False,
        chunks={"lon": 10}
    ).time
    ds_tasmax = xr.open_dataset(
        "/ccdp/BCCAQv2/tasmax_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231.nc",
        mask_and_scale=False,
        drop_variables="time",
        chunks={"lon": 10}
    )
    ds_tasmax["time"] = time

    # encoding = {var: chunks for var in ds_tasmax.data_vars}
    # encoding["time"] = {"dtype": "single"}

    ds_tasmax.to_netcdf(
        "tasmax_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231.nc",
        # encoding=encoding,
    )

if __name__ == "__main__":
    main()
```

**Comment by dbyrns** [comment]
I would say that if the data provider (PCIC) can apply the fix to their files, send us the exact procedure so we can apply it here and then run a md5 checksum, that would be as if we got the official fixed dataset.

**Comment by tomLandry** [comment]
Ok, I contacted James by email on this issue. Stand by.

**Comment by jameshiebert** [comment]
Hey all,

I don't see any problem with the referenced data file on our end. Maybe you had a file corruption on your end?

Here's how to test for monotonically increasing time. So I start by opening the file, reading out the time values, and computing the difference between each step.

```python
(env) hiebert@lynx:/local_temp/hiebert$ ipython
Python 3.6.8 (default, Apr 25 2019, 21:02:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import netCDF4                                                                                                                       

In [2]: import numpy                                                                                                                         

In [3]: nc = netCDF4.Dataset('/storage/data/climate/downscale/BCCAQ2/bccaqv2_with_metadata/tasmin_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historic
   ...: al+rcp85_r1i1p1_19500101-21001231.nc')                                                                                               

In [4]: t = nc['time'][:]                                                                                                                    

In [5]: dt = numpy.diff(t)                                              
```

Next, we can easily test to see if the values are monotonically increasing. They are.

**Comment by jameshiebert** [comment]
Not sure how you're subsetting the data, but from our end, the source data is A-OK.

**Comment by davidcaron** [comment]
Thanks for the confirmation, so we need to see why the subsetting is creating this error...

**Comment by davidcaron** [comment]
oh, I see you use the file 
`tasmin_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231.nc`

I ran the same commands as yours with `tasmax`, here is the output:

``` bash
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import netCDF4
>>> import numpy
>>> nc = netCDF4.Dataset("/ccdp/BCCAQv2/tasmax_day_BCCAQv2+ANUSPLIN300_CESM1-CAM5_historical+rcp85_r1i1p1_19500101-21001231.nc")
>>> t = nc['time'][:]
>>> dt = numpy.diff(t)
>>> numpy.all(dt > 0)
False
```

**Comment by davidcaron** [comment]
``` bash
>>> netCDF4.num2date(nc['time'][31680:31700], nc['time'].units, nc['time'].calendar)
array([cftime.DatetimeNoLeap(2036, 10, 18, 12, 0, 0, 0, 2, 291),
       cftime.DatetimeNoLeap(2036, 10, 19, 12, 0, 0, 0, 3, 292),
       cftime.DatetimeNoLeap(2036, 10, 20, 12, 0, 0, 0, 4, 293),
       cftime.DatetimeNoLeap(2036, 10, 21, 12, 0, 0, 0, 5, 294),
       cftime.DatetimeNoLeap(2036, 10, 22, 12, 0, 0, 0, 6, 295),
       cftime.DatetimeNoLeap(2036, 10, 23, 12, 0, 0, 0, 0, 296),
       cftime.DatetimeNoLeap(2036, 10, 24, 12, 0, 0, 0, 1, 297),
       cftime.DatetimeNoLeap(2036, 10, 25, 12, 0, 0, 0, 2, 298),
       cftime.DatetimeNoLeap(2036, 10, 26, 12, 0, 0, 0, 3, 299),
       cftime.DatetimeNoLeap(2036, 10, 27, 12, 0, 0, 0, 4, 300),
       cftime.DatetimeNoLeap(1850, 1, 1, 0, 0, 0, 0, 2, 1),
       cftime.DatetimeNoLeap(2036, 10, 29, 12, 0, 0, 0, 6, 302),
       cftime.DatetimeNoLeap(2036, 10, 30, 12, 0, 0, 0, 0, 303),
       cftime.DatetimeNoLeap(2036, 10, 31, 12, 0, 0, 0, 1, 304),
       cftime.DatetimeNoLeap(2036, 11, 1, 12, 0, 0, 0, 2, 305),
       cftime.DatetimeNoLeap(2036, 11, 2, 12, 0, 0, 0, 3, 306),
       cftime.DatetimeNoLeap(2036, 11, 3, 12, 0, 0, 0, 4, 307),
       cftime.DatetimeNoLeap(2036, 11, 4, 12, 0, 0, 0, 5, 308),
       cftime.DatetimeNoLeap(2036, 11, 5, 12, 0, 0, 0, 6, 309),
       cftime.DatetimeNoLeap(2036, 11, 6, 12, 0, 0, 0, 0, 310)],
      dtype=object)
```

**Comment by jameshiebert** [comment]
Ah good catch. You're right I see that on our side as well.

I don't see a problem with us independently updating that single timestep in the metadata and comparing md5sums.

**Comment by davidcaron** [comment]
@tlogan2000 If you had time to into this today, that would be great. I think I found a faster way.

Here are the results, the first one is using the current function in xclim, and the second one my function.
[subset_tasmax_montreal_heat_wave - xclim.zip](https://github.com/Ouranosinc/xclim/files/3241375/subset_tasmax_montreal_heat_wave.-.xclim.zip)
[subset_tasmax_montreal_heat_wave - faster.zip](https://github.com/Ouranosinc/xclim/files/3241376/subset_tasmax_montreal_heat_wave.-.faster.zip)

Running this for all the datasets, it finishes in 7-8 minutes vs almost 2 hours using the current method.

Here is my code. Basically, I replaced the `xclim.run_length.windowed_run_events` function with `rolling_window_events`. So the metadata will be exactly the same. You can also see the function I used to compare the results.

``` python
import warnings
from pathlib import Path
from time import perf_counter

import xarray as xr
import numpy as np
from xclim.atmos import heat_wave_frequency
import xclim.run_length


def rolling_window_events(da, window, dim="time"):
    window_count = da.rolling(time=window).sum()
    w = window_count.values[window - 1 :] >= window

    count = np.count_nonzero(w[1:] > w[:-1]) + w[0]

    data = np.array([count], dtype=np.int64)
    data = data.reshape(())
    out = xr.DataArray(data, coords={"lon": da.lon, "lat": da.lat})

    return out


def compute_heat_wave(output_path, tasmax_file, tasmin_file):
    t = perf_counter()

    tasmax = xr.open_dataset(str(tasmax_file)).data_vars["tasmax"]
    tasmin = xr.open_dataset(str(tasmin_file)).data_vars["tasmin"]
    thresh_tasmax = "30 degC"
    thresh_tasmin = "20 degC"
    out = heat_wave_frequency(
        tasmax=tasmax,
        tasmin=tasmin,
        thresh_tasmax=thresh_tasmax,
        thresh_tasmin=thresh_tasmin,
        window=2,
        freq="MS",
    )
    output_name = output_path / tasmin_file.stem.replace(
        "tasmin", "heat_wave_frequency"
    )
    out.to_netcdf(str(output_name) + ".nc")

    print(f"{perf_counter() - t:.2f} seconds")


def compare_data():
    heat_wave_faster = "/d/xclim_data/subset_tasmax_montreal_heat_wave - faster"
    heat_wave_xclim = "/d/xclim_data/subset_tasmax_montreal_heat_wave - xclim"

    hw_faster_files = list(sorted(Path(heat_wave_faster).glob("*.nc")))
    hw_xclim_files = list(sorted(Path(heat_wave_xclim).glob("*.nc")))

    for f1, f2 in zip(hw_xclim_files, hw_faster_files):
        ds1 = xr.open_dataset(f1)
        ds2 = xr.open_dataset(f2)
        np.allclose(ds1.heat_wave_frequency.values, ds2.heat_wave_frequency.values)


def main():
    # monkeypatch windowed_run_events with a faster version
    xclim.run_length.windowed_run_events = rolling_window_events

    tasmin_files = list(
        sorted(Path("/d/xclim_data/subset_tasmin_montreal").glob("*.nc"))
    )
    tasmax_files = list(
        sorted(Path("/d/xclim_data/subset_tasmax_montreal").glob("*.nc"))
    )

    output_path = Path("/d/xclim_data/subset_tasmax_montreal_heat_wave")
    output_path.mkdir(exist_ok=True)

    t = perf_counter()

    for tasmin_file, tasmax_file in zip(tasmin_files, tasmax_files):
        compute_heat_wave(output_path, tasmax_file, tasmin_file)

    print(f"{perf_counter() - t:.2f} seconds")


if __name__ == "__main__":
    warnings.filterwarnings("ignore", category=FutureWarning)
    warnings.filterwarnings("ignore", category=UserWarning)
    main()

```

**Comment by tlogan2000** [comment]
I'll try to take a look at it this morning.

**Comment by huard** [comment]
Does chunking along time interrupt rolling operations ? Probably inconsequential here because heat waves do not occur in December-January.

**Comment by davidcaron** [comment]
Good question, but I think this wouldn't affect us in finch, because we are using the subsetted files, which are not chunked.

I know this would need more verification before being integrated in xclim itself, but I think It works as it should for our current requirements in finch.

**Comment by tlogan2000** [comment]
I think this is possibly related to the fact that  rle and window_run_length etc were altered/optimized to work on n-dimensional grids of data.  This required a fair bit of work and could still be improved but they were considerably faster than our original 1d versions (still in run_length.py but not used)

For example calculating run length on a large grid over all of Canada was considerably faster : https://github.com/Ouranosinc/xclim/pull/139

@davidcaron fix here would probably only work for single gridpoint data?

**Comment by davidcaron** [comment]
Yes, not tested on nD arrays, only 1D. 

It may not be a good candidate for nD arrays, but... I think it would be worth investigating. I could do it when we get to processing bounding boxes in finch. And add testing for edge cases if there aren't already.

**Comment by tlogan2000** [comment]
The heat wave calculation for the 

> Probably inconsequential here because heat waves do not occur in December-January.

Note the heat wave calculations for the portal was done only for the annual frequency : 'YS'

**Comment by davidcaron** [comment]
> Note the heat wave calculations for the portal was done only for the annual frequency : 'YS'

Hum... for the `BCCAQv2_heat_wave_frequency_gridpoint` job, it's currently hard-coded as 'MS' in the frontend, should that be changed?

**Comment by tlogan2000** [comment]
The more I think about it. There's probably a sweet spot that could be found based on grid size between the old version 1d version of run_length (that used an 'apply_ufunc()' call) and the newer 'nDim' code.   If we dig deeper we could potentially have the code use one vs the other base on input data grid shape?

**Comment by tlogan2000** [comment]
> > Note the heat wave calculations for the portal was done only for the annual frequency : 'YS'
> 
> Hum... for the `BCCAQv2_heat_wave_frequency_gridpoint` job, it's currently hard-coded as 'MS' in the frontend, should that be changed?

Yes

**Comment by davidcaron** [comment]
Also here are the subsetted files I used to check the results. You need to remove the `.gif` extension, github doesn't allow 7-zip files.

![subset_tasmax_montreal 7z](https://user-images.githubusercontent.com/16667564/58711871-6040d600-838d-11e9-883c-b82a22aae497.gif)
![subset_tasmin_montreal 7z](https://user-images.githubusercontent.com/16667564/58711872-6040d600-838d-11e9-8c20-17ca5bc1c775.gif)

**Comment by tlogan2000** [comment]
In the actual xclim heat wave code we could simply add something like this. 
Further tests could determine what value of npoints gives us the best performance in all cases

```
npoints = 1
if len(tasmin.lon) * len(tasmin.lat) <= npoints:
    return group.apply(rl.windowed_run_events_ufunc, window=window)
else:
    return group.apply(rl.windowed_run_events, window=window, dim='time')

**Comment by tlogan2000** [comment]
I realize time is critical. 
Is it too much time to redeploy an instance of finch etc etc with this small adjustment to the actual code

**Comment by tomLandry** [comment]
We have no problem redeploying Finch several times in the next few days. Including today.

**Comment by davidcaron** [comment]
No need to update xclim before the launch, I can patch it on the fly directly within the finch process.

**Comment by tlogan2000** [comment]
ok good.

**Comment by davidcaron** [comment]
I patch it exactly like in the example code above. In fact, it's already deployed 😀

**Comment by tlogan2000** [comment]
> I patch it exactly like in the example code above. In fact, it's already deployed

Everything is working? performance is better? Results are the same? I did a quick check and it should work fine but wasn't overly careful... was kind thinking out loud

**Comment by davidcaron** [comment]
Yes, it's working. Heat wave frequency process went from 3h15 to 50 minutes (40 minutes subsetting, 10 minutes to compute). The results are exactly like in the files I provided.

**Comment by tlogan2000** [comment]
@huard I'm going to open a new issue on this for xclim.  I think now we should think of fixing directly in run_length.py in order accommodate all indices that could possibly be affected by this.

**Comment by davidcaron** [comment]
By the way, I'd be ok if you closed this in favor of #217. I might revisit this and try to lend a hand when we get to computations involving bounding boxes and polygons in finch.

**Comment by tlogan2000** [comment]
closing - discussion redirected to #217

**Comment by tomLandry** [comment]
Hey guys, bounding boxes and polygons are most absolutely coming our way next. Very short-term though, I think we should aim to have grid-cell perfectly under control and mastered. For instance, I'm thinking about caching subsets for highly populated areas. Anyway we need "user feedback" to support larger subsets in the UI.
