### ISSUE TITLE
Extra netCDF variable attributes in output

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#227]
The created netCDF outputs have attributes that were not meant to be in the netCDF file: 
`'identifier', 'var_name', 'abstract', 'keywords', 'parameters', 'notes'`
These are used by the WPS process generator, but should not be stored in the netCDF output. I propose to remove them.

**Comment by huard** [comment]
@tlogan2000 
Would those values be used by Habitat7 in the frontend ?

**Comment by tlogan2000** [comment]
I don't think so .  I think the history attr contains most of what is needed?

**Comment by tlogan2000** [comment]
The ```description``` field is probably the most useful for plain language understanding

**Comment by huard** [comment]
Description is still outputed.
