### ISSUE TITLE
max_nday_precipitation_amount is not in the same file as max_1day...

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#244]
I'm struggling a bit to find where are the functions. The percentile based thresholds are not in thresholds, but in multivariate. I understand the logic, but it's not intuitive. Frankly, I liked it better when all the indices were in the same big hunking file.

**Comment by huard** [comment]
Also, I think we could merge these two functions into one.

**Comment by Zeitsperre** [comment]
In terms of restructuring, since the true locations of the functions are hidden from the user, we can rearrange them as we see fit without breaking the API. If it makes more sense to have them separated by variable (`_precipitation.py, a larger `_temperature.py`, etc.), we can implement that.

**Comment by huard** [comment]
@Zeitsperre Could you move function "max_n_day..." to `_simple.py` ? That will do for now.
