### ISSUE TITLE
Stabilizing the API

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#257]
I was watching a really great talk by a MongoDB developer on how to warn of deprecations in APIs. The talk is on [youtube](https://www.youtube.com/watch?v=dqDnB6jKzcE) but his guide is available here: https://emptysqua.re/blog/api-evolution-the-right-way/.

Among the things he mentioned is how best to use libraries like `warnings` with stack-levels, and using the `*` in function call signatures to demand users use keywords, rather than order to launch processes. Is this something that we might want to consider integrating by v1.0?

**Comment by huard** [comment]
Sounds reasonable.

**Comment by Zeitsperre** [comment]
Let's discuss this in the meeting.

**Comment by Zeitsperre** [comment]
The API has been stable (no major breaking changes) for at least 6 months now. I think it's safe to close this issue.
