### ISSUE TITLE
Rename test function

### ISSUE THREAD

**Issue by Balinus** [Ouranosinc/xclim#26]
Should be named `test_fit` ? And in folder tests.
https://github.com/Ouranosinc/xclim/blob/8078cb5ac5d331361f6ff5255e1f88f6750bbb41/xclim/stats.py#L46

**Comment by huard** [comment]
Yep, but it's still very much experimental (it works, but needs polishing).

**Comment by Balinus** [comment]
I know, it's just so that we don't forget. Was browsing the code!

**Comment by Zeitsperre** [comment]
Added a note to address this in the future with b3d2debabff51ad5d4844295e28228b85d57e330
