### ISSUE TITLE
Configure the Windows build in Travis CI

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#269]
Some preliminary research has suggested that the `language` options supported by Windows Travis CI environments is quite limited and (in many cases) a misconfigured language will result in a build environment that can't even boot up.

Seeing as the Windows build is hanging, I suspect the problem is a matter of setting the language to `generic`, `shell`, or `bash`. All other configurations in the windows yaml recipe should be consistent with a sane python environment.

**Comment by Balinus** [comment]
Appveyor is full-featured for Windows build. Had great success with it in the past.

https://www.appveyor.com/docs/lang/python/
