### ISSUE TITLE
Fix deprecations in xarray

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#270]
### Description

xarray 0.13 will deprecate a couple of usages we rely on. I suggest we list those and fix them in advance of the 0.13 release.

**Comment by Zeitsperre** [comment]
@Ouranosinc/hailstorm Looks like [xarray 0.13](https://pypi.org/project/xarray/)came out yesterday and a lot of usages are now broken. I can pin the requirements in a hotfix and push that to PyPI, but all new installations will now fail the `test_subset.py` test ensemble.

**Comment by huard** [comment]
I can spare an hour today on this.

**Comment by tlogan2000** [comment]
Ok we should definitely push this up on the todo list

**Comment by huard** [comment]
Almost done.
@Zeitsperre I'm hitting a snag. black and autopep8 are in conflict, so there is no way to commit my changes...

**Comment by tlogan2000** [comment]
@huard are you fixing FutureWarnings only... there are also test failing with xr v.0.13   I 've gone the route of upgrading xarray and am working through things that are completely broken

**Comment by huard** [comment]
No, fixing broken subset stuff as well.

**Comment by tlogan2000** [comment]
sounds good I will wait for your commits.. was just getting started

**Comment by huard** [comment]
Check the PR I just made. WIP, I'll let you continue, I need to work on another project. 
used `git ci -n` to skip the pre-commit hooks.

**Comment by tlogan2000** [comment]
10-4 merci

**Comment by huard** [comment]
@tlogan2000 I've added support for lat_bnds=[None, float] but it's untested... 

Also need to add a test for curvilinear grids when one of lat_bnds or lon_bnds is None.

**Comment by Zeitsperre** [comment]
@huard just saw this. In the future, suppress running hooks with `git commit --no-verify`.

**Comment by tlogan2000** [comment]
closed with #274
