### ISSUE TITLE
Reduce conda/pip package size

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#279]
### Description

The xclim conda package is 31 MB. That's bigger than scipy. We need to bring this down. I assume it's the test data.

**Comment by Zeitsperre** [comment]
I see us as having two options:
- We need to chop down the test file sizes and rewrite/optimize the tests we have currently.
- We opt not to include the testdata in the PyPI and Conda packages and create a pytest rule to skip tests if we don't have the source files (ie: only those files installed via pip/conda)

Given that the builds are performed on a small but representable variety of Python builds, I feel like the second option is preferable. It would also be much less work.

**Comment by Zeitsperre** [comment]
After chatting with @tlogan2000, I also came up with the idea to not include the `tests` folder in the manifest file. Since the build are checked against a clone of the master branch, the tests data does not need to be formally installed. Once tests pass on Travis CI, we can assume that the package is working and then deploy that build to PyPI and conda-forge. This is probably the easiest option and will reduce the size the most.

**Comment by Zeitsperre** [comment]
@huard I can work on this tomorrow while out of the office. Just wondering which option you are leaning towards. I'm tempted to move forward with option two, to drop all tests requiring `testdata` and skip tests reliant on that. That way, we can maintain some test ensemble for very light testing from a pip installation.

**Comment by kinow** [comment]
> That way, we can maintain some test ensemble for very light testing from a pip installation.

I think `xclim` has both wheel and source files in PYPI. Installing with `pip install xclim` should follow [pip's default approach](https://packaging.python.org/tutorials/installing-packages/#source-distributions-vs-wheels) when both files are available:

>pip can install from either Source Distributions (sdist) or Wheels, but if both are present on PyPI, pip will prefer a compatible wheel.

Wheels installations avoid running code, instead simply [unpacking and moving files around](https://www.python.org/dev/peps/pep-0427/#installing-a-wheel-distribution-1-0-py32-none-any-whl) during the installation.

So the tests and test data will not be used by users installing via `pip install xclim`, unless the wheels file is not uploaded, or if installed manually via sdist.
