### ISSUE TITLE
test against xarray master

### ISSUE THREAD

**Issue by dcherian** [Ouranosinc/xclim#281]
It would be mutually beneficial for `xclim` to test against xarray master, I think. This would help with things like #270, #280 and https://github.com/pydata/xarray/issues/3402. 

What do you think?

**Comment by Zeitsperre** [comment]
Definitely. This would solve a lot of problems (or at least let us know further in advance what might be coming).

**Comment by huard** [comment]
@Zeitsperre Would it be possible to keep our current test suite as is (for our docker/conda releases where we can freeze dependencies), and add a "bleeding edge" case that would pull the  xarray master ? A failure on the bleeding edge branch would not block our own releases, but would help us diagnose upcoming issues and provide feedback to xarray devs.

**Comment by Zeitsperre** [comment]
That's pretty much what I had in mind. I was going to set a new the tox environment that reinstalls xarray with the master branch.

**Comment by dcherian** [comment]
This sounds great. Thanks guys. And also thank you for reporting issues and contributing pull requests upstream

**Comment by tlogan2000** [comment]
I agree to all of this ... we'll stay ahead of the curve and help xr devs catch some bugs earlier at the same time,

**Comment by Zeitsperre** [comment]
I can get to this this afternoon. Thanks again for the suggestion @dcherian !
