### ISSUE TITLE
subset_bbox adds dimensions and removes chunks on data_vars such as "rotated_pole"

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xclim#286]
* xclim version: 0.11.0-beta
* Python version: 3.6
* Operating System: Unix

### Description
Opening multiple netCDF files (each netCDF's dimension = 8760, 130, 155). In this case, the files were NA-CORDEX hourly precipitation : pr_NAM-44_ICHEC-EC-EARTH_historical_r3i1p1_DMI-HIRHAM5_v1_1hr_(years).nc

**ds = xr.open_mfdataset(sub_files, drop_variables=["time_vectors", "ts", "time_bnds"])**
ds:
Dimensions:       (rlat: 130, rlon: 155, time: 245424)
Coordinates:
    lon           (rlat, rlon) float64 dask.array<chunksize=(130, 155), meta=np.ndarray>
    lat           (rlat, rlon) float64 dask.array<chunksize=(130, 155), meta=np.ndarray>
  * rlat          (rlat) float64 -28.4 -27.96 -27.52 ... 27.48 27.92 28.36
  * rlon          (rlon) float64 -33.88 -33.44 -33.0 -32.56 ... 33.0 33.44 33.88
  * time          (time) datetime64[ns] 1981-01-01T00:30:00 ... 2043-12-31T23:30:00
Data variables:
    rotated_pole  (time) |S1 b'R' b'R' b'R' b'R' b'R' ... b'R' b'R' b'R' b'R'
    pr            (time, rlat, rlon) float32 dask.array<chunksize=(8760, 130, 155), meta=np.ndarray>

**ds_subset = subset.subset_bbox(ds, lat_bnds=lat_bnds, lon_bnds=lon_bnds,
                                           start_date=str(np.min(years)), end_date=str(np.max(years)))**
ds_subset:
Dimensions:       (rlat: 49, rlon: 44, time: 245424)
Coordinates:
    lon           (rlat, rlon) float64 -84.98 -84.36 -83.74 ... -43.53 -42.93
    lat           (rlat, rlon) float64 45.73 45.66 45.59 ... 58.39 58.13 57.87
  * rlat          (rlat) float64 -1.12 -0.68 -0.24 0.2 ... 19.12 19.56 20.0
  * rlon          (rlon) float64 8.36 8.8 9.24 9.68 ... 25.96 26.4 26.84 27.28
  * time          (time) datetime64[ns] 1981-01-01T00:30:00 ... 2043-12-31T23:30:00
Data variables:
    rotated_pole  (time, rlat, rlon) object dask.array<chunksize=(245424, 49, 44), meta=np.ndarray>
    pr            (time, rlat, rlon) float32 dask.array<chunksize=(8760, 49, 44), meta=np.ndarray>

Notice how "rlat, "rlon" was added to rotated_pole's dimensions. The chunk size is also non-existent for the new rotated_pole, which means that my workers get overloaded with memory errors when I try to save this new dataset to a NetCDF.

**Comment by RondeauG** [comment]
I've used this code after subset_bbox. It seems to circumvent the multiple errors I had in dask :

if "grid_mapping" in ds_subset[variable].attrs.keys():
        gmap = ds_subset[variable].attrs["grid_mapping"]
        new_gmap = xr.DataArray()
        new_gmap.attrs = ds_subset_tmp[gmap].attrs
        new_gmap.name = gmap  # many bugs if a name is not attributed to the DataArray
        ds_subset[gmap] = new_gmap  # only the attributes matter for the grid_mapping

**Comment by tlogan2000** [comment]
This seems to be occurring in the masking ```da.where()``` call (line 246) of subset.py when subsetting a xr.DataSet (versus xr.DataArray) that has additional data_vars without rlon, rlat dimensions ...  an ```iisinstance(da,xarray.Dataset)``` check followed by a masking of individual data_vars while ensuring presence of rlon, rlat dims would probably work

**Comment by tlogan2000** [comment]
@RondeauG while awaiting  pull request #287 youcould also use subset_bbox on individual variables in the dataset...  something like this would probably work
```
ds = xr.open_mfdataset(sub_files, drop_variables=["time_vectors", "ts", "time_bnds"])

ds['pr'] = subset.subset_bbox(ds.pr,   lat_bnds=lat_bnds, lon_bnds=lon_bnds,
start_date=str(np.min(years)), end_date=str(np.max(years)))

```

**Comment by tlogan2000** [comment]
closing via #287
