### ISSUE TITLE
TestMissingAnyFills::TestMonth random failures

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#298]
### Description

TestMissingAnyFills::test_month tends to fail intermittently, particularly on the macOS Python3.7 build but also on Linux and Windows at a lesser frequency. Caution suggests that if this specific case is failing sometimes, there must either be a bug within xclim or xarray or there is some RNG-dependent call or test setup that we've coded that has some failing edge cases.

I'm not sure what the urgency of this bug is but it's been plaguing TravisCI builds for several months so I'm opening an issue to at least have this on the board. Here's the stack:
```
________________________ TestMissingAnyFills.test_month ________________________
self = <test_checks.TestMissingAnyFills object at 0x11b253150>
tasmin_series = <function tasmin_series.<locals>._tasmin_series at 0x11a409f80>

    def test_month(self, tasmin_series):
        ts = tasmin_series(np.zeros(36))
        miss = checks.missing_any(ts, freq="YS", month=7)
        np.testing.assert_equal(miss, [False])
    
        miss = checks.missing_any(ts, freq="YS", month=8)
        np.testing.assert_equal(miss, [True])
    
        with pytest.raises(ValueError, match=r"No data for selected period."):
            miss = checks.missing_any(ts, freq="YS", month=1)
    
        miss = checks.missing_any(ts, freq="YS", month=[7, 8])
        np.testing.assert_equal(miss, [True])

        ts = tasmin_series(np.zeros(76))
        miss = checks.missing_any(ts, freq="YS", month=[7, 8])
>       np.testing.assert_equal(miss, [False])

E       AssertionError: 
E       Items are not equal:
E        ACTUAL: <xarray.DataArray (time: 1)>
E       array([ True])
E       Coordinates:
E         * time     (time) datetime64[ns] 2000-01-01
E        DESIRED: [False]
```

**Comment by aulemahal** [comment]
Hypothesis
On line 206-8 of `checks.py::missing_any()`, we do:
```
sda = xr.DataArray(data=np.empty(len(t)), coords={"time": t}, dims=("time",))
st = generic.select_time(sda, **indexer)
sn = st.notnull().resample(time=freq).sum(dim="time")
```
AFAIK, `np.empty` creates an empty array, without initializing its values, so you get what was in the memory before the initialization. There is a non-null chance that a NaN was there. Thus, both in `generic.select_time` and `st.notnull()`, this value is dropped and the test fails.

Whatcha think? 

I have tried the current tests many time on two different computers and never had a fail, so testing this is difficult...

**Comment by huard** [comment]
I think that's a very real possibility. Good thinking. I suggest replacing by something like: 
```
sda = xr.DataArray(data=np.ones(len(t), dtype=bool), coords={"time": t}, dims=("time",))
st = generic.select_time(sda, **indexer)
sn = st.resample(time=freq).sum(dim="time")
```
