### ISSUE TITLE
Benchmark Processing Libraries for Comparisons

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#3]
Libraries we've identified as being useful for grid manipulation:

- [x] [`xarray`](http://xarray.pydata.org/en/stable/) + [`dask`](https://dask.pydata.org/en/latest/)

- [ ] [`numpy`/`scipy`](https://docs.scipy.org/doc/) + [`netcdf4-python`](https://unidata.github.io/netcdf4-python/) 

- [ ] [`numpy`/`scipy`](https://docs.scipy.org/doc/) + [`numba`](https://numba.pydata.org/numba-doc/latest/index.html)

- [ ] [`ICCLIM`](https://icclim.readthedocs.io/en/latest/)

- [ ] [`OCGIS`](https://ocgis.readthedocs.io/en/latest/)

Feel free to edit this post to add or remove what we are certain to look/not look into.

Benchmarking libraries (see https://perf.readthedocs.io/en/latest/)

- performance: the Python benchmark suite which uses perf
- Airspeed Velocity: A simple Python benchmarking tool with web-based reporting
- pytest-benchmark
- boltons.statsutils

**Comment by huard** [comment]
I guess my point was rather to test our xarray/dask implementation against ICCLIM to see if we have a meaningful speedup. Otherwise it may not be worth recoding everything.

**Comment by tlogan2000** [comment]
I had never heard of numba - seems interesting as well.  

I think a few tests in the next week(?) or so would be good in order to quickly narrow in on possibilities. We don't have unlimited time to play around unfortunately.  I will probably be able to do something next week on this (at least to begin looking at ICCLIM vs xclim for indices that David has already coded)

**Comment by Balinus** [comment]
ICCLIM seems to be coded in C. So, unless we compile (JIT or static) the code I'm not sure we'll get a lot of speedup in single-threaded applications.

The advantage of dask is the easy multi-threading of calculations. Hece, Dask could probably be used in conjunction with ICCLIM, resulting in multi-threaded calculations of compiled indices. Or am I missing something?

**Comment by tlogan2000** [comment]
I think the point is that ICCLIM isn't particularly intuitive. We were thinking of rewriting priority indices using xarray (Dask is already included in xarray) to create our xclim package (note- name keeps changing..... ;)  
Anyways, David has already coded a bunch of ICCLIM indicators using xarray. so the first step would be to make sure we are actually doing better than the original ICCLIM package in terms of performance.

**Comment by huard** [comment]
Our assessment is that it's going to be more effective to rewrite the ICCLIM indices using xarray than trying to build dask into ICCLIM. We're also counting on ocgis to take care of the metadata handling.

**Comment by sbiner** [comment]
made a quick test regarding speed/memory for different options of reading netCDF files with xarray. Not sure it's the right way to document this but for now I did put it [here](https://github.com/Ouranosinc/xclim/wiki/Development-Notes)

**Comment by sbiner** [comment]
More like no speed gain and only more memory need using the xarray.concat trail.

**Comment by Balinus** [comment]
Here's some preliminary remarks about benchmarking:

1. Functions should have unit tests (i.e. no need to benchmark untested functions)
2. The benchmarking framework will use `timeit`. There seem to be enough options for thorough benchmarking with it.

if you know other benchmarking frameworks, let me know!

**Comment by Balinus** [comment]
Does anyone had success in running icclim?

**Comment by Balinus** [comment]
Ok. ICCLIM works with Python 2.7. First results are good! For a simple calculation of mean value of daily temperature xclim is **2x faster** than ICCLIM.

**Comment by Balinus** [comment]
@huard J'aurais besoin d'un dépôt sur Ouranosinc. J'irais avec "xclim-benchmark" ?

Je n'ai pas les persmissions requises.
Merci!

**Comment by Zeitsperre** [comment]
@Balinus Done.

**Comment by huard** [comment]
For benchmarking libraries, see the issue description at the top ; )

**Comment by huard** [comment]
Why another repo for benchmarking ? I

**Comment by Balinus** [comment]
My take was that it's easier to do it from an external point (importing perf, icclim, etc.). But I guess I can pack everything in a subfolder with all the benchmark files and their outputs. I just thought it wasn't a priority to have it inside the package from an end-user perspective.

**Comment by Balinus** [comment]
I'm working on the other repo right now. I can push here is that's the final consensus, just let me know what you prefer.
