### ISSUE TITLE
Indices default freq set to None

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#300]
The latest xclim version sets a number of `freq` to None instead of "YS". The result is that freq is not set, it fails. The tests don't seem to catch that, which implies they all set freq to something.

**Comment by Zeitsperre** [comment]
I was under the impression from the docstrings that this field was optional. I can fix this fairly quickly.

**Comment by tlogan2000** [comment]
Yep. Default is 'YS' at least for indices module not sure about streamflow

**Comment by huard** [comment]
It's optional, but the default **has** to be among the values accepted by resample.
