### ISSUE TITLE
Extend the xarray/xclim object class to accept "groupby()" method

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#31]
Building on the non-standard calendar issue raised in #30, it would be good to see if there are ways of extending the DataArray class to allow us to perform resampling via class methods.

Since this DataArray class is built from xarray and pandas, it might be worthwhile to build out the existing class to include `groupby()` and potentially other methods. I'll be starting a new branch called `class_extension` to look into ways of adding these methods. Help appreciated.

**Comment by huard** [comment]
I dont understand. Dataarray supports groupby already.

**Comment by Zeitsperre** [comment]
I realized this after I opened this. I'm going to wait on Seb's fixes to see if he can find a better way to handle the non-standard calendars. False alarm!
