### ISSUE TITLE
xclim pins xarray version

### ISSUE THREAD

**Issue by mathause** [Ouranosinc/xclim#313]
* xclim version: 0.12.2
* Python version: 3.7
* Operating System: Linux

### Description

xclim pins xarray to 0.13. Currently xarray is at version 0.14.1 - it would be nice if we could use xclim with newer xarray versions.

``` bash

> conda search --info xclim

...
xclim 0.12.2 py_1
-----------------
...
  - xarray 0.13.0
```

**Comment by tlogan2000** [comment]
Yes, this should only be temporary.  Recent xarray update to v0.14 is breaking certain xclim functionalities (mainly connected to a nerwer version of cftime).  So we have pinned to 0.13 for now.  Work is in progress in order to unpin  ...

**Comment by Zeitsperre** [comment]
@mathause From what i can tell, the issue has to do with the newest `cftime` being incompatible with `xarray` 0.14. In the newest `xarray`, `cftime` below v1.0.4 is no longer compatible so our hands are tied at the moment. A new cftime release is needed before we can update the dependencies.

See #309 for the work being done on this issue.

**Comment by mathause** [comment]
Thanks. IIRC `xarray` 14.1 is compatible with `cftime` 1.0.4.2 - so I think it should be possible. However, you can probably not support `xarray` 0.13 AND `xarray` 0.14.1. I guess you'd need the following requirements

```
- xarray >= 0.14.1
- cftime >= 1.0.4.2
```

Which is incompatible with the current requirements
```
- cftime >=1.0.3.4,<1.0.4
- xarray 0.13.0
```

**Comment by huard** [comment]
@Zeitsperre I suggest we update those deps with the next release. I think we can assume xclim users are "bleeding-edge" power users, so there are more benefits to following xarray closely than ensuring stability until we reach 1.0 status.

**Comment by tlogan2000** [comment]
FYI,   I just ran the xclim test suite locally using xarray 0.14.1 and cftime 1.0.4.2  without any problems ... Can do a quick PR to make sure it builds on Travis_CI but I think it the issues have more or less solved itself with the latest updates to xarray and cftime

**Comment by mathause** [comment]
Any news on this?

Related: does pyproj really need to be pinned? I only see it used here:

https://github.com/Ouranosinc/xclim/blob/efc530c52cd563b27f61c3bfb022e64505169dcc/xclim/subset.py#L1036

Unpinning would just make solving environments much easier... I am currently testing xclim installed with `pip -no-deps xclim`

**Comment by tlogan2000** [comment]
@mathause This PR https://github.com/Ouranosinc/xclim/pull/309 should take care of it ... @Zeitsperre can you confirm  / give a timeline for this?    I know you were away this week ..

**Comment by tlogan2000** [comment]
> Related: does pyproj really need to be pinned? I only see it used here:

Not sure about pyproj though..  @Zeitsperre do you know why we pin this package?

**Comment by Zeitsperre** [comment]
We can unpin it. It was pinned due to some strange issues I was having when installing it at the time. Those are dealt with now.

**Comment by huard** [comment]
Working on it, also trying to fix the docs.

**Comment by Zeitsperre** [comment]
@huard see #326

**Comment by huard** [comment]
#326 mixes a lot of things. Unclear what am I supposed to do with this.

**Comment by mathause** [comment]
Thanks! Currently calculating `CDD` - glad I don't have to implement this myself.
