### ISSUE TITLE
Sea ice extent indicator

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#314]
### Description

In DACCS we planned a couple of sea-ice indicators. We could have: 
- Arctic/Antarctic sea ice area
- Arctic/Antarctic sea ice extent  
- Sea ice fluxes

**Comment by tlogan2000** [comment]
In cases of area we may want to see if we can implement a gridcell-area utility calculation in order to be able to properly average areas via a weighted mean

**Comment by mathause** [comment]
xref: pydata/xarray/pull/2922

**Comment by tlogan2000** [comment]
@mathause This looks great.  

Do know of a method for calculating grid-cell weight values that would be used? E.g. similar to CDO Grid area weights https://code.mpimet.mpg.de/projects/cdo/embedded/index.html#x1-140001.3.1

**Comment by mathause** [comment]
I often use `cos(lat)` which is simple and precise enough (for me).

**Comment by cothel** [comment]
cos(lat) is a bit dangerous since some global datasets do not use the same spacing for latitudes and longitudes. Map projections are getting more "exotic" so grid cell-area need to be computed properly when not provided by the areacella (atmosphere, land) or areacello (ocean) variables.

**Comment by huard** [comment]
Started working on it. The current indicators require that area be passed explicitly. Agreed it would be useful to have a function to reconstruct grid cell areas.

**Comment by tlogan2000** [comment]
> cos(lat) is a bit dangerous since some global datasets do not use the same spacing for latitudes and longitudes. Map projections are getting more "exotic" so grid cell-area need to be computed properly when not provided by the areacella (atmosphere, land) or areacello (ocean) variables.

@cothel any idea how prevalent the areacella, areacello variables would be for CMIP / CORDEX datasets...  Best case would be getting the "official" values directly from modeling centres as much as possible

**Comment by huard** [comment]
For CMIP5 I think I have the vast majority of them.

**Comment by huard** [comment]
WIP in branch `ice`

**Comment by cothel** [comment]
les valeurs pour areacella peuvent se trouver à l'intérieur des fichiers des autres variables ou bien être fournies dans un fichier à part (comme nous le faisons pour MRCC5). C'est une obligation de le fournir. Même chose pour areacello.
