### ISSUE TITLE
Docs failing due to the need for spatialindex library

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#321]
* xclim version: 0.12.3

### Description

The dependencies needed for Fiona and GeoPandas included RTree, which relies on a C library (libspatialindex) without this library, the builds will fail.

Unfortunately, this complicates the docs build as ReadTheDocs doesn't allow installation of random C libraries to satisfy Python dependencies. We need to mock the installation of python libraries that require this binary.

ReadTheDocs has some suggestions on how best to approach this. https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules. Unfortunately, I can only do so much way from the office. @huard I feel like we've deal with this problem in this past. Do you think mocking the dependencies is a reasonable approach?

**Comment by tlogan2000** [comment]
@tlvu would this be something you would be able knowledgeable about?

**Comment by tlvu** [comment]
I was actually search for the mock trick I used previously for Raven.  I was mocking python modules, not C library like in this case.  Have to find the PR where there are links to RtD issues I opened with the RtD dev.  Will get back once I find it.

**Comment by tlvu** [comment]
Got it.  Here's my Raven PR using `autodoc_mock_imports` (the same suggested for C library) https://github.com/Ouranosinc/raven/pull/167/files#diff-1ec61223727a10e5e4c74c68336809fc

There the RtD issue I opened with reponse from the RtD dev https://github.com/readthedocs/readthedocs.org/issues/5847#issuecomment-519198831 (start reading from here and below, the stuff on top is less useful).  They can manually enable `UPDATE_CONDA_STARTUP` to our RtD project to improve speed if needed.  This is manual on their server-side so have to ask them.
