### ISSUE TITLE
some comments on polygon subsetting

### ISSUE THREAD

**Issue by mathause** [Ouranosinc/xclim#322]
Sorry to chip in - I just saw #285 and couldn't resist. For `regionmask` I found that the `shapely.vectorized` functions are faster than even converting lat/ lon to `Points` and it is also faster than `[poly.intersects(point) for point in points]` (which is basically what `gpd` does internally, although it also applies some tricks to make it faster).

To get the same as `intersects` you have to combine `touches` and `contains`:

``` python
from shapely import geometry
from shapely import vectorized
import numpy as np

lon = np.arange(-180, 181)
lat = np.arange(89.5, -90, -1)

outline = np.array([[-100.0, 50.0], [-100.0, 28.0], [-80.0, 28.0], [-80.0, 50.0]])
poly = geometry.Polygon(outline)

LON, LAT = np.meshgrid(lon, lat)
points = [geometry.Point(pt) for pt in zip(LON.flatten(), LAT.flatten())]

a = np.array([poly.intersects(point) for point in points]).reshape(LAT.shape)

b = vectorized.touches(poly, LON.flatten(), LAT.flatten()).reshape(LAT.shape)
c = vectorized.contains(poly, LON.flatten(), LAT.flatten()).reshape(LAT.shape)

(a == (b | c)).all()
```
And some timings:
``` python

%timeit points = [geometry.Point(pt) for pt in zip(LON.flatten(), LAT.flatten())]

%timeit a = np.array([poly.intersects(point) for point in points]).reshape(LAT.shape)

%timeit b = vectorized.touches(poly, LON.flatten(), LAT.flatten()).reshape(LAT.shape)
%timeit c = vectorized.contains(poly, LON.flatten(), LAT.flatten()).reshape(LAT.shape)

```
I get
```
~ 370 ms
~ 185 ms
~ 7.64 ms
~ 4.96 ms
```

Note: `a = ` is likely faster in `gpd.tools.sjoin` as he uses an `rtree` and `np.vectorize` internally, but still... (I could not get `gpd.tools.sjoin` to work, so I wasn't able to time it).

In `regionmask` I trade a tiny bit of precision for a bit of time; but also get a consistent point-on-border behavior (https://github.com/mathause/regionmask/blob/93bcc1a4a9656c13e1d6ecb0656b12980d471d4e/regionmask/core/mask.py#L259-L264).

I wasn't sure - do you allow to subset more than one Polygon at a time? Then your results may depend on the order of the polygons (if the polygons touch and you have points on the border).

Anyway, feel free to close...

---
edit: fix example

**Comment by tlogan2000** [comment]
@mathause thanks for the info.  Do you know offhand if ```vectorized``` method handles MultiPolygon regions well?   I can test my self to see how it works but was simply wondering...

From memory, the basis for the create_mask() portion of the code ( using gpd spatial join on the individual points)  came from a simple script  used when having trouble with dealing with MultiPolygon geometries (e.g. administrative regions that include many small islands etc.)

**Comment by mathause** [comment]
I just realised that I don't have an explicit test for this - I should add one (however, I test that `rasterio.features.rasterize` is equal to `shapely.vectorized.contains` for my defined regions which include MultiPolygons). But yes, vectorized handles MultiPolygons (not sure if this is a new feature, though, should check this as well):

``` python
from shapely import geometry
from shapely import vectorized
import numpy as np

lon = np.arange(-180, 181)
lat = np.arange(89.5, -90, -1)

outline1 = np.array([[-100.0, 50.0], [-100.0, 28.0], [-80.0, 28.0], [-80.0, 50.0]])
poly1 = geometry.Polygon(outline1)

outline2 = np.array([[-125., 30], [-105, 30], [-105, 40], [-125, 40]])
poly2 = geometry.Polygon(outline2)

poly = geometry.MultiPolygon([poly1, poly2])

LON, LAT = np.meshgrid(lon, lat)
points = [geometry.Point(pt) for pt in zip(LON.flatten(), LAT.flatten())]

a = np.array([poly.intersects(point) for point in points]).reshape(LAT.shape)

b = vectorized.touches(poly, LON.flatten(), LAT.flatten()).reshape(LAT.shape)
c = vectorized.contains(poly, LON.flatten(), LAT.flatten()).reshape(LAT.shape)

(a == (b | c)).all()
```
