### ISSUE TITLE
maximum_consecutive_dry_days returns zero for all NaN input

### ISSUE THREAD

**Issue by mathause** [Ouranosinc/xclim#333]
* xclim version: '0.12.3'
* Python version: 3.7
* Operating System: linux

### Description

If a whole year of data is `NaN` `xclim.indices.maximum_consecutive_dry_days` (and maybe others) returns 0. I would rather expect `NaN`?

### What I Did

``` python
import numpy as np
import xclim
import xarray as xr

data = [0, np.NaN, 0, np.NaN]
time = xr.cftime_range("2006-01-01", periods=4, freq="A")
attrs = dict(units="kg m-2 s-1")
da = xr.DataArray(data, dims=["time"], coords=dict(time=time), attrs=attrs)
xclim.indices.maximum_consecutive_dry_days(da)

```

**Comment by huard** [comment]
NaNs are handled by Indicator classes: 

``` 
from xclim import atmos                                                                                                                                                                             
atmos.maximum_consecutive_dry_days(da)  
```
will fail saying input should be daily. If you pass daily series with missing values, the output with missing data should be set to NaNs. This was a deliberate design decision to keep indices simple, and manage missing values at a higher abstraction level.

**Comment by mathause** [comment]
Ok, thanks for the info, that works indeed as I would have expected. However, `atmos` is very hard to find but it should probably be the default? Also `atmos` is not a very intuitive name for what it does.

I did `import xclim` `<tab>`: oh there is `indices`, let's use this. Naively I would expect the `atmos` category in `indices` and the unchecked ones in `indices_no_check` (or something like this).

**Comment by huard** [comment]
The idea was to have two layers, one with basic calculations (indices), and the other with metadata formatting and missing value checks. 
We thought to put these indicators in categories reflecting the cmip realm they belong to (atmos, land, ocean, seaIce). 
One issue we have is that those indicators are class instances, and it's not yet clear how to document those in sphinx. So you're right, for the moment they're not very visible. 

Suggestions on how to improve on the current setup are most welcome !

One action we could take is clean the scope of xclim, so we have only ICCLIM, atmos, land, indices, seaIce and utils.

**Comment by tlogan2000** [comment]
On my todo list as well. Need to improve the docs to explain atmos (and class indicators) vs indices better. There is a small section explaining the differences in the workflow examples but this definitely needs a better structure and more examples.

**Comment by mathause** [comment]
Sounds good to me - one small thing you could also do is to make `atmos` discoverable from `xclim` directly, i.e. enable `xclim.atmos` (such that it does not need to be imported as `from xclim import atmos`).

**Comment by huard** [comment]
That's now in master, with a release planned Friday.
