### ISSUE TITLE
Pytest notebooks

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#343]
There have been a few points brought to light about our working examples notebook. It seems that many of the example calls are no longer valid due to breaking changes. It would be good to do the following:
- Split our example notebook into a few distinct notebooks (two to four) and showcase different functionalities in a separate environment.
- Run the Jupyter Notebook pytest tools within our `docs` Travis CI test ensemble.

What this requires:
- Adding `jupyter` and `nbval` to the `docs` build dependencies
- Adding a sanitization file with sanitation rules for the output (can be grabbed from other repos).
- Adding a script to evaluate the notebooks folder within the docs.

**Comment by aulemahal** [comment]
Just parsing the docs of `nbsphinx` and I see that you can make it run the notebooks while building the docs, it simply fails if an exception is raises. But you can also allow exceptions on a per-notebook/per-cell basis. I suggest we enable this, so the doc build will simply fail in Travis if breaking changes have been made.
