### ISSUE TITLE
Change setup.py to use x/rst

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#345]
* xclim version: 0.13.0

I was curious as to what would be necessary to fix the project description for Xclim on PyPI, seeing as the text formatting has been broken on there ever since we started (https://pypi.org/project/xclim/). Well it turns out the solution is one line fix.

After changing the `setup.py`'s `long_description_content_type` to `text/x-rst`, I got something that looks like this: https://test.pypi.org/project/xclim/0.2.0/ (this is a testing sandbox for PyPI). Oustide of the image not being rendered (this functionality isn't allowed on PyPI), everything works.

With this changes, I'm thinking that for the cookiecutter recipe I've used to template xclim (https://github.com/Ouranosinc/cookiecutter-pypackage-ouranos), it might be good have an option to set this on package creation (ie: `What language are your docs written in? [x-rst / markdown]`).

**Comment by huard** [comment]
Nice ! Note that the logo doesn't show up.

**Comment by Zeitsperre** [comment]
Noted. I've seen a few examples around that suggest it can still work, just not as an inline image. I'll try putting it above again and uploading to the testing PyPI. If it takes more than two tries, I'll drop it.
