### ISSUE TITLE
Improve Fire Weather Indexes

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#351]
As of #226, we now have code to compute the Fire Weather Indexes, but it is still quite slow and restrictive.

We need to: 

- [x] Vectorize the three code (DC, DMC, FFMC) functions, either directly or with [numba](https://numba.pydata.org/)
- [x] Add ways of computing the start up and shut down of the indexes. Right now, only the GFWED way, using the snow depth from the previous 60 days is implemented.
- [x] Find a way to get test data without bloating up xclim. Right now, the exposed indices are not tested.
- [x] Find a nice way to expose the individual indices OR expose a `MultiIndicators` object in `atmos`. Right now, only the `drought_code` is accessible through `atmos` and the others are computable in one go through `xclim.indices.fire_weather_indexes`.

As for the second point: we could try to use the "dry start up" method everywhere. The [CFS](https://cwfis.cfs.nrcan.gc.ca/background/dsm/fwi) has more info about a DC-specific method. Also, in the paper below, they didn't use any start up/shut down for the three codes and had an arbitrary threshold for masking the compound indexes (20% snow-covered cell area). 

Vitolo, C. et al. A 1980–2018 global fire danger re-analysis dataset for the Canadian Fire Weather Indices. Sci. Data. 6:190032 https://doi.org/10.1038/sdata.2019.32 (2019).

**Comment by aulemahal** [comment]
I am currently working on the vectorization of the code functions and here are the computation times for different version of the FFMC:

1. Current loop on spatial dimensions : 35 s
2. Same function but vectorized with `np.vectorize` : 40 s
3. Same function but vectorized with numba : 450 ms
4. Rewritten ND numpy function  : 1.1 s

(data is 125x100, iterated on a full year)
The problem with #4 is that it uses a lot of compound `np.where()` and I found it difficult to maintain readability while optimizing the computation. On the other hand, it allows to boost computation without adding a new dependency.
We could have both options implemented to make numba optional, but that's a bit ugly.  It's easier to do this with 2 and 3 as we only need to redefine the "vectorize" decorator.

So. Are we ok with adding numba as dependency, or do we prefer stick to numpy and still accerated by a lot anyway?

@huard @tlogan2000 @Zeitsperre

**Comment by tlogan2000** [comment]
I would have a tendency to go with numba.  We might want to explore combining numba+dask for some bottlenecks in xclim in general down the road?  Combining numba and dask together could give us some pretty interesting performance i think : see https://towardsdatascience.com/how-i-learned-to-love-parallelized-applies-with-python-pandas-dask-and-numba-f06b0b367138

**Comment by huard** [comment]
No strong opinion. I like that we don't have to mess with the original code. I say let's try numba and learn from the experience.

**Comment by Zeitsperre** [comment]
For the data problem, how big are we talking? One way around this would be to create a python package that does nothing but install a test data folder that is accessible via Python. Alternatively, we could use `intake` (https://github.com/intake/intake) as a means of grabbing the data we need for more in-depth testing of FWI.

**Comment by aulemahal** [comment]
Oh, not that much, right not the FWI tests would need a 100K dataset. But I think we decided not to add it directly and wait for a system that could remove most of the datasets in `testdata/` .

**Comment by Zeitsperre** [comment]
@aulemahal 100K is not that much. I can see it being a problem farther down the line, but if it helps in performing/testing the analyses, I'd put it in for the time being.

We don't install the testdata in the wheel files so it has no impact on users that aren't developing from source. Cutting down the testdata might involve using `intake` or another means (bunk data generation?) and in both cases we need to perform that separately some time from now.

**Comment by Zeitsperre** [comment]
@aulemahal let me know what you think of this proposal when you can.

**Comment by aulemahal** [comment]
Oh! I think we had parts of this discussion with others in another FWI PR earlier, but the conclusion I remember was: 
1 - Use generated data as often as possible in tests (most new tests do that, but not older ones)
2 - Use some on-the-fly download technique to test with real datasets (allowing larger files and maybe more dask-behaviour testing?) 

@huard has written some code in xclim/testing for 2, but if another package like `intake` can take care of it, I vote that : exclude out-of-scope as much as possible (says the guy with the complex wrapped_partial PR).

1 Will be a painful job, but I'm pretty sure it will accelerate the tests by far.

What needs to be thought of, I think, is how to test indices (and indicators) with correct expected output when we try 2?

**Comment by Zeitsperre** [comment]
I like the idea of using `intake` for tackling 2. My only worry is whether or not we are pointing towards a server that won't go down too often. I haven't gotten my feet wet with using `intake` but we can examine this more in depth in the coming weeks (I imagine it works fine with THREDDS-supplied data).

Writing up a notebook would probably be the easiest way to test the outputs more generally. We can modify some existing ones to do that and create more particular tests for others (I feel like `hasattr` will come in handy for most indicator tests).

**Comment by huard** [comment]
`intake` is a catalog, it doesn't store any data.

**Comment by Zeitsperre** [comment]
It looks like we can create an `intake` specifically for xarray based on our THREDDS server's OPeNDAP links (see: https://intake-xarray.readthedocs.io/en/latest/index.html). The only concern now would be how best to limit the slowness due to latency/server availability.

**Comment by aulemahal** [comment]
I just really read what `intake` does (sorry I didn't clearly know before). It seems that is pretty much does the same as David's work in xclim/testing/.  However, using intake as the advantage of taking this out-of-scope code out of xclim and adds bit more flexibility, if we ever need it. 

I agree with @Zeitsperre : I think I would opt for constructing an `intake` catalog, we just need to make the data accessible somewhere...  Note that `intake` catalog entries have a `persist` option, which could be useful, but I don't know how this would work with OPeNDAP links...

**Comment by aulemahal** [comment]
This old issue was closed by #620 I believe. Also, #643 is the new cool issue.
