### ISSUE TITLE
Fire Induced Flashover Potential Index

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#353]
FIFPI = 1 / (1 + e −(196+6.24RH+0.0505T+0.557WD−0.909WS))

Where RH is the relative humidity in %, T the air temperature in °C, WD the wind direction in degrees from North and WS the wind speed in m/s.

In "Vegetation fire characteristics and the potential impacts on overhead line performance". 

See also 
Frost, P.E. 2011, Development of a Fire-induced Flashover Probability Index (FIFPI) for Eskom Transmission Lines. M.Sc. Thesis, University of Johannesburg.

**Comment by aulemahal** [comment]
I have started some work on this in the `fix-353-fifpi` branch. However, when digging for documentation I realized this index seemed pretty specific for that South African transmission line case. Do we know of other people that use it elsewhere? As it is a statistical fit of less than 1 year data for a specific climate, I'm wondering how universal the coefficients are.

**Comment by huard** [comment]
No, just something I came across and flagged as potentially interesting. If you feel this has limited usefulness, please say so and close the issue.

**Comment by aulemahal** [comment]
Ok, then I declare that this index is too narrow for inclusion in xclim. The purely statistical method and the limited diversity of the data used to derive it, as well as the lack of litterature/studies showing its use make it unreliable for a more generic package as xclim.
