### ISSUE TITLE
Huglin Heliothermal index, Biologically Effective Degree Days, and other agricultural indices

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#355]
I would like to see the following indices considered as potential contributions to the xclim library:

- [x]  Biologically Effective Degree Days (BEDD) (sum of degree-days with floor of 10 Celsius and a ceiling of (usually 19 Celsius)) (Gladstones, 1992).
- [x] Crop/Corn Heat Units (CHU) (Zhang et al., 2011)
- [x] Effective Growing Degree Days (EGDD) (https://doi.org/10.1175/2009JAMC2275.1, https://cdnsciencepub.com/doi/pdf/10.4141/S04-019)
- [x] Huglin Heliothermal Index (Huglin, 1978),
- [x] Cool Night Index (Tonietto and Carbonneau, 1999) (https://doi.org/10.1016/j.agrformet.2003.06.001),
- [x] Dryness Index (Tonietto and Carbonneau, 1999) (https://doi.org/10.1016/j.agrformet.2003.06.001)
- [x] Latitiude-Temperature Index
- ~Hardiness Zones (USDA is the most common/simple one, but there are other versions)~

These are relatively popular agricultural indices that wouldn't be too difficult to implement based on a handful of the already-developed heat summation indices.

**Comment by cothel** [comment]
À propos de Crop/Corn Heat Units (CHU). Vérifier si la formule diffère de la formule des UTM de l'atlas Agroclimatique du Québec. **La formule utilisée dans l'atlas à une valeur légale au Québec et est la seule reconnue par la Financière Agricole du Québec pour fin d'assurance récolte**.  **_Si la forme CHU est codée dans xclim, il faut que la documentation soit très claire à ce sujet_**. Pour les autres indices, je suggère de consulter Anne Blondlot.

**Comment by Zeitsperre** [comment]
@cothel Good point. Seeing as these indices are used for insurance purposes and are different between regions, it would be good to make that very clear. It might possibly be a case for adding a regional keyword (e.g `method = {"region" : "qc"}` or `"region" : "usa"`) to differentiate the methods; Either that or using the background logic to create specific stand-alone functions.

I hadn't thought of speaking with Anne about this. I'll see what she thinks. Thanks for the suggestions!

**Comment by cothel** [comment]
Je trouve qu'il vaut mieux créer des indices différents, car l'approche method = {"region" : "qc"} or "region" : "usa" me semble dangereuse.
Donc _unités thermiques maïs_ (UTM) pour la formule du Québec et _crop heat Unit_s (CHU).
Les québécois vont reconnaitre facilement UTM.
Je crois que ça vaut la peine de vérifier si les formule américaines et celle du ROC sont les mêmes.

**Comment by Zeitsperre** [comment]
J'attends après Anne pour la fiche avec les formules pour Québec, mais je voudrais dire qu'ils ne sont pas les mêmes. Je dois trouver une meilleure façon de spécifier les différences. Si par exemple les formules sont les mêmes, mais leurs coefficients sont différents, on pourrait en mettre une par défaut avec les critères pour l'autre dans le docstring?

Aussi, je ne suis pas super à l'aise de mettre les noms de quelques indices seulement en français. De plus, on est en train de mettre le support pour multilingue. On pourrait discuter pour trouver comment procéder cette semaine.

**Comment by aulemahal** [comment]
I just added "hardiness zones" as another possible indice. Should be quite simple to code.
This is not for a project, but rather as a personal interest. (Did you know that most of Québec gained a _full_ zone since 1990?)

**Comment by Zeitsperre** [comment]
After discussion, it's clear that the process of building the climatology calculation that "Hardiness Zones" requires would be useful within the context of some more complicated indicators, such as SPI/SPEI. This indicator would be a "fun addition" to build upon the work needed if we were to support https://github.com/monocongo/climate_indices.

For those reasons, I'm going to remove it from the list here, but we should consider adding this as part of the goals for SPI/SPEI.

**Comment by Zeitsperre** [comment]
Closed by #1235
