### ISSUE TITLE
Testing Procedures

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#36]
I stumbled upon a much better way to perform tests on local machines. I didn't realize that `tox` could be run locally. `tox` is a virtualenv-based testing environment that the Travis CI runs to verify build success. By ensuring that you have `tox` installed in your system python (for Ubuntu: `apt-get install tox`) as well as within your conda environment (`conda install tox`), running tox as a Python Testing configuration (in PyCharm) will trigger the build-tests on all available Python environments for your machine. An example:

![screenshot from 2018-09-27 09-57-32](https://user-images.githubusercontent.com/10819524/46151023-e5db1780-c23b-11e8-8ff9-4cffd386b9b0.png)

Errors reports are divided by build so you'll be able to see where your errors are and what builds they are on. For reference, the configured builds are `py27, py34, py35, py36, flake8,` and `docs`

**Comment by huard** [comment]
Works for me.
