### ISSUE TITLE
Improve missing data check

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#365]
### Description
Currently missing data checks in indicator classes are very strict (single missing day or single nan value) will result in nan for a given resample time step

Options include:

1.  Percent missing : https://github.com/Ouranosinc/xclim/issues/364#issuecomment-585804628
2. WMO data completeness https://github.com/Ouranosinc/xclim/issues/364#issuecomment-585798512

For option 1 need to decide on :

- How % missing data is determined on a annual frequency : see https://github.com/Ouranosinc/xclim/issues/364#issuecomment-585828201

- Whether missing data is interpolated or not before averaging / summing : https://github.com/Ouranosinc/xclim/issues/364#issuecomment-585838629

**Comment by tlogan2000** [comment]
This could likely be implemented without a major refactor  (mentioned in #364 ) so am putting a milestone for v.0.15

Option 1 seems to me like the simplest way forward despite having a couple of discussion points to tackle

**Comment by Zeitsperre** [comment]
Would it be possible to integrate this goal into the very stale #65 and accompanying #268 ?
