### ISSUE TITLE
Development Roadmap page in wiki is outdated

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#386]
Update ? Remove ?

**Comment by aulemahal** [comment]
I vote remove. The project "[kanban](https://github.com/Ouranosinc/xclim/projects/1)" already kinda shows an up-to-date version of this.

**Comment by Zeitsperre** [comment]
I vote remove as well. Not a fan of the Scrum approach to goal-setting and based on how out of date it is, I don't think we need it.

**Comment by Zeitsperre** [comment]
Page removed.
