### ISSUE TITLE
Resample / Custom resample - mask incomplete periods

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#39]
### Description
In both native resample and @sbiner 's custom 'daily_downsampler' current results keep incomplete periods as valid data.

For now the main issue is seasonal  resampling of QS-DEC.  For example the DJF value of the intial year of multfile dataset (containing only Jan/Feb) has valid data and starting time stamp of DEC of year-1.  Similarly, the last Dec in a multi file data array becomes a valid DJF season even when only 1 month is present.

I suggest that the xclim default should mask (assign nans?) the time steps. XCLIM would have a default behavoir 'mask_incplt=True', which could be changed to 'False' return to default xarray resample behavior if wanted?
I think a mechanism like this will help us long-term when eventually dealing with station data (lots of missing values and potential problems not just in the beginning / end of the calculations)

thoughts?
Ideas on implementing this?

**Comment by sbiner** [comment]
I agree. I did this elsewhere by comparing the number of days to a target depending on the frequency (i.e year, season, month, ...). This could be done in the 'data cleaning' done (i.e. units conversion, ...) done before the indice computation. Maybe in a decorator?

We also have to remember that this check is not only one number, it could be 1D (stations) or 2D(gridded data with varying missing values).

**Comment by huard** [comment]
This is now implemented in checks.missing_any. 
It counts the expected number of days in each period, compares with the resampling notnull count, and returns True if count does not match. 
Not tested with 2D data yet. 
This function should be used outside of the indicators, e.g. in the UnivariateIndicator subclass.
