### ISSUE TITLE
Latitude-influenced indicators

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#390]
Follow-up from the discussion point raised in https://github.com/Ouranosinc/xclim/pull/379#discussion_r386492522

Also relevant to this discussion: #355 

Now that we are beginning to see expanded support for seasonal indicators such as `growing_season_`-based calculations, there is a clear need for latitude as an evaluable criteria during `run_length` calculations. The reasons for this have to do with supporting the different phenological timings between the North and South hemispheres when evaluating global-scale data sets (evaluations of growing seasons, [Corn/Crop Heat Units](https://open.canada.ca/data/en/dataset/07875f11-c342-4450-bdaa-0cdeaf43c0c9) ) as well as indicators that are sensitive to a range in latitudes (e.g. Latitude-Temperature Index, Huglin Index, etc., Biologically-Effective Degree Days, etc.).

There are complexities around how to gain access to the latitudes of a DataArray (misnamed dimensions, missing dimension, projected geocoordinates) and I imagine that integrating these into `run_length`-type calculations would require another level of complexity for some evaluations.

Opening the issue here so we can suggest ways forward.

**Comment by aulemahal** [comment]
Honestly,  instead the issue really comes up user-wise, I suggest we leave latitude as an explicitly passed argument.
And that we do not try to handle season problems for that aspect. I mean, if a user has a global dataset and wants to compute `growing_season_length`, he should divide it in two parts and run them separately with `mid_date` and `freq` set accordingly.  If we try to implement it, we would have to manage the fact that two freqs have been used and the outputs `time` dimensions thus differ. And what does gsl mean at the equator *anyway*?

**Comment by Zeitsperre** [comment]
Good point on the equator scenario. Growing seasons are limited by excessive or insufficient rain at the equator. Very difficult to determine and can also lead to problems with comparing countries/regions that straddle or are split by the equator (for the Americas: Colombia, Ecuador, Brazil, Peru, etc.).

**Comment by Zeitsperre** [comment]
It looks like the way forward for now is to supply `lat` as a variable (see: #735 and #742). Maybe we'll revisit this if ever we integrate cf-xarray (though given the fact that we support reanalysis data, I doubt we can demand that latitudes conform to CF; It sure is complicated!), but this seems good enough for now.

Thanks for the help @aulemahal !
