### ISSUE TITLE
Investigate using boltons.funcutils to create modules

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#392]
### Description

functools.partials generate objects that are interpreted as data by the `help` function. Maybe boltons could fix this. 

```
help(xclim.icclim)
```

**Comment by aulemahal** [comment]
@huard #394 partly solves the help issue and the signature of the wrapped functions. However, the name and the docstring are still the ones from the wrapped indice. Is this something we want to fix? (Considering that fixing the docstring is on another level of complexity...)
