### ISSUE TITLE
DataArray attributes

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#40]
### Description
When coding index functions using the daily_downsampler make sure to use 'keep_attrs=True' or to create appropriate attrs (minimally suggest : units, long_name, standard_name) as an ordered dictionary

Example:
from xclim.utils import daily_downsampler as dds
grouper = dds(da, freq=freq)
output = grouper.max(dim='time',keep_attrs=True)

In cases where the index calculation results in a change of units (or both units and name attrs) they should be modified (as an ordered dictonary) before returning the dataarray.  

E.g. Calculation of growing season length from temperature data would change all attributes (units, long_name, standard_name)

**Comment by huard** [comment]
I suggest to use ``with_attrs`` for this (see indices.py).

**Comment by tlogan2000** [comment]
Ok. @huard If I am understanding correctly 'with_attrs' will assign the listed attributes in the decorator to the output xr.DataArray.

However, the keep_attrs=True (in the resample / grouby) is potentially still of interest for cases when we wish to retain some or  all of the orginal attrs...  For example in some cases units won't change but standard names etc will

**Comment by huard** [comment]
@tlogan2000 Correct. 
That's my understanding as well.

**Comment by sbiner** [comment]
Donc si on change les attributs dans le calcul d'un indice, ce changement se fera écrasé par @with_attrs c'est ça?

**Comment by sbiner** [comment]
Ok c'est beau, Travis a répondu à ma question.
