### ISSUE TITLE
Decorators - Daily time step and Units conversion

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#41]
### Description

XCLIM assumes a daily time-step (currently) : 

- [ ] Create decorator  to test monotonic daily time

All functions should also be decorated with a units converter decorator:

- [ ] Temp units to Kelvin (from C and F(?))
- [ ]  Pr units to 'mm'  (from kg m-2 s-1  and mm s-1, others?)

In my mind these replace the various 'check_valid' decorators  (which currently do not convert and simply check) and are potentially too strict on CF-Compliance ?  CF-checking could eventually be done on WPS PAVICS side for non expert users. (i.e. we assume that internal XCLIM users know what they are doing)

**Comment by Balinus** [comment]
Does non-standard calendars have monotonic daily time?

**Comment by huard** [comment]
Within their own calendars, yes. But the issue is to implement this check for these non standard calendars.
