### ISSUE TITLE
Water cycle intensity indicator

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#410]
### Description

Add indicator for the intensity of the terrestrial water cycle
https://www.sciencedirect.com/science/article/pii/S0022169418301276

**Comment by aulemahal** [comment]
So with the water cycle intensity WCI = P + AET, (eq 4) where P is precipitation and AET the "actual evapotranspiration". What variables are usually available to compute AET?
Eq. 1 says : P = AET + Q + dS/dt, so I guess: WCI = 2P + Q + dS/dt, but are Q and dS/dt available in models?

**Comment by huard** [comment]
I *think* Q + dS/dt would be given by `mrro` (https://pcmdi.llnl.gov/mips/cmip3/variableList.html)

Note that this is a low priority task. I just noted it as I thought it would be interesting to look into for model diagnostics.
