### ISSUE TITLE
Implement ANUCLIM module &  indicators 

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#411]
Many users in forestry / biology / agriculture use ANUCLIM bioclimatic variables. I suggest creating a  submodule xclim.anuclim for these users

Many indices are already presnt but some will require coding .. Also most of the derived indices (seasonality, etc) here  work of monthly or seasonal datasets so might require expansion of checks etc

Chapter 6 describes indices.
https://fennerschool.anu.edu.au/files/anuclim61.pdf

---

The descriptions below assume that BIOCLIM is using the weekly time step (the default). If
the monthly time step is selected, monthly values are used when calculating these parameters.
The quarterly parameters are not aligned to any calendar quarters. BIOCLIM's definition of a
quarter is any 13 consecutive weeks, (or any consecutive 3 months if running with a monthly
time step). For example, the driest quarter will be the 13 consecutive weeks that are drier than
any other set of 13 consecutive weeks.

- [x] 1) Annual Mean Temperature
The mean of all the weekly mean temperatures. Each weekly mean temperature is the
mean of the weekly maximum and minimum temperatures over the whole year.
- [ ] 2) Mean Diurnal Range(Mean(period max-min))
The mean over the whole year of the weekly diurnal temperature ranges. Each weekly
diurnal range is the difference between that week's maximum and minimum temperature.
- [ ] 3) Isothermality 2/7
The mean diurnal range (parameter 2) divided by the Annual Temperature Range
(parameter 7).
- [x] 4) Temperature Seasonality (C of V)
The temperature Coefficient of Variation (C of V) is the standard deviation of the weekly
mean temperatures expressed as a percentage of the mean of those temperatures. For this
calculation, the mean in degrees Kelvin is used. This avoids the possibility o f having to
divide by zero, but it does mean that the values are usually quite small.
- [x] 5) Max Temperature of Warmest Period
The highest maximum temperature in all weeks of the year.
- [x] 6) Min Temperature of Coldest Period
The lowest minimum temperature in all weeks of the year.
- [ ] 7) Temperature Annual Range (5-6)
The difference between the Max Temperature of Warmest Period and the Min
Temperature of Coldest Period.
- [x] 8) Mean Temperature of Wettest Quarter
The wettest quarter of the year is determined (to the nearest week), and the mean
temperature of this period is calculated.
- [x] 9) Mean Temperature of Driest Quarter
The driest quarter of the year is determined (to the nearest week), and the mean
temperature of this period is calculated.
- [ ] 10) Mean Temperature of Warmest Quarter
The warmest quarter of the year is determined (to the nearest week), and the mean
temperature of this period is calculated. 
- [ ] 11) Mean Temperature of Coldest Quarter
The coldest quarter of the year is determined (to the nearest week), and the mean
temperature of this period is calculated.

...

**Comment by tlogan2000** [comment]
This is needed for a Ouranos VIA project (Northern program) ...

**Comment by aulemahal** [comment]
I suggest the we divide the labor as follows:
@tlogan2000  : 2, 3, 4, 7, 10, 11, 15,  16, 17
@aulemahal  : 8, 9,  13, 14, 18, 19
1, 5 and 6 are already available.
