### ISSUE TITLE
Update docs to indicate refactor of percentile_doy

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#418]
Refactoring has moved the percentile_doy() function to xclim.core.calendar but a number of examples in the help still indicate imports from utils() 
e.g. hot_days example  (but others present as well): 

>>> import xarray as xr
>>> import xclim.utils
>>> tas = xr.open_dataset("temperature_data.nc").tas
>>> t90 = xclim.utils.percentile_doy(tas, per=0.9)
>>> hot_days = tg90p(tas, t90)

**Comment by aulemahal** [comment]
Ach.  Maybe we should consider running the examples while testing?

**Comment by tlogan2000** [comment]
If possible that would be the best.  There could be others which do not work....  This is one that I spotted
