### ISSUE TITLE
Diagnostic tests for downscaling methods

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#424]
### Description

Define generic diagnostics (e.g. trend preservation) to evaluate how various method perform.

**Comment by aulemahal** [comment]
Discussions about Ouranos' internal scenarisation workflow and needs for the upcoming ESPO-R dataset have brought this issue back to the priorities.

I suggest going forward by implementing something inspired from the VALUE project (value-cost.eu). I see 2 new "submodule" : "indices" or "diagnotics" and "measures", replicating the division shown here : http://www.value-cost.eu/validationportal/app/#!indices

- `indices` : Functions reducing the time axis of the variables, very similar to the main Indicators. How much we can pull from the core xclim library is yet to be seen.
- `measures` : Functions giving means to compare the indices between different dataset, usually obs, hist and scen. They might also include further dimension reduction (time? spatial?).

As for the rest of `sdba`, these are basic tools that users must then use in their own script. We're not implementing any mega function returning a Good/Bad flag or any plotting methods.

The VALUE code is here : https://github.com/SantanderMetGroup/R_VALUE, 
However, I see that their code license is incompatible with ours... I'm not sure what that means, but I guess I'll make sure that names are different and that I implement the indices without looking at their code??

**Comment by RondeauG** [comment]
Looking at the link provided, I'd say that most of the indices seem relevant. If we want to prioritise, the areas where we currently are lacking with our in-house qualitative checkups (figures) are:

- Anything spell-related (e.g. Median of wet (>=1mm) Spell Length Distribution)
- Transition probabilities & autocorrelation
- Extremes (e.g. 98th percentile, 20-year return value)  --> High and low
- Monthly variability
- Interannual variability

**Comment by juliettelavoie** [comment]
Thanks for your input Gabriel! J'ai regroupé les indices de VALUE par aspect avec quelques infos supplémentaires. Veux-tu indiquer ceux que tu trouves pertinents dans la colonne Q ? https://ouranos-my.sharepoint.com/:x:/g/personal/jullav1_ouranos_ca/ETCaUuKJUz5OmjVkM1gOLJsBInomqAUA8-Llu-Ox__lIfA?e=ZAERfs
