### ISSUE TITLE
Add warning loggers for field changes after setting "keep_attrs" to True

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#43]
A warning should be logged when calculations of an index results in changes to the variable/units outputted. For example:

* Tmax and Tmin (K / deg C / F) -->  Growing Degree Days (sum deg C days )

Logging is a better option than printing as warnings can be selectively suppressed.

**Comment by huard** [comment]
If I understand correctly, this is already handled using the with_attrs decorator in indices.py. What remains to be done is to add the decorator to each index.

**Comment by huard** [comment]
@Zeitsperre Ok to close ?

**Comment by Zeitsperre** [comment]
Yep, looks good to me. Thanks!
