### ISSUE TITLE
Create a dictionary of cell methods for indices 

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#44]
Within the variable attributes of NetCDF data the cell methods are a CF-Standard convention for tools and users to better understand pixel values and AFAIK, incorrect cell methods constitute a critical error for PAVICS, among other platforms reading these data sets.

Indices should be set to update the cell methods for each transformation/calculation/aggregation/etc. performed. e.g.:

* "time: mean over days" --> "time: mean over season" / "mean over year"
* "time: sum over hour" --> "time mean over year", etc.

One possible solution is to create dictionary of fields that can be set to update when algorithms are called. These definitions could exist in a separate file (e.g. `attrs.py`).

Solutions for this issue should ideally be combined with #43

**Comment by huard** [comment]
I think I can handle this using the with_attrs decorator.

**Comment by huard** [comment]
One issue is that for many indices, the operation does not reduce to the cell method vocabulary: http://cfconventions.org/cf-conventions/cf-conventions.html#appendix-cell-methods

For those that do, see branch fix_44 and let me know if that's what you had in mind.
