### ISSUE TITLE
DetrendedQuantileMapping only applies the last correction factor

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xclim#441]
* xclim version: '0.16.1-beta' (master, as of 2020-05-08)
* Python version: 3.8.2
* Operating System: Linux

### Description
The figure below is the daily average : `plt.plot(data.groupby("time.dayofyear").mean("time").values)`. The black line is my OBS data, the blue line is my RAW data, the green line is the result of EmpiricalQQMapping and the orange line is the result of DetrendedQuantileMapping.

![image](https://user-images.githubusercontent.com/38501935/81433867-41b59400-9133-11ea-8adf-b3be4e38fa67.png)

These are the options I used to create the orange line:
```
group_month_nowindow = xclim.sdba.utils.Grouper('time.month')
QQ_m_nw_ni = xclim.sdba.adjustment.DetrendedQuantileMapping(nquantiles=50, kind='+', group=group_month_nowindow, extrapolation='constant')
QQ_m_nw_ni.train(obs, hist)
qq_m_nw_ni = QQ_m_nw_ni.adjust(hist, degree=3)
```

And this is `QQ_m_nw_ni.ds.af.plot.contourf()`
![image](https://user-images.githubusercontent.com/38501935/81434207-d3250600-9133-11ea-9934-0f0d2e31771a.png)

The huge jump in May leads me to believe that the correction factor associated to the last quantile is what is being applied for the whole distribution.

### Additional Information
In `xclim.sdba.adjustment` and `_adjust` (line 230), I added the line with `+269` (which is roughly the annual average) :

```
sim = apply_correction(sim,
            broadcast(self.ds.scaling, sim, group=self.group, interp=self.interp),
            self.kind,
        )
        sim_fit = PolyDetrend(degree=degree, kind=self.kind).fit(sim)
        sim_detrended = sim_fit.detrend(sim)
        sim_detrended.values = sim_detrended.values + 269
        scen_detrended = super()._adjust(sim_detrended)
        scen = sim_fit.retrend(scen_detrended)
        scen.values = scen.values - 269  # I need to remove that +269
```
With that additional line, I don't have the bug. This leads me to believe that this is a discrepancy between `sim`, which is centered around 269°K, and `sim_detrended`, which is normalized and centered around 0.

**Comment by aulemahal** [comment]
Bug found: The problem is that the detrending is not performed per-group. 
In the case above, `sim_detrended` still has a inter-monthly variation, while its _overall_ mean is now 0. In contrast, the quantiles were computed from monthly-normalized `ref` and `hist`.  
This leads to, for example, July values centered around 10-15 on `sim_detrended` and  around 0 on `hist_q`. All warm months take the largest quantiles' factors, all cold ones the lowest quantiles'.

In the current data, it just seems that there is a high bias in large values in May. A more "well behave" simulation could have make this problem slip under the carpet. On est chanceux!

**Comment by huard** [comment]
So the fix would be to add a "per period normalization" step before the detrending ?

**Comment by aulemahal** [comment]
That would be simple, but maybe not general enough? 

I was thinking of making the whole Detrending process group-wise? So add a `group` to the Detrend objects. 
I can see the following needs coming up for this: 
- The BaseDetrend object could manage the grouping/ungrouping, the other only implementing the fitting itself. Which is yet again more Grouper gymnastic to be done.
- In order for the `add_dims` and `window` options on `Grouper` to work with this, we need to modify `xr.DataArray.polyfit` to accept non-unique fitting coordinate which it doesn't accept currently, but has no reason to.

**Comment by RondeauG** [comment]
To add to this, I would personally prefer a Detrending calculated on the groups, rather than on the whole series. This would allow trends to be different in winter and in summer, for example.

**Comment by huard** [comment]
I agree detrending by group would be useful, however, I suggest we do this in two steps: 
1. Fix the original but with a normalization step. This should be a small and quick fix and keeps us close to the original paper. 
2. Open a new issue for a "detrend_by_group" option. I expect this isn't something we can do quickly, so better plan it.
