### ISSUE TITLE
sdba - QuantileDeltaMapping not working with dask

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#448]
* xclim version: master
* Python version: 3.8
* Operating System: Linux

### Description

`QuantileDeltaMapping.adjust`does not accept dask arrays at the moment because it uses `DataArray.rank` which fails on them.

### What I Did

```
from xclim.sdba.adjustment import QuantileDeltaMappign
QDM = QuantileDeltaMapping()
QDM.train(ref, hist)
scen = QDM.train(scen)
```
With `sim`, `ref` and `hist` in dask-stored DataArrays.

### What I Received

```
TypeError: rank does not work for arrays stored as dask arrays. Load the data via .compute() or .load() prior to calling this method.
```

**Comment by huard** [comment]
@aulemahal  Can this be closed ?

**Comment by aulemahal** [comment]
Yes. WIth #447, QDM works with dask arrays, but only with 1D arrays, which is kinda useless, but it works.
