### ISSUE TITLE
sdba - Broadcasting with two new coordinates of differing dimensions fails

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#449]
* xclim version: master
* Python version: 3.8
* Operating System: Linux

### Description

In `QuantileDeltaMapping.adjust` with grouping (here 'time.month') there is a broadcasting operation that fails when `sim` and `hist` have additional dimensions (other then `quantiles` and `time`).
In fact, calls of `xclim.sdba.utils.broadcast` fails when grouping is used, interp is not 'nearest' and both `grouped` and the coordinate in `sel` have dimensions that are not trageted by the broadcasting operation.

### What I Did

```
from xclim.sdba.adjustment import QuantileDeltaMapping
QDM = QuantileDeltaMapping(group='time.month', interp='linear'
QDM.train(ref, hist)
scen = QDM.adjust(sim)
```
Where, `ref` has one spatial dim + 'time' and `hist` and `sim` have the same spatial dim, 'time' and an additional dim, in my case `realization`.

### What I Received

```
ValueError: axes don't match array
```
The traceback is quite long, but it all comes down to `xr.interp`.

**Comment by aulemahal** [comment]
xarray's interp doesn't understand multidimensionnal interpolation when the new coordinates have differing set of coords, so I tried to broadcast all arrays of the  `sel` dictionary together which makes it work but enlarges the arrays a lot. Hopefully, no data is created so memory should be ok. However, dask arrays chunked along one of the additional dimensions will make broadcast fail. So, that's not a solution.

Kinda stuck on this. A way would be to call a `xr.apply_ufunc` with a wrapper of  `scipy.interpolate.interpn`, but that's a lot of machinery just because xarray as kind of a bug.

**Comment by huard** [comment]
Is there an open issue about this ?

**Comment by aulemahal** [comment]
Not that I can found.

**Comment by huard** [comment]
I suggest you design a short, self-contained example illustrating the issue and open an issue with it.

**Comment by aulemahal** [comment]
I didn't realize up to now, but it is worth noting that xarray raises a "NotImplementedError". It's not a real bug.

**Comment by aulemahal** [comment]
Corresponds to issue pydata/xarray#4058.
