### ISSUE TITLE
Not all doctests are picked by pytest

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#450]
### Description

- Not all doctests in docstrings are picked up by pytest.
- I don't think code in the docs is exercised by pytest yet.

For example, in `indices`, `max_n_day_precipitation_amount` runs, but not `max_1day_precipitation_amount`.

**Comment by Zeitsperre** [comment]
I've been looking into this for the past little while. `Xdoctest` seems to be much more capable of picking up the test statements and more intelligently parsing the commands. I'm currently developing a PR using this module in lieu of the standard `doctest` module. This change creates new problems though and I'm opening an issue specifically for it.
