### ISSUE TITLE
Ensemble percentiles as dimension instead of variables

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#462]
Currently, `xclim.ensembles.ensemble_percentiles` takes in a dataset and returns a new one with one variable per percentile and data variable. A more "xarray-like" behaviour would be to replace the `realization` dimension by the `percentile` dimension. In fact, `ensemble_percentiles` is more or less a xr-wrapper and workaround because `xr.quantiles` doesn't work on dask arrays. 

Moreover, it would be nice if `ensemble_percentiles` accepted DataArrays directly.

Discussion points:
- Should we keep the old behaviour (creating new variables)?
- If yes, should it be the default?

**Comment by tlogan2000** [comment]
> * Should we keep the old behaviour (creating new variables)?

I think I would still need via a ``split`` flag: climatedata.ca is pretty much built to read the separate variable output (e.g. tg_mean_p10, p_50, p_90).   

it seems like it should most likely be the default though... as it is more xarray like
