### ISSUE TITLE
Document and implement one robustness metric for ensemble statistics

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#497]
### Description

Look at how AR5 WG1 is estimating the confidence of the climate change signal from an ensemble and implement it.
See Box 12.1 in AR5 WG1 Chapter 12 for a discussion on this topic. 

The use case would be to reproduce figures where stippling/hatching on a map indicates model agreement. 

### TODO

- List the various algorithms used and estimate implementation time; 
- Discuss in group which ones we want to include in xclim;
- Discuss API;
- Submit PR.

**Comment by aulemahal** [comment]
I went through the Box 12.1 of the report. Comments on the methods:

A - The most used for AR5, but has a relatively complex computation of the internal variability using 400 years of historical (pre-industrial) simulation. Given that we would have this data, implementation time would be a ~2 hours.
B - Minor modification to A, so would likely be implemented together.
C - Uses the metric _R_ defined by [Knutti and Sedláček (2013)](https://www.nature.com/articles/nclimate1716). Doesn't look to hard to implement but I am really struggling to understand the algorithm. The method section is way to short... 
D - Requires to wrap a t-test, but looks simple for the rest. Implementation time of 2-3 hours.
E - Doesn't _look_  too bad, but the article ([Power et al. (2012)](https://journals.ametsoc.org/jcli/article/25/11/3792/99349/Consensus-on-Twenty-First-Century-Rainfall) has many typos and I'm still unable to understand their algorithm (mainly in the appendix).

In general, all methods except C would output a categorical map with 2-4 categories, the labeling differing from one method to the other. Thresholds could (should) be user-customizable.
