### ISSUE TITLE
Implement KKZ selection algorithm (ensembles.py)

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#499]
### Description
Implement the KKZ selection technique described in https://journals.ametsoc.org/jcli/article/28/3/1260/106748/Selecting-GCM-Scenarios-that-Span-the-Range-of

Similar to cluster selection but gives nested selection results

nb* requested by P. Grenier

**Comment by tlogan2000** [comment]
@aulemahal I did this once in matlab before but not as a function... not really that complicated but we might need to investigate the most appropriate library for calculating normalized n-d distances in python.  `scipy` or `sklearn` will probably be good start ??

**Comment by tlogan2000** [comment]
`cdist` would like work well.  
https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html#scipy.spatial.distance.cdist

**Comment by aulemahal** [comment]
Doesn't look too hard!
I agree with `pdist`, looks like it has the potential metric choice an user could need.
