### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#5]
For each index, I think we'll want a short textual description, a longer explanation including the mathematical formula, an example, and references to papers either defining the indicator or using it.

**Comment by Zeitsperre** [comment]
Would it make sense to use docstrings to an extent? e.g. https://stackoverflow.com/a/24385103/7322852

While the benefits of following reST conventions are lost on Python2, Python3 IDEs can extract type indications from the text and IIRC, we can configure sphinx to extract this info directly to HTML.

**Comment by huard** [comment]
That's the idea. My preference goes to the numpy doc style, which supports references and examples. I find the rest convention really ugly.

**Comment by Zeitsperre** [comment]
According to the Python maintainers, reST is the standard ([PEP 287](https://www.python.org/dev/peps/pep-0287/)) but thankfully, PyCharm has support for all of the docstring types [as mentioned here](https://stackoverflow.com/a/33497841/7322852).

So long as we're consistent, my joy will know no bounds.

**Comment by huard** [comment]
Oh nice ! Good catch. I've created an example for your consideration and critique. Pull the latest from master, build the docs and check out the TG function in the ICCLIM page.

**Comment by Zeitsperre** [comment]
Question: Will we be using ReadTheDocs to put our documentation online? I'm wondering if it makes sense for me to sign-up and allow them read-access to this repo.

**Comment by huard** [comment]
Sure, go ahead.

**Comment by Zeitsperre** [comment]
Docs are now up! https://xclim.readthedocs.io/en/latest/
