### ISSUE TITLE
Most doctests are not written to be tested

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#506]
I'm currently integrating some better doctest handling into the tox builds and have run up against a glaring issue: Many of the documentation examples are reliant on fictional files, for instance in `subset.py`:
```
    Examples
    --------
    >>> import geopandas as gpd
    >>> ds = xarray.open_dataset(path_to_tasmin_file)  # This file doesn't exist --> Failure
    >>> polys = gpd.read_file(path_to_multi_shape_file) # This file doesn't exist --> Failure

    Get a mask from all polygons in the shape file
    >>> mask = create_mask_vectorize(x_dim=ds.lon, y_dim=ds.lat, poly=polys)
    >>> ds = ds.assign_coords(regions=mask)
```
and for the documented examples in `ensembles.py`, they effectively all must be skipped:
```
    Examples
    --------
    Create ensemble dataset
    >>> ens = create_ensemble(temperature_datasets)  # doctest: +SKIP  # This file doesn't exist --> Failure

    Calculate default ensemble percentiles
    >>> ens_percs = ensemble_percentiles(ens)  # doctest: +SKIP # The previous line was skipped so all subsequent lines must be as well
    ...
```
I can skip all the tests that can't be tested for the moment, but unless we add some very small bunk data to the main package or run doctests only when the source files are present (which isn't so much issue for Travis CI or when building from the release source files in `.tar.gz`), most of these tests will need to be skipped.

Wondering if we have any ways of envisioning how we structure doctests. I will link to the PR here once it's been opened, so we can see exactly how many tests are passing/failing.

**Comment by huard** [comment]
@Zeitsperre Status ? If there is no time to do this before the release date, I suggest reverting #507 to reinstate the doctests, even if some were not exercised.

**Comment by huard** [comment]
The issue description mentions "fictional files", but for the record, these are real test files defined in `conftest.py` and injected in the doctest namespace using the pytest fixture `doctest_namespace`. The open question is why are they not recognized by `xdoctest`.

**Comment by Zeitsperre** [comment]
Been working on this today Managed to figure out how best to inject to the `xdoctest_namespace`. Doing my best to catch errors in the doctests, but I may need yours and @aulemahal's help in dealing with them.

Should be able to push a PR this afternoon.
