### ISSUE TITLE
Document Indicator creation and customization

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#516]
With the merge of Indicator class refactoring, need for examples on how to create and customize new Indicator classes arises.
We should explain how a user can create those on-the-fly or in an external package, it could be added to the "customizing and controlling xclim" notebook.

Moreover, the Table of Indicator could be reintegrated to the documentation index and be improved by removing duplicates and adding a bit more info on each indicator + giving a link to the docstring.

**Comment by huard** [comment]
There is already some material here: https://xclim.readthedocs.io/en/stable/api.html#defining-new-indicators

However, there is no mention of multi-output indicators, or the expected frequency of inputs.
