### ISSUE TITLE
Clarification needed on warm_spell_duration_index documentation

### ISSUE THREAD

**Issue by guidocioni** [Ouranosinc/xclim#521]
* xclim version: 0.10.10b0
* Python version: 3.7.6
* Operating System: MacOS

### Description
The documentation on the function `warm_spell_duration_index` is missing some details and (I think) contains some error. 

1. it is stated that `tx90` should be a float, however the function expects a data array (which makes more sense given that the percentile should depend on the day of the year) with time coordinate named `dayofyear`. 
2. It is not clear why the time coordinate of `tx90` shall be named `dayofyear` if the function expects a simple `datetime` object from which it will extract `dt.dayofyear`. I think the naming should be consistent with `tasmax` which contains a `time` coordinate. 
3. It is not explicitly stated how to compute the percentile ('5-day window centred' is misleading) and to me it is not clear why this is not done directly into the function as `tasmax` contains all the necessary input to do so... 

### What I Did
As I had a pandas series of daily 2m Maximum Temperature what I did was 
```python
maxT  = df['Maximum 2m Temp'].to_xarray()
maxT.attrs['units'] = 'degC'
maxT = maxT.rename({'index':'time'})

maxTquant = df['Maximum 2m Temp'].groupby(df.index.dayofyear).transform('quantile', 0.90).to_xarray()
maxTquant.attrs['units'] = 'degC'
maxTquant = maxTquant.rename({'index':'dayofyear'})
```

### What I Received

```python
~/miniconda3/lib/python3.7/site-packages/numpy/core/function_base.py in linspace(start, stop, num, endpoint, retstep, dtype, axis)
    141 
    142     delta = stop - start
--> 143     y = _nx.arange(0, num, dtype=dt).reshape((-1,) + (1,) * ndim(delta))
    144     # In-place multiplication y *= delta/div is faster, but prevents the multiplicant
    145     # from overriding what class is produced, and thus prevents, e.g. use of Quantities,
ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
```

The error is coming from numpy. I'm pretty sure it is cause by some inconsistencies in the data that I'm passing to the function as I did not understand the documentation and probably passed something in the wrong format.

**Comment by huard** [comment]
3. The reason tx90 is not computed over the input array is that the time period might not be the right one. The percentile is usually computed over an historic, user-defined reference period. There is a function in `xclim.core.calendar` called `percentile_doy` that will compute the percentile for each day of the year. 

2. Because the function expects the percentile values to be already computed using `percentile_doy`. 

1. This may be a relic of other percentile-based indices which accept a float as a percentile value (then assumed to be constant throughout the year). Will be fixed. 

Try using `percentile_doy` to compute `tx_90`. You'll see usage examples in the docstrings from other indices such as `tg90p`. 

Thanks for the feedback !

**Comment by Zeitsperre** [comment]
Hi @guidocioni, thanks for the bug report!

Before I look into it though, I notice that the version you're using is a bit old. If you want to upgrade the library to the current version, you'll (hopefully) find fewer bugs in general.

I'm opening a branch `warm_spell_fix` to fix the typing errors. I'll need to investigate further into the other issues you've raised before I can implement the datetime-based accessor method for `.dayofyear`. The main goal is to maintain consistency between indices calculations and not break everything while doing it.

Expect a PR soon.

**Comment by guidocioni** [comment]
Hey guys, as a matter of fact yes I was running an outdated version of many packages. I've took the time to clean up my conda installation and update everything. 
Actually the only real problem within the issue is the 'float' attribute in the documentation. Besides that I was only confused as I didn't see the usage example which is only there for the cold_spell_days function. As stated by @huard there it is clearly explained how to use the `percentile_doy` function before calling the warm spell function. Now it works flawlessly. I would only suggest to copy paste the cold spell example to the warm spell section just to avoid any confusion and make clear that the function expects as input an output from `percentile_doy`.

Keep up the good work!
