### ISSUE TITLE
Clean-up test and doctests datasets

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#525]
I suggest we review and update our test datasets.  The NRCan datasets that we currently use will be unfamiliar to many users, and have a lot of grid points, which slows down testing. 

I suggest we discuss what datasets should be included in the test, doctest and documentation. 
For example, we could use recent CMIP6 simulations.

**Comment by huard** [comment]
@sbiner I suggest we include some of the observational datasets that caused you issues. 

@Zeitsperre We could create a `xclim-data` repository playing the same role as `xarray-data`, then add an `xclim.tutorial` wrapping `xarray.tutorial`. 

@aulemahal Comments ?

**Comment by aulemahal** [comment]
We had the same discussion in #351, where we evaluated the `intake` option. While it did take care of the machinery part, it did not solve the storage.
`xclim-data` seems a good idea indeed. Also the code of  `xarray.tutorial` is super simple, it would be easy to adapt and that solution adds no dependency.
Are there any challenges to creating a data-only repo?  I think I remember from earlier discussions, that we didn't want to do that, but I have no memory why...

**Comment by Zeitsperre** [comment]
> Are there any challenges to creating a data-only repo? I think I remember from earlier discussions, that we didn't want to do that, but I have no memory why...

Interestingly enough, the folks at roocs have done precisely that with our existing data via sub-modules: https://github.com/roocs/xclim-testdata/tree/master. When the source code for one of their projects is cloned, they also pull this testdata repo using `git clone --recursive <link>`. If anything I suggest we use this repo (and maybe add in some data license texts and Apache 2 License stating that this was forked from xclim).

Integrating this into xclim would be extremely simple:
```
cd tests/
git submodule add https://github.com/roocs/xclim-testdata/
git submodule init
```

**Comment by huard** [comment]
+1 for using xclim-testdata, but -1 for the submodule approach. I would use the `xarray.tutorial` access mechanism to simplify access for users.

**Comment by aulemahal** [comment]
After today's discussions, we discussed the following partial fixes:

1 - Create a `xclim-testdata` github repo and use `xr.tutorial.open_dataset` to read data from it.

2 - Using the implementation suggested in #558, create a large dataset with a sample of all kinds of variables used in xclim. Cycle through all indicators (with the registry) and call them with the dataset (all other parameters default).  

Simple as this, it would at least test that the computation works for most indices. Moreover, we will be able to test if attributes are carried on or not.

Bonus 1: A dictionary (json file?) could be created to store expected outputs of these simple calls. 
Bonus 2: The same dict could list different combination of arguments (other than variables) to test a larger set. This would reduce the number of hand-written tests, but might also be less intuitive to work with...

**Comment by tlvu** [comment]
> `xarray.tutorial` access mechanism

@huard
Can I have more details?  Would like to plan https://github.com/Ouranosinc/raven/issues/185.

**Comment by aulemahal** [comment]
@tlvu `xarray.tutorial.open_dataset` is a method that retrieves a dataset (by name) from a git repository and stores it in a hidden folder on the local machine. It has the flexibility to check in the repository before hand, as not to redownload the same things more than once. It also performs a md5 checksum to ensure data integrity, but that's it, nothing much fancier.

Our goal is to put all test data in a Ouranosinc/xclim-testdata repo and pull it on demand when testing or making examples.

**Comment by huard** [comment]
One step toward this would be to wrap `xr.tutorial.open_dataset` inside raven, so we have `raven.tutorial.open_dataset` that connects to `raven-testdata`. As Pascal explained, in the original, files are cached locally. For raven I think we need to be able to get a DAP URL that can be passed to remote services.

**Comment by aulemahal** [comment]
Steps:
[x] - Transfer test data to a seperate repo
[ ] - Replace heavy datasets by smaller ones and adapt tests.

**Comment by huard** [comment]
- [ ] Update doctests, tutorials and notebooks

**Comment by Zeitsperre** [comment]
@aulemahal We good to close this with #620 ?

**Comment by huard** [comment]
Are the files referenced in `conftest/add_example_file_paths` taken from xclim-testdata ?

**Comment by aulemahal** [comment]
@huard Yep. This trick relies on the fixture just above (`add_imports`) where `xr` is mapped to `xclim.testing`, so we can trick the reader when doing `xr.open_dataset`.

@Zeitsperre  We could, but there is the "Update docstests, tutorials and notebooks" check box that is unchecked. I think that to complete the task we want to use `xclim-testdata` everywhere needed in the notebooks (I'm not sure it is the case currently).

**Comment by Zeitsperre** [comment]
> @huard Yep. This trick relies on the fixture just above (`add_imports`) where `xr` is mapped to `xclim.testing`, so we can trick the reader when doing `xr.open_dataset`.

Yes, it's very sneaky at first but very obvious if you take a look at it. Very happy with the `xdoctest` namespace injection approach. 

> @Zeitsperre We could, but there is the "Update docstests, tutorials and notebooks" check box that is unchecked. I think that to complete the task we want to use `xclim-testdata` everywhere needed in the notebooks (I'm not sure it is the case currently).

For `conftest/add_example_file_paths`, everything but the `.json` files map to the right folder on `xclim-testdata`. I can fix this, run the doctests and notebooks and go from there.

**Comment by Zeitsperre** [comment]
Looks as though our `atmos` checks are scrutinizing our test data pretty deeply. This test file:
```
ns["path_to_tas_file"] = str(cmip3 / "tas.sresb1.giss_model_e_r.run1.atm.da.nc")
```
isn't passing our Validation checks any more:
```
xclim.core.utils.ValidationError: Variable has a non-conforming cell_methods. Got `time: mean`, expected `['*time: mean within days*']`
```
And our artificial data needs much more in terms of standards (`cell_methods`, `standard_name`, etc.). The artificial data is easy enough to fix, but since cmip3 data probably doesn't follow modern CF conventions, I may need to replace it in doctests. More to come.
