### ISSUE TITLE
Implement one new bias adjustment method

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#533]
### Description

- [x] Identify a bias correction algorithm that would be useful to add to the `sdba` library 
- [ ] Implement and test
- [ ] Document

**Comment by huard** [comment]
@Paattrriicckk proposes 
*[Multisite bias correction of precipitation data from regiona climate models](https://rmets.onlinelibrary.wiley.com/doi/abs/10.1002/joc.4890)*

**Comment by aulemahal** [comment]
Am going to try and do this before the Dec 4th deadline, unless @huard had already started something?

**Comment by huard** [comment]
Nope. Working on updating finch with xclim 0.21.
