### ISSUE TITLE
slow missing_wmo with stations data

### ISSUE THREAD

**Issue by sbiner** [Ouranosinc/xclim#535]
* xclim version: 0.18.2-beta
* Python version: 3.6
* Operating System: centos version on prod server

### Description
I was trying to use missing_wmo on station data and hit a drastic increase in time when hitting a certain number of stations. The `xr.DataArray` I used has a few coords giving characteristics of each stations.

I had a few exchanges about this problem with @aulemahal about this.

I noticed that the timing was getting to usual values when I got rid of superfluous coords data from the `xr.DataArray` used.

Sorry but the tests have been done on local  machine at ouranos.ca. I tried to reproduce the problem with synthetic netcdf files but it did not work. If I succeed I will update but wanted to report this issue in the meantime.

### What I Did
Here is  an example of code comparing timing for `xclim.core.missing.missing_wmo` using the `xr.DataArray` with and without extra coords.

```
from xclim.core.missing import missing_wmo
import xarray as xr

# load les donnees des stations
ds = xr.open_mfdataset("/path/to/file/sndtot_eccc_daily_*.nc", combine="by_coords", concat_dim="time", data_vars="minimal")

# selection selon la province
dsr = ds.sel(station=ds.Province=='QUEBEC')

# selection selon la periode de donnees valides
#
debut_per = '1980'
fin_per = '2010'
dsr = dsr.sel(time=slice(debut_per, fin_per))

# on extrait la variable sntot
da = dsr.sndtot

# boucle sur differents nombre de stations
l_timing = []
l_timing_noextra = []
l_nb_stat = range(10, 121,10)
for nb_stat in l_nb_stat:

    print(f"traitement de {nb_stat} stations")

    dar = da.isel(station=slice(0, nb_stat))
    # on drop les coords extras
    coords_to_drop = [v for v in dar.coords if v not in dar.dims]
    dar_noextra = dar.drop(coords_to_drop)

    # timing pour dar
    t0 = time.time()
    missing = missing_wmo(dar, freq=FREQ, nm=5, nc=3).load()
    timing = time.time() - t0
    print(f'timing: {timing}')

    # timing pour dar_noextra
    t0 = time.time()
    missing = missing_wmo(dar_noextra, freq=FREQ, nm=5, nc=3).load()
    timing_noextra = time.time() - t0
    print(f'timing_noextra: {timing_noextra}')

    # ajout des timing
    l_timing.append(timing)
    l_timing_noextra.append(timing_noextra)

# on fait la figure
fig = plt.figure()
plt.plot(l_nb_stat, l_timing, label='timing')
plt.plot(l_nb_stat, l_timing_noextra, label='timing_noextra')
plt.legend()
plt.savefig('timing_wmo.png')
plt.show()
```

Here's a view of `dar` and `dar_noextra` for 10 stations. As you can see there is only an extra `station_id` coords between both.

```
In [6]: dar                                                                                                                                                                                           
Out[6]: 
<xarray.DataArray 'sndtot' (station: 10, time: 11323)>
dask.array<getitem, shape=(10, 11323), dtype=float64, chunksize=(10, 3653), chunktype=numpy.ndarray>
Coordinates:
    station_id  (station) object dask.array<chunksize=(10,), meta=np.ndarray>
  * station     (station) int64 4095 4096 4097 4098 4099 ... 4101 4102 4103 4104
  * time        (time) datetime64[ns] 1980-01-01 1980-01-02 ... 2010-12-31
Attributes:
    units:           m
    id:              1010066
    element_number:  013
    standard_name:   surface_snow_thickness
    long_name:       Snow on the Ground

In [7]: dar_noextra                                                                                                                                                                                   
Out[7]: 
<xarray.DataArray 'sndtot' (station: 10, time: 11323)>
dask.array<getitem, shape=(10, 11323), dtype=float64, chunksize=(10, 3653), chunktype=numpy.ndarray>
Coordinates:
  * station  (station) int64 4095 4096 4097 4098 4099 4100 4101 4102 4103 4104
  * time     (time) datetime64[ns] 1980-01-01 1980-01-02 ... 2010-12-31
Attributes:
    units:           m
    id:              1010066
    element_number:  013
    standard_name:   surface_snow_thickness
    long_name:       Snow on the Ground
```

### What I Received

The following output shows an increase of the timing from ~12 _s_ using 90 stations to ~150 _s_ for 100 (and more) stations when using the `xr.DataArray` with all the coords (i.e. `dar`). The timing stays around ~12 _s_ no matter the number of stations when using the `xr.DataArray` without extra coords (i.e. `dar_noextra`)

```
**********************************************************************
2020/08/26 16:29:22
debut de  test_missing_wmo.py
**********************************************************************
traitement de 10 stations
timing: 6.655572891235352
timing_noextra: 6.572109937667847
traitement de 20 stations
timing: 8.748908281326294
timing_noextra: 9.08896517753601
traitement de 30 stations
timing: 7.843413352966309
timing_noextra: 7.722684860229492
traitement de 40 stations
timing: 8.277944326400757
timing_noextra: 8.223512411117554
traitement de 50 stations
timing: 9.306388854980469
timing_noextra: 9.332110404968262
traitement de 60 stations
timing: 10.23855710029602
timing_noextra: 9.573577880859375
traitement de 70 stations
timing: 10.901669979095459
timing_noextra: 10.746152400970459
traitement de 80 stations
timing: 11.703601837158203
timing_noextra: 11.248552322387695
traitement de 90 stations
timing: 12.414949417114258
timing_noextra: 11.784504890441895
traitement de 100 stations
timing: 150.10797500610352
timing_noextra: 12.374486684799194
traitement de 110 stations
timing: 148.51791191101074
timing_noextra: 12.940536737442017
traitement de 120 stations
timing: 148.66783475875854
timing_noextra: 13.68501901626587
traitement de 130 stations
timing: 148.23591351509094
timing_noextra: 13.515788316726685
traitement de 140 stations
timing: 146.6818528175354
timing_noextra: 12.605632781982422
traitement de 150 stations
timing: 145.7523798942566
timing_noextra: 14.297184705734253
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
**********************************************************************
fin normale de  test_missing_wmo.py
temps d'execution : 1160.21 (s)
**********************************************************************
```

**Comment by aulemahal** [comment]
Found it!
The culprit is @tlogan2000 . (not really just entertaining way to tag you)
`MissingWMO` makes use or `run_length.longest_run`. This xclim-made function exists in two flavors : a vectorized "apply_ufunc" call and a fancy dask-proof function. Upon the call of `longest_run` the number of points in the array is computed and if it is under an arbitrary number (9000), the apply_ufunc version if chosen. For larger arrays, the dask-complete version is used. The apply_ufunc is also dask proofed, but I believe requires slightly more memory, thus justifying this switch. But the fancy dask function is much slower for small arrays.

**However**, there is a bug in `run_length.get_npts`. The number of points is computed using the product of the sizes of all _coords_ (except `time`). In this specific case, there is a  `station_id` extra coord. Even if it doesn't participate to the computation, its size is included in the number of points. So, as soon as we reach sqrt(9000) ~ 95 stations, the number of points (station.size * station_id.size) is reached and the dask version is used.  As it is slower, the computation time increases a lot right there...

A first fix would be that `get_npts` uses only the _dimensions_ of the data, not all coords. A second "fix", would be to think in more depth our arbitrary threshold of 9000 points and to benchmark the two versions of the algorithm.

**Comment by tlogan2000** [comment]
This is my fault I guess

**Comment by tlogan2000** [comment]
@aulemahal Pretty sure I did some very elementary benchmarking to get the 9000 value by the way!! but we could definitely revisit this..

**Comment by sbiner** [comment]
super @aulemahal. 

Par contre je vais vérifier pourquoi je n'ai pas résussi à recréer le problème avec mes pseudo-données aux stations pour lesquelles je n'ai pas eu le problème.

Aussi, est-ce que cette explication "fit" avec le fait que tu n'obtenais pas d'augmentation du temps de calcul lorsque tu loadais les coords (il me semble que c'est ce que tu obtenais comme résultats, non?).

**Comment by tlogan2000** [comment]
> pseudo-données aux stations

Si les pseudo données sont généree en mémoire seulement dask ne sera pas utliser du tout (je pense).   c.a.d le dtype de tes données fictives sera float et non 'dask-array' donc le calcul va se faire comme en numpy pure selon moi.

**Comment by aulemahal** [comment]
MWE:
```
import time
import numpy as np
import xarray as xr
from xclim.core.missing import missing_wmo

Nthresh = np.floor(np.sqrt(9000)).astype(int)

for N in [Nthresh - 1, Nthresh, Nthresh + 1]:
    t = xr.cftime_range('2000-01-01', '2019-12-31', freq='D')
    x = np.arange(N)
    fake = xr.DataArray(np.random.random_sample((N,len(t))), dims=('x', 'time'), coords={'x': x, 'time': t})
    x2 = xr.DataArray(x**2, dims=('x',),  coords={'x': x})
    ds = xr.Dataset(data_vars={'fake': fake}, coords={'x2': x2})
    ds['x2'] = ds.x2.chunk({'x': -1})
    
    t0 = time.time()
    missing_wmo(ds.fake, 'MS').load()
    tot = time.time() - t0
    print(f'{N=} : {tot=:.1f}')
```
Output:
```
N=93 : tot=2.3
N=94 : tot=2.3
N=95 : tot=10.9
```
**CQFD**

**Comment by aulemahal** [comment]
En effet, ça change rien que l'array soit en dask ou pas selon mon explication. Par contre, j'ai l'impression que les passe-passes dans le `longest_run` fancy sont légèrement plus lourdes avec dask. Loader les données avant donne un petit avantage.

**Comment by sbiner** [comment]
C'est bon, 

je confirme, j'ai trouvé le problème avec le test utilisant mes données synthétiques, il y a bien une chute de performance. 

En attendant on pourrait peut-être ajouter l'argument `ufunc_1dim` de `run_length` à `missing_wmo`... ou modifier `get_npts` pour ne pas tenir compte des coords superflues. En fait, pourquoi on ne tient pas seulement compte des dimensions en excluant `time`? Pourquoi passer par les coords?

**Comment by tlogan2000** [comment]
> C'est bon,
> 
> je confirme, j'ai trouvé le problème avec le test utilisant mes données synthétiques, il y a bien une chute de performance.
> 
> En attendant on pourrait peut-être ajouter l'argument `ufunc_1dim` de `run_length` à `missing_wmo`... ou modifier `get_npts` pour ne pas tenir compte des coords superflues. En fait, pourquoi on ne tient pas seulement compte des dimensions en excluant `time`? Pourquoi passer par les coords?

I think when I wrote this original bit of code I wasn't 100% understanding the nuances between coords and dims in xarray.   Using dimensions should work I think for most of our application as long as it is applied to dataarray of interest and not complete datasets 

There is a possibility of 4d (or ND) variables (e.g. w/ height dimension)... off the top of my head I would say it should use the same logic for n_pts calculation.  i.e. The 1D_ufunc would have to vectorize each lon, lat, height combination
@aulemahal can you confirm?

**Comment by aulemahal** [comment]
Oui. The number of dimensions of the data doesn't change the logic of computing n_pts as the product of dimension size. However, I believe that dask chunk sizes should be taken into account. A benchmarking should explore that and may be set npts relative to the size of the chunk? We'll see.
For now, I can submit a PR fixing get_npts.
