### ISSUE TITLE
Required units for index computations

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#54]
### Description
To support unit conversion (with ocgis or not), we'll need functions to be able to tell which units they are expecting (a required_units attribute). 

This underlines again the tension between having simple basic index functions, and all the bells and whistles (output metdata, cf-compliance, unit checks) that are necessary to integrate these functions into WPS processes and scientific workflows. 

So far, we've been able to put all this into decorators, but I'm not sure it will scale well.

**Comment by Zeitsperre** [comment]
What about a hidden function that handles these cases? We might not need something on the level of say a full CF-Compliance checker, but maybe we can start fleshing out a function that can either be hidden with the \_\_init\_\_.py and made to decorate a set of base functions called on xarray objects?

**Comment by Zeitsperre** [comment]
Would extending the xarray.DataArray class with a method to examine variable units work?
```
import xarray

class DataArray(xarray.DataArray):
    def _units_handler(self):
        if 'tas' in self.variables:
            # foo
        elif 'pr' in self.variables:
            # bar
        else:
            warn("Units unknown or whatever. Not good!")

**Comment by huard** [comment]
What I mean is that if the function itself is not responsible for unit conversion, then it needs to tell the unit converter what unit it is expecting. So yes, unit conversion could be done inside a DataArray class, but it still needs to know which unit it should convert to.

**Comment by tlogan2000** [comment]
Is a simple subfunction call in each index really that much trouble?  We could put a units checker converter in the utils.py and call it at the beginning of each xclim index

For every index we would have a first line something like:

def max_1day_precipitation_amount(da, freq='YS', skipna=False):

    da = check_and_convert_units(da,expected='mm')


For now there are relatively few conversions needed in the check_and_convert_units function:

- [ ] Kelvin to Celsius for temp

- [ ] mm s-1  (kg m-2 s-1 ) to mm (or perhaps mm d-1 i guess but we assuming a daily time step for now)

**Comment by Zeitsperre** [comment]
You could technically implement this for the time being and refactor/restructure the code later. If it turns out that there are far too many conversions needed, a more generic function/decorator/class method could work.

I'd be cautious bringing in `utils.py` as a dependency as I think this function should be uncallable from userspace, but that's just my inclination.

**Comment by huard** [comment]
MetPy has a function decorator specifying the type of variable that is expected. 
```
@check_units(temperature='[temperature]', speed='[speed]')
def windchill(temperature, speed, face_level_winds=False, mask_undefined=True):
```
It then uses the `pint` package to handle conversions. As far as I can understand, the input array is preprocessed (units are read then the array is wrapped as a pint.Quantity with units), so it can be converted to whatever unit is needed using the to(unit) method. It probably looks like what Trevor suggested above. 

I've implemented a poor man's version in the UnivariateIndicator class I've been working on. Another option is to import their preprocessor and use their decorator.

**Comment by tlogan2000** [comment]
Seems like an interesting option:  The poor man's version of simply using pint seems fairly straight forward... is there a big gain that I'm not seeing to using MetPy's decorator? 

Question for precip : Am i right in thinking MetPy / pint probably won't understand a converison of 'kg s-1 m-2' to 'mm'  ... we'll have to go to in kg d-1 m-2 then manually change units attr to 'mm'6

**Comment by huard** [comment]
This is now handled in the UnivariateIndicator class.
