### ISSUE TITLE
implement check for whitespace in unit parameters 

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#543]
I accidently entered `'deg C'` as the `thresh` value to an xclim.atmos() call.  

Calculations run but give erroneous values.
example:

```
import xarray as xr
from xclim import atmos
import numpy as np
import matplotlib.pyplot as plt

ds = xr.tutorial.open_dataset('air_temperature')
tasmax = ds.air.resample(time='D').max(dim='time',keep_attrs=True)
d1 = atmos.tx_days_above(tasmax, thresh='10 degC', freq='MS')
d2 = atmos.tx_days_above(tasmax, thresh='10 deg C', freq='MS')
plt.figure()
d1.mean(dim=['lat','lon']).plot(label='Correct')
plt.legend()
d2.mean(dim=['lat','lon']).plot(label='Error')
plt.show()
plt.legend()
```
This is clearly a user error on my part but could likely be a pretty common one.  I think it would be good to try to implement some type of check for this.  I'm not sure what the best method would be... i..e doesn't have to be a whitespace check

Not sure if this could affect input parameters than `thresh`

**Comment by aulemahal** [comment]
hum, I don't think pint can help us here... See hgrecco/pint#799.
We could patch all our unit functions to transform "deg C" to "degC", not very elegant, but it would work for that specific case...
Personally, I think this is a responsability of the user, not ours, but I can easily make a PR if we want to go forward.

**Comment by Zeitsperre** [comment]
If it comes down to a vote, I think we should sanitize the whitespace using a decorator, or at the very least raise a UserWarning about it.

**Comment by huard** [comment]
I believe the issue is that deg is interpreted as an angle (dimensionless) and C as a temperature. The `check_units` confirms that the dimension of `deg C` is a temperature. I need to work out why the results are different.

**Comment by aulemahal** [comment]
@huard  Hypothèse: 10 deg C is translated as 10 deg * 1 C, 1 C is 274.15 K, thus, 10 deg C is 2741.5 K.

**Comment by tlogan2000** [comment]
quick check shows that '10degC' and '10 degC' gives the same correct result.  So  whitespace removal decorator might do the trick...  
However, I am not sure what would happen for precip or hydro units....

**Comment by huard** [comment]
```
>>> units.parse_expression("10 deg C").to("K")
47.84820144342454 <Unit('kelvin')>
```
This is interpreted as 10 deg * 1 C and degrees are converted to radians.

**Comment by huard** [comment]
By `pint` default, `C` stands for Coulomb, so this would raise a dimensionality error. We've added an alias for C. I'm not sure there is an elegant way around it. Before removing spaces, I suggest we think about how it could break legitimate code.

**Comment by aulemahal** [comment]
Quick example on the top of my head : `"1 kg s^-1 m^-2"`:
 - With spaces, it translates to `"1 mm/s"`,
 - Without spaces : `UndefinedUnitError: 'kgs' is not defined in the unit registry`.

**Comment by huard** [comment]
Unless someone has a better idea, I suggest we just highlight this *gotcha* somewhere in the docs.

**Comment by Zeitsperre** [comment]
Can we create a set of allowed unit types? Then sanitize them before sending them to pint? The greatest concern is raised from sending the wrong units to indicators/indices, then so long as we aren't overloading/monkeypatching `pint`, we shouldn't have to worry too much about breaking legit code (like another function using pint further down a user's script/analysis).

I agree that this needs to be communicated somewhere.

**Comment by aulemahal** [comment]
If we go this way, I'd rather define a list of _forbidden_ units. A simple list of strings that must not be used, with "deg C" and "deg K" in it, for example.

Or, what you are suggesting could be implemented by simply having our own list of pint units? Instead of reading from the `defaults_en.txt` file that ships with pint, we could copy it and remove everything unrelated to climate science. Removing `deg` would solve this issue, as "deg C" would raise an `UndefinedUnitError`.

**Comment by Zeitsperre** [comment]
> Or, what you are suggesting could be implemented by simply having our own list of pint units?

It's a bit ridiculous to think, but given that our list of units needed for existing indices/indicators is relatively small, we can probably limit ourselves only to climate and hydro units used in our functions.

**Comment by tlogan2000** [comment]
> >>> units.parse_expression("10 deg C").to("K")
> 47.84820144342454 <Unit('kelvin')>

is there not a way to get the units before `.to("K")` here?  We can make sure they are temperature units before moving forward

**Comment by aulemahal** [comment]
Thing is, they are "temperature" units. Since "deg" is dimensionless, "deg C" is "temperature.

**Comment by huard** [comment]
If we restrict the units that can be used, we're limiting extensibility for users. Any function operating on angles (wind, ocean currents) could get crippled by blocking degree units.

**Comment by aulemahal** [comment]
After these discussions I see 3 options:

1) Do nothing in the code. Add a note in the docs.
2) Add a list of forbidden units to `check_units` to catch the most common errors ("deg C" and "deg K"). Clunky, but mostly safe for temperature units, minimal usability breaking.
3) Redefine `deg` to something ridiculous, so that pint raises an error. Ex: `deg = kg * cd * A = [mass][luminous intensity][electric current]`. So there is no way it ever validates the units declared in the decorate, and it will never successfully convert in the indicator. Quite ugly, but also funny.

I vote (1).

**Comment by Zeitsperre** [comment]
@aulemahal You've sold me on (3). 

But yes, I think if anything a note to users about it would be the best option, so (1) is probably the most reasonable approach. It's really a fix in pint that we need, but it seems to be a design decision on their part to not support it for the time being. Maybe things will change down the line.

**Comment by huard** [comment]
Before we do any change, I suggest we ask a question on a pint ML or raise an issue: "How do we check that a `Quantity` has units of temperature, and not angle x temperature?"

**Comment by tlogan2000** [comment]
FYI my initial mistake / discovery was when exploring the holoviz xclim calculator prototype @aulemahal has been working on (see screen capture).  I think we should be able to adjust the panel input so that users enter an `int` and the units will be stripped from the default .  input title could become thresh ({units}) and input accepts simply a number.   Basically I think we can reduce the possibility of user error in the tool itself instead of diving into the xclim code (more involved than anticipated)

![image](https://user-images.githubusercontent.com/22454970/92751229-ca4c7700-f355-11ea-8468-7efc73fc9d94.png)

**Comment by tlogan2000** [comment]
It would still be a good idea to follow up wiht pint devs and / or put the note in the help

**Comment by huard** [comment]
https://github.com/hgrecco/pint/issues/1171
