### ISSUE TITLE
travis-ci flooded by builds

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/xclim#552]
Hi, I would like to discuss the possibility to limit how many things gets built by travis-ci for this repo.

All other repos under `Ouranosinc` are stalled by the massive queue of `xclim` builds generated by various commits and/or forks each time anything is pushed.
Is it possible to improve the `if` rules of the travis config?

example below spans from [build#2280](https://travis-ci.com/github/Ouranosinc/xclim/builds/184271020) upto [build#2295](https://travis-ci.com/github/Ouranosinc/xclim/builds/184281989)  (ie 15 builds of 10+ jobs each, spawned within seconds)

![image](https://user-images.githubusercontent.com/19194484/93139317-812a5900-f6ae-11ea-8094-5d05f84e5847.png)

**Comment by huard** [comment]
@Zeitsperre We can remove the documentation builds since it's now done on RtD. 
Can we run the "Allowed Failures" on releases only ? 
Can linting go with the black, flake8 stuff that does not require installation ? 
The doctests could be run with one of the normal test suites.

**Comment by Zeitsperre** [comment]
@fmigneault @huard 

Yes, absolutely, can clean this up a bit. Those suggestions are pretty great/no-nonsense. I can start on this right now. The one thing I would do differently is run the `allowed_fail` builds on master branch only. I'd like some warning before tagging a release that breaks on Windows/macOS.
