### ISSUE TITLE
from xclim.core.calendar import percentile_doy:ModuleNotFoundError: No module named 'xclim.core'

### ISSUE THREAD

**Issue by sosnku** [Ouranosinc/xclim#554]
* xclim version:0.10.10b0
* Python version:Python 3.8.5
* Operating System:Ubuntu 20.04.1 LTS

### Description
import xclim 
import numpy as np
import xarray as xr
xr.set_options(display_style='html')
from xclim.core.calendar import percentile_doy
from xclim.indices import tx10p

​I trying to import percentile_doy from xclim.core.calendar and I got the error below. How can I fix it

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-25-77e59898f3c4> in <module>
      5 xr.set_options(display_style='html')
      6 
----> 7 from xclim.core.calendar import percentile_doy
      8 from xclim.indices import tx10p
ModuleNotFoundError: No module named 'xclim.core'

**Comment by tlogan2000** [comment]
@sosnku 
It looks like you are using a relatively old version of xclim...  could you try updating to the latetest release 0.19 to see if it solves your issue.

**Comment by Zeitsperre** [comment]
That's what I suspected. We moved much of the internal code around in April/May 2020, so the documentation won't be accurate for versions before then. Be sure to read the release notes in case other changes have happened to functions you use: https://xclim.readthedocs.io/en/latest/history.html

**Comment by sosnku** [comment]
Thanks for your feedback . Tried to update  xclim ( conda install -c conda-forge xclim , tried also with pip) and  the available xclim  0.10.10b0 
here is the message I got  when i tried to update xclim
Requirement already satisfied: heapdict in /home/zenbook/anaconda3/lib/python3.8/site-packages (from zict>=0.1.3->distributed>=2.0; extra == "complete"->dask[complete]->xclim[gis]) (1.0.1)

**Comment by tlogan2000** [comment]
Maybe try `conda update` instead of `install`.  

If all else fails you could try removing xclim before reinstalling
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#removing-packages

**Comment by sosnku** [comment]
Thank you very much @tlogan2000 !, I removed the xclim , reinstalled it using pip and it is now working
