### ISSUE TITLE
Difference between xclim.ICCLIM.TX10p and tx10p functions

### ISSUE THREAD

**Issue by sosnku** [Ouranosinc/xclim#556]
xclim version:0.10.10b0
    Python version:Python 3.8.5
    Operating System:Ubuntu 20.04.1 LTS

Description
Question1: What is the difference between functions example xclim.ICCLIM.TX10p and tx10p. 
Question2: for  percentile_doy(tasmaxref, per=0.1) # here it takes  long time to process; is there anyway I can speed up the process
Question3 : My jupyter notebook kernel keeps crashing at the stage of  performing xclim.ICCLIM.TX10p(tasmaxfut,t10 ,freq='YS')
Reporting issue:
In the  available documentation ( https://xclim.readthedocs.io/en/stable/icclim.html#)  xclim.icclim  is given and this does not work but xclim.ICCLIM does work.
Here is the code 

import xclim
import numpy as np
import xarray as xr
xr.set_options(display_style='html')
from xclim.core.calendar import percentile_doy
from xclim.indices import tx10p
```
#Reading Data reference(tasmaxref )  and future periods(tasmaxfut )
tasmaxref = xr.open_dataset('/media/zenbook/D355-608B/Indices/tasmax_CCCma-CanESM2_baseline_19802010.nc').tasmax
tasmaxfut = xr.open_dataset('/media/zenbook/D355-608B/Indices/tasmax_CCCma-CanESM2_rcp45_20212050.nc').tasmax

#calculate 10th percentile of daily maximum temperature(reference period)
t10 = percentile_doy(tasmaxref, per=0.1) # here it takes  long time to process

#calculate the cold days
xclim.ICCLIM.TX10p(tasmaxfut,t10 ,freq='YS')
Many thanks

**Comment by huard** [comment]
1. Just the name. icclim is a virtual module we created for users of ICCLIM who are familiar with the ICCLIM identifiers. For some indices, xclim uses other names, so `icclim` provides a mapping between xclim and icclim. For example
`"CSU": indices.maximum_consecutive_tx_days`. See https://github.com/Ouranosinc/xclim/blob/1ec2ca8ad90085366ac7dbd2550722ba9692275b/xclim/indicators/__init__.py#L97
2. Chunk the array and use dask client to distribute work across "worker nodes". 
3. Without the traceback, it's hard to diagnose. Please update xclim to the latest version and copy the traceback here. 

The ICCLIM vs icclim naming is a problem we'll fix. I suggest we use lowercase everywhere, but we can maintain the upper case version for backward compatibility.

**Comment by sosnku** [comment]
Thank you very much . The problem solved
