### ISSUE TITLE
Support `dt.datetime` objects in `get_calendar`

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#568]
* xclim version: 0.20

### Description

Would it be possible to support normal datetime objects in `get_calendar` ?

**Comment by aulemahal** [comment]
I'm not sure of the exact use case you are suggesting. Right now, `get_calendar ` takes a xarray Dataset or DataArray as input (`da`) and a dim name (that defaults to "time"). Then, it checks the type of `da[dim]`.
AFAIK, xarray datetime objects do not have other types than `np.datetime64` or one of the `cftime.Datetime`.

Do you mean python's `datetime.datetime`?

**Comment by huard** [comment]
Yes
