### ISSUE TITLE
Implement degree-day depassment date indicator

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#569]
#334 # Description

User interest for a calculation of date when the accumulated sum of degree-days reaches a user provided total.

E.g. the date when one reaches a sum of 100 degree-days (5 degC) starting from jan-01

I would suggest a 'generic' calculation allowing a single algorithm for all degree day types (Heating, cooling, growing etc etc). i.e. User provides parameter on the `op`  (<=, >=) as well as a `sum_threshold` (or similar), as well as all other params typically found in the degree day calculations already present.    

It would be interesting to see if there could be flexibility on whether the calculation is performed on daily tmin, tavg or tmax as well.

edit : Adding note that interested parties indicate that a `after_date` param would be ideal

**Comment by tlogan2000** [comment]
Putting milestone 0.22 for now... we'll see if possibe

**Comment by Zeitsperre** [comment]
@tlogan2000 This would partially satisfy some indice needs present in #355 as well. Nice.

**Comment by tlogan2000** [comment]
> @tlogan2000 This would partially satisfy some indice needs present in #355 as well. Nice.

Yes.  I've seen lots of applications for this... agrcultural, forestry, transportation.  Definitely something that wilke useful for various groups
