### ISSUE TITLE
Refine missing data checks

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#570]
Currently `wmo` missing checks only run on with monthly resampling frequencies (`"MS"` or `"M"`) 
However it should be possible to first identify valid months and then subsequently identify valid periods of coarser frequencies (E.g. QS_DEC or YS) I.e. those that have no invalid months.  

In fact this seems to be what the core calculation is doing in `missing.py`

```
def missing_wmo(da, freq, nm=11, nc=5, src_timestep=None, **indexer):  # noqa: D103
    src_timestep = src_timestep or xr.infer_freq(da.time)
    missing = MissingWMO(da, "M", src_timestep, **indexer)(nm=nm, nc=nc)
    return missing.resample(time=freq).any() 
```

but is then blocked by a if statement within `MissingWMO` class itself (line 264 missing.py)

`        if not freq.startswith("M"):
            raise ValueError `

Furthermore it would seem that this logic of checking monthly values initially then combining for coarser frequencies  would be appropriate for other missing checks as well.  

For example with a percent_missing check on a yearly frequency, a threshold of `0.1` missing data would allow for ~36 days of missing data. This could mean that an entire month of data could be absent but the year would still be considered valid.  

Minimally I think we should allow `wmo` to work on frequencies coarser than monthly, but we may wish to rethink the treatment in general

**Comment by aulemahal** [comment]
Oh! I think we intended the snipping in `missing_wmo` to be applicable to indicators too. We should simply add it to the `execute` class method of `MissingWMO`.

**Comment by tlogan2000** [comment]
> Oh! I think we intended the snipping in `missing_wmo` to be applicable to indicators too, but forgot when coding it. We should simply add it to the `execute` class method of `MissingWMO`.

Yes sorry just to be clear that this is wrt to the implicit checks in the indicator classes e.g. `xclim.atmos`
