### ISSUE TITLE
Upgrade to xarray 0.17 and drop python 3.6

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#592]
Some of our code involving xarray's `apply_ufunc` raise the following warnings:
```
 FutureWarning: ``output_sizes`` should be given in the ``dask_gufunc_kwargs`` parameter. It will be removed as direct parameter in a future version.
```

The change would be quite easy. 

I am not aware of any other future change in xarray that could impact xclim, but those could added to this issue.

**Comment by aulemahal** [comment]
The next xarray version (either 0.16.3 or 0.17) will drop python 3.7. The master branch has dropped it as of pydata/xarray#4720.

**Comment by Zeitsperre** [comment]
> The next xarray version (either 0.16.3 or 0.17) will drop python 3.6.

This will cause some formatting changes and will mean changes across all our xarray-based projects. Might be good to get acquainted with the newer features we can start making use of: https://www.python.org/dev/peps/pep-0537/#features-for-3-7
