### ISSUE TITLE
Agree on a versioning schema

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#6]
As we start adding features and indices, it would be good to use a [semantic versioning](https://semver.org/) (ie: **major.minor.patch-build**) release system where:

**Major** = For the finished product with a stable API (ie: Milestone v1.0)
**Minor** = For additions of modules or maybe changes to indices that likely break API
*Patch* = For bug fixes and fixes to algorithms that break tests
Build =  Either "dev" or "rc" (release-candidate: the version we send up to PyPi)

[Bumpversion](https://github.com/peritus/bumpversion) is a way of managing the version releases almost automatically. @huard have you worked with this tool? AFAIK, the versions are hard coded in the following places:

* setup.cfg
* setup.py
* \_\_init\_\_.py

This shouldn't be too cumbersome to manage. We'll simply need to add the method we agree on to the contributing.rst and bump when needed.

**Comment by huard** [comment]
Nope, but willing to learn bumpversion. Please set it up and provide instructions in the docs, I'll follow them.
