### ISSUE TITLE
Indice Checklist for xclim 1.0 Milestone

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#61]
In reference to [this spreadsheet of ICCLIM indicators](https://docs.google.com/spreadsheets/d/1TRWfgWOmFxft-HsddJPUT-yDM48MLkgs4xQekAIqDRw/edit#gid=18087391) and building off of #1 

**For short term indicator development tracking: [Indicator Development Priorities](https://docs.google.com/spreadsheets/d/1TRWfgWOmFxft-HsddJPUT-yDM48MLkgs4xQekAIqDRw/edit#gid=539742109)**

When a function has satisfied the following parameters, please check them off. An indicator needs:

- To be coded and placed within an appropriate file (indices.py or others);
- With a clear docstring that contains parameters;
- Containing tests (pytests or unittests) that test for desired and undesired behaviour (e.g. negative degree days).

Indicators are as follows:
- [x]  CDD
- [x]  CFD
- [x]  CSDI
- [x]  CSU
- [ ]  CW
- [x]  CWD
- [x]  ETR
- [x]  FD
- [x]  GD4
- [x]  HD17
- [x]  ID
- [x]  R10mm
- [x]  R20mm
- [x]  R75p
- [x]  R75pTOT
- [x]  R95p
- [x]  R95pTOT
- [x]  R99p
- [x]  R99pTOT
- [x]  RR1
- [x]  RX1day
- [x]  RX5day
- [ ]  SD1
- [ ]  SD50cm
- [ ]  SD5cm
- [x]  SDII
- [x]  SU
- [x]  TG10p
- [x]  TG90p
- [x]  TN10p
- [x]  TN90p
- [x]  TNn
- [x]  TNx
- [x]  TR
- [x]  TX10p
- [x]  TX90p
- [x]  TXn
- [x]  TXx
- [x]  vDTR
- [ ]  WD
- [x]  WSDI
- [ ]  WW
- [ ] CD
- [x] DTR
- [x] PRCPTOT
- [ ] SD
- [x] TG
- [x] TN
- [x] TX
- [x] GSL

**Please check the boxes or remove them as progress and priorities shift for xclim 1.0.**

**Comment by bzah** [comment]
Hello,
As discussed with @huard, I would like to implement the following indices :
SD : Snow depth
CD : Cold and dry days
CW: Cold and wet days
WD: Warm and dry days
WW: Warm and wet days

Do you wish to open a new issue or this one is good enough ?

**Comment by tlogan2000** [comment]
@bzah I'll open a new issue...  We aren't really tracking the list of indices in this issue anymore as it was related mainly with a connected project for a website.
