### ISSUE TITLE
Bug: Indicators "TMIN,TEST123,I2D,MINMAXTEMP,CLIM,PRMAX,T_{}" are not translated

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#615]
* xclim version: 0.22.1-beta
* Operating System: FreeBSD

### Description
```
FAILED xclim/testing/tests/test_locales.py::test_xclim_translations[fr] - Failed: Indicators TMIN,TEST123,I2D,MINMAXTEMP,CLIM,PRMAX,T_{} do not have translations for official locale fr.
```

**Comment by aulemahal** [comment]
Wut, is this happening in the branch where tests were moved inside xclim?
The failing tests does not check the indicators when they have a module name starting with something else than "xclim". Moving tests inside xclim will require a new trick to remove them...
El problema esta aqui:
https://github.com/Ouranosinc/xclim/blob/748948b16f157cea23b17f0bcfc22ad88daf87f9/tests/test_locales.py#L145

**Comment by Zeitsperre** [comment]
You are correct, my bad! If you can think of a workaround, feel free to commit to the branch. I can't merge before it's dealt with.
