### ISSUE TITLE
Various improvements for automated parsing of xclim 

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#619]
I am putting here a list of things that we could do on xclim to improve automated parsing of xclim. For context, the two main current use cases are [finch](https://github.com/bird-house/finch/) and [custom_climate_portraits](https://github.com/Ouranosinc/custom_climate_portraits/).

 - [ ] More uniform and general indicator names (ex : not `tropical_nights` but rather `tn_days_above`)
 - [x] Better distinction between input parameter types (unit str vs int vs choice of strings)
 - [x] Related to above : a way for the parser to retrieve the different choices of a param (ex: `op = {'>', '<'}`)
 - [ ] Rewrite abstracts/other metadata when the wrapping changes it (ex: `liquid_precip_accumulation` vs `precip_accumulation`)
 - [ ] Mechanism to add alternative function names
 - [ ] Mechanism to search through indices (free text in abstract, title, function name, keywords, etc)
 - [ ] Have `indicator.json()` return a json-able object.

Feel free to add anything I missed.

**Comment by aulemahal** [comment]
I feel like a lot of these changes would be relatively easy to do, but some of them might be breaking (1st one especially), so we could concentrate them in one release? Or push the more breaking ones to v1.0.

**Comment by huard** [comment]
It's still OK to break things, as long as we have a deprecation mechanism and visibility for breaking changes. 

WRT to tropical_nights, alternative function names should be included in the metadata such that they can be caught by search engines.
