### ISSUE TITLE
start_date parameter clash

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#623]
* xclim version:0.22

### Description

`degree_day_exceedance_date` has a `start_date` argument, and subsetting functions as well from clisops (subset_gridpoint). Finch offers processes that combine subset operations and climate indices, so we end up with two `start_date` argument that mean different things. 

If we want to deploy this indicator in the next Finch release, we need to come up with a solution, for example change the `dded` start_date parameter name.

**Comment by huard** [comment]
@tlogan2000 @aulemahal

**Comment by tlogan2000** [comment]
tricky : 
options quickly off the top of my head
- `first_date`
- 'cumul_start`
-  'cumul_start_date`

**Comment by tlogan2000** [comment]
I am fine with any one I think ... first date is a little funny but sometimes we need a bit of humour in life??

**Comment by tlogan2000** [comment]
`cumul_start` might be the best to avoid any kind of 'date' repeats in the finch call?

**Comment by huard** [comment]
You'd have a `start` repeat anyway.

**Comment by tlogan2000** [comment]
> You'd have a `start` repeat anyway.

I think i'm getting tired

**Comment by tlogan2000** [comment]
Param description in the doc string is 'Date at which to start the cumulative sum'    So I think `cum_start` fits the function in 'isolation' (i.e. xclim only) and should be relatively distinct in the finch call as well ... Anyway that would be my vote.  We can decide before release on friday and merge in as a final change ?

**Comment by aulemahal** [comment]
Under the hood, `start_date` is used as the  `after_date` of `run_length.first_run_after_date`. We could also use that?
Also, for now, I think this is the only xclim indice where that tweak is possible : start the computation at another date than prescribed by `freq`. It's presence could be debatable.

**Comment by tlogan2000** [comment]
@aulemahal Good points but Finch call would end up with 'start_date','end_date',and new 'after_date' params (if I understand correctly) ... still too confusing @huard or ok?

**Comment by aulemahal** [comment]
I see that finch already implements `after_date`:

https://github.com/bird-house/finch/blob/8164c294b8a38febc4b407868bab4a9b737a0614/finch/processes/wps_base.py#L152-L153
