### ISSUE TITLE
Missing functions are not handling statistics 

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#625]
* xclim version: 0.22
* Python version:
* Operating System:

### Description

The `fit` indicator in `land` expects minimally 20 values to not be considered missing and masked. However, the missing functions expect daily or hourly data (src_timestep), and here our individual values can be monthly or yearly max/min, or any stats at any frequency. The result is that the masking function applies a mask with the wrong shape, filled with NaNs. 

So we need to fix the missing function framework to allow for this, and improve the test suite.

**Comment by huard** [comment]
I'm checking if `default_freq` is used anywhere. @aulemahal I'm thinking this `default_freq` function is a hack.

**Comment by aulemahal** [comment]
Same as for #626, I think we could just `missing='skip'` for all "unconventional" indicators.

`default_freq` really feels like a hack indeed. It's only use is for indicators resampling their output but without having a `freq` keyword?

**Comment by huard** [comment]
Closed by #627
