### ISSUE TITLE
Remove freq_analysis indicator

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#626]
* xclim version: 0.22

### Description

The `freq_analysis` function combines three operations: computing max/min stats at a given frequency (yearly, monthly), fitting a distribution to those stats, and then computing quantiles from the fitted distribution. 

The `missing` functionality is only applied to the output. In this case, `missing` should be applied twice: 
- once for the stats computation (how many values per year do we want to compute a max)
- once for the fit (how many values do we need for a fit)

So I think although we can keep `freq_analysis` in `indices.stats`, I suggest we remove it from `indicators.land` for now, and document how to combine the `stats`, `fit` and `parametric_quantiles` indicators into a workflow.

**Comment by huard** [comment]
Another option would be to scrap `missing` operations completely for this indicator.

**Comment by aulemahal** [comment]
The `missing` mechanism was indeed not made for the kind of output of `freq_analysis`... I would go with disabling it on all indicators that do not return a simple resampled timeseries.

**Comment by huard** [comment]
Ok, let's use "skip" for this and leave the indicator.
