### ISSUE TITLE
Issue with percentile_doy

### ISSUE THREAD

**Issue by ChrisDrozdowski** [Ouranosinc/xclim#632]
* Win 8.1 64-bit, Win 10 64-bit
* Python 3.8.3 64-bit
* numpy 1.18.4
* xarray 0.16.2
* dask 2021.1.1
* xclim 0.22.0

### Description
`percent_doy` function throws many warnings during call and takes what seems to be an excessive amount of time (>15 minutes) to run.

NC files for below example are available here: https://code.dented-planet.net/Indices.zip

#### Example code:
```
import xarray as xr
import xclim as xc
from xclim.core.calendar import percentile_doy

ds = xr.open_mfdataset(['tasmin.nc', 'tasmax.nc'])
tas = xc.indices.tas(ds.tasmin, ds.tasmax) 
t10 = percentile_doy(tas, per=0.1)
```
#### Repeated warnings during call:
```
C:\Users\C Drozdowski\AppData\Local\Programs\Python\Python38\lib\site-packages\dask\array\core.py:1428: FutureWarning: The `numpy.nanpercentile` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
```

**Comment by tlogan2000** [comment]
Hello @ChrisDrozdowski thanks for posting the issue. 
Will try to take a look at your file and the `doy` calculation problems ... keep you posted

**Comment by tlogan2000** [comment]
I might have a solution here but will need a bit of testing to be 100% certain

If interested : Our original implementation of `percentile_doy` used an `xr.reduce(np.nanpercentile, )` call.  Changes in dask seem to be the source of the FutureWarning and major slowdown 

However I see that since our original work on `percentile_doy` there is now a  native xarray `quantile()` method that can receive a skip nan  parameter ... seems to work and is not painfully slow

Will validate that calculations are identical to orginal and try to get a fix implemented and into the master relatively quickly

**Comment by tlogan2000** [comment]
@ChrisDrozdowski PR #633 has your test code executing in <2 seconds on my vm ...  Seems more reasonable :)  
(Wasn't patient enough to let finish with the original code so can't give a true comparison)
Thanks again for flagging.

Fix will be merged to master branch in a few minutes

**Comment by Zeitsperre** [comment]
@tlogan2000 @huard Would it make sense to push a new patch release? I can publish one pretty quickly before I end today if we want.

**Comment by aulemahal** [comment]
Makes sense, but let me finish the benchmark! I took the dumb decision of running them on my laptop and its taking forever. But I think I will edit @tlogan2000 's PR with some simpler code.

**Comment by tlogan2000** [comment]
> @tlogan2000 @huard Would it make sense to push a new patch release? I can publish one pretty quickly before I end today if we want.

I agree. if we can get #638 hammered out it will be a much more interesting fix in terms of performance so would wait on the release of a patch  for now

**Comment by huard** [comment]
This is an optimization, not a critical bug. My take is to stick to our release cycle.

**Comment by ChrisDrozdowski** [comment]
Hi developers,
Where does this leave a potential fix for the issue with `percentile_doy`? I don't mean an actual public release, but at least something I can install from git to work with and test. xclim fits so well into my workflow, I'd hate to not be able to use it.

**Comment by aulemahal** [comment]
@ChrisDrozdowski  Right now there is a working fix in the `fix-632_b` branch. It's much faster than the old version but makes some breaking changes for various reasons.

The simplest way to install that version of xclim with pip would be:
```bash
python -m pip install git+https://github.com/Ouranosinc/xclim.git@fix-632_b
```

Warning: Tests are not completed on that code, I might have missed some things.
Breaking changes of this new version (copied from my comment in #638):

 -  I modified the per arg to accept a sequence as well as a scalar. As such, the output has a percentiles axis, which could be a breaking change.
 - I modified `per` to be 0-100 (not 0-1). Which is a breaking change, but is more coherent with (1) our use of the word "percentile", (2) the same argument in ensemble_percentiles.
- The use of the MultiIndex-unstack trick is quite nice, but it requires **daily** datasets (or coarser). The `groupby` method could accept any sampling.

If any of those (especially the last one) are an issue for you, I'll try to find another solution.

**Comment by tlogan2000** [comment]
I think there is a bit of a daily assumption already in the docstring .. for the window parameter docstring `Number of days around each day of the year to include in the calculation`.  But I guess with the old code a 24*5 would work.     More flexibility is good, but i don't find it totally unreasonable that a dayofyear statistics output should receive daily data only...
