### ISSUE TITLE
Explore xr.quantile() performance 

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#635]
> Oh goodness, I responded to the wrong Issue!!!! I am truly sorry. Multitasking never works well for me!
> I meant to respond to the closed "Issue with percentile_doy #632 ". That's the one I'm pushing for a release on.
> Please forgive me.

_Originally posted by @ChrisDrozdowski in https://github.com/Ouranosinc/xclim/issues/631#issuecomment-768607590_

**Comment by tlogan2000** [comment]
@ChrisDrozdowski transferring this thread to a new issue:

We will see what we can do short term.  However, note that I was somewhat overzealous in my ~2sec performance quote when closing #632.   Dask is no longer throwing warnings so the code completes very quickly but as the `mf_dataset` automatically creates dask arrays the actual calculations haven't occurred in the provided example (my mistake).  Adding a `.compute()` at the end results in a ~5-6 min computation on my end.  I suspect `xr.quantile(skipna=True)` is still using the `np.nanpercentile` under the hood which is known to be much slower than the non nan version.   

All that to say I think it could be interesting to spend a bit more time investigating performance on this one before releasing any kind of public patch release.  

In the meantime you could maybe try the current fix via a pip install?

`pip install git+https://github.com/Ouranosinc/xclim.git@master`

**Comment by ChrisDrozdowski** [comment]
@tlogan2000,

I installed 0.23.1b0 last night and saw the speed improvement to `percentile_doy`.

But then, I attempted to use the result of a `percentile_doy` calculation in an indicator and ran into a very long delay (I gave up on it). I was going to report it. But now I see why the delay!

Please let me know if you find any potential fixes or workarounds. Now that I learned that I can install from git, no need for a quick public release.
