### ISSUE TITLE
Using xr.set_options(keep_attrs=True) and Units Parsing Issue

### ISSUE THREAD

**Issue by ChrisDrozdowski** [Ouranosinc/xclim#639]
* xclim version: 0.23.2b0
* Python version: 3.8.3
* Operating System: Win 8.1 and Win10 64-bit 

### Description
Using `xr.set_options(keep_attrs=True)` causes an exception in indicator call(s). See script below. If removed, no exception.

Is this expected and, as far as you know, will removing `xr.set_options(keep_attrs=True)` produce proper results?

Please download this file and put into same folder as script:
https://code.dented-planet.net/pr.nc

```
import xarray as xr
import xclim as xc

xr.set_options(keep_attrs=True)

ds = xr.open_mfdataset(['pr.nc'], engine='netcdf4')
da = xc.atmos.wetdays(ds.pr, thresh='1 mm/day', freq='YS')
```
Result: Exception

**Comment by aulemahal** [comment]
Thanks for pointing this issue! 

Short answer : It is indeed a bug. As `xclim.atmos` takes care of setting all appropriate attributes, you can safely remove `xr.set_options(keep_attrs=True)`, all indicator-related attributes will be set. However,  any other attributes that xclim doesn't know of will *not* be kept. On your example data I see no attribute of `pr` that should be kept, so, at least with this dataset, removing the line is perfectly safe.

Bug explanation : The indice function (here `xc.indices.wetdays`) should explicitly take care of setting the units on its output. Here, with `keep_attrs=True` the precipitation units have been kept even if the data is now `days`. Our decorator would patch the correct unit if it was missing, but it raises an error (as it should) when an _incorrect_ unit is seen. 

We can easily push a bug fix for xclim 0.24, we'll need to see if this happens in other indices as well.
