### ISSUE TITLE
Modify fire weather index calcs to reproduce R library functionality

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#643]
### Description
The official Canadian Forest Service R package for Canadian Forest Fire Danger Rating System (includes FWI) has functionality that differs form our current FWI implementation based on GFWED.  

R package : https://cran.r-project.org/web/packages/cffdrs/index.html
Docs pdf : https://cran.r-project.org/web/packages/cffdrs/cffdrs.pdf

In particular cffdrs FWI allows for:

- [ ]  different temperature thresholds for season startup / shutdown
- [ ]  for 'overwintering' of the drought code 

The first case is likely relatively simple to fix 

The second could be more work we could look into https://cfs.nrcan.gc.ca/pubwarehouse/pdfs/29152.pdf or contact Alan Cantin (contact for R Package)

**Comment by aulemahal** [comment]
I'd add:

 - [ ] use dask now that multiple outputs are supported

**Comment by tlogan2000** [comment]
More info on overwintering DC
https://essd.copernicus.org/articles/12/1823/2020/

**Comment by aulemahal** [comment]
And if not too difficult:
- [ ] Pass "starting_date" as an array, in order to prescribe different season start ups for each grid cells. Requires to rethink the dc0/dcm0/ffmc0 machinery.
