### ISSUE TITLE
Applying warm_spell_duration_index to part of the year

### ISSUE THREAD

**Issue by guidocioni** [Ouranosinc/xclim#646]
* xclim version: 0.23.0
* Python version: 3.8.6
* Operating System: Mac OS 10.15.7

### Description
I'm experiencing some issues while trying to apply some of the indices on a subset of the year. For example I want to compute the periods with warm spell only in winter. To do that I subset the DataArray before only on some months and then apply the indices. This only works half of the time and I cannot really understand why. 

### What I Did
```python
# maxT si the array with daily maximum temperature 

# Computhe percentile over the 1981-2010 period
tx90 = percentile_doy(maxT.sel(time=slice('1981', '2010')), per=.9)

# restrict to only some months 
maxT = maxT.sel(time=maxT.time.dt.month.isin([1, 2, 3, 11]))
# Then select only those days from tx90
days = np.unique(maxT.time.dt.dayofyear.values)
tx90 = tx90.sel(dayofyear=days)

result = warm_spell_duration_index(maxT, tx90, freq='Y', window=6)
```

### What I Received
```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-89-69dfc27d12f3> in <module>
     10 tx90 = tx90.sel(dayofyear=days)
     11 
---> 12 result = warm_spell_duration_index(maxT, tx90, freq='Y', window=6)#.to_pandas().to_frame()
     13 result['year'] = result.index.year.astype(str)
     14 result = result.rename(columns={0: 'warm spell duration'})

<boltons.funcutils.FunctionBuilder-31> in warm_spell_duration_index(tasmax, tx90, window, freq)

~/miniconda3/lib/python3.8/site-packages/xclim/core/units.py in wrapper(*args, **kwargs)
    399                 check_units(val, bound_units.arguments.get(name, None))
    400 
--> 401             out = func(*args, **kwargs)
    402 
    403             def _check_out_units(out, out_units):

~/miniconda3/lib/python3.8/site-packages/xclim/indices/_multivariate.py in warm_spell_duration_index(tasmax, tx90, window, freq)
   1387     """
   1388     # Create time series out of doy values.
-> 1389     thresh = resample_doy(tx90, tasmax)
   1390 
   1391     above = tasmax > thresh

~/miniconda3/lib/python3.8/site-packages/xclim/core/calendar.py in resample_doy(doy, arr)
    550 
    551     # Adjust calendar
--> 552     adoy = adjust_doy_calendar(doy, arr)
    553 
    554     # Create array with arr shape and coords

~/miniconda3/lib/python3.8/site-packages/xclim/core/calendar.py in adjust_doy_calendar(source, target)
    527         return source
    528 
--> 529     return _interpolate_doy_calendar(source, doy_max)
    530 
    531 

~/miniconda3/lib/python3.8/site-packages/xclim/core/calendar.py in _interpolate_doy_calendar(source, doy_max)
    497 
    498     # Interpolate to target dayofyear range
--> 499     tmp.coords["dayofyear"] = np.linspace(start=1, stop=doy_max, num=doy_max_source)
    500 
    501     return tmp.interp(dayofyear=range(1, doy_max + 1))

~/miniconda3/lib/python3.8/site-packages/xarray/core/coordinates.py in __setitem__(self, key, value)
     38 
     39     def __setitem__(self, key: Hashable, value: Any) -> None:
---> 40         self.update({key: value})
     41 
     42     @property

~/miniconda3/lib/python3.8/site-packages/xarray/core/coordinates.py in update(self, other)
    116             [self.variables, other_vars], priority_arg=1, indexes=self.indexes
    117         )
--> 118         self._update_coords(coords, indexes)
    119 
    120     def _merge_raw(self, other):

~/miniconda3/lib/python3.8/site-packages/xarray/core/coordinates.py in _update_coords(self, coords, indexes)
    290         coords_plus_data = coords.copy()
    291         coords_plus_data[_THIS_ARRAY] = self._data.variable
--> 292         dims = calculate_dimensions(coords_plus_data)
    293         if not set(dims) <= set(self.dims):
    294             raise ValueError(

~/miniconda3/lib/python3.8/site-packages/xarray/core/dataset.py in calculate_dimensions(variables)
    204                 last_used[dim] = k
    205             elif dims[dim] != size:
--> 206                 raise ValueError(
    207                     "conflicting sizes for dimension %r: "
    208                     "length %s on %r and length %s on %r"

ValueError: conflicting sizes for dimension 'dayofyear': length 122 on <this-array> and length 335 on 'dayofyear'
```

Weirdly enough if I use the months `[1, 2, 3, 11, 12]` it works just fine.... I cannot really understand why t

**Comment by huard** [comment]
The `_interpolate_doy_calendar` needs the full year to interpolate from one calendar to another. 
https://github.com/Ouranosinc/xclim/blob/cbde866a79670187ca6dc87e52dd1ce8a4a33120/xclim/core/calendar.py#L582
When you include month=12, it sees the last day of the year and is happy. 

Please try without restricting `tx` to some months, that is, pass the full `tx` array.  The `warm_spell_duration_index` should take care of the reindexing by itself.

**Comment by guidocioni** [comment]
> The `_interpolate_doy_calendar` needs the full year to interpolate from one calendar to another.
> https://github.com/Ouranosinc/xclim/blob/cbde866a79670187ca6dc87e52dd1ce8a4a33120/xclim/core/calendar.py#L582
> 
> 
> When you include month=12, it sees the last day of the year and is happy.
> Please try without restricting `tx90` to some months, that is, pass the full `tx90` array. The `warm_spell_duration_index` should take care of the reindexing by itself. Internally, the `resample_doy` function creates a `thresh` array aligned on the day of the year of the `tasmax` array.

Mmmm but then how I can "restrict" the `warm_spell_duration_index`  to only consider the winter season? One way would be to use 'Q-NOV' as aggregation frequency and then drop the not wanted seasons from the results, but this is not ideal.

**Comment by aulemahal** [comment]
Another way would be to "cheat" and put small temperatures in the other months?

Editing your first snippet:
```python
# maxT si the array with daily maximum temperature 

# Computhe percentile over the 1981-2010 period
tx90 = percentile_doy(maxT.sel(time=slice('1981', '2010')), per=.9)

# restrict to only some months (put a very cold temp otherwise)
maxT = maxT.where(maxT.time.dt.month.isin([1, 2, 3, 11]), 0)  # 0 is assuming temp in Kelvins, could be -100 in °C.

result = warm_spell_duration_index(maxT, tx90, freq='AS-NOV', window=6)
```
As you can see, I used `freq='AS-NOV'`. That makes the year start in november. So for each time slice in the output, the data is for the winter season starting on that date. (Otherwise, with `Y`, you get data of  november and january _of the same year_).

Note that dropping december like this might have strange effects : a warm spell starting in Nov 26 and ending in Dec 2 will not be included.

**Comment by huard** [comment]
Does it work if you do
```
maxTwinter = xclim.indices.generic.select_time(maxT, month=[11, 12, 1, 2, 3])
result = warm_spell_duration_index(maxTwinter, tx90, freq='Y', window=6)
```

**Comment by guidocioni** [comment]
> Does it work if you do
> 
> ```
> maxTwinter = xclim.indices.generic.select_time(maxT, month=[11, 12, 1, 2, 3])
> result = warm_spell_duration_index(maxTwinter, tx90, freq='Y', window=6)
> ```

Nope, I get the same error.

**Comment by guidocioni** [comment]
> Another way would be to "cheat" and put small temperatures in the other months?
> 
> Editing your first snippet:
> 
> ```python
> # maxT si the array with daily maximum temperature 
> 
> # Computhe percentile over the 1981-2010 period
> tx90 = percentile_doy(maxT.sel(time=slice('1981', '2010')), per=.9)
> 
> # restrict to only some months (put a very cold temp otherwise)
> maxT = maxT.where(maxT.time.dt.month.isin([1, 2, 3, 11]), 0)  # 0 is assuming temp in Kelvins, could be -100 in °C.
> 
> result = warm_spell_duration_index(maxT, tx90, freq='AS-NOV', window=6)
> ```
> 
> As you can see, I used `freq='AS-NOV'`. That makes the year start in november. So for each time slice in the output, the data is for the winter season starting on that date. (Otherwise, with `Y`, you get data of november and january _of the same year_).
> 
> Note that dropping december like this might have strange effects : a warm spell starting in Nov 26 and ending in Dec 2 will not be included.

Actually this is the solution that I thought of. Without touching the two arrays you can just change the aggregation frequency to consider the season, so AS-NOV as you did, and that from the array only take the winter season. It is possible sure, I thought just that avoiding computing data that I would not use at the end would be better. Also I'm not sure how I would be able to arbitrarily decide the start-end of the aggregation period in this case. 

BTW I only removed December (12) to show the error, in my use case I still wanted to use December to March. 

I was asking mainly because I thought that other people may have to use incomplete timeseries missing some months so I believe the function should not fail if December is missing. 


> The `_interpolate_doy_calendar` needs the full year to interpolate from one calendar to another.
> https://github.com/Ouranosinc/xclim/blob/cbde866a79670187ca6dc87e52dd1ce8a4a33120/xclim/core/calendar.py#L582
> 
> 

I may not understand everything that's going on, so it may be a stupid question, but why you need to interpolate between two different calendars if both DataArrays have dayofyear as time coordinate? Can't you just compare them directly?

**Comment by aulemahal** [comment]
The thing is that different calendars will have a different number of days in a year. This function was implemented so because we had to deal with data from many different models, some having 360 days per year, others 365 and some 366 (or a normal calendar). 
But I understand your point about being capable of passing incomplete data without having to think to much about workarounds. 

@huard could we skip the interpolation in `_interpolate_doy_calendar` if `doy_max_source != source.dayofyear.size` ? I see that as a reasonable compromise...

@guidocioni Also I tested your example without cutting tx90. Ex:
```python3
# maxT si the array with daily maximum temperature 

# Computhe percentile over the 1981-2010 period
tx90 = percentile_doy(maxT.sel(time=slice('1981', '2010')), per=.9)

# restrict to only some months 
maxT = maxT.sel(time=maxT.time.dt.month.isin([1, 2, 3, 11]))
# Skip this step ## Then select only those days from tx90
# days = np.unique(maxT.time.dt.dayofyear.values)
# tx90 = tx90.sel(dayofyear=days)

result = warm_spell_duration_index(maxT, tx90, freq='Y', window=6)
```
And it works, because the `interpolate_doy_calendar` issue is avoided. Trying the fix I just suggested, I ran your example (cutting `tx90`) and it gave me the exact same results on my data. For my small test dataset (4 years on 5 points), my suggestion is even faster, I'm guessing because xarray's internal alignment has it easier. However, I do not expect that to hold with larger datasets.

**Comment by aulemahal** [comment]
Oh and we usually recommend using the `indicators` instead of the `indices`. Our indicator class takes care of more metadata and validation checks. In the case here, that would mean using `xc.atmos.warm_spell_duration_index`  (and not `xc.indices.xxxx`). However, @tlogan2000 @huard , it's not there? haha we forgot to wrap it.
Moreover, your example data would fail the "daily" check which raises the other issue : is our dailiness (?) check too strict?

**Comment by huard** [comment]
Skip calendar interpolation if calendars are  identical: I think this is already the case.
Wrap: yes
Relaxing checks: not convinced, but worth a discussion. Overlaps with missing data checks.

**Comment by guidocioni** [comment]
> @guidocioni Also I tested your example without cutting tx90. Ex:
> 
> ```python
> # maxT si the array with daily maximum temperature 
> 
> # Computhe percentile over the 1981-2010 period
> tx90 = percentile_doy(maxT.sel(time=slice('1981', '2010')), per=.9)
> 
> # restrict to only some months 
> maxT = maxT.sel(time=maxT.time.dt.month.isin([1, 2, 3, 11]))
> # Skip this step ## Then select only those days from tx90
> # days = np.unique(maxT.time.dt.dayofyear.values)
> # tx90 = tx90.sel(dayofyear=days)
> 
> result = warm_spell_duration_index(maxT, tx90, freq='Y', window=6)
> ```
> 
> And it works, because the `interpolate_doy_calendar` issue is avoided. 

Wait wait, does this piece of code works for you? because I get exactly the same error as in the first post :D Now I'm confused

**Comment by guidocioni** [comment]
> @guidocioni Also I tested your example without cutting tx90. Ex:
> 
> ```python
> # maxT si the array with daily maximum temperature 
> 
> # Computhe percentile over the 1981-2010 period
> tx90 = percentile_doy(maxT.sel(time=slice('1981', '2010')), per=.9)
> 
> # restrict to only some months 
> maxT = maxT.sel(time=maxT.time.dt.month.isin([1, 2, 3, 11]))
> # Skip this step ## Then select only those days from tx90
> # days = np.unique(maxT.time.dt.dayofyear.values)
> # tx90 = tx90.sel(dayofyear=days)
> 
> result = warm_spell_duration_index(maxT, tx90, freq='Y', window=6)
> ```
> 

Somehow I had some spurious data in `maxT` and was getting the same error so I was confused. This works and actually should be the preferred way of obtaining what I needed! So we do have a solution, I just didn't notice.Sorry :D

**Comment by aulemahal** [comment]
> Skip calendar interpolation if calendars are identical: I think this is already the case.

Hmm, not what I meant, sorry. 

In `resample_doy`,  its the doy_max that makes it skip interpolation when it is the same on both source and target, not the calendar itself (because we can't infer a calendar only with a daofyear coordinate). In the issue raised here, source and target have the same calendar but differing `doy_max`. 

My proposition is to rethink this line:
https://github.com/Ouranosinc/xclim/blob/cbde866a79670187ca6dc87e52dd1ce8a4a33120/xclim/core/calendar.py#L580
so we can manage the case where dayofyears are missing.

**Comment by huard** [comment]
You're right, got it. 
I suggest opening an issue, but not directing efforts to it immediately.

**Comment by aulemahal** [comment]
As one of the solution seems to have satisfy the need of this issue, I will close it.
The sub-issues raised in the discussion here have been transported to new issues.
