### ISSUE TITLE
Deal with cases where all values in grouping are 0

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#658]
* xclim version:0.24

### Description

`snd_max_doy` returns the day of year with the highest snow depth. If all snow depths are 0, it will return the first day in the grouping. I believe it should return NaN in this case. 

This is not really a missing value operation (values are 0, not missing), nor a datacheck (since we don't want to raise an error, just set NaNs). 

Should we just deal with this inside the indice function, or is there another option ?

**Comment by aulemahal** [comment]
I would say that this is indice dependent? So deal with it in the indice. It's short enough not too need an helper function and it's too simple to justify a new mechanism. At least for now, where it is only used once.
