### ISSUE TITLE
Potential evapotranspiration

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#668]
### Description

- [x] Existing software review
- [x] Select subset of algorithms with low complexity
- [ ] Implementation, testing and documentation.

**Comment by huard** [comment]
Raven has PET algorithms in C++ with good documentation. 

See also: http://python.hydrology-amsterdam.nl/modules/evaplib.py

**Comment by tlogan2000** [comment]
Quebec atlas agroclimatique has a daily ETP calc.  http://www.agrometeo.org/atlas/display_guide/Formules_atlas_agroclim_2019.docx
Baier et Robertson (1965)

**Comment by huard** [comment]
- https://github.com/woodcrafty/PyETo
- https://github.com/monocongo/climate_indices

**Comment by marielabonte** [comment]
Thornthwaite, Hamon, and Hargreaves (temperature based methods), Turc, Makkink, and Priestley-Taylor (radiation based methods):  https://www.srs.fs.usda.gov/pubs/ja/ja_lu004.pdf

Penman-Monteith method: https://edis.ifas.ufl.edu/pdf/AE/AE45900.pdf

**Comment by huard** [comment]
Est-ce qu'on considère qu'on en a assez comme ça ou il y en a d'autres qui s'en viennent ?

**Comment by tlogan2000** [comment]
@huard These 3 are all we will have time to look at / need this summer
