### ISSUE TITLE
CC scaling

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#669]
### Description

Brainstorm on design ideas to apply clausius-clapeyron scaling to indicators, e.g. IDF curves.

**Comment by JeremyFyke** [comment]
As I mentioned a few weeks ago via phone, I'd like to have a go at an initial implementation of this, @huard !

Could you review this proposed workflow before I jump in?

I’ve forked xclim (0.27) to https://github.com/ECCC-CCCS/xclim, and cloned this locally to my workspace.

I’ve created a new, clean, isolated conda Python 3.8 development environment to work on xclim without affecting other (operational) environments.

My naïve plan beyond this is:
1.	activate into new development environment
2.	pip-install the local xclim clone with pip install –e [path-to-xclim-clone]
3.	develop xclim code base (under version control)
4.	to test: 
a.	    re-install xclim clone via pip install –e [path-to-xclim-clone]
b.	    import into test python project, test 
5.	submit pull request to when satisfied

Is this at all similar to the workflow you would suggest/recommend here, especially the 'naive' part?  Also, would you like to me flag this development as ongoing work in any way, on this primary xclim repo?

**Comment by huard** [comment]
Fixed with #748
