### ISSUE TITLE
Bias correction method managing extreme values

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#670]
### Description

Implement bias-correction method dealing with the tail of the distribution. 

Release target: ~july 2021

**Comment by huard** [comment]
See https://github.com/JuliaClimate/ClimateTools.jl/blob/2048f7428b899eddf8efdbadc9e93d3d7ce09518/src/biascorrect.jl#L216 for reference.

**Comment by Balinus** [comment]
N'hésitez pas si vous avez des questions!
