### ISSUE TITLE
L-moments code fails with scipy 1.6

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#684]
### Description
Since the update of scipy 1.6, on December 31st 2020, the `frechet_r` distribution has been definitely renamed "Weibull". It was deprecated since 1.0, but the name "frechet_r" was still accessible. Ironie du sort: `lmoments3` already names it "Weibull", but imports "frechet_r" from scipy. Thus, broken on import and unusable.

So this reopens the "how do we use L-moments" debate...

**Comment by huard** [comment]
https://github.com/OpenHydrology/lmoments3/pull/11

**Comment by aulemahal** [comment]
Good luck!

![](https://media.giphy.com/media/4TvCBG884cugIpLVtf/giphy.gif)

**Comment by huard** [comment]
PR merged, but unclear if the current maintainers have permissions to update PyPi. We may have to install from the git repo.

**Comment by Zeitsperre** [comment]
@huard Do we want to the CI tot test using `lmoments3`? If so, we simply need to add `-lm3` to the calls to `tox` in our workflows: https://github.com/Ouranosinc/xclim/blob/a5ab63daee7d361c698b44c1322222ce41fe7913/.github/workflows/main.yml#L46
