### ISSUE TITLE
sdba - Using Grouper with non-temporal dimensions.

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#687]
The `Grouper` object in `sdba.base` is supposed to help in applying function to groups of data. Most commonly we use it with `time.dayofyear` or `time.month`, applying the training and adjustment to single values of each, but on all years. Compared to xarray's groupby, it adds the possibility to include a "window" in the group, which is quite useful with `time.dayofyear`.

It was made general, so that _any_ dimension name can be passed, not only "time-like" dimensions. For example, we could want to apply the adjustment differently on each week, but also on each weekend. This doesn't exist in xarray, so one would create a new integer array (call it "week_ends_of_year"):  "0" on the first week of the year, "1" on the first week-end, "2" on the second week, and so on. This way a grouping over the 104 (ish) groups could be used. 

But this is currently broken. If one creates `Grouper("week_ends_of_year")` the further call to `apply` will fail in most cases because `week_ends_of_year` is not a dimension, but rather an auxiliary coordinate. A fix is possible, but would take some time and more overhead to work around xarray's internals.

Discussion : My example use here seems a bit weird. Is this functionality even needed? Are there cases where the groups we want to apply the adjustment on are _not_ aready defined by xarray's internals?

Tagging super-users : @RondeauG @kemccusker @dgergel

**Comment by tlogan2000** [comment]
@aulemahal I am completely open to discussion from others but my initial reaction would be to makes some notes on a possible fix (below in the discussion here?) but hold off on implementation until someone raises a 'real-world' need.   I personally can't think of a case where grouping would occur on something other than time but I am not really a bias adjustment power user .
