### ISSUE TITLE
Implement a 'doy_to_days_after' and reverse functionality

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#688]
### Description
Certain indices outputting 'day of year' or `doy` values are not directly usable for ensemble percentiles and statistics due to its circular nature.   

Averaging `doy` results can potentially be handled by users via https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.stats.circmean.html.  However I have not easily found a percentiles option.

The other solution is to  create offset functions allowing units to become a 'days after %mm%dd' or similar which will allow valid ensemble statistics to be calculated..   Final results (mean, percentiles etc) could potentially be restored to original `doy` via a reverse function.

To streamline wps calls in `finch` it would be potentially interesting to have an `units` parameter for the calculation of indicators that currently return to `doy` to output `days_after` instead.  Non exhaustive list of indices include  `degree_day_exceedance`, `first_day_*`, `last_day_*`  

Note I think xarray may interpret 'days_since' as a cftime flag and try to automatically 'help' in certain cases. This is why I suggest a `days_after` unit for now but I am open to debate / validation

 

 

```

**Comment by tlogan2000** [comment]
Starting point from another project:
````
def doy_to_days_since(da, start=None, calendar=None):
    """convert day-of-year data to days since a given date.
    
    If start is None, the elements time coordinate is used a the start date.
    Start must be in the "mm-dd" format.
    
    Calendar is the reference calendar used in computing the doys,
    However, the output has the same calendar as the input.
    """
    calendar = calendar or xc.core.calendar.get_calendar(da)
    dac = xc.core.calendar.convert_calendar(da, calendar)
    
    if start is not None:
        mm, dd = map(int, start.split('-'))
        base = xr.apply_ufunc(
            lambda y: xc.core.calendar.datetime_classes[calendar](y, mm, dd),
            dac.time.dt.year,
            vectorize=True
        )
    else:
        base = dac.time

    offset = (
        base - xr.apply_ufunc(
            lambda y: xc.core.calendar.datetime_classes[calendar](y, 1, 1),
            dac.time.dt.year,
            vectorize=True
        )
    ).dt.days + 1
    
    doy_max =  xr.apply_ufunc(
        lambda y: xc.core.calendar.days_in_year(y, calendar),
        dac.time.dt.year,
        vectorize=True
    )
    out = xr.where(dac >= offset, dac, dac + doy_max) - offset
    out.attrs.update(da.attrs)
    if start is not None:
        out.attrs.update(units='days since {start}')
    else: 
        out.attrs.update(units='days since coordinate')
    
    out.attrs.update(calendar=calendar)
    out['time'] = da.time
    return out
````

**Comment by tlogan2000** [comment]
@aulemahal preference for seeing this in `core.utils` vs `core.calendar`?

**Comment by aulemahal** [comment]
I'd vote for `calender` as well!
