### ISSUE TITLE
sdba - "verbose" mode?

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#698]
As suggested in slack by @dgergel and also discussed this morning with Patrick, it could be interesting to output more than just the training dataset / scenario timeseries. I am thinking of some kind of "verbose" or "debug" mode, where sdba trains and adjusts would provide ancillary "diagnostics" variables to help the user understand what happened.

What would be the implementation? A class/method keyword argument? A new option in `xclim.set_options`?

Non exhaustive list of interesting diagnostics:
- EQM/DQM/QDM
    * `quantiles` : Which quantiles of the traning was used by each element of sim
    * `extrapolated` : Boolean flag True for elements where extrapolation was used
- ExtremeValues
   * `nclusters` : The number of clusters (and extreme values) re-adjusted.
- PrincipalComponents
   * The "best" orientation vector.

**Comment by dgergel** [comment]
@aulemahal thanks for starting this thread! 

I like the idea of having it as a class/method keyword argument - I think that would allow for more flexibility. 

Another category I would add to what you have above would be: Dry Day Frequency Correction, and a useful diagnostic for that might be a boolean mask indicating which values were corrected.
