### ISSUE TITLE
Handling Requirements

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#7]
@huard 

In order to get Travis to install properly, I needed to hard code the requirements in `setup.py`:

https://github.com/Ouranosinc/xclim/blob/6808fd2160413c7b2cbd83c411526043745a910c/setup.py#L17

I'm wondering though if we should try and reimplement the previous model, seeing as the error that likely caused it was that we didn't specify the working directory, like this cookie-cutter templates does:

https://github.com/wdm0006/cookiecutter-pipproject/blob/master/{{Bcookiecutter.app_name}}/setup.py

Having a `requirements.txt` is good for pinning versions of libraries as they're integrated, but having them hard-coded in the `setup.py` prevents us from just putting a ton of packages in there with `pip freeze -r requirements.txt` and running into an "everything plus the kitchen sink" scenario.

Thoughts?

**Comment by huard** [comment]
I'm hoping that we'll be able to keep the list of requirements on the low side. That does not preclude us from using a requirements file though. I suggest we keep it as is for the moment and switch to an external file as the need arises.
