### ISSUE TITLE
Reimplement "wet startup" in FWI

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#700]
Last FWI PR (#664) removed some "wet startup" code for DC and DMC because it wasn't covered in the cffdrs R package. It appears that this switch is however quite commonly used in the field, so it makes most sense to have it in xclim. 

Furthermore, there is a small bug in the standalone `overwintering_drought_code`. `output_core_dims` should be `[[]]` and not `[[]] * 5`. And it is missing a test.

Ref ECCC-CCCS/CanLEAD-FWI#6 (see comments at the end).

**Comment by JeremyFyke** [comment]
Hi @aulemahal - what is status of 'cffdrs-compliant' FWI xclim code (including the fixes described within this Issue), and is this code yet available in an official xclim release?  Thanks!  (cc @EPDiaconescu)

**Comment by aulemahal** [comment]
Hi!
I think most of the changes are ready, in branch `fix-fwi-wDC-wDC`, PR #704.

I was waiting to see if you guys could test this version and waiting to have some time for writing up a notebook about it. I'm not sure I have access to the same data that you use for testing, so couldn't run a complete comparison. But, the current version in the PR imitates GFWED within 3% when the proper parameters are passed and CFFDRS-compliance has not been changed, except for this dry/wet startup thing.

**Comment by JeremyFyke** [comment]
Ah, OK thanks.  Laura, our primary 'tester', is no longer with us at CCCS (although returning in Sept).  So it's unlikely we have capacity to do another round of dedicated testing on our end for you.  If you are happy with the testing on your end, perhaps best to move ahead to a merge without waiting for comments from us.  Once this is done, do you have a sense of when this would become available via, e.g., pip?

**Comment by aulemahal** [comment]
Oh I see! Well, as it works well for the other tests, I can merge this soon. Our next release is due at the end of May, is that good for you?

**Comment by JeremyFyke** [comment]
Sounds perfect.  If we need it sooner I can grab it directly from Github master, if I'm not mistaken.   (cc @EPDiaconescu)
