### ISSUE TITLE
Can we build xclim indicators out of MetPy indices ?

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#703]
### Description

I'm wondering how difficult it would be to use MetPy meteorological indices as input to xclim indicators. 

MetPy has an extensive library of indices https://unidata.github.io/MetPy/latest/api/generated/metpy.calc.html#module-metpy.calc

**Comment by aulemahal** [comment]
Doesn't look impossible! There might be ways to make it "automatic", but I think we'd be better to start semi-manual, implementing indices individually.
I see no support for dask. If we want laziness, we'll have to wrap the indices ourselves.

If this works well, it could open new possibilities and the same could be done with https://github.com/TEOS-10/GSW-Python.

But I would prefer not adding those as hard dependencies, even reimplementing most wanted indices if needed.
