### ISSUE TITLE
sdba - Moving window for adjustments

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#712]
It could be interesting to have a "moving window" feature for sdba's adjustments.

Here I mean that a long timeseries would be bias-adjusted on sections of X-years at a time. The goal and use of this is that for any given point of sim, the correction was done using the same number of points in ref/hist and sim. For example, in QuantileDeltaMapping, if the length of ref/hist and sim is different, the statistical properties of the result are not the same (Cannon goes over this real quick in the paper). Similarly, with ExtremeValues.

This is not a _real_ moving window, because the steps are full years.

Implementation idea:  A function that takes the input timeseries and cuts it into those X-year (overlapping) sections. For each section, the time axis is normalised (ex: `section[i].time = section[0].time`). We stitch everyting back along a "year" dimension and adjust.

A second function takes the result and rebuilds the full timeseries. I'm less certain here. Which value do we take?

This was discussed with @dgergel and recently with @RondeauG (because it appears in @Balinus's extreme values correction). The latter julia code could be used as an inspiration also.

**Comment by dgergel** [comment]
@aulemahal we are already doing this in our bias correction and downscaling pipeline! We're using an argo workflow to fan out future years, and we're bias correcting in rolling slices of 21 years, with a +/- 10-yr window. We have a combined implementation of this in our pipeline and with an argo workflow - happy to direct you to those if that would be helpful. @brews can also describe it more detail since he was the person who worked on this more closely. For reference, our pipeline implementation is [here ](https://github.com/ClimateImpactLab/dodola/blob/main/dodola/core.py) (see the `train_quantiledeltamapping` and `adjust_quantiledeltamapping_year`). We don't have the argo workflow .yaml up yet but Brewster can provide more info on that.

**Comment by Balinus** [comment]
There is indeed an "moving window" when the timeserie that we want to correct is longer than the reference period by 50%. @RondeauG can chime in here as he's the architect of the algo. The idea was to estimate GPD parameters as we progress in the timeseries.
https://github.com/JuliaClimate/ClimateTools.jl/blob/5dde47186bd160c80ae1795db31ce6fff7b601df/src/biascorrect.jl#L281

The index for the moving window is calculated here : https://github.com/JuliaClimate/ClimateTools.jl/blob/5dde47186bd160c80ae1795db31ce6fff7b601df/src/biascorrect.jl#L325
https://github.com/JuliaClimate/ClimateTools.jl/blob/5dde47186bd160c80ae1795db31ce6fff7b601df/src/biascorrect.jl#L464

The function creates windows where the statistics are calculated and the bias correction is applied over a shorter window.

The current function is unnecessarily complicated though and I'm sure there are other solutions. Probably by using https://github.com/JeffreySarnoff/RollingFunctions.jl

**Comment by RondeauG** [comment]
> There is indeed an "moving window" when the timeserie that we want to correct is longer than the reference period by 50%. @RondeauG can chime in here as he's the architect of the algo. The idea was to estimate GPD parameters as we progress in the timeseries.
> https://github.com/JuliaClimate/ClimateTools.jl/blob/5dde47186bd160c80ae1795db31ce6fff7b601df/src/biascorrect.jl#L281
> 

Indeed, this was a necessary step for ExtremeValues in the absence of time-dependant GPD parameters to take into account future possible changes in frequency and intensity. I also agree with @Balinus that the current implementation is probably unnecessarily complicated, and not ideal for computation efficiency. I would be happy to contribute to the discussions.
