### ISSUE TITLE
Threshold-based indicators could use more generalised names 

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#714]
There are more than a few indicators that I would like to use with such drastically different thresholds that the meaning of their names is rendered obsolete. 

For example, computing `tropical_nights` with a threshold of 10 degC is hardly "tropical". A more generalized version would be to have `tropical_nights` with a specific, literature-based threshold value and a `tn_days_above` (with indicator mapping).

It would be great to have a discussion about this as it would potentially be a breaking change (assuming we remove existing mappings). Perhaps once we can put together a list of potential candidates for generalization.

### Generalisable indices (WIP)

- [x]  `tropical_nights` → `tn_days_above` (#715)
- [x] `daily_freezthaw_cycles` → `multiday_temperature_swing` (with `window=1, op="count"`) (#717)
- [x] `ice_days` → `tx_days_below`
- [x] `frost-days` → `tn_days_below`
...

**Comment by tlogan2000** [comment]
I agree (especially for the case of tropical nights).   Not sure if we should keep both the specific `tropical_nights`  and the general `tn_days_above` indicators.   

Possibility of building Yaml custom modules can now provide these "common name" indices  for those that prefer this nomenclature etc.  Basically I would lean towards simply renaming `tropical_nights` to a general `tn_days_above`  and let users customize based on preference via the yml customization

**Comment by huard** [comment]
Note that having dedicated specialized functions has the advantage of allowing us to add custom documentation with references and examples. I agree its code duplication, but it can be useful nonetheless.
