### ISSUE TITLE
Make xclim more FAIR

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#721]
Possibly add 
- richer software metadata (see https://codemeta.github.io/)
- citation information (see https://citation-file-format.github.io/)

### References
- https://www.sciencedirect.com/science/article/pii/S2666389921000362?via%3Dihub
- https://content.iospress.com/articles/data-science/ds190026

**Comment by Zeitsperre** [comment]
>     * richer software metadata (see https://codemeta.github.io/)

We seem to be checking all the boxes listed here (GJ us!): https://codemeta.github.io/crosswalk/python/

>     * citation information (see https://citation-file-format.github.io/)

I've done a bit of reading for this, and I'm not sure if it's worth the effort to actually do this. We already provide this information automatically (though I'm unsure how author order is determined) via Zenodo (https://doi.org/10.5281/zenodo.2795043). Versioning a CFF file with every release might be cumbersome (we can't parse the Zenodo citation for this info until we tag a release -- chicken and the egg problem). I still like this idea in principle, but implementing it in a way that is portable (to other projects in our software ecosystem) and easy-to-maintain seems like a hassle. Thoughts?

**Comment by Balinus** [comment]
As far as I remember, authors in Zenodo is somewhat based on commits. Note that even small commit counts.

**Comment by huard** [comment]
I agree that the CFF seems to replicate information already in the .zenodo.json file. +1 for dropping it. 

We can hard-code authors in the .zenodo.json file.
