### ISSUE TITLE
Var names of land processes broken (and untested)

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#728]
* xclim version: master

PR #716 introduced some formatting for "op" arguments (min, max, etc). I didn't realize, but the `var_name` of `freq_analysis` and `stats` both use the "op" placeholder. Thus, var names are now changed. I noticed it while updating finch. For example there the output variable `q1maxsummer` became `q1maximalsummer`, which broke the tests.

Solutions:
- Revert those changes.
- Add a special "raw" _modifier_ which doesn't modify the input. For example, using "r", the `var_name` would change from `"q{window}{mode}{indexer}"` to `"q{window}{mode:r}{indexer}"`.

I prefer the second one. @huard?

**Comment by huard** [comment]
You're not going to like this, but I feel it would be best to do the opposite. That is, having a format modifier that instructs xclim to expand the expression (e.g. `:P` for pretty print or something like that).

**Comment by aulemahal** [comment]
Oh! Haha, It's already the case, where no modifier is implicit for `:adj` (adjective). Changing so that no modifier means "raw", would require many changes. For example, the change above would become: `"q{window}{mode}{indexer:adj}"`. All the  `"{freq}"` would become `"{freq:adj}"`. (But we could change `adj` and `noun` for `a ` and `n`)

Right now we have the most common case by default. This would change the behaviour with a xclim-specific feature for `freq`, `indexer` and `op`.

**Comment by huard** [comment]
It's the most common, but it's weird that you need an option to instruct xclim to not do something (and I'm responsible for that...)

@tlogan2000 Executive decision ?

**Comment by tlogan2000** [comment]
I'm reading through quickly and might not completely grasp everything ...  

Question : what would be some example varnames with different options?  Gut feeling is to keep nc file varnames short and have the pretty / expanded test in the `long_name` and `description`.  I think this means that I would go with the 'raw' modifier as Pascal suggests

**Comment by aulemahal** [comment]
Currently, I think only the example above and one other very similar case have "expandable" placeholders in the `var_name` field (they both have `mode` and `indexer`, so no matter the solution they would change). However, many `description` and `long_name` have a `{freq}` and a few others `{indexer}` or `{op}`.

**Comment by tlogan2000** [comment]
I think I can live with a little bit of 'weird' xclim behavior for these relatively rare cases vs a major overall  ...

**Comment by tlogan2000** [comment]
Basically if the `raw` modifier is doable in a relatively short amount of time I would go with that
