### ISSUE TITLE
Feature request: Add a way to bootstrap the calculation of percentiles

### ISSUE THREAD

**Issue by bzah** [Ouranosinc/xclim#732]
This feature request is based on the information available in "Avoiding Inhomogeneity in Percentile-Based Indices of Temperature Extremes" _Zhang et.al_ ([doi]( https://doi.org/10.1175/JCLI3366.1))

Xclim already provides multiple indices/indicators based on a percentile comparison such as _atmos.tg90p_.
However, if we want to calculate the percentiles on a specific period (base period) and then use these percentiles for comparison in the whole studied period (in base + out of base) we cannot rely on the current implementation.

In short, using directly the percentiles computed for the base period would introduce an artificial discontinuity at the edges of this base period.
The paper above explains in details the issue.

To fix this, Zhang et.al suggest a bootstrapping algorithm which iterates over the base period in order to construct a computation context similar to the rest of the calculation.
For a base period of _x_  years, it iterates over theses years and create an in-base of _x-1_  years and an out of base period of a single year. Then it calculates the exceedance rate of the out of base year using the percentiles of the in-base period.
This is the approach implemented by [icclim](https://github.com/cerfacs-globc/icclim) and [RClimDex](https://github.com/ECCC-CDAS/RClimDex/search?q=bootstrap).

**I'm willing to work on this issue.**
However, I will need help to see how can this be included in the existing code base, especially regarding the API.

**Comment by bzah** [comment]
So[ I made a branch](https://github.com/bzah/xclim/commits/feature/bootstrapping) with a working bootstrapping algorithm.
For now I chose to work on a separated module (boostrapping.py) for simplicity.
@huard suggested that this algorithm could go in _indices/stats.py_. I would advocate to have this in a separated file to ease readability, but the choice is yours.

Regarding the API, _boostrapping.py_ exposes a "public" method `compute_bootstrapped_exceedance_rate`.
This methods handles the whole bootstrapping process without concern of the variables it is working on.
I believe it can be included into the current API by adding a flag parameter to the "bootstrapables" indicators which, when true, will redirect the processing into _boostrapping.py. 
[I made a commit](https://github.com/bzah/xclim/commit/b8e32aeb2ca23d27d937bdfb3d150255d92399e7) to illustrate, more or less, this integration possibility.

The main issue with that idea is that the current percentile indicators expect the percentile thresholds as an input.
Take Tx90p for example.
`def tx90p(
    tasmax: xarray.DataArray, t90: xarray.DataArray, freq: str = "YS"
) -> xarray.DataArray:` 
`t90` parameter is the thresholds in a DataArray.
However, when the bootstrapping is wanted, `t90` would be useless because the percentile calculation **must** be performed within the bootstrapping algorithm itself (that's the whole point).

Hence, I'm not sure how the bootstrapping could be included without uglifying the current API.

Any thought on that ?

As a side note, I still have to add unit tests, as soon as I understand how to run them.

**Comment by huard** [comment]
I just quickly scanned the reference, and wanted to respond before leaving in vacation, so please pardon any misunderstanding on my part. 

Do you think it would be possible to have a mechanism where the "indices" function is an argument to the bootstrap algorithm? That is, instead of specifying the `operator` , you'd specify a generic function? I'm trying to see if we could use a decorator to run the bootstrapping part automatically if the percentile object is some kind of bootstrap array. 

What I mean is that we could do:
```
tn10 = percentile_doy(tasmin, per=10, bootstrap=True).sel(percentile=10)
# tn10 is a special bootstrap object with extra config attributes (in_base, percentile, window, etc)
cold_spell_duration_index(tasmin, tn10)
```

and
```
@percentile_bootstrap
def cold_spell_duration_index(tasmin, tn10):
   ... 
```

where `percentile_bootstrap` would be responsible for detecting that `tn10` is a `bootstrap` object and repeatedly calling the `cold_spell_duration_index` function on the in-base bootstrap samples before averaging. 

Does that make sense ?

**Comment by bzah** [comment]
Yeah it could be done quite easily either by replacing `comparator` by a `exceedance_function: Daily` in the `BootstrapConfig` class. It could look like : 
```
config = BootstrapConfig(
        percentile=90,
        ...
        exceedance_function=xc.atmos.tx90p
    )
```

However in your proposition, I find it confusing to have percentile_doy: 
- Do nothing but returning a bootstrap config object when `bootstrap=True` is passed. 
- Have two completely different objects possibly returned (a percentile DataArray or a bootstrap configuration)
I understand that it aims to minimize the api changes but in the long run I believe it reduce the readability to not separate concerns.

Would it be ok to do the following ? 
```
config = bootstrapping.BootstrapConfig(
        percentile=90,
        window=5,
        in_base_slice=slice("2015-01-01", "2024-12-31"),
    )
result = cold_spell_duration_index(tasmin, tn10, config)
```
and then use @percentile_bootstrap to handle the config parameter ?

**Comment by aulemahal** [comment]
Hi! Thanks for this feature!

Would you mind opening a PR, leaving it in "draft" mode if you prefer, so we can discuss code sections more specifically?

Do I understand correctly that the bootstrapping is only done for indice calculations on the reference period? For all other years, the computation is the same as we previously have done it?

I think I would prefer if we could avoid introducing a new type of input for _Indicators_. The list of currently "implemented" types (or "kinds") is here : https://xclim.readthedocs.io/en/stable/api.html#xclim.core.utils.InputKind. But I realize this would increase the number of arguments incredibly...

I like the decorator idea, but I also suggest we go in the direction of #714 : scrap all those repeating indices and implement only the basic exceedance functions, and this.

@bzah You might not be familiar with xclim internals, but we divide things in 2 parts : the computational _indices_ and the Indicators which carry the metadata. Up to recently, the relation between those was 1-to-1, but with xclim growing it doesn't make sense anymore. A goal of #714 is to merge those indices that do the same thing, simply creating multiple indicators that call the same indice while injecting some parameters. I can help on that part, I think your code as it is currently would work well with what I am suggesting.

**Comment by bzah** [comment]
Hi @aulemahal , I made the draft PR,

You are right about the reference period. I would just add that compare to the current version, the only different thing happening on the out of base period, is that we take the percentiles of the in base period for comparison, instead of percentiles of the whole studied period.

Oopsi, I added an InputKind for bootstrap configuration. However I don't really understand how we can avoid that. 
Even if we split the configuration object into multiple parameters, we would still have to add these in InputKind, shouldn't we ?

In the refactoring of #714, will you merge together indices which are compared to arbitrary thresholds and those compared to percentiles thresholds ? Because the bootstrapping only makes sense for the later.
For example, will SU (Tº > 25ºC) and T90p (Tº > 90th percentile) be merged in one ?
If you don't intent to merge them, I think it will be sufficient to decorate the percentile based indices to make bootstrapping available for theses.

About the indices vs indicators, I'm beginning to understand what is going on. I specifically added @percentile_bootstrap to the indices and not the indicators because in the iteration process I wanted to avoid the checks done on indicators.
I too believe it will work fine because new indicators will not have to be decorated, if they require a "bootstrappable" indice, they will automatically benefit from it.

Thanks for your help :)

**Comment by aulemahal** [comment]
The more I think of it, it makes more sense to have a "bootstrap" object "kind" then 6-7 of them. I believe all types were present, but that would have required to split slices in two bounds and so on...

The refactoring will only merge the function which share the same algorithm. The goal is that `indices` become what we meant them to be : computational elements + unit handling. 

I'll take a deeper look at the PR and comment some things soon!
