### ISSUE TITLE
Corn heat units returns array of with zeros

### ISSUE THREAD

**Issue by MorningGlory747** [Ouranosinc/xclim#741]
* xclim version: 0.27
* Python version: 3.9
* Operating System: Windows 10

### Description

I am trying to get corn heat units from my data. Although no error message appears, The output array is filled with zeros, but it is expected to have numerical values above 0. Some warning messages also appear (see further down).

### What I Did

I am currently working with DAYMET v4 1km daily weather grid. The description of the array is the following :

```
import xclim
import xarray as xr
daymet_ds = open_dataset('"C:\\temp\\DAYMET_temperature_fields.nc")
print(ds)

<xarray.Dataset>
Dimensions:                  (time: 4017, x: 45, y: 46)
Coordinates:
  * time                     (time) datetime64[ns] 2010-01-01 ... 2020-12-30
  * y                        (y) float32 617.0 616.0 615.0 ... 574.0 573.0 572.0
  * x                        (x) float32 1.876e+03 1.877e+03 ... 1.92e+03
Data variables:
    lat                      (time, y, x) float32 45.59 45.58 ... 45.06 45.06
    lambert_conformal_conic  (time) float64 -3.277e+04 -3.277e+04 ... -3.277e+04
    lon                      (time, y, x) float32 -74.41 -74.4 ... -74.04 -74.03
    tmax                     (time, y, x) float32 -2.07 -2.09 ... 4.49 4.39
    tmin                     (time, y, x) float32 -5.23 -5.24 ... -8.25 -8.32
    tmean                    (time, y, x) float32 -3.65 -3.665 ... -1.88 -1.965
Attributes:
    start_year:          2010
    source:              Daymet Software Version 4.0
    Version_software:    Daymet Software Version 4.0
    Version_data:        Daymet Data Version 4.0
    Conventions:         CF-1.6
    citation:            Please see http://daymet.ornl.gov/ for current Dayme...
    references:          Please see http://daymet.ornl.gov/ for current infor...
    History:             Translated to CF-1.0 Conventions by Netcdf-Java CDM ...
    geospatial_lat_min:  45.049526726382624
    geospatial_lat_max:  45.59192101970437
    geospatial_lon_min:  -74.59920972670209
    geospatial_lon_max:  -73.83904281088773

```

The variables of interest are tmin and tmax. The structure is the following :
```
print(ds.tmin)

Out[56]: 
<xarray.DataArray 'tmin' (time: 4017, y: 46, x: 45)>
array([[[ -5.23,  -5.24,  -5.27, ...,  -5.75,  -5.74,  -5.7 ],
        [ -5.25,  -5.26,  -5.28, ...,  -5.71,  -5.7 ,  -5.69],
        [ -5.27,  -5.31,  -5.31, ...,  -5.65,  -5.65,  -5.66],
        ...,
        [ -9.1 ,  -9.04,  -8.94, ...,  -8.11,  -8.2 ,  -8.24],
        [ -9.03,  -8.99,  -8.92, ...,  -8.14,  -8.2 ,  -8.27],
        [ -8.99,  -8.92,  -8.88, ...,  -8.18,  -8.25,  -8.32]]],
      dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 2010-01-01 2010-01-02 ... 2020-12-30
  * y        (y) float32 617.0 616.0 615.0 614.0 ... 575.0 574.0 573.0 572.0
  * x        (x) float32 1.876e+03 1.877e+03 1.878e+03 ... 1.919e+03 1.92e+03
Attributes:
    long_name:     daily minimum temperature
    units:         degrees C
    grid_mapping:  lambert_conformal_conic
    cell_methods:  area: mean time: minimum
    _ChunkSizes:   [   1 1000 1000]
```
### What I Received
The computation for CHU and the output is the following
```
utm = xclim.atmos.corn_heat_units(tasmin = ds.tmin,tasmax = ds.tmax)
print(utm)

C:\Users\sebastien durocher\PycharmProjects\Weather_Data_39\lib\site-packages\xclim\core\cfchecks.py:40: UserWarning: Variable has a non-conforming cell_methods. Got `area: mean time: minimum`, expected `['time: minimum*']`
  check_valid(
C:\Users\sebastien durocher\PycharmProjects\Weather_Data_39\lib\site-packages\xclim\core\cfchecks.py:44: UserWarning: Variable does not have a `standard_name` attribute.
  check_valid(var, "standard_name", data["standard_name"])
C:\Users\sebastien durocher\PycharmProjects\Weather_Data_39\lib\site-packages\xclim\core\cfchecks.py:40: UserWarning: Variable has a non-conforming cell_methods. Got `area: mean time: maximum`, expected `['time: maximum*']`
  check_valid(

<xarray.DataArray 'corn_heat_units' (time: 4017, y: 46, x: 45)>
array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 2010-01-01 2010-01-02 ... 2020-12-30
  * y        (y) float32 617.0 616.0 615.0 614.0 ... 575.0 574.0 573.0 572.0
  * x        (x) float32 1.876e+03 1.877e+03 1.878e+03 ... 1.919e+03 1.92e+03
Attributes:
    units:          
    cell_methods:   tasmin: area: mean time: minimum tasmax: area: mean time:...
    xclim_history:  tasmin: \ntasmax: \n[2021-06-10 14:57:47] corn_heat_units...
    long_name:      Corn heat units (tmin > 4.44 degc and tmax > 10 degc).
    description:    Temperature-based index used to estimate the development ...
```

Small specificiation, Daymet daily outputs are at time 12:00:00. This seems to be a problem for ```xarray.infer_freq``` that outputs False when asked if its daily. My quick fix to this problem was to do a ```ds.resample(time='D').mean(keep_attrs=True)```. Because the ds is already daily, this daily mean didn't have any (noticeable) impact on the values, but maybe it had an impact on the ds?

**Comment by Zeitsperre** [comment]
> Small specificiation, Daymet daily outputs are at time 12:00:00. This seems to be a problem for `xarray.infer_freq` that outputs False when asked if its daily. My quick fix to this problem was to do a `ds.resample(time='D').mean(keep_attrs=True)`. Because the ds is already daily, this daily mean didn't have any (noticeable) impact on the values, but maybe it had an impact on the ds?

Good call on that treatment. That is precisely the approach one should use to deal with the time signatures. It should have at least modified the `datetime` signatures to read as "days since".

For the rest, could you provide the geographic region you were examining? I can try performing a similar operation using the Daymet data I have on hand.

**Comment by aulemahal** [comment]
Hi @MorningGlory747, I think your problem arises from the units of the data. In your example it says "degrees C", which is not one of the accepted versions of "°C" that xclim (through pint and its translations of cf units) supports. Sadly, that string translates to "degrees * delta_degree_Celsius" in xclim which has dimension [temperature] (degrees is dimensionless) and is thus convertible to "°C". That's why you receive no error or warning...

Because pint sees "C" as "delta_degree_Celsius", it translates them as if they were Kelvins, so `1` in your data becomes `-272.15 °C`...

I believe this is part because of #608, which was made to accept units like "degC days" (degree days). I'm not sure how we could have both a support for these and a support for `degrees C`... Sorry!

**Comment by MorningGlory747** [comment]
Hi, it looks like it was an issue with the units after all. Putting it to 'degC' worked. Embarassing that I didn't notice that beforehand. Thank you!

**Comment by aulemahal** [comment]
Even if `degree C` is not one of the (numerous) official ways to write `°C`, I agree that this silent error in pint/xclim is not very intuitive! Happy that you could fix your problem!
