### ISSUE TITLE
Issue with dtype after conversion to netcdf

### ISSUE THREAD

**Issue by bzah** [Ouranosinc/xclim#749]
* xclim version: 0.27.3-beta
* Python version: Python 3.8.5
* Operating System: Mac OS

### Description
When converting a xclim indices to netcdf using DataArray::to_netcdf method, the dtype is changed from float64 to timedelta64[ns].

### How to reproduce
```
ds = xr.open_dataset("climpact.sampledata.gridded.1991-2010.nc")
t90 = percentile_doy(ds.tmax, window=5, per=90).sel(percentiles=90)
result = xc.atmos.tx90p(
    tasmax=ds.tmax,
    t90=t90,
    freq="MS"
)
print(result.dtype)
# prints float64

result.to_netcdf("result.nc")
new_ds = xr.open_dataset("result.nc")

print(new_ds.tx90p.dtype)
# prints timedelta64[ns]
```

I found this out when trying to compare xclim results with icclim and climpact.
I don't really know what could modify the dtype, it may be an issue within xarray or even in netcdf library.

**Comment by huard** [comment]
See https://github.com/Ouranosinc/xclim/issues/89

**Comment by bzah** [comment]
Oups, I forgot to check the existing issues first...
Thanks for your quick reply !
