### ISSUE TITLE
sdba - Is OOP really necessary?

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#754]
I am implementing Cannon's MBCn adjustment and I am confronted to an adjustment object that can not follow the train-adjust scheme : it needs to do both in a single step. Furthermore, I have part of the adjustment that could be performed by an object that doesn't need a train step. This adds to the `ExtremeValues` adjustment object that is re-implementing the `train` and `adjust` method (so like 95% of its base class...).

I think I have painted myself in a corner with this OOP structure that is `BaseAdjustment`. Internally, we still need objects, to remember parameters and to have common methods (like the json parsing stuff).

I am suggesting to move to 2 types of objects (or more if needed):

- Classic Adjustment following the train-adjust scheme, but `train` would become a _class_ method returning an instance that can perform adjustments.
- No-train adjustments : with a single `adjust` _static_ method. No object is ever returned even if the code uses one internally. This is for methods where the training is not separable from the adjust, or where there is enormous computational efficiency to be gained when doing both together.

All current algorithms would loose need for an `__init__`, at least from the point of view of the user. This will divide the kwargs in 2 categories (as it is now, except for `ExtremeValues`). So, for most cases this is merely a merge between the init and the train step, but I think it will ease my implementing and will go in the direction of Patrick's advice : Do no implement "published methods", but provide the modular tools to replicate those.

Example, using `NPDFTransfer` which is part of the MBCn process.
```python
from xclim.sdba import QuantileDeltaMapping, NPDFTransfer

## Before: 
QDM = QuantileDeltaMapping(n_quantiles=10, kind='+', group='time.dayofyear')
QDM.train(ref, hist)
scen = QDM.adjust(sim, interp='linear')

NPDFT = NPDFTransfer() # No params really
# This step doesn't really need both and the training data has the same shape as either, so it's not efficient
NPDFT.train(ref, hist)
scen = NPDFT.adjust(sim)

## After
QDM = QuantileDeltaMapping.train(ref, hist, n_quantiles=10, kind='+', group='time.dayofyear')
scen = QDM.adjust(sim, interp='linear')

scen = NPDFT.adjust(ref, sim)
```

What do our power users @RondeauG  @dgergel and @huard think?

**Comment by huard** [comment]
No objection.

**Comment by dgergel** [comment]
Also have no objection - I think this all sounds good.
