### ISSUE TITLE
Unable to import xclim in conda environment

### ISSUE THREAD

**Issue by Balinus** [Ouranosinc/xclim#755]
* xclim version: 0.27.0
* Python version: 3.8.10
* Operating System:
```julia
Platform Info:
  OS: Linux (x86_64-redhat-linux)
  CPU: Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

### Description
Created an environment with Conda and installed xarray, cartopy and xclim.

### What I Did
```
# bash
$ conda create --name xclim_test python=3.8
$ conda activate xclim_test
$ conda install pip xclim xarray cartopy

# python
>>> import xclim as xc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/xclim/__init__.py", line 17, in <module>
    build_indicator_module_from_yaml(f, mode="raise")
  File "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/xclim/core/indicator.py", line 1252, in build_indicator_module_from_yaml
    yml = safe_load(f)
  File "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/yaml/__init__.py", line 112, in load
    loader = Loader(stream)
  File "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/yaml/reader.py", line 169, in update
    self.check_printable(data)
  File "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/yaml/reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0097: special characters are not allowed
  in "/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/xclim/data/icclim.yml", position 2033
```

I am attaching the yml env file, hoping it helps in the investigation (yml file inside the zipped file).

Thanks!
[xclim_env.zip](https://github.com/Ouranosinc/xclim/files/6704129/xclim_env.zip)

**Comment by aulemahal** [comment]
This problem is really strange! I can't replicate it on any of my machines (all linux 64-bit). I also can't find the "x0097" character in the icclim.yml file....

Can you try to reinstall xclim? With pip? 

Also, could you send here the file: `/gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/xclim/data/icclim.yml` ? The error make it look like it is different from the one on github...

**Comment by Zeitsperre** [comment]
This makes me wonder if your environment supports UTF-8 characters...

**Comment by aulemahal** [comment]
> This makes me wonder if your environment supports UTF-8 characters...

That might be it! The 2033th character of `icclim.yml` is "◦" (which doesn't translate to 0x0097, but rather 25e6 in hex and 9702 in dec. well). The full line reads: `long_name: Summer days (TX>25◦C)`.

@Balinus  What is the result of:
```python
import sys
sys.maxunicode
```
?

Anyway, ◦ is "White bullet"  and not °, "Degree Sign", which should be accepted by most machines (maybe @Balinus you could try is your python understands `"\u00B0"`?). Sorry, that was copy-pasta from the ECAD docs on my part, I didn't realize the character was wrong!

**Comment by Balinus** [comment]
The problem was indeed utf-8!

For reference, here's my previous locale default configuration

```bash
(xclim_test) [dl2594@login-9-1 ~]$ locale
LANG=fr_CA.utf8
LC_CTYPE="en_US.iso885915"
LC_NUMERIC="en_US.iso885915"
LC_TIME="en_US.iso885915"
LC_COLLATE="en_US.iso885915"
LC_MONETARY="en_US.iso885915"
LC_MESSAGES="en_US.iso885915"
LC_PAPER="en_US.iso885915"
LC_NAME="en_US.iso885915"
LC_ADDRESS="en_US.iso885915"
LC_TELEPHONE="en_US.iso885915"
LC_MEASUREMENT="en_US.iso885915"
LC_IDENTIFICATION="en_US.iso885915"
```

Here's the new one (changed every setting... probably overkill!): 

```bash
LANG=fr_CA.utf8
LC_CTYPE="fr_CA.utf8"
LC_NUMERIC="fr_CA.utf8"
LC_TIME="fr_CA.utf8"
LC_COLLATE="fr_CA.utf8"
LC_MONETARY="fr_CA.utf8"
LC_MESSAGES="fr_CA.utf8"
LC_PAPER="fr_CA.utf8"
LC_NAME="fr_CA.utf8"
LC_ADDRESS="fr_CA.utf8"
LC_TELEPHONE="fr_CA.utf8"
LC_MEASUREMENT="fr_CA.utf8"
LC_IDENTIFICATION="fr_CA.utf8"
LC_ALL=fr_CA.utf8

```

**Comment by aulemahal** [comment]
Re-opening because we still need to fix the wrong degree signs in the yamls.

But happy you were able to workaround it on your side!

**Comment by Balinus** [comment]
Do you still need the /gpfs/groups/gc086/DL2495/s2s_conda/lib/python3.8/site-packages/xclim/data/icclim.yml file?

**Comment by aulemahal** [comment]
No, thanks! We'll change the "white circle" to "degree sign" in the current file and test with "en_US.iso885915" for good measure.
