### ISSUE TITLE
Support for GRIB files

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#77]
### Description

Make sure xclim indices work with grib files. 
The main issue is probably the install process of dependencies required for xarray to support grib (pynio). I've played a bit and it seems the conda-forge version is not compatible with the libraries installed in the default conda channel. My understanding is that we need to specify conda-forge as the default channel to get it to work. 

That probably means adding an environment.yml file to xclim. 

See http://tech.weatherforce.org/blog/multicore-grib-processing-xarray/index.html for an example.

**Comment by aulemahal** [comment]
This sounds out-of-scope for xclim. Closed for the time being, feel free to reopen if needed. @huard
