### ISSUE TITLE
Calculating r95p and r99p

### ISSUE THREAD

**Issue by GeoFelpave** [Ouranosinc/xclim#770]
* xclim version: 0.27.0
* Python version: 3.8 - running in Jupyter
* Operating System: Linux

### Description
I am trying to calculate the r95p and r99p using xclim.indicators.icclim.R99p.

### What I Did

```
xc.indicators.icclim.R95pTOT(dataset_ERA.tp, freq='YS')

```

where:

* dataset_ERA.tp has the precipitation values

### What I Received
```
NotImplementedError: Source of type `<class 'NoneType'>` is not supported.
```

### What I tried
```
xc.indicators.icclim.R95pTOT(dataset_ERA.tp, dataset_ERA.tp, freq='YS')
```

And I do get an output. However, I am not sure what I will need to add the precipitation data twice. I checked the docs and it shows: 
per (str or DataArray) – Daily 99th percentile of wet day precipitation flux. Default : ds.per. [Required units : [precipitation]]

However, it isn't clear what the input really is. What does the doc mean by ds.per? I am meant to get a percentage before calculating the index

Thanks.

**Comment by huard** [comment]
Whenever you see `per` in the argument list, it stands for a percentile. It can be computed using `DataArray.quantile`, or `xclim.core.calendar.percentile_doy` if you want a percentile that varies with the day of the year. In this case, my understanding is that you'd do
```
p95 = xc.core.calendar.percentile_doy(dataset_ERA.tp, per=95)
xc.indicators.icclim.R95pTOT(dataset_ERA.tp, per=p95, freq='YS')
```

**Comment by GeoFelpave** [comment]
Many thanks for the prompt response and clarifying how the percentage should be calculated using xclim, it is much appreciated. 

I have now been able to find the r95p and r99p.

**Comment by huard** [comment]
Excellent, cheers.

**Comment by guo066600** [comment]
> xc.indicators.icclim.R95pTOT

If I want to use these two line codes (p95 = xc.core.calendar.percentile_doy(dataset_ERA.tp, per=95)
xc.indicators.icclim.R95pTOT(dataset_ERA.tp, per=p95, freq='YS')), how should I import the required package or function? Many thanks

**Comment by guo066600** [comment]
> What have you tried ? Did you try `import xclim as xc` ?

Yes
