### ISSUE TITLE
Hawkins-Sutton calculations and graphic

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#771]
Implement function to create data structure to generate the classic Hawkins-Sutton graphic of relative uncertainty contributions from GHG scenario, model and natural variability. 

- [ ] Lit review
- [ ] Create a test dataset
- [ ] Decide on structure of output data
- [ ] Code the compute function
- [ ] Code the graphic function
- [ ] Tests
- [ ] Documentation
- [ ] Example notebook

# Literature Review

- [Partitioning climate projection uncertainty with multiple large ensembles and CMIP5/6](https://doi.org/10.5194/esd-11-491-2020)
- [A Simple, coherent framework for partitioning uncer- tainty in climate predictions](https://doi.org/10.1175/2011JCLI4085.1)
- [The potential to narrow uncertainty in projections of regional precipitation change](https://doi.org/10.1007/s00382-010-0810-6)
- [The potential to narrow uncertainty in regional climate predictions](https://doi.org/10.1175/2009BAMS2607.1)

**Comment by aulemahal** [comment]
Interesting! 
Are we talking about the graphs and data of figure 5 in : https://journals.ametsoc.org/view/journals/bams/90/8/2009bams2607_1.xml?tab_body=pdf ?
Do you have other examples of the use of these?
