### ISSUE TITLE
Indicator for maximum snow water equivalent

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#776]
Ideally return values would include date at which event occurs.

**Comment by aulemahal** [comment]
In CMIP6 there is now "swe", so I assume the best option would be "snw": 
swe is the thickness of the water equivalent of the snow on the ground, in m,
snw is the snow amount in kg/m². So simply swe * 1000.

I suggest implementing `snw_max_doy`, which would be almost the same as `snd_max_doy`.
