### ISSUE TITLE
Percentile threshold indices : Frequencies?

### ISSUE THREAD

**Issue by tlogan2000** [Ouranosinc/xclim#79]
For indices such as 'R95p' (with the following definition taken from icclim)
-  Days with RR > 95th percentile of daily amounts (very wet days)
(days)

- Let RRwj be the daily precipitation amount at wet day w (RR ≥ 1.0 mm)
of period j and let RRwn95 be the 95th percentile of precipitation at wet
days in the 1961–1990 period. Then counted is the number of days where:

- RRwj > RRwn95

Does the definition of RRwn95 (the percentile threshold value calculated from the reference period) change with the frequency? i.e if the R95p resampling value is seasonal does the RRwn95 value get calculated seasonally? or is the percentile threshold always annual?  ICCLIM docs are unclear on thisI

**Comment by Balinus** [comment]
From https://cran.r-project.org/web/packages/climdex.pcic/climdex.pcic.pdf

And guess that TX90p is similar to R95p in essence.
```
This function computes the climdex index TX90p.
Computation of these values outside of the base period involves comparing the temperature data for
each day with the corresponding percentiles for a 5 day running window surrounding that day. The
resulting monthly series is then the monthly percentage of values that meet the criteria.
```

**Comment by tlogan2000** [comment]
A few more details here: http://etccdi.pacificclimate.org/list_27_indices.shtml
precipitation percentile descriptions make no mention of 5-day windows ... I have a feeling that for precipitation it may be annual, while temp  uses the windowing.  James Hiebert from PCIC should be able to confirm but is on leave.

**Comment by tlogan2000** [comment]
from https://github.com/pacificclimate/climdex.pcic/blob/master/R/climdex.r
only temp percentiles uses the 'running.qtile' function so I believe the :  But my R knowledge is limited ... can anyone confirm?.

code block:

get.temp.var.quantiles <- function(filled.data, date.series, bs.date.series, qtiles, bs.date.range, n, in.base=FALSE, min.base.data.fraction.present=0.1) {
  base.data <- create.filled.series(filled.data, date.series, bs.date.series)
  if(in.base)
    return(list(outbase=zhang.running.qtile(base.data, dates.base=bs.date.series, qtiles=qtiles, bootstrap.range=bs.date.range, n=n, min.fraction.present=min.base.data.fraction.present),
                inbase=zhang.running.qtile(base.data, dates.base=bs.date.series, qtiles=qtiles, bootstrap.range=bs.date.range, n=n, get.bootstrap.data=TRUE, min.fraction.present=min.base.data.fraction.present)))
  else
    return(list(outbase=zhang.running.qtile(base.data, dates.base=bs.date.series, qtiles=qtiles, bootstrap.range=bs.date.range, n=n, min.fraction.present=min.base.data.fraction.present)))
}

get.prec.var.quantiles <- function(filled.prec, date.series, bs.date.range, qtiles=c(0.95, 0.99)) {
  wet.days <- !(is.na(filled.prec) | filled.prec < 1)
  inset <- date.series >= bs.date.range[1] & date.series <= bs.date.range[2] & !is.na(filled.prec) & wet.days
  pq <- quantile(filled.prec[inset], qtiles, type=8)
  names(pq) <- paste("q", qtiles * 100, sep="")
  return(pq)
}

**Comment by Balinus** [comment]
En effet, ça semble être sur une base annuelle.
