### ISSUE TITLE
unpin pandas<1.3

### ISSUE THREAD

**Issue by raybellwaves** [Ouranosinc/xclim#794]
* xclim version: 0.28.1
* Python version: 3.9.6
* Operating System: Mac

### Description

I bumped my conda environment today and I realised my pandas version got downgraded. From running `mamba repoquery whoneeds pandas` I noticed it's pinned to <1.3
https://github.com/Ouranosinc/xclim/blob/master/setup.py#L26
in this repo.

I had a quick look in the issue tracker and couldn't find any issues on this so wanted to raise this here. There may be good reason why it's pinned. Happy to help work on unpinning it if it's desired.

**Comment by raybellwaves** [comment]
found a PR related to this: https://github.com/Ouranosinc/xclim/pull/763

**Comment by raybellwaves** [comment]
`pytest --nbval docs/notebooks` passed with latest pandas
`pytest --rootdir=xclim/testing/tests --xdoctest xcli` gives one failure 

```
FAILED xclim/testing/tests/core/calendar.py::time_bnds:0
```

**Comment by aulemahal** [comment]
Hi @raybellwaves ! Indeed, I am not sure the pandas pin is still necessary. 
The error you spotted is due to an update of cftime, and I am surprised it didn't show up elsewhere before... I'll try to unpin and fix that in a PR soon.

**Comment by aulemahal** [comment]
For the info : The pandas failure was fixed in xarray 0.19, which came out a month ago. (https://github.com/pydata/xarray/pull/5359)
