### ISSUE TITLE
add testing deps to environment file

### ISSUE THREAD

**Issue by raybellwaves** [Ouranosinc/xclim#795]
When looking at https://xclim.readthedocs.io/en/latest/contributing.html#get-started there's a number of steps i.e.

 - install environment (`xclim`)
 - install testing deps (`pytest`, `black`, ...) (https://github.com/Ouranosinc/xclim/blob/master/requirements_dev.txt)

The testing deps could be added to the same file (https://github.com/Ouranosinc/xclim/blob/master/environment.yml) i.e. similar to https://github.com/pydata/xarray/blob/main/ci/requirements/environment.yml

**Comment by Zeitsperre** [comment]
Closed with #798
