### ISSUE TITLE
Indicators for OPG

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#8]
Check box when indices are coded, include a docstring and are accompanied by unit tests. 

Indicator | Description | Units | Done
-- | -- | -- | --
Heat wave index | Days that are part of a heat wave (5 or more consecutive days with Tmax > 25°C) | # of days / year | <ul><li> [x] </li></ul>
Cold spell index | Days that are part of a cold spell (5 or more consecutive days with Tavg < -10°C) | # of days / year | <ul><li> [x] </li></ul>
Freeze/thaw cycles | days when Tmax >0°C and Tmin < 0°C | # of days / year | <ul><li> [x] </li></ul>
Very hot days | Days when Tmax > 30°C | # of days / year | <ul><li> [x] </li></ul>
Cooling degree days | Air conditioning indicator: number of degrees a given day’s Tavg is >18°C | Sum of degree days / year | <ul><li> [x] </li></ul>
Heating degree days | Heating indicator: number of degrees a given day’s Tavgis <18°C | Sum of degree days / year | <ul><li> [x] </li></ul>
Freshet start | First day of year that is followed by >5 consecutive days each having Tavg > 0°C | Day of year | <ul><li> [x] </li></ul>
Winter rain | Ratio of rainfall to total precipitation during December/January/February(rainfall assumed when Tavg > 0°C) | ratio | <ul><li> [x] </li></ul>
Possible rain-on-snow events | Days with rainfall that followed 7 or more days of Tavg< 0°C    (rainfall assumed when Tavg > 0°C) | # of days / year | <ul><li> [x] </li></ul>
Maximum 3-day spring precipitation | Maximum 3-day total precipitation during spring (March-May) | mm | <ul><li> [ ] </li></ul>
Mean Monthly Temperature | Mean monthly temperature | °C | <ul><li> [x] </li></ul>
Max Monthly Temperature | Max monthly temperature (daily max of month) | °C | <ul><li> [x] </li></ul>
Min Monthly Temperature | Min monthly temperature (daily min of month) | °C | <ul><li> [x] </li></ul>
Total Monthly Precipitation | Sum of all precipitation during a month | mm | <ul><li> [x] </li></ul>
Frost Days | Number of days with Tmin <0°C | Days | <ul><li> [x] </li></ul>
Consecutive dry days | Maximum number of consecutive days with precip < 1mm | Days | <ul><li> [x] </li></ul>
Heavy precipitation days index | Number of days when precipitation >10mm | Days | <ul><li> [ ] </li></ul>
Heavy precipitation days | Number of days when precipitation >20mm | days | <ul><li> [ ] </li></ul>
Monthly Temperature variability | Standard deviation of monthly temperature (over e.g 30-year period) | °C | <ul><li> [ ] </li></ul>
Monthly Precipitation variability | Coefficient of variation of monthly precipitation (over e.g. 30-year period) | - | <ul><li> [ ] </li></ul>

**Comment by Zeitsperre** [comment]
@huard 

I've copied-pasted this table into the GitHub wiki (https://github.com/Ouranosinc/xclim/wiki/Indicator-List). To be revised as we continue to develop, I suppose.

**Comment by huard** [comment]
We can close this one when #90 is merged. The remaining indices can be obtained by existing indices.

**Comment by Zeitsperre** [comment]
Cool. Closing now!
