### ISSUE TITLE
Add heat index calculation

### ISSUE THREAD

**Issue by raquel-ucl** [Ouranosinc/xclim#807]
We have some code to calculate the heat index (i.e. how the human body perceives temperature, which combines relative humidity with air temperature) that we can also add to the list of indices. It uses [this formula](https://en.wikipedia.org/wiki/Heat_index#Formula).

Original code by @clairbarnes

**Comment by Zeitsperre** [comment]
This looks to be fairly simple to implement. Nice suggestion!

**Comment by raquel-ucl** [comment]
I have the code, just haven't pushed it yet :) We were wondering if the right place to put it is [this](https://github.com/Ouranosinc/xclim/blob/master/xclim/indicators/atmos/_temperature.py).

**Comment by huard** [comment]
I think it would go into `_conversion.py`. See the `humidex` index for a closely related index.

**Comment by Zeitsperre** [comment]
@raquel-ucl We are aiming to tag a release of xclim in the coming days. I just wanted to ping you to see if this is something that could be easily integrated before the end of the week. If no, not a problem; We can aim for the following release.

Thanks!

**Comment by clairbarnes** [comment]
@Zeitsperre Raquel is out of the office for the next couple of weeks, so let's aim for the next release. Thanks for checking!

**Comment by Zeitsperre** [comment]
Hey there @clairbarnes and @raquel-ucl, just a reminder notification!

**Comment by raquel-ucl** [comment]
Hi, we'll be working on this again this week, so hopefully we can get all the remaining indices calculations submitted in the next few weeks and make it to 1.0. Watch this space!

**Comment by raquel-ucl** [comment]
I've looked into `humindex` and it is quite different from our `heat_index` calculation in that ours is just looking into what days are considered hot (default is > 20°C). Wouldn't it fit better `_threshold.py` instead? I've made an initial attempt in #915.
