### ISSUE TITLE
Possible modification to PRCPTOT

### ISSUE THREAD

**Issue by GeoFelpave** [Ouranosinc/xclim#812]
* xclim version: 0.27.0
* Python version: 3.8 - running in Jupyter
* Operating System: Linux

### Description
I would like to suggest a modification to the ```xclim.indicators.atmos.precip_accumulation()``` function for PRCPTOT

Currently the function does not match the definition of PRCPTOT given by the ETCCDI for annual precipitation and extreme indices. The modification will need to allow a precipitation threshold similar to the one in the ```xclim.indicators.icclim.SDII()``` function.

The definition of PRCPTOT for extreme precipitation is:

RCPTOT | Annual total wet-day PR | Sum of daily PR >= 1.0 mm | Total wet-day rainfall | mm | 

I have done an evaluation looking at the mean of the differences over 20 years for R95pTOT, R99pTOT, RX1day, RX5day, SDII, R10mm, R20mm, CDD and CWD and they all return a nearly identical match. Hence, this will be a great improvement for xclim particularly when looking at extreme precipitation indices. . 

The current work around is to simply modify the file containing the data using CDO, by changing values <= 1.0 mm to 0 mm

Thanks.

**Comment by huard** [comment]
Agreed, our `prcptot` index should match ICCLIM's. 

@aulemahal I see that the cf.yml entry for `prcptot` is commented out, so I suppose you came across this already. Thoughts ?

**Comment by aulemahal** [comment]
Haha oups, yes it is commented out for this specific reason, and I forgot to fix entirely. Adding a `thresh` to `precip_accumulation`, would be easy it there wasn't already one that controls the temperature under which precipitations are considered solid. That arg doesn't (or shouldn't) appear in the `PRCPTOT` indicator, but it does in `LIQUIDPRCPTOT` that shares the same indice.

Should we rename `thresh` to `tas_tresh` or `freeze_thresh` ? Or we add `wet_thresh`?

**Comment by Zeitsperre** [comment]
Whichever change we do should be very clearly indicated to the user, and a good way to do this would be ensuring that calling the function using the existing signature raises a warning.

For some backwards compatibility, I don't think we should change `thresh` to `tas_thresh`, but rather we add another signature element (`wet_thresh`, `accumulate_above`, `pr_floor`, whatever) that has a default value that triggers a warning if it isn't supplied by the user, at least for the next 2-3 versions.

**Comment by huard** [comment]
We could leave the indice as is and use thresholded_statistics in the indicator, no ?
