### ISSUE TITLE
Default group is not parsed in TrainAdjust

### ISSUE THREAD

**Issue by Levin000** [Ouranosinc/xclim#832]
* xclim version: 0.29.0
* Python version: 3.8.11
* Operating System: Centos 8

### Description
Some error about calendar popped up when I want do bias adjustments using EmpiricalQuantileMapping.train().

### What I Did

for s, sc, t in zip(scenarios_save, scenarios_cmip6, times):
    
    for m in models:
        
        for vo, vc, obs_dsel in zip(variables_cn051, variables_cmip6, [obs_dsel_tmax, obs_dsel_tmin]):
            cur_path = main_path / s / (vc+'_day_%s_0.25_qm_%s.zarr' % (m, t))
            if cur_path.exists():
                pass
            else:
                ccur_path = cmip6_path / sc / m
                gcm_ds = xr.open_mfdataset((ccur_path / (vc+'*.nc')).as_posix())
                if s == 'his':
                    gcm_dsel = gcm_ds.sel(time=slice("1985-01-01","2014-12-31"))
                    
                    gcm_dsel[vc] = gcm_dsel[vc] - 273.15
                    
                    gcm_dsel_interp = gcm_dsel.interp(lon=lon,lat=lat)
                    gcm_dsel_interp.load()
                    gcm_dsel_interp.attrs['units']='degC'
                    gcm_dsel_interp[vc].attrs['units']='degC'
                    
                    gcm_dsel_interp = calendar.convert_calendar(gcm_dsel_interp, calendar.get_calendar(obs_dsel),
                                                                align_on="date")
                    
                    rm_vars_list = getRmVarsKey(gcm_dsel_interp.data_vars.keys(), vc)
                    gcm_dsel_interp = gcm_dsel_interp.drop_vars(rm_vars_list).reset_coords(drop=True)
                    
                    encoding = {vc: comp}
                    interp_file = (main_path / s / (vc+'_day_%s_0.25_%s.zarr' % (m, t))).as_posix()
                    
                    gcm_dsel_interp = gcm_dsel_interp.transpose("lat", "lon", "time")
                    gcm_dsel_interp.to_zarr(interp_file, mode="w", compute=True)#encoding=encoding)
                    
                    # 0.29.0
                    QM=sdba.EmpiricalQuantileMapping.train(ref=obs_dsel[vo],
                                                           hist=gcm_dsel_interp[vc]) #, nquantiles=20, kind='+', group="time")
                    scen = QM.adjust(gcm_dsel_interp[vc]) #, interp='linear', extrapolation='nan')

                    scen=scen.chunk(chunks={"lat":11, "lon":36, "time":-1}).transpose("lat", "lon", "time")
                    gcm_dsel_interp_qm = xr.Dataset({vc: scen})
                    
                   
                    qm_file = (main_path / s / (vc+'_day_%s_0.25_qm_%s.zarr' % (m, t))).as_posix()
                    gcm_dsel_interp_qm.to_zarr(qm_file, mode="w", compute=True)#encoding=encoding)

### What I Received

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_138518/2247513382.py in <module>
     38                     QM=sdba.EmpiricalQuantileMapping.train(ref=obs_dsel[vo],
     39                                                            hist=gcm_dsel_interp[vc]) #, nquantiles=20, kind='+', group="time")
---> 40                     scen = QM.adjust(gcm_dsel_interp[vc]) #, interp='linear', extrapolation='nan')
     41 #                     # <= 0.28.1
     42 #                     QM=sdba.EmpiricalQuantileMapping(nquantiles=20, kind='+')

~/.conda/envs/xclim/lib/python3.8/site-packages/xclim/sdba/adjustment.py in adjust(self, sim, *args, **kwargs)
    181 
    182         if "group" in self:
--> 183             self._check_inputs(sim, *args, group=self.group)
    184 
    185         sim = convert_units_to(sim, self.train_units)

~/.conda/envs/xclim/lib/python3.8/site-packages/xclim/sdba/adjustment.py in _check_inputs(cls, group, *inputs)
     82 
     83         # All calendars used by the inputs
---> 84         calendars = {get_calendar(inda, group.dim) for inda in inputs}
     85         if not cls._allow_diff_calendars and len(calendars) > 1:
     86             raise ValueError(

~/.conda/envs/xclim/lib/python3.8/site-packages/xclim/sdba/adjustment.py in <setcomp>(.0)
     82 
     83         # All calendars used by the inputs
---> 84         calendars = {get_calendar(inda, group.dim) for inda in inputs}
     85         if not cls._allow_diff_calendars and len(calendars) > 1:
     86             raise ValueError(

AttributeError: 'str' object has no attribute 'dim'
1`

**Comment by Levin000** [comment]
this question has been solved by set ' group="time" 'for EmpiricalQuantileMapping.train( )

**Comment by aulemahal** [comment]
Happy to see you were able to solve your issue! However, it shows a bug in xclim, so I'll reopen and we will try to take care of this.

More precisely, the `@parse_group` decorator decorates a function that doesn't explicitly show a `group` arg and therefore cannot manage the case where it is not passed (and the default is used).  I tried copying the signature from the child class to the inherited function, but that didn't work, so we need to find another solution. One could be to make `group` non-optional? In that case the code above would have raised an error, but at least it would have been explicit.

**Comment by aulemahal** [comment]
@huard  What do you think of making the "group" arg required for all adjustments that use it? This is the second issue in 2 weeks that relates to this. Both were xclim bugs in reality, but they could have been avoided if group was required.

**Comment by huard** [comment]
Your first suggestion sounds cleaner.
