### ISSUE TITLE
Subset crashing randomly

### ISSUE THREAD

**Issue by yrouranos** [Ouranosinc/xclim#838]
* xclim version: 0.25.0
* Python version: 3.7.6
* Operating System: LinuxMint 20.1

### Description
The algorithm is trying to select the cells that are located within a polygon (defined by a .geojson file) using the function clisops.core.subset.subset_shape. The DataArray passed to this function contains a 2D matrix of climate indices with annual frequency ('YS').
It sometimes works the way it should, sometimes crashes, when calling the function with the same exact parameters (DataArray; path of a .geojson file defining polygon boundaries).
I would expect the same behaviour and result every time I run the function with unchanged parameters. Right now, the behaviour appears random, although there must be an explanation.

### What I Did
The test was done on 2 climate indices, which are 'drought_code' and 'tx_days_above'. In the former case, the index was calculated with xclim.indices.drought_code and with xclim.indicators.atmos.drought_code. In the latter case, the index was calculated using xclim.indices.tx_days_above.
The subset_shape function was then applied to a Dataset that contains a DataArray corresponding to a climate index. This is where the crash happens, when there is a crash.
I shared a .py file, along with 3 input NetCDF files and a .geojson file to help PCDO investigate this problem. The path of these directory on the server was communicated by email.

### What I Received
```
Traceback (most recent call last):
  File "/home/yrousseau/anaconda3/envs/xclim-dev/lib/python3.7/site-packages/clisops/core/subset.py", line 673, in subset_shape
    ds_copy = subset_bbox(ds_copy, lon_bnds=lon_bnds, lat_bnds=lat_bnds)
  File "/home/yrousseau/anaconda3/envs/xclim-dev/lib/python3.7/site-packages/clisops/core/subset.py", line 265, in func_checker
    return func(*args, **kwargs)
  File "/home/yrousseau/anaconda3/envs/xclim-dev/lib/python3.7/site-packages/clisops/core/subset.py", line 947, in subset_bbox
    "There were no valid data points found in the requested subset. Please expand "
ValueError: There were no valid data points found in the requested subset. Please expand the area covered by the bounding box, the time period or the level range you have selected.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "subset_shape_tester.py", line 474, in <module>
    main()
  File "subset_shape_tester.py", line 466, in main
    ds_idx = subset_shape(ds_idx, d_bounds, idx_name)
  File "subset_shape_tester.py", line 63, in subset_shape
    ds_res = subset.subset_shape(ds_res, d_bounds)
  File "/home/yrousseau/anaconda3/envs/xclim-dev/lib/python3.7/site-packages/clisops/core/subset.py", line 678, in subset_shape
    ) from e
ValueError: No grid cell centroids found within provided polygon bounding box. Try using the "buffer" option to create an expanded area.
```

**Comment by Zeitsperre** [comment]
Hey @yrouranos, I would open this ticket in https://github.com/roocs/clisops. The subsetting utilities are now maintained by the ROOCS team. If you could share the python file (without hard-coded internal paths) as a script in an issue, it'll help them get a sense of what might be happening.

**Comment by huard** [comment]
And the problem is not what is described in the error message ?

**Comment by yrouranos** [comment]
I don't understand your comment @huard. A call to clisops.core.subset.subset_shape is making my script crash, so it is related to the clisops.

**Comment by aulemahal** [comment]
Hi all! I found the problem and it is indeed not related to clisops!

I ran the script in a debugger fashion and found the culprit : `get_coord_names`. @yrouranos  uses this function to get the current spatial dimensions and ensure `clisops` receives `lat` and `lon` (instead of `latitude` and `longitude`). However, the function returns a **set**, not a tuple, and sets are _unordered_. Thus, here the returned order is not constant. Note that the scripts fails when the order is the "wrong" one as there is also an error on line 465.   I'm not sure what the python implementation really does, but the order is constant within a python process, but may switch across processes (when you restart python).

**Comment by aulemahal** [comment]
Note for `drought_code`  : Sadly the use of `xr.apply_ufunc` internally does change the axis order by sending 'time' to the last place. However, we made the decision to follow xarray and _not_ rely on dimension order. DataArrays have named dimensions, and thus no need to have a specific order. This is also motivated by the fact that transpose actions are not free when using dask, they add complexity to the compute tree.

**Comment by yrouranos** [comment]
The tricky part is that the call to subset_shape does not always result in a crash. The error message doesn't make sense to me knowing that if I run the code a few times, it will end up working. This may be why @huard mentioned that the problem is not what is described in the error message.

I will create an issue in the ROOCS repository, as suggested by @Zeitsperre.

**Comment by yrouranos** [comment]
It makes a lot of sense. It now works every time when `get_cord_names` returns an array instead of a set. Thanks for fixing my bug, which was not related to clisops.
