### ISSUE TITLE
Altered order of dimensions when calculating drought_code 

### ISSUE THREAD

**Issue by yrouranos** [Ouranosinc/xclim#839]
* xclim version: 0.25.0
* Python version: 3.7.6
* Operating System: LinuxMint 20.1

### Description
I calculated the index 'drought_code' using xclim.indices.drought_code or xclim.indicators.atmos.drought_code. The behaviour is the same with either function.
When visualizing the DataArray that contains the calculated climate indices, I realized that the order of dimensions in the resulting DataArray ('latitude', 'longitude', 'time') was different than the order of dimensions in the input DataArrays (temperature and precipitation) ('time', 'latitude', 'longitude').
In addition of keeping dimensions in the same order, I think that it is more convenient for subsequent analyses to let 'time' be the first dimension. I used 34 climate indices, but only noted this behaviour with 'drought_code'.

### What I Did
I shared a .py file, along with 3 input NetCDF files and a .geojson file to help PCDO investigate this problem. The path of these directory on the server was communicated by email.
Until there is a fix for this (if this is a bug), I adjust the order of dimensions of the Dataset containing climate indices using the function xarray.transpose.

### What I Received
There is no error message. The easiest way is to use the provided test .py code to reproduce the problem and to explore the DataArray containing the climate indices in debug mode.

**Comment by aulemahal** [comment]
Copying my comment from the other issue : 
The use of `xr.apply_ufunc` along `time` (internally for all forest weather indices) does change the axis order by sending 'time' to the last place. We made the decision to follow xarray and not rely on dimension order.
DataArrays have named dimensions, and thus no need to have a specific order. This is also motivated by the fact that transpose actions are not free when using dask, they add complexity to the compute tree.

But I could be convinced otherwise.

**Comment by yrouranos** [comment]
@aulemahal : Thanks for the explanation. I tried to locate information about conventions regarding the order of dimensions. According to:
[CF conventions](http://cfconventions.org/cf-conventions/cf-conventions.html):
> The CF convention places no rigid restrictions on the order of dimensions, however we encourage data producers to make the extra effort to stay within the COARDS standard order.
Then, I looked for information about 
[COARDS convention](http://wiki.seas.harvard.edu/geos-chem/index.php/The_COARDS_netCDF_conventions_for_earth_science_data) and found the following sentence:
> The recommended ordering of dimensions in the file is time, lev (if necessary), lat, lon.
Does it apply to the type of analyses that we are doing?

**Comment by aulemahal** [comment]
Oh! I didn't know of this recommendation in the CF conventions.

Doing this would need us to _parse_ the dimension names (we currently only consider "time"), as so to reorder them.

What do @Zeitsperre and @huard think?

**Comment by yrouranos** [comment]
@aulemahal @Zeitsperre @huard ...

With expressions such as "encourage" and "no rigid restrictions", the final decision seems to be up to us.

My main concern is related to the order of dimensions being different between the computed DataArray (of climate indices) and the scenario DataArray (used to calculate indices). I think it's confusing from a user's perspective. Not everybody would know this (there was at least one person who was not aware until 10 minutes ago), and the "drought_code" index seems to behave differently than the other indices with respect to the order of dimensions.

**Comment by huard** [comment]
I'm not too hot for the forced reordering *if there is performance penalty*. If there is no penalty, I agree sticking to the convention is best.

**Comment by aulemahal** [comment]
Woups forgot about this issue.

As far as I have experienced it, there is a (small) performance penalty on large datasets using dask because of the addition of a task (on each chunk) and xclim stuff already suffers from generating an enormous amount of dask tasks. I'll thus suggest we don't do anything.
