### ISSUE TITLE
Standard_name check

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#84]
### Description

Make sure that standard_name for our output is on the official list.

**Comment by Zeitsperre** [comment]
Just a word of warning but there are a lot of indices that don't have a CF-compliant `standard_name`. For the full list see: http://cfconventions.org/Data/cf-standard-names/60/build/cf-standard-name-table.html

In the past I've opted for "CF-ish" variable names where an equivalent didn't exist. Not the end of the world.

**Comment by huard** [comment]
Correct, this is going to be a problem. Closing.
