### ISSUE TITLE
Feature request: Add linear interpolations when bootstrapping percentile based indices

### ISSUE THREAD

**Issue by bzah** [Ouranosinc/xclim#846]
* xclim version: master
* Python version: all
* Operating System: all

### Description

Now that:
- `percentile_doy` accept *alpha* and *beta* parameters to customize the linear interpolation.
- `bootstrap_func` works fine and use internally percentile_doy

From the icclim point of view, it would be great if we could pass alpha and beta for the internal percentile_doy of bootstrap.

For example I would like to do something like:
```
per_90 = percentile_doy(in_base_da, 5, 90, alpha, beta)
result = atmos.tx90p(
      tasmax=da,
      t90=per_90,
      freq=freq,
      bootstrap=True,
      # alpha= alpha,
      # beta= beta
  )
```

However, it will "pollute" the API of **all** the bootstrapped indices...

**Comment by bzah** [comment]
It leads me to a design question.
All the percentile based indices accept a `t90` or equivalent DataArray as an input. 
**Why isn't this parameter a scalar value such as "90" ?** It would make the indice function calls `percentile_doy` instead of letting the function user do it.
Is it to be able to have another source of percentiles than the evaluated DataArray ?

This became particularly uneven because of bootstrapping (my bad, sorry). Indeed bootstrapping calls percentile_doy within its process but it also depends on the percentiles passed in parameters.
It means it compares the in base values to percentiles computed from the evaluated DataArray and compare the out of base values to the percentiles given in parameters. This seems quite misleading.
To avoid this we could make `t90` (or equivalent) mutually exclusive with `bootstrap` parameter.

**Comment by huard** [comment]
I think there are a couple of reasons:
1. Keep a record of t90;
2. Reuse t90 in multiple indicator calculations; 
3. Compute t90 from another dataset than the one used for the indicator. 

Not sure I fully understand the issue. Could you walk us through it ?

**Comment by bzah** [comment]
> Keep a record of t90

From icclim point of view this is actually an excellent reason!

----
My issue is we have to trust the user not to use bootstrapping improperly.

Bootstrapping percentiles is only useful if the wanted percentiles are:
- From the same sample as the studied values.
- Computed on a part of the sample time period.

With an example:
```
thresholds = xr.open_mfdataset("some_data.nc").thresholds
tasmax = xr.open_mfdataset("some_other_data.nc").tasmax
xc.atmos.tx90p(tasmax=tasmax, t90=thresholds, freq="MS", bootstrap=True)
```

If bootstrap is True, the in base period will be the time range of `thresholds`
However, if the thresholds are from another dataset it would make no sense to bootstrap and we can't let the user know about this nor forbid it.
But if the indice function calls `percentile_doy` there is no way to do this mistake.

Maybe I'm overthinking a bit here, we can suppose a user using bootstrap will have sufficient knowledge to understand when to use it.

**Comment by huard** [comment]
Got it. 
For now, I'm comfortable addressing this through the documentation. 
If we want a stronger safety net, we could think about further options (e.g. checksum comparing datasets), but as long as bootstrap=True is not the default value, I'm not overly worried.
