### ISSUE TITLE
Aligning xclim function with ETCCDI definition.

### ISSUE THREAD

**Issue by lpcaron** [Ouranosinc/xclim#848]
A request from CCDP PWG:

Two wet day indices on ClimateData.ca (XClim) use > rather than >= (ETCCDI) in the definition.

Would it be possible to change the default option in xclim such that the definition is consistent with ETCCDI?

**Comment by aulemahal** [comment]
In xclim, the `wetdays` indicator already uses `>=`. On thredds, I randomly checked 2 netCDF files in the `cccs_portal` folder, for r1mm et r20mm. Both have metadata saying that `>=` was used.
I might have missed something, but it might also be that the documentation on the portal is not exact?

**Comment by tlogan2000** [comment]
@aulemahal @Zeitsperre  Thanks, I think this is probably a case where the website data descriptions have simply not identically followed the metadata fields.  @lpcaron I will close the issue here and we can follow up with the CCDP project collaborators
