### ISSUE TITLE
Heat wave frequency seems ambiguous

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#85]
Our current implementation of heat wave frequency counts the number of events. So if we have a heat wave of 20 consecutive days, it returns 1, while if we have a cold day in between, it will return 2. I think there is high potential for confusion. So my question is: where does the index comes from ? Is this the way it has been implemented ?

**Comment by huard** [comment]
https://journals.ametsoc.org/doi/10.1175/JCLI-D-12-00383.1

**Comment by tlogan2000** [comment]
I20 | Heat waves frequency
I21 | warm night frequency
I22 | warm day frequency
I24 | hot minimum and maximum temp. frequency
come from https://journals.ametsoc.org/doi/10.1175/JAMC-D-12-0341.1
Identified as priority by people working on the health module

**Comment by tlogan2000** [comment]
I think this has been dealt with for now.  We've implemented heat wave definition as in Casati 2013 https://journals.ametsoc.org/doi/10.1175/JAMC-D-12-0341.1

As well we have added the max_length_heat_wave see https://github.com/Ouranosinc/xclim/issues/126
