### ISSUE TITLE
Harmonize compute function parameter handling

### ISSUE THREAD

**Issue by huard** [Ouranosinc/xclim#857]
* xclim version: 0.30

### Description

It is possible to customize `compute` functions using the `wrapped_partial` utility function, but there is a second mechanism that also modifies the compute signature in `indicators._parse_indice` to : 

- add the `ds` argument and allow `str` values instead of DataArrays
- modify defaults as specified by the YAML file 

My suggestion would be to consolidate the "signature modifying logic" to one function, or indicator method. So for example, the Indicator class could take arguments such as: 
- `compute_new_defaults`
- `conpute_frozen_params`

A second related issue is the fact that the signature of indicators varies depending on whether or not `compute` is defined using `wrapped_partial`. `wrapped_partial`, due to its use of `partial`, converts all parameters following a `suggested` or `fixed` parameters into KEYWORD_ONLY parameters. If we want a consistent signature across indicators, one option would be to make all non DataArray arguments KEYWORD_ONLY. I would do this within the logic above, and leave indices as is.

**Comment by aulemahal** [comment]
Suggestion:

- Similar to the yaml specs, pass parameters in a dict `parameters`, keys are arguments of the compute function (indice), values are:
    * A value (int, float, bool, str, None). This means it will be _injected_.
    * A dict with possible keys : {'default', 'kind', 'description',  'choices', 'units'}. (the two first will always be there, the third may be absent and the last depend on the parameter).
- The "compute" function is stored as-is, no more partial and injection. Instead, the "injection" happens in the indicator's `__call__`.
- However, same as currently, the _signature_ of the indicator's `__call__` is modified to fit what `parameters` sets (defaults, injections, annotations).

This leaves a naming problem, the current `Ind.parameters` doesn't include "injected" parameters, but it does in my suggestion.  We could cheat in the `__new__` : rename `parameters` to `_parameters` and have a `parameters` property that returns only the non-injected arguments.
Or we could rename one of those. The argument to `__new__` could be `params` (and so the section in the yaml)?

Example:
Current:
```python
relative_humidity_from_dewpoint = Converter(
    identifier="hurs_fromdewpoint",
    #  [... other stufff ...]
    compute=wrapped_partial(
        indices.relative_humidity,
        suggested={"tdps": _empty},
        huss=None,
        ps=None,
        invalid_values="mask",
    ),
)
```

Suggested:
```python3
relative_humidity_from_dewpoint = Converter(
    identifier="hurs_fromdewpoint",
    #  [... other stufff ...]
    compute=indices.relative_humidity,
    parameters={
       "tdps": {'default': _empty},
       "huss": None,
       "ps": None,
       "invalid_values": "mask",
    },
)
```

Annotations would still be parsed from the compute's signature and each parameter will be assigned a "kind". In the final indicator signature, arguments with kinds "VARIABLE" pr "OPTIONAL_VARIABLE" will be `positional_or_keyword`, all other wouldl be `keyword_only`.

In this model, inheritance of parameters is thus done within the class creation. This allows the following:

```python3
relative_humidity_from_dewpoint_clip = registry['hurs_fromdewpoint'](
    parameters={
        "invalid_values": "clip"
    }
)
```
I.e.: I changed the injected value without re-assigning (and re-parsing) the compute function. The parameters dict is updated on the new indicator and its `__call__` will use the correct argument. This might not feel a big bonus here, but I think it might be nice to have in the yaml modules.
