### ISSUE TITLE
Equivalent of relative_humidity_from_dewpoint for specific_humidity

### ISSUE THREAD

**Issue by RondeauG** [Ouranosinc/xclim#864]
* xclim version: 0.29

### Description
The only currently implemented method to calculate specific humidity requires `hurs` and `ps`. An equivalent method to `relative_humidity_from_dewpoint`, requiring instead `tas` and `tdps`, could be useful.

**Comment by huard** [comment]
@RondeauG  I don't think we can get away without air pressure. The signature would look like:
`def specific_humidity_from_dewpoint(tdps: xr.DataArray, pr: xr.DataArray) -> xr.DataArray:`

**Comment by RondeauG** [comment]
Ok, I thought that an equivalent method might exist but if it's not the case, this Issue could be closed.
