### ISSUE TITLE
DOC: Update contribution guidelines

### ISSUE THREAD

**Issue by abel-bzz** [Ouranosinc/xclim#868]
The [contribution guidelines](https://xclim.readthedocs.io/en/stable/contributing.html) seems to be a bit outdated.

It's a followup to a discussion started [here](https://github.com/Ouranosinc/xclim/pull/866#r727133329_).

1. The new rule to have the issue and pull request number in History.rst entries is missing (introduced by https://github.com/Ouranosinc/xclim/pull/860/files).
2. A "By xxx" was also introduced through the above PR but it's not clear (to me) if it should be added on each new history entry.
3. The project `readme.rst` chapter "Contributing" could have a link to the contribution guide.

**Comment by Zeitsperre** [comment]
Thanks for opening this up!


>     1. The new rule to have the issue and pull request number in History.rst entries is missing (introduced by https://github.com/Ouranosinc/xclim/pull/860/files).

Currently working on this in a PR. Should be submitted in the next few minutes. 

>     2. A "By xxx" was also introduced through the above PR but it's not clear (to me) if it should be added on each new history entry.

We came up with this idea a few weeks ago (or at the very least, realized that something needed to be done), but I feel like we didn't communicate this well. The issue with this that we identified right away is that some authors who add quite a lot of changes would have their names everywhere in the HISTORY. One thing we could do instead is to add a listing of `Authors contributing to this version`. Might be a much cleaner approach.

Will be proposing this in the upcoming PR.

>     3. The project `readme.rst` chapter "Contributing" could have a link to the contribution guide.

Good idea! Will integrate this as well. Thanks!
