### ISSUE TITLE
Feature request: calculate return period, given maximum value and distribution parameters

### ISSUE THREAD

**Issue by JeremyFyke** [Ouranosinc/xclim#876]
* xclim version: 0.29
* Python version: 3.8
* Operating System: Ubuntu Linux

Hi!  First, thanks again for the great coding that went into xclim.  I'm finding new features all the time.

Currently, I am exploring use of the handy [frequency analysis utilities](https://xclim.readthedocs.io/en/stable/notebooks/frequency_analysis.html) tools.  In particular, I am calculating return periods based on daily input provided by CanESM simulations (@huard, actually, the CanESM ensemble that @swartn ran with [CEPM ](https://github.com/JeremyFyke/CEPM)output).   So far, so good.

Next, I would like to programmatically recreate the concept of [this ](https://changingclimate.ca/CCCR2019/chapter/4-0/4-2/4-2-2/4-2-2-3/figure-4-12-2/) figure in the CCCR 2019 report, which estimates changes in return period (e.g. likelihood, e.g. risk relevant change), for a given magnitude (in the case of the CCCR figure, the magnitude of a present-day 1-in-50 year maximum temperature). 

I believe that to do this, I need a tool that is essentially the inverse of the xclim `parametric quantile` function: i.e., a routine that is passed a magnitude value and distribution parameter values, and returns a percentile level that is consistent with this magnitude value (instead of being passed a percentile level and distribution parameter values, and returning a magnitude value that is consistent with the percentile level).

Is this an operation that the existing xclim code base can be easily manipulated/hacked to produce?  A quick skim of the source code for the frequency analysis routines suggests 'no', but I certainly could be mistaken.  If 'no' - what would the feasibility be of introducing such an option to the current set of xclim frequency analysis utilities?  I think from a risk perspective, it could be very useful/used.  I would be potentially interested in helping develop this, given some guidance on underlying (scipy?) tools to wrap with xarray.

Thanks for any help!

@JeremyFyke

**Comment by huard** [comment]
Hi @JeremyFyke, 

Do you want to push your work so far? I could take it from there.

**Comment by JeremyFyke** [comment]
@huard good call.  I just wrapped back to this code myself after the holidays.  Expect a push soon with what I have to date (certainly not to xclim release standards)

**Comment by JeremyFyke** [comment]
@huard I've submitted a pull request from ECCC-CCCS:JeremyFyke/frequency-analysis to Ouranosinc:master: https://github.com/Ouranosinc/xclim/pull/982

I'm not sure if you wanted the pull request routed there or another branch (feel free to reject if so).   More immediately,  I think it's failing some pre-merge checks as well.  LMK how to proceed on both counts if you are able!
