### ISSUE TITLE
Proposal: Issue Forms and/or Markdown template options

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#886]
GitHub now offers Issue Forms using Markdown (video: https://www.youtube.com/watch?v=2Yh8ueUE0oY; docs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms).

It would be good to differentiate between Bug Reports and Feature Requests at the very least. There should be some required information fields for both of them. Nothing too fancy. (This can also be ported to our existing cookiecutter templates that are closely aligned with xclim's project template).

**Comment by huard** [comment]
I'm -1 on this. This is meant to add friction for users issuing bug or feature requests. The large majority of issues are created by ourselves, so I don't see why we'd want more friction.
