### ISSUE TITLE
Masking and indexing as argument of indicator's call

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#899]
Proposition to inject the `**indexer` args to _all_ indicators. 

With this proposition, `[Resampling]Indicator`'s call would mask values along the `time` axis according to the instruction passed to the `indexer` kwargs. The masking would occur before the compute. The `missing` methods would need to be modified to take this masking into account.

If possible, the masked values could even be dropped, in order to accelerate computation.

For example:  `xc.atmos.tg_max(tas, season='MAM', freq='YS')` would return one value per year (on Jan 1st) of the maximal temperature in the spring months. Internally, it would look like `tas2 = tas.where(tas.time.dt.month.isin([3, 4, 5]))`.

But we could open up to fancier indexing: 
Ex: `xc.atmos.tg_max(tas, within_dates=['03-13', '05-14'], freq='YS')`. Again yearly values of maximal temperature but only considering days between March 13th and May 14th. 

Maybe even : 
```
start = xc.atmos.first_day_above(...)
end = xc.atmos.first_snowfall(...)
xc.atmos.tg_max(tas, within)_dates=(start, end), freq='YS')
```
?

I think this needs:

- [ ] A standalone function to mask a timeseries according to a tuple of dates (doy int , month-day str, arrays of doys). @yrouranos has a draft of this in #894. @RondeauG  has also a need for this. 
- [ ]  #867 to be done.
- [ ] A way for `missing` methods to take this into account.

It would fix a reccuring issues of users wanting to compute some indicators on clea-but-incomplete data or on subsets. It would on other hand either fill the signature with many arguments or, if we leave them as kwargs, forbid the use of kwargs by indices (which is not too bad).

**Comment by RondeauG** [comment]
My need is slightly different, in the sense that I'm interested to apply a function on specific periods of the year (e.g. cumulative precipitation deficit over summer and fall), but the output should be a time series, not an aggregate.

**Comment by yrouranos** [comment]
@aulemahal

I think that it would be a nice feature. In agriculture, there is often a need for masking. Weather conditions usually affect a specific part of the life cycle of a plant/culture (ex: growth, development of flowers/fruits, dormancy). Drought during rain season, too warm during dormancy, strong winds removing flowers from trees, etc.

Masking before computation may be a problem for a few climate indices. My feeling is that it could be problematic if there's a `window` involved (when the algorithm needs to consider values beyond the `within_dates` range).

If we wish to calculate the number of days per year with Tmax >= threshold, but only within a period of the year (e.g., June and July), masking before computation makes sense and is faster.

In other situations, masking before vs after computation (of the climate index) will result in different outcomes. This is the case with the proposed `dry_spell_total_length` algorithm (issue #843). If a sequence of 14 dry days starts before `start_date` and ends after `start_date`, masking before computation will result in ignoring this dry period. However, there are days between `start_date` and `end_date` that are comprised in a dry period, so they should be detected. In a case like this, masking needs to be applied just before aggregating to the `YS` frequency. 

The situation is similar with the proposed `rain_season_start` and `rain_season_end` algorithms (issue #842). There are 3 calculation methods for `rain_season_end`: `{"max", "sum","etp"}`. The first 2 methods require to know the `window` days following the end of the rain season. If masking is applied before computation, the end of the rain season may not be detected. The 3rd method would be compatible with before-computation masking. So, that's a little bit tricky.

Would it be possible to offer this masking, as suggested in the current issue, but let the `within_dates` be overridden when a specific climate index needs a different behaviour?

**Comment by aulemahal** [comment]
Indeed, that's a good point!

I think we could have this parameter injection be controlled by some keyword upon indicator creation. This way, if a function needs to have control of the masking, it can implement the functionality itself, like in your case. That's why I see the implementation of the masking as a standalone function usable by indices and indicators.

**Comment by RondeauG** [comment]
Two considerations to be taken into account:

1. If we allow a `'mm-dd'` format, such as `within_dates=['03-13', '05-14']` given as an example above, working through a `day-of-year` approach might be more complicated with standard calendars (but easy for calendars with always the same number of days per year).
2. In some cases, such as snow-related indicators, someone might want to compute indicators from November/December of the previous year, such as `within_dates=['12-01', '04-30']`. Do we want to support that? It would be useful, I believe. If not, we'll need a check that `start_doy < end_doy`.

**Comment by bzah** [comment]
FYI, I have implemented something similar in icclim but for now it is a post treatment of xclim output so the performance are suboptimal.
@RondeauG I'm interested in case 2.
