### ISSUE TITLE
Huglin Index formula

### ISSUE THREAD

**Issue by odo64** [Ouranosinc/xclim#902]
* xclim version: 0.30.1
* Python version: 3.8.5
* Operating System: Linux Pop!_OS 21.04

### Description
In xclim Huglin index (xclim.indices.huglin_index) is based on the mean of daily max and min temperature, but many sources, as
Huglin & Schneider,1998 " Biologie et écologie de la vigne", Tec&DOC and Tonietto and Carbonneau, 2004. "A multicriteria climatic classification system for grape-growing regions worldwide", Agricultural and Forest Meteorology, and Hall&Jones 2010, Spatial analysis of climate in winegrape-growing regions in Australia AJGWR, define the index as based on the mean of daily MEAN and max temperature, not min and max.

**Comment by Zeitsperre** [comment]
@odo64 You're absolutely right. This will be dealt with before we release a new version today.

 Thanks for pointing this out!
