### ISSUE TITLE
Rolling indicators with window=1 cause huge memory usage spikes

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#910]
When running indicators that use the `run_length` functions in their backend (eg: `xclim.atmos.dlyfrzthw`), if `window=1` then this will cause enormous memory usage spikes; enough to grind servers to a halt. This likely due to `dask` running lots of `rolling()` calculations.

In order to address this, we might need to intelligently dictate to the `run_length` function that if the `window=1` to not perform rolling calculations. I say intelligently since we don't want to add a ton of if/else statements if we can avoid it.

**Comment by aulemahal** [comment]
Well.
There are 4 base run-length algorithms that involve `window`:

- `rle_statistics`
- `windowed_run_events`
- `windowed_run_count`
- `first_run`

In the first one, there's no escape. But for the other three, the `window=1` case is usually kinda trivial to compute. Even if that's more `if`s, I suggest we implement them directly.
