### ISSUE TITLE
Add developer notes on how to implement indices and indicators

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#928]
I think the documentation of xclim is missing a "developer notes" page that is quite common in other projects. 

I am thinking specifically of enhancing the "contributing" page with info on :
- Steps to take when implementing
    * New indices/indicators
    * New sdba functions and objects
- More info on what coding style to use
- Where to put which test, what data to use.

**Comment by bzah** [comment]
For the step to take when implementing new indices I created my own check list when I was working on a few this summer:
```
- Implement indice
- Add unit tests
- Update icclim.yml
- Update unit test for icclim.yml (expected number of indices)
- Add fr translation for indice
- Update hystory.rst
- Test with real data and compare output to icclim
```
It's probably incomplete but it's a start.
