### ISSUE TITLE
Feature request: Provide the ECAD definition of R75p R95p and R99p indices.

### ISSUE THREAD

**Issue by bzah** [Ouranosinc/xclim#931]
* xclim version: 0.31.x
* Python version: all
* Operating System: all

### Description

Currently, the indices R75p R95p and R99p (as per icclim.yml file) rely on `days_over_precip_thresh` function which expect in `per` parameter a DataArray of **doy** percentiles.

However, when reading the definition from [ECAD](https://www.ecad.eu/documents/atbd.pdf#subsubsection.5.3.8) documentation:
> R75p
• Days with RR > 75th percentile of daily amounts (moderate wet days)
(days)
Let RRwj be the daily precipitation amount at wet day w (RR ≥ 1.0 mm)
of period j and let RRwn75 be the 75th percentile of precipitation at wet
days in the 1961–1990 period. Then counted is the number of days where:
RRwj > RRwn75

As per this definition, the percentiles should be computed on the whole base period (above 61-90) and not for each day of year.

Thus, I would like to implement an index function similar to `days_over_precip_thresh` with a `thresh` DataArray parameter having values thresholds for each spatial point.
Or maybe simply replace `days_over_precip_thresh` but both definition could make sens I suppose.
icclim.yml should be updated to probably follow ECAD definition as icclim v4 does.

### What I Did

I compared the output of icclimv4 and found very different results.

Notes: 
- **I'm willing to work on this issue.**
- climdex/climpact use again another definition for r99p (and others indices). It sum the precipitation amounts above the percentile thresholds and the percentiles are **not** for doy.
- The subject of RxxP definition is discussed on clix-meta: https://github.com/clix-meta/clix-meta/issues/53.
- The [WMO definition](https://library.wmo.int/doc_num.php?explnum_id=9419) for R95p is 
>R95p [...] the number of days with rainfall above the 95th percentile of daily accumulations.

Thus current `days_over_precip_thresh` is following a valid definition, the one from WMO, but it differ from icclim which uses ECAD definition.

**Comment by bzah** [comment]
My bad, I miss read the code of `days_over_precip_thresh`, it already accepts **either** daily percentiles or non daily values for per.

However, when **non** daily percentiles are used, `days_over_precip_thresh` indicator description becomes invalid: `{freq} number of days with precipitation above a daily percentile.`
The doc of `per` parameter could also be changed from "Daily percentile of wet day precipitation flux." to something like  "Percentiles of wet day precipitation flux."
Also, an error should probably be raised if `bootstrap` is True but `per` doesn't have a coordinate variable "dayofyear". But this should likely go in `percentile_bootstrap`.

**Comment by huard** [comment]
Hi @bzah 
I agree with your suggestions to clarify the docs and description.
