### ISSUE TITLE
Bootstrapping quickly exhausts memory

### ISSUE THREAD

**Issue by huaracheguarache** [Ouranosinc/xclim#932]
* xclim version: 0.31.0
* Python version: 3.9.7
* Operating System: Linux 74cf36c51c91 4.18.0-305.19.1.el8_4.x86_64 #⁠1 SMP Wed Sep 15 15:39:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Description

Trying to calculate indices with bootstrap set to True results in a rather large amount of RAM (120 GB) being exhausted. No matter how small I make the chunks of the dataset that is used to calculate the index it fails. Is this something that's expected due to the computationally heavy nature of bootstrapping, or is this an issue with xclim?

### What I Did

Here's the code that I ran:

```python
import xarray as xr
import xclim

mpi_historical = xr.open_dataset('http://esgf-data3.ceda.ac.uk/thredds/dodsC/esg_cmip6/CMIP6/CMIP/MPI-M/MPI-ESM1-2-LR/historical/r1i1p1f1/day/tasmin/gn/v20190710/tasmin_day_MPI-ESM1-2-LR_historical_r1i1p1f1_gn_19900101-20091231.nc',
                                 chunks=dict(time=1000))

p10 = xclim.core.calendar.percentile_doy(mpi_historical.tasmin, per=10)
TN10p_mpi_historical = xclim.indicators.icclim.TN10p(mpi_historical.tasmin, t10=p10,
                                                     freq='QS-DEC', bootstrap=True)

TN10p_mpi_historical.load()
```

### What I Received

I'm doing these computations through a remote jupyterlab instance, and a short while after the code starts to execute the .load() part it crashes due to memory exhaustion. If the imported dataset is divided into smaller chunks it takes a longer time for the crash to happen. 

I also get the following warnings about chunk sizes:

```
/opt/conda/envs/my_kernel/lib/python3.9/site-packages/xarray/core/indexing.py:1227: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  return self.array[key]
```

**Comment by bzah** [comment]
You don't need to turn bootstrap on if you compute percentiles on exactly the same period as the index.
Bootstrapping is only useful if the percentiles are computed on an in_base period (like WMO standard normals period) and the climate index itself is computed on a longer period.
But yes, bootstrapping process is inherently memory and CPU hungry.

Its principle is to recompute the percentiles multiple times by switching each time which years are in base (part of percentile computation) or out of base (part of index computation). This avoids some statistical bias between the in base and the out of base periods.
Thus, when bootstrapping is used, I would avoid chunking on time dimension, because Dask will likely have to load multiple chunks for the bs to complete.
I also had great results by setting up a Dask distributed scheduler to limit the memory load Dask can use, as @aulemahal recommended me.
Here is the configuration I'm using to run indices on my laptop:
```
from distributed import Client

c = Client(n_workers=1, threads_per_worker=10, memory_limit='10GB')
```
Beware the memory_limit is not exact, Dask may use a little more than that, I would advise you not to put you actual physical memory limit in here.

**Comment by huaracheguarache** [comment]
@bzah 

I must admit that I'm a bit confused about bootstrapping in general. The code I posted is just a minimal example that produced the issues I was seeing in a longer script. What I'm interested in is finding the difference in TN10p (also a few other indices) between a historical baseline (1990-2014) and a future scenario (2075-2099). Here's the relevant part of the code:

```python
p10 = xclim.core.calendar.percentile_doy(dset_hist.tasmin, per=10)

TN10p_dset = xclim.indicators.icclim.TN10p(dset.tasmin, t10=p10, freq='QS-DEC')
TN10p_dset_hist = xclim.indicators.icclim.TN10p(dset_hist.tasmin, t10=p10, freq='QS-DEC', bootstrap=True)

TN10p_dset_sm = TN10p_dset.groupby('time.season').mean(dim='time')
TN10p_dset_hist_sm = TN10p_dset_hist.groupby('time.season').mean(dim='time')

TN10p_diff = TN10p_dset_sm - TN10p_dset_hist_sm
```

The 10th percentile (p10) is calculated from the historical tasmin data. This is used to find the TN10p values for the same historical period and the future scenario. I then find the seasonal means and the seasonal difference. I assume that there's no need to set bootstrap=True like I've done for the calculation of the historical TN10p, right?

Also, thanks for showing me Dask distributed. These things are all very new to me, and I really appreciate the help!

**Comment by bzah** [comment]
Exactly, you don't need bootstrap on neither of the calls of `TN10p`.
On _hist_ case, you don't have a out_of_base period, both percentiles and tn10p are called on the same period.
On _futur_ case, you have an in_base and an out_of_base but they don't overlap so bootstrap is useless here as well.

**Comment by huaracheguarache** [comment]
Ok, that cleared up my confusion about bootstrapping, Thanks for your help!

**Comment by bzah** [comment]
I'm closing this, feel free to reopen if there are other concerns on bootstrap.

**Comment by bzah** [comment]
Hi,
I'm reopening this if you don't mind.
With Christian we have seen that bootstrap can exhaust memory very well on large datasets. It happens even with the latest version of xclim (0.33.x).

I'm trying to fix this and will drop a PR when I'm finished done.
My current approach is to try to use `map_block` but I'm having very mixed results for now.
