### ISSUE TITLE
Usage Notebook in Docs seems to be broken

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#946]
Browsing through the docs, I came across a few cells which seem to not be registering anything interesting:

![image](https://user-images.githubusercontent.com/10819524/144285208-5e14834e-f6c8-4f4b-ab39-5630b1b8cc04.png)

Unsure if the notebook needs to be re-run or if the API of xarray may have changed. Either way, this should be adjusted.

**Comment by aulemahal** [comment]
Woups my bad! I'll push a fix soon.
