### ISSUE TITLE
Adopt Code of Conduct Guidelines

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#948]
We are presently gaining a fair amount of regular contributors and those raising issues, so in the interest of maintaining a welcoming and respectful developer community, I would like to propose adopting a Code of Conduct (https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project). 

Ideally, we could make Code of Conduct and Contributor guidelines an organisation-wide default when creating public-facing repositories as well (https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file).

There are a few options available right off the bat, so no need to develop something from scratch:
 - [Code of Conduct templates from GitHub](https://github.com/topics/code-of-conduct-template)
 - [Contributor Covenant](https://www.contributor-covenant.org/) (adopted by the [xarray project](https://github.com/pydata/xarray/blob/main/CODE_OF_CONDUCT.md))

The Code of Conduct should be something that we collectively agree to, so I'm tagging most of the established maintainers here. If you have no strong opinions on this, just leave a :+1: !

**Comment by aulemahal** [comment]
Question : as this repo is part of the OuranosInc organization and that the core team is almost only made up of employees of said organisation, does this need to be flagged/managed/approved by the bosses?

Ça et la langue du code étant donné l'aspect "fonds publics québécois" d'Ouranos?

**Comment by juliettelavoie** [comment]
If we go with the Contributor Covenant, what does banning entail? Does github have a function for temporary and permanent ban ? 

Also, who is the community leader ?

**Comment by Zeitsperre** [comment]
> Question : as this repo is part of the OuranosInc organization and that the core team is almost only made up of employees of said organisation, does this need to be flagged/managed/approved by the bosses?

If we as a group propose something reasonable/permissive, I'm of the opinion that admin/management will likely approve whatever we present them with. At the very least, this can be brought up to a higher level by our development lead. Given that we're the ones adopting/adapting the standard, we can expect at most some modifications. I don't imagine that we would experience fundamental changes. Ultimately, this is to help codify engagement/expectations to support contributions/contributors; I imagine not having this type of agreement is an issue already is something that our direction would want to address, no ?

> Ça et la langue du code étant donné l'aspect "fonds publics québécois" d'Ouranos?

Bonne question. I'm not sure where to begin on this matter. We are already doing this work primarily in English for international engagement / code development purposes, but I don't see an issue with us adding that we explicitly support French contributions as well? I'm not sure what is asked of us and what other publicly-financed organismes en Québec do.

> If we go with the Contributor Covenant, what does banning entail? Does github have a function for temporary and permanent ban ?

Yes, there are tools for permanently banning contributors from engaging with our repositories, ie: cannot make issues or post, cannot fork, cannot open PRs on upstream master, etc. (I'm not sure if temporary bans are supported in the GitHub API, but probably - Will look for curiosity's sake). We've never needed to use them, thankfully.

> Also, who is the community leader ?

Great question. We should discuss that here.

**Comment by Zeitsperre** [comment]
Welcome back, @Ouranosinc/xclim-core

In the interest of hitting the ground running, it would be incredibly valuable for the process if we had a few more people weighing in on this (relevant links for the discussion above). Some questions summarized:

- In the event of abuse, how do we determine suspension/banning practices?
- Do we want to adopt a standard Code of Conduct (like [Contributor Convenant](https://www.contributor-covenant.org/), or something else) or develop one ourselves (e.g. https://miloslav.website/code-of-conduct/)?
- To what degree are we free to adopt a Code of Conduct?
- Are there issues related to xclim project financing that affect this process?
- How do we identify/nominate a Community Leader?

@tlogan2000 I feel as though your knowledge on the project management aspects of Xclim would help us answer a few questions (obligations due to financing, freedoms to adopt Code of Conduct, necessary admin/SH input, etc.).

**Comment by Zeitsperre** [comment]
After some discussion with @tlogan2000, I think I'll be pushing a PR to add a Code of Conduct today.

>     * In the event of abuse, how do we determine suspension/banning practices?

For this, we can discuss internally on an as-needed basis. I don't see this needing to happen often/at all.
 
>     * Do we want to adopt a standard Code of Conduct (like [Contributor Convenant](https://www.contributor-covenant.org/), or something else) or develop one ourselves (e.g. https://miloslav.website/code-of-conduct/)?

The Contributor Covenant covers all the bases that we want covered. It's recognizable and accessible as well. 

>     * To what degree are we free to adopt a Code of Conduct?

We have full artistic license on this aspect of the library.

>     * Are there issues related to xclim project financing that affect this process?

None whatsoever. Xclim is a means to support and deliver on contractual obligations to our research partners, and not the end result. We are free to conduct ourselves according to our own set of standards.

>     * How do we identify/nominate a Community Leader?

I'm nominating myself for the role for now. Always open to revise that decision.
