### ISSUE TITLE
Change request: `heating_degree_days` does not use the ECA&D formula (HD17)

### ISSUE THREAD

**Issue by bzah** [Ouranosinc/xclim#952]
* xclim version: 0.32
* Python version: n/a
* Operating System: n/a

### Description

`heating_degree_days` is clipping values below 0 after subtracting the threshold.  It is acting similar as `growing_degree_days` (gd4 in eca&d).
However, ECA&D definition of this index does not indicate this clipping should be done on `heating_degree_days`
See HD17 in [PDF](https://www.ecad.eu/documents/atbd.pdf)

### What I Did

I compared `heating_degree_days` with the equivalent index of climpact `hddheatn` (with n=17).

<img width="559" alt="image" src="https://user-images.githubusercontent.com/16700639/144876834-17a49f3f-ad1e-4848-b71c-41e3508d1c96.png">

However I'm not sure if it makes that much sense to not clip values below 0.

**Comment by huard** [comment]
I think that's an oversight in the ECA&D definition. I stand by our algorithm.

**Comment by bzah** [comment]
Thanks David I agree with you, without this clipping I don't really see the point of subtracting 17.

In that case, I'll write a PR to update the index doc, the math formula should be 
`sum_{i=1}^{I} (17℃ - TG_{ij}) | TG_{ij} > {17}℃)` instead of `sum_{i=1}^{I} (17℃ - TG_{ij})`
I will also add a note to make it clear it differs from ECA&D index.

For the record, icclim v4 was also clipping these values.

**Comment by huard** [comment]
FYI @heroldn  -- follow up from discussion on harmonizing indices definitions.

**Comment by tlogan2000** [comment]
I agree that I believe the general rule is to clip degree day calculations.   The only application I personally have seen over the years where clipping was not employed was a freezing degree day application specific to lake ice cover thickness modeling during winter.  I.e. warm days were seen as a mechanism for ice cover loss so in this case were not clipped

**Comment by bzah** [comment]
I just found another definition of the same index, also from ECA, but from a newer document: https://code.mpimet.mpg.de/projects/cdo/embedded/cdo_eca.pdf#subsection.2.0.10
>[...] the heating degree days are defined as the sum of T1 - TG, where only values TG < T2 are considered. If T1 and T2 are omitted, a temperature of 17°C is used for both parameters.

So, for the sum, instead of ignoring values below 17ºC, it ignores values above 17ºC.
I'm confused.

**Comment by huard** [comment]
Yes, because we're only heating when the temperature is below 17.

**Comment by bzah** [comment]
Update on this. I was using tas_min instead of tas for this index on both version of icclim. Hence the difference...
Once fixed the results are exactly similar with climpact.
