### ISSUE TITLE
Bad performance of run length algorithms

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#956]
As flagged in #912, an important weakness of xclim in term of performance is the huge number of tasks it generates when using dask. That issue discusses improvements that could be made at the indicator-level, but one major functionality of xclim that generates heavy load is the run-length algorithm(s),

As issue #916 raises, implementation choices have been made to ensure reasonable dask loads even though they were not scientifically correct. Specifically, we decided to resample and then count events, which incorrectly handles events spanning multiples periods but reduces the number of tasks a lot by running `rle` on smaller datasets.

Moreover, the `xclim.indices.run_length` module is somewhat messy because of the existence of 3 separate algorithms for most base functions : the `window=1` version,  the "ufunc" version (`run_length.rle_1d`) and the "normal" verson (`run_length.rle`).

The "ufunc" version requires a single chunk along  `time` and is said to be faster with smaller datasets, which was not verified extensively. The "normal" version is generic and works with any chunking or data size, but it generated an awful lot of dask tasks.

Before rewriting indices to their scientifically correct version, we must rewrite `rle` in order for it to work on large datasets.

EDIT: Just to be clear, the current `rle` does the following:
Takes in a boolean array and flags the runs of true values. The output is a float array where the first day of each run is the length of the run, all other days of the run are NaN and days outside of the runs are 0. An option exists to put the run-length at the end of the run instead. A new implementation could modify how the output is given, if that new output allows the computation of the same statistics.

**Comment by aulemahal** [comment]
@bzah would you be interested and available to look into this?

**Comment by aulemahal** [comment]
I'm adding an idea I had, but that wouldn't work in all cases, for discussion:

The problem with chunked arrays is that we need  `rle` to count run days across chunks. It is usual that datasets are chunked along time and often impractical to rechunk along that dimension without the need to go through an expensive independent rechunking step.

My idea is to compute the run lengths in 2 steps : 
First, for each chunk independently, compute the `rle` as usual, using something like `map_blocks`. 
Then, use `dask.array.map_overlap` to take care of the chunk's edges:
    - If a run `R1` ends at the boundary and the first element of the next chunk is the start of a run `R2`, add the run length of `R2` to the run  `R1`. Because `R2` is simply the continuation of `R1`.
    - Correspondingly, if the first element of the chunk is the start of a run (is an int) and the previous chunk ended with a run (is NaN), then replace that first element by NaN to denote the continuation of the run.
 
This would allow ti rewrite `rle` in numpy only, even maybe in numba. It would also reduce the number of tasks to `Nchunks` x 2. However, it fails when a run spans more than 2 chunks.

**Comment by bzah** [comment]
> @bzah would you be interested and available to look into this?
Interested: yes ; available: not sure before February.

About your algorithm, I think it just needs to handle of intermediary chunks but it can be adapted with recursions.

Suppose we put the run_length result at the start of the run and we work on a 1d arrray with time being the dimension.
Approximately it could look like:

```
def rle_on_chunks(i: int):
   if chunks[i][0] == len(chunks[i]):
      # chunk_i is an intermediary chunk, it has a run lasting on its whole period
      return chunks[i][0] +  rle_on_chunks(i+1)

   elif chunks[i][0] > 0 and chunks[i][0] < len(chunks[i]):
     # chunk_i is a end chunk.
     return chunks[i].run_length

  elif chunks[i][0] == 0 and if chunks[i][-1] is nan:
     # chunk_i is a start chunk.
     return chunks[i].max() +  rle_on_chunks(i+1)

  else:
   # chunk has no run or its run is not overlapping with other chunks
   return chunks[i].max() 
```

I haven't tested it though.

**Comment by aulemahal** [comment]
> Interested: yes ; available: not sure before February.

Ok, I might have time before february, I'll keep you updated.

The potential problem with your function is that it needs to read the chunk before it decides if it will read another or not. I believe this goes against the "laziness" required by dask algorithms...

**Comment by bzah** [comment]
It would be nice to assess performance of running run_lenght **then** resampling when [flox](https://github.com/dcherian/flox) is enabled.
