### ISSUE TITLE
update_xclim_history misreporting keyword arguments

### ISSUE THREAD

**Issue by aulemahal** [Ouranosinc/xclim#963]
* xclim version: 0.32.

### Description

Calling a function wrapped by `update_xclim_history` correctly appends a line with the call string and xclim version to the output, but in the call string everything is written as if they were positional arguments, even though I passed them as kwargs.

### What I Did

```python3
from xclim.core.formatting import update_xclim_history
from xclim.testing import open_dataset

@update_xclim_history
def func(da, arg1, arg2=None, arg3=None):
    return da

ds = open_dataset('ERA5/daily_surface_cancities_1990-1993.nc')
out = func(ds.tas, 1, arg2=2, arg3=None)
print(out.attrs['history'])
# [2021-12-20 10:38:35] tas: func(tas, 1, 2, <NoneType>) - xclim version: 0.32.1.
```
I think this is a bug because some functions cannot be called this way. 

Moreover, I think the call string printer should understand "None" and print that, instead of "<NoneType>".

**Comment by Zeitsperre** [comment]
This is pretty significant. If you want to push a PR in the next few days, I don't mind tagging another bugfix release.
