### ISSUE TITLE
missing 1 required positional argument: 'hist' 

### ISSUE THREAD

**Issue by ODOU** [Ouranosinc/xclim#970]
* xclim version: 0.25.0
* Python version:2.7.17
* Operating System: linux

### Description
 I am trying to run a bias correction on some set of data by following the example described here :https://xclim.readthedocs.io/en/stable/sdba.html

### What I Did
When I run this : 

```
$ from xclim import sdba
$ dqm = sdba.adjustment.EmpiricalQuantileMapping.train(ref,hist)
```
### What I Received

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-0280ac57f594> in <module>()
      1 from xclim import sdba
----> 2 dqm = sdba.adjustment.EmpiricalQuantileMapping.train(ref,hist)

TypeError: train() missing 1 required positional argument: 'hist'

**Comment by Zeitsperre** [comment]
Hi there,

It looks as though you're running a much older version of Xclim on Python2.7. In [Xclim v0.29](https://xclim.readthedocs.io/en/stable/history.html#id17), we changed much of the internal workings of `sdba`, including the API for it, so the behaviour of your version doesn't reflect the stable documentation. My suggestion would be to update your Python environment to 3.7+ and reinstall Xclim to get access to the newer features and speedups (https://xclim.readthedocs.io/en/stable/installation.html#installation)

**Comment by aulemahal** [comment]
If you can't update your env and xclim, the older way of calling EQM was this:

```
from xclim import sdba
EQM = sdba.adjustment.EmpiricalQuantileMapping()
EQM.train(ref, hist)
scen = EQM.adjust(sim)
```

Sadly, I think read-the-docs doesn't keep an archive of older documentation, so you'll have to inspect the objects themselves to read their docstrings. Or build the doc from your copy of this repo checked-out at v0.25 (see the "contributing" page of the current doc).

xclim is still evolving rapidly, and we make breaking changes from time to time, in the goal of improving the code. We have plans of releasing a more stable v1.0 version during 2022.

**Comment by ODOU** [comment]
Thank you very much for your answers. It is now clear. I was using an old version. I ran the suggested code and it works fine for me.
