### ISSUE TITLE
Feature request: Drought indices

### ISSUE THREAD

**Issue by khider** [Ouranosinc/xclim#973]
It would also be convenient to add some drought indices. This package is useful: https://climate-indices.readthedocs.io/en/latest/

The code can be called outside the command line and be made to work with `apply_ufunc` as in: https://github.com/mintproject/droughtIndices/blob/d1149ba63f275b5a4531fbd6a6cadefaef90ecc2/WM_climate_indices.py#L369

**Comment by tlogan2000** [comment]
Hello @khider. Thanks for your interest. We are actually hoping to have an intern look at incorporating these exact indices this summer.

**Comment by huard** [comment]
Duplicate of #131.
