### ISSUE TITLE
Adapt to the newest Pandas release (v1.4.0)

### ISSUE THREAD

**Issue by Zeitsperre** [Ouranosinc/xclim#992]
The Pandas devs released a new (and breaking) version of Pandas over the weekend (https://pypi.org/project/pandas/1.4.0/). We should see what level of effort is needed to support it (https://pandas.pydata.org/docs/whatsnew/index.html#version-1-4)

Given that `xarray` is strongly tied to `pandas`, we should be testing against it in at least one of our CI builds.

**Comment by huard** [comment]
I'm concerned we're going to spend a considerable amount of time tracking regressions in pandas. I suggest we pin pandas < 1.4 and wait for 1.4.1 before looking into this. Hopefully some of the upstream issues will have been resolved by then.

**Comment by aulemahal** [comment]
Looking quickly at the failed tests, it indeed seems that the broken things are in xarray? And it seems all the bugs are related to the same issue ("Prefix not defined"). As such, I would suggest at least waiting for a diagnostic before pinning pandas in a xclim release.

**Comment by aulemahal** [comment]
https://github.com/pandas-dev/pandas/issues/45595
